// Are We A Match? — pack 👯 Amis.
// Goûts et modes de vie généraux : ça marche avec n'importe qui.
// Chaque question = 3 options à classer. Les options sont pensées pour être
// CLIVANTES (pas d'option « évidemment meilleure ») : c'est ce qui étale les
// scores de compatibilité et rend les résultats parlants.
// `id` est stable : il sert de clé pour la persistance des réponses.

module.exports = [
  { id: "am-weekend", q: "Le week-end parfait", o: ["🏔️ Rando et grand air", "🥐 Brunch puis expo", "🛋️ Canapé, série, zéro contrainte"] },
  { id: "am-soiree", q: "La soirée idéale", o: ["🕺 Bar bondé et musique forte", "🍲 Dîner à 4 à la maison", "🎬 Ciné puis debrief"] },
  { id: "am-vacances", q: "En vacances, tu es plutôt", o: ["🗺️ Tout planifier à l'avance", "🎲 Improviser sur place", "🏖️ Ne rien faire du tout"] },
  { id: "am-reveil", q: "Ton rapport au réveil", o: ["🌅 Debout à 6h, la journée est à moi", "☕ 8h avec un café, tranquille", "😴 Le plus tard possible"] },
  { id: "am-resto", q: "Au restaurant, tu choisis", o: ["🍜 Un truc que tu n'as jamais goûté", "🥩 Ta valeur sûre habituelle", "🌱 L'option la plus saine"] },
  { id: "am-musique", q: "Le son en soirée", o: ["🎸 Rock / guitares", "🎧 Électro / house", "🎤 Variété et sing-along"] },
  { id: "am-transport", q: "Pour un trajet de 3 h", o: ["🚗 Voiture, on s'arrête où on veut", "🚆 Train, je lis / je dors", "✈️ Avion, le plus vite possible"] },
  { id: "am-argent", q: "Ton rapport à l'argent", o: ["🐿️ J'épargne d'abord", "🎈 Je dépense pour les expériences", "📊 Je calcule et j'optimise tout"] },
  { id: "am-conflit", q: "Face à un désaccord", o: ["🗣️ On en parle tout de suite", "⏳ Je laisse retomber puis j'en parle", "🤐 J'évite, ça finit par passer"] },
  { id: "am-samedi", q: "Un samedi après-midi libre", o: ["🏃 Du sport", "🛍️ Traîner en ville", "🎮 Jeu vidéo / lecture au calme"] },
  { id: "am-cuisine", q: "En cuisine", o: ["👨‍🍳 Je cuisine, ça me détend", "🥡 Je commande, la vie est courte", "🍳 Le minimum vital"] },
  { id: "am-anniv", q: "Ton anniversaire idéal", o: ["🎉 Grosse fête, tout le monde", "🍷 Dîner avec 5 personnes", "🤫 Rien du tout, on n'en parle pas"] },
  { id: "am-sport", q: "Le sport que tu préfères", o: ["⚽ Sport collectif", "🏋️ Salle / solo", "🚶 Marcher, c'est déjà bien"] },
  { id: "am-tel", q: "Ton téléphone en soirée", o: ["📵 Rangé, je suis là", "📸 Je prends des photos", "📱 Je scrolle un peu quand même"] },
  { id: "am-menage", q: "Le ménage chez toi", o: ["🧽 Impeccable en permanence", "🌀 Bordel organisé, je m'y retrouve", "🙈 On verra la semaine prochaine"] },
  { id: "am-film", q: "Pour un film un soir", o: ["😂 Comédie qui détend", "🧠 Un truc qui fait réfléchir", "💥 Action, pop-corn, zéro prise de tête"] },
  { id: "am-ville", q: "Ta ville idéale", o: ["🏙️ Grande ville qui bouge", "🏡 Petite ville tranquille", "🌾 Carrément la campagne"] },
  { id: "am-matin", q: "Le petit-déjeuner", o: ["🥓 Salé et copieux", "🥐 Sucré, viennoiserie", "☕ Juste un café"] },
  { id: "am-cadeau", q: "Le cadeau que tu préfères recevoir", o: ["🎟️ Une expérience à vivre", "📦 Un objet bien choisi", "💌 Quelque chose de fait main"] },
  { id: "am-groupe", q: "Dans un groupe, tu es", o: ["📣 Celui qui organise", "🎭 Celui qui met l'ambiance", "👂 Celui qui écoute"] },
  { id: "am-boisson", q: "À l'apéro, ton verre", o: ["🍺 Bière", "🍷 Vin", "🍹 Cocktail"] },
  { id: "am-imprevu", q: "Un plan annulé à la dernière minute", o: ["😤 Ça m'agace vraiment", "🤷 Aucun souci, je m'adapte", "🎉 Secrètement soulagé"] },
  { id: "am-voyage-type", q: "Le voyage qui te tente le plus", o: ["🎒 Sac à dos, auberges, imprévu", "🏨 Hôtel confortable, tout organisé", "🚐 Van, on dort où on veut"] },
  { id: "am-social", q: "Après une grosse semaine", o: ["🥳 J'ai besoin de voir du monde", "🧘 J'ai besoin d'être seul", "👥 Une ou deux personnes max"] },
  { id: "am-deco", q: "Ton intérieur", o: ["🪴 Chaleureux, plein de trucs", "⬜ Minimaliste et épuré", "🎨 Coloré et assumé"] },
  { id: "am-humour", q: "L'humour qui te fait le plus rire", o: ["🙃 Absurde", "🗡️ Sarcastique / cynique", "🤪 Bon gros humour bête"] },
  { id: "am-planning", q: "Ton agenda", o: ["📅 Rempli et planifié", "✏️ Quelques repères, souple", "🌊 Rien, je vis au jour le jour"] },
  { id: "am-animal", q: "Team", o: ["🐕 Chien", "🐈 Chat", "🚫 Aucun animal chez moi"] },
  { id: "am-debat", q: "Un débat animé à table", o: ["🔥 J'adore, je fonce", "🙂 J'écoute et je nuance", "😬 Ça me met mal à l'aise"] },
  { id: "am-vetements", q: "Ton style vestimentaire", o: ["👔 Soigné, ça compte", "👟 Confort avant tout", "🧢 Décontracté mais pensé"] },
  { id: "am-nouveau", q: "Face à quelque chose de nouveau", o: ["🚀 Je teste tout de suite", "🔍 Je me renseigne d'abord", "⏸️ J'attends que d'autres essaient"] },
  { id: "am-fete-fin", q: "En fin de soirée", o: ["🌙 Je pars le premier sans bruit", "🕐 Je reste jusqu'au bout", "🚕 Je pars quand le groupe part"] },
  { id: "am-serie", q: "Une nouvelle série", o: ["📺 Je binge tout d'un coup", "🗓️ Un épisode par soir", "⏳ J'attends que la saison soit finie"] },
  { id: "am-photo", q: "Les photos de voyage", o: ["📷 J'en prends des centaines", "🖼️ Quelques-unes, bien choisies", "👀 Aucune, je profite"] },
  { id: "am-retard", q: "Ton rapport à la ponctualité", o: ["⏰ Toujours en avance", "🎯 Pile à l'heure", "🐢 Souvent un peu en retard"] },
  { id: "am-lecture", q: "Un livre, c'est", o: ["📚 Roman, m'évader", "🧭 Essai, apprendre", "🚫 Pas trop mon truc"] },
  { id: "am-cuisine-monde", q: "La cuisine que tu choisirais pour un an", o: ["🍝 Italienne", "🍣 Japonaise", "🌮 Mexicaine"] },
  { id: "am-risque", q: "Ton rapport au risque", o: ["🪂 J'aime l'adrénaline", "⚖️ Calculé, jamais gratuit", "🛡️ Je préfère la sécurité"] },
  { id: "am-cafe", q: "Un moment à toi", o: ["☕ Terrasse de café à observer", "🎧 Musique et marche", "🛁 À la maison au calme"] },
  { id: "am-groupe-taille", q: "La taille de groupe idéale", o: ["👫 À deux", "👨‍👩‍👧 4 ou 5", "🎪 Le plus de monde possible"] },
  { id: "am-decision", q: "Pour prendre une décision", o: ["🧠 Je liste le pour et le contre", "❤️ Je suis mon instinct", "🗣️ Je demande conseil autour de moi"] },
  { id: "am-competition", q: "En jeu de société", o: ["🏆 Je joue pour gagner", "😄 Je joue pour l'ambiance", "😈 Je joue pour saboter les autres"] },
  { id: "am-saison", q: "Ta saison", o: ["☀️ Été", "🍂 Automne", "❄️ Hiver"] },
  { id: "am-message", q: "Tu réponds aux messages", o: ["⚡ Dans la minute", "🕒 Dans la journée", "📭 Quand j'y repense... parfois"] },
  { id: "am-souvenir", q: "Ce que tu ramènes d'un voyage", o: ["🧲 Un objet souvenir", "🍫 De la nourriture locale", "📖 Juste des histoires"] },
];
