// Are We A Match? — pack 👯 Amis.
// Goûts et modes de vie généraux : ça marche avec n'importe qui.
//
// Chaque question :
//   q   — une vraie question, courte, affichée en gros.
//   ctx — la scène en une phrase, puis le critère de classement (« du plus
//         tentant au moins tentant », « du plus « toi » au moins « toi »… »).
//         C'est lui qui lève l'ambiguïté : « préféré » ne veut rien dire pour
//         « face à un désaccord », « ce que tu ferais vraiment » si.
//   o   — 3 options à classer, pensées pour être CLIVANTES (pas d'option
//         « évidemment meilleure ») : c'est ce qui étale les scores de
//         compatibilité et rend les résultats parlants.
//
// RÈGLE DE STABILITÉ — les réponses mémorisées dans les comptes sont des
// classements d'INDEX dans `o`, rangés par `id`. Donc, pour une question
// existante : `id` ne change jamais, et les options gardent leur ORDRE et leur
// SENS (retoucher la formulation est permis, permuter ou remplacer une option
// ne l'est pas — ça fausserait les compatibilités historiques en silence).

module.exports = [
  { id: "am-weekend", axis: "gouts",
    fr: { q: "C'est quoi, ton week-end parfait ?",
          ctx: "Deux jours libres, météo parfaite, zéro obligation. Du plus tentant au moins tentant.",
          o: ["🏔️ Rando et grand air", "🥐 Brunch puis expo", "🛋️ Canapé, série, zéro contrainte"] },
    en: { q: "What does your perfect weekend look like?",
          ctx: "Two free days, perfect weather, nothing you have to do. From most tempting to least.",
          o: ["🏔️ Hiking and fresh air", "🥐 Brunch, then a museum", "🛋️ Sofa, series, zero obligations"] } },
  { id: "am-soiree", axis: "rythme",
    fr: { q: "Vendredi soir, on fait quoi ?",
          ctx: "Semaine finie, tout le monde est libre. De la soirée que tu proposes en premier à celle que tu évites.",
          o: ["🕺 Bar bondé et musique forte", "🍲 Dîner à 4 à la maison", "🎬 Ciné puis debrief"] },
    en: { q: "Friday night — what are we doing?",
          ctx: "The week is over and everyone is free. From the night you'd suggest first to the one you'd dodge.",
          o: ["🕺 Packed bar, loud music", "🍲 Dinner for four at home", "🎬 Cinema, then pick it apart"] } },
  { id: "am-vacances", axis: "rythme",
    fr: { q: "En vacances, tu fonctionnes comment ?",
          ctx: "Une semaine ailleurs avec les copains. De la façon de faire qui te ressemble le plus à celle qui te ressemble le moins.",
          o: ["🗺️ Tout planifier à l'avance", "🎲 Improviser sur place", "🏖️ Ne rien faire du tout"] },
    en: { q: "On holiday, how do you operate?",
          ctx: "A week away with friends. From the way of doing it that's most like you to the least.",
          o: ["🗺️ Plan every bit in advance", "🎲 Work it out once we're there", "🏖️ Do absolutely nothing"] } },
  { id: "am-reveil", axis: "rythme",
    fr: { q: "Un matin sans réveil, tu te lèves quand ?",
          ctx: "Personne ne t'attend, rien ne presse. Du réveil qui te ressemble le plus à celui qui te ressemble le moins.",
          o: ["🌅 Debout à 6h, la journée est à moi", "☕ 8h avec un café, tranquille", "😴 Le plus tard possible"] },
    en: { q: "A morning with no alarm — when do you get up?",
          ctx: "Nobody's waiting on you, nothing is urgent. From the wake-up most like you to the least.",
          o: ["🌅 Up at six, the day is mine", "☕ Eight, with a coffee, slowly", "😴 As late as humanly possible"] } },
  { id: "am-resto", axis: "gouts",
    fr: { q: "Au resto, tu commandes quoi ?",
          ctx: "Nouvelle adresse, carte inconnue, le serveur attend. Du réflexe le plus « toi » au moins « toi ».",
          o: ["🍜 Un truc que tu n'as jamais goûté", "🥩 Ta valeur sûre habituelle", "🌱 L'option la plus saine"] },
    en: { q: "At a restaurant, what do you order?",
          ctx: "New place, unfamiliar menu, the waiter is waiting. From your most typical reflex to your least.",
          o: ["🍜 Something you've never tried", "🥩 Your usual safe bet", "🌱 Whatever's healthiest"] } },
  { id: "am-musique", axis: "gouts",
    fr: { q: "On te tend l'enceinte : tu mets quoi ?",
          ctx: "Soirée entre amis, la playlist est à toi. De l'ambiance que tu lances en premier à celle que tu évites.",
          o: ["🎸 Rock / guitares", "🎧 Électro / house", "🎤 Variété et sing-along"] },
    en: { q: "You're handed the speaker — what goes on?",
          ctx: "Night in with friends, the playlist is yours. From the mood you'd start with to the one you'd avoid.",
          o: ["🎸 Rock, guitars", "🎧 Electronic, house", "🎤 Big singalong hits"] } },
  { id: "am-transport", axis: "gouts",
    fr: { q: "Trois heures de trajet : tu voyages comment ?",
          ctx: "Même prix, même heure d'arrivée. De ta façon de voyager préférée à celle que tu subis.",
          o: ["🚗 Voiture, on s'arrête où on veut", "🚆 Train, je lis / je dors", "✈️ Avion, le plus vite possible"] },
    en: { q: "Three hours of travel — how do you go?",
          ctx: "Same price, same arrival time. From your favourite way to travel to the one you just endure.",
          o: ["🚗 Car, stop wherever we like", "🚆 Train, I read or sleep", "✈️ Plane, get it over with"] } },
  { id: "am-argent", axis: "argent",
    fr: { q: "Une prime tombe : tu en fais quoi ?",
          ctx: "Une somme inattendue, sans besoin urgent. Du réflexe le plus « toi » au moins « toi ».",
          o: ["🐿️ J'épargne d'abord", "🎈 Je dépense pour les expériences", "📊 Je calcule et j'optimise tout"] },
    en: { q: "A bonus lands — what do you do with it?",
          ctx: "Unexpected money, nothing urgent to cover. From your most typical reflex to your least.",
          o: ["🐿️ Save it first", "🎈 Spend it on experiences", "📊 Work out the optimal split"] } },
  { id: "am-conflit", axis: "autres",
    fr: { q: "Un ami t'a blessé : tu réagis comment ?",
          ctx: "Rien de grave, mais ça t'est resté en travers. De ce que tu ferais vraiment à ce que tu ne ferais jamais.",
          o: ["🗣️ On en parle tout de suite", "⏳ Je laisse retomber puis j'en parle", "🤐 J'évite, ça finit par passer"] },
    en: { q: "A friend hurt you — how do you react?",
          ctx: "Nothing serious, but it stuck. From what you'd actually do to what you'd never do.",
          o: ["🗣️ Say something right away", "⏳ Let it cool, then bring it up", "🤐 Avoid it, it'll pass"] } },
  { id: "am-samedi", axis: "rythme",
    fr: { q: "Samedi après-midi, rien de prévu : tu fais quoi ?",
          ctx: "Les corvées sont faites, le téléphone est calme. Du plus tentant au moins tentant.",
          o: ["🏃 Du sport", "🛍️ Traîner en ville", "🎮 Jeu vidéo / lecture au calme"] },
    en: { q: "Saturday afternoon, nothing planned. What now?",
          ctx: "The chores are done and your phone is quiet. From most tempting to least.",
          o: ["🏃 Something sporty", "🛍️ Wander around town", "🎮 Games or reading, somewhere quiet"] } },
  { id: "am-cuisine", axis: "rythme",
    fr: { q: "Le soir, pour manger, tu fais quoi ?",
          ctx: "Un soir de semaine ordinaire, personne à impressionner. Du plus fréquent chez toi au plus rare.",
          o: ["👨‍🍳 Je cuisine, ça me détend", "🥡 Je commande, la vie est courte", "🍳 Le minimum vital"] },
    en: { q: "Dinner on a weeknight — what happens?",
          ctx: "An ordinary evening, nobody to impress. From what you do most often to least.",
          o: ["👨‍🍳 I cook, it relaxes me", "🥡 I order in, life is short", "🍳 The bare minimum"] } },
  { id: "am-anniv", axis: "autres",
    fr: { q: "Ton anniversaire, tu le fêtes comment ?",
          ctx: "C'est toi qui décides, personne ne t'impose rien. De ce qui te fait vraiment plaisir à ce que tu redoutes.",
          o: ["🎉 Grosse fête, tout le monde", "🍷 Dîner avec 5 personnes", "🤫 Rien du tout, on n'en parle pas"] },
    en: { q: "Your birthday — how do you mark it?",
          ctx: "Entirely your call, nobody is imposing anything. From what genuinely pleases you to what you dread.",
          o: ["🎉 Big party, everyone invited", "🍷 Dinner with five people", "🤫 Nothing at all, don't mention it"] } },
  { id: "am-sport", axis: "rythme",
    fr: { q: "Bouger, pour toi, ça ressemble à quoi ?",
          ctx: "Une activité régulière, pas un exploit par an. De ce qui te motive le plus à ce qui te motive le moins.",
          o: ["⚽ Sport collectif", "🏋️ Salle / solo", "🚶 Marcher, c'est déjà bien"] },
    en: { q: "What does moving your body look like for you?",
          ctx: "Something regular, not one heroic effort a year. From what motivates you most to least.",
          o: ["⚽ Team sport", "🏋️ Gym, on my own", "🚶 Walking counts, thanks"] } },
  { id: "am-tel", axis: "vices",
    fr: { q: "En soirée, ton téléphone est où ?",
          ctx: "Une bonne soirée entre amis, comme celle-ci. De l'attitude la plus honnête à ton sujet à la moins honnête.",
          o: ["📵 Rangé, je suis là", "📸 Je prends des photos", "📱 Je scrolle un peu quand même"] },
    en: { q: "At a party, where is your phone?",
          ctx: "A good night with friends, like this one. From the most honest answer about you to the least.",
          o: ["📵 Away, I'm here", "📸 I'm taking the photos", "📱 I scroll a bit anyway"] } },
  { id: "am-menage", axis: "vices",
    fr: { q: "Chez toi, ça ressemble à quoi un mardi soir ?",
          ctx: "Pas le jour où tu reçois : un jour normal. Du plus proche de la réalité au plus éloigné.",
          o: ["🧽 Impeccable en permanence", "🌀 Bordel organisé, je m'y retrouve", "🙈 On verra la semaine prochaine"] },
    en: { q: "What does your place look like on a Tuesday?",
          ctx: "Not the day you have people over — an ordinary day. From closest to the truth to furthest.",
          o: ["🧽 Spotless, always", "🌀 Organised chaos, I know where things are", "🙈 Next week's problem"] } },
  { id: "am-film", axis: "gouts",
    fr: { q: "Film ce soir : tu choisis quoi ?",
          ctx: "Canapé, plaid, la télécommande est à toi. Du genre que tu lances en premier à celui que tu gardes pour une autre fois.",
          o: ["😂 Comédie qui détend", "🧠 Un truc qui fait réfléchir", "💥 Action, pop-corn, zéro prise de tête"] },
    en: { q: "Film tonight — what do you pick?",
          ctx: "Sofa, blanket, the remote is yours. From what you'd start with to what you'd save for another time.",
          o: ["😂 A comedy, something easy", "🧠 Something that makes you think", "💥 Action, popcorn, no thinking"] } },
  { id: "am-ville", axis: "gouts",
    fr: { q: "Vivre n'importe où : ce serait où ?",
          ctx: "Le boulot suit, les amis aussi, seul le cadre change. De ce qui te fait rêver à ce qui te fait fuir.",
          o: ["🏙️ Grande ville qui bouge", "🏡 Petite ville tranquille", "🌾 Carrément la campagne"] },
    en: { q: "If you could live anywhere — where?",
          ctx: "Work follows, friends follow, only the setting changes. From what you'd dream of to what you'd flee.",
          o: ["🏙️ Big city with a pulse", "🏡 Quiet small town", "🌾 Properly out in the countryside"] } },
  { id: "am-matin", axis: "gouts",
    fr: { q: "Le petit-déj, c'est quoi pour toi ?",
          ctx: "Un dimanche matin, avec le temps de le préparer. Du plus tentant au moins tentant.",
          o: ["🥓 Salé et copieux", "🥐 Sucré, viennoiserie", "☕ Juste un café"] },
    en: { q: "Breakfast — what is it for you?",
          ctx: "A Sunday morning, with time to make it properly. From most tempting to least.",
          o: ["🥓 Savoury and substantial", "🥐 Sweet, something baked", "☕ Just a coffee"] } },
  { id: "am-cadeau", axis: "autres",
    fr: { q: "Quel cadeau te fait le plus plaisir ?",
          ctx: "Même budget, même intention derrière. De celui qui te touche le plus à celui qui te touche le moins.",
          o: ["🎟️ Une expérience à vivre", "📦 Un objet bien choisi", "💌 Quelque chose de fait main"] },
    en: { q: "Which gift means the most to you?",
          ctx: "Same budget, same thought behind it. From the one that moves you most to the least.",
          o: ["🎟️ An experience to live", "📦 A well-chosen object", "💌 Something handmade"] } },
  { id: "am-groupe", axis: "autres",
    fr: { q: "Dans une bande d'amis, tu es qui ?",
          ctx: "Sois honnête, pas flatteur. Du rôle que tu tiens le plus souvent à celui que tu tiens le moins.",
          o: ["📣 Celui ou celle qui organise", "🎭 Celui ou celle qui met l'ambiance", "👂 Celui ou celle qui écoute"] },
    en: { q: "In a group of friends, who are you?",
          ctx: "Be honest, not flattering. From the role you play most often to the one you play least.",
          o: ["📣 The one who organises", "🎭 The one who brings the energy", "👂 The one who listens"] } },
  { id: "am-boisson", axis: "gouts",
    fr: { q: "À l'apéro, tu bois quoi ?",
          ctx: "Terrasse, fin de journée, on prend la commande. Du verre que tu demandes en premier au dernier.",
          o: ["🍺 Bière", "🍷 Vin", "🍹 Cocktail"] },
    en: { q: "Drinks are being ordered — what's yours?",
          ctx: "Terrace, end of the day, the waiter is taking orders. From the first glass you'd ask for to the last.",
          o: ["🍺 Beer", "🍷 Wine", "🍹 A cocktail"] } },
  { id: "am-imprevu", axis: "vices",
    fr: { q: "On annule le plan une heure avant : tu ressens quoi ?",
          ctx: "Tu étais prêt, tu allais partir. De la réaction la plus vraie pour toi à la moins vraie.",
          o: ["😤 Ça m'agace vraiment", "🤷 Aucun souci, je m'adapte", "🎉 Secrètement soulagé(e)"] },
    en: { q: "A plan is cancelled an hour before. How does that feel?",
          ctx: "You were ready, you were about to leave. From the truest reaction for you to the least true.",
          o: ["😤 It genuinely annoys me", "🤷 No problem, I adapt", "🎉 Secretly relieved"] } },
  { id: "am-voyage-type", axis: "gouts",
    fr: { q: "Deux semaines de voyage : tu pars comment ?",
          ctx: "Même destination, même budget, trois manières de la vivre. De celle qui te fait rêver à celle qui te tente le moins.",
          o: ["🎒 Sac à dos, auberges, imprévu", "🏨 Hôtel confortable, tout organisé", "🚐 Van, on dort où on veut"] },
    en: { q: "Two weeks away — how do you travel?",
          ctx: "Same destination, same budget, three ways to live it. From the one you'd dream of to the one that tempts you least.",
          o: ["🎒 Backpack, hostels, no plan", "🏨 Comfortable hotel, all arranged", "🚐 Van, sleep wherever we stop"] } },
  { id: "am-social", axis: "autres",
    fr: { q: "Après une semaine épuisante, il te faut quoi ?",
          ctx: "Vendredi 19 h, batterie à plat. Du besoin le plus urgent pour toi au moins urgent.",
          o: ["🥳 J'ai besoin de voir du monde", "🧘 J'ai besoin d'être seul(e)", "👥 Une ou deux personnes max"] },
    en: { q: "After an exhausting week, what do you need?",
          ctx: "Friday, seven o'clock, battery flat. From your most urgent need to your least.",
          o: ["🥳 I need to see people", "🧘 I need to be alone", "👥 One or two people, no more"] } },
  { id: "am-deco", axis: "gouts",
    fr: { q: "Chez toi, c'est quel genre de déco ?",
          ctx: "Ou celle que tu aurais avec carte blanche. Du style le plus proche de toi au plus éloigné.",
          o: ["🪴 Chaleureux, plein de trucs", "⬜ Minimaliste et épuré", "🎨 Coloré et assumé"] },
    en: { q: "What's the style of your place?",
          ctx: "Or the one you'd have with a free hand. From the style closest to you to the furthest.",
          o: ["🪴 Warm, full of things", "⬜ Minimal and bare", "🎨 Colourful and unapologetic"] } },
  { id: "am-humour", axis: "gouts",
    fr: { q: "Qu'est-ce qui te fait vraiment rire ?",
          ctx: "Le rire sincère, celui qu'on ne contrôle pas. De ce qui te fait pleurer de rire à ce qui te laisse de marbre.",
          o: ["🙃 Absurde", "🗡️ Sarcastique / cynique", "🤪 Bon gros humour bête"] },
    en: { q: "What actually makes you laugh?",
          ctx: "The real laugh, the one you can't control. From what leaves you in tears to what leaves you cold.",
          o: ["🙃 Absurd", "🗡️ Sarcastic, dry", "🤪 Good honest stupidity"] } },
  { id: "am-planning", axis: "rythme",
    fr: { q: "Ton agenda de la semaine ressemble à quoi ?",
          ctx: "Pas celui du travail : celui de ta vie perso. Du plus proche du tien au plus éloigné.",
          o: ["📅 Rempli et planifié", "✏️ Quelques repères, souple", "🌊 Rien, je vis au jour le jour"] },
    en: { q: "What does your week's calendar look like?",
          ctx: "Not your work one — the rest of your life. From closest to yours to furthest.",
          o: ["📅 Full and planned out", "✏️ A few anchors, loose around them", "🌊 Nothing, I take it as it comes"] } },
  { id: "am-animal", axis: "gouts",
    fr: { q: "Chez toi, quel animal aurait sa place ?",
          ctx: "Tu as la place, le temps et le budget. De ce qui te fait plaisir à ce que tu refuses.",
          o: ["🐕 Chien", "🐈 Chat", "🚫 Aucun animal chez moi"] },
    en: { q: "Which animal belongs in your home?",
          ctx: "You have the space, the time and the budget. From what would delight you to what you'd refuse.",
          o: ["🐕 A dog", "🐈 A cat", "🚫 No animals in my home"] } },
  { id: "am-debat", axis: "autres",
    fr: { q: "Le ton monte à table : tu fais quoi ?",
          ctx: "Un vrai débat, des avis tranchés, personne ne lâche. De l'attitude que tu adoptes le plus à celle que tu adoptes le moins.",
          o: ["🔥 J'adore, je fonce", "🙂 J'écoute et je nuance", "😬 Ça me met mal à l'aise"] },
    en: { q: "The argument heats up at dinner. What do you do?",
          ctx: "A real debate, strong opinions, nobody backing down. From what you do most to what you do least.",
          o: ["🔥 I love it, I dive in", "🙂 I listen and add nuance", "😬 It makes me uncomfortable"] } },
  { id: "am-vetements", axis: "gouts",
    fr: { q: "Tu t'habilles comment au quotidien ?",
          ctx: "Un jour normal, ni mariage ni dimanche malade. Du style le plus proche du tien au plus éloigné.",
          o: ["👔 Soigné, ça compte", "👟 Confort avant tout", "🧢 Décontracté mais pensé"] },
    en: { q: "How do you dress day to day?",
          ctx: "An ordinary day — no wedding, no sick Sunday. From the style closest to yours to the furthest.",
          o: ["👔 Put together, it matters", "👟 Comfort above all", "🧢 Casual but considered"] } },
  { id: "am-nouveau", axis: "rythme",
    fr: { q: "Une nouveauté débarque : tu réagis comment ?",
          ctx: "Une appli, un resto, une activité dont tout le monde parle. Du réflexe le plus « toi » au moins « toi ».",
          o: ["🚀 Je teste tout de suite", "🔍 Je me renseigne d'abord", "⏸️ J'attends que d'autres essaient"] },
    en: { q: "Something new arrives — how do you react?",
          ctx: "An app, a restaurant, an activity everyone is talking about. From your most typical reflex to your least.",
          o: ["🚀 I try it immediately", "🔍 I read up on it first", "⏸️ I wait for others to try"] } },
  { id: "am-fete-fin", axis: "rythme",
    fr: { q: "Il est 2 h du matin : tu es où ?",
          ctx: "La soirée est bonne mais elle s'étire. Du départ que tu choisis le plus souvent à celui que tu choisis le moins.",
          o: ["🌙 Je pars en premier, sans bruit", "🕐 Je reste jusqu'au bout", "🚕 Je pars quand le groupe part"] },
    en: { q: "It's two in the morning — where are you?",
          ctx: "The night is good but it's dragging on. From the exit you choose most often to the one you choose least.",
          o: ["🌙 First to leave, quietly", "🕐 I stay until the end", "🚕 I leave when the group leaves"] } },
  { id: "am-serie", axis: "vices",
    fr: { q: "Une série te plaît : tu la regardes comment ?",
          ctx: "Huit épisodes viennent de sortir d'un coup. Du rythme le plus proche du tien au plus éloigné.",
          o: ["📺 Je binge tout d'un coup", "🗓️ Un épisode par soir", "⏳ J'attends que la saison soit finie"] },
    en: { q: "You like a series — how do you watch it?",
          ctx: "Eight episodes just dropped at once. From the pace closest to yours to the furthest.",
          o: ["📺 All of it, in one go", "🗓️ One episode a night", "⏳ I wait for the season to finish"] } },
  { id: "am-photo", axis: "vices",
    fr: { q: "En voyage, tu prends combien de photos ?",
          ctx: "Un endroit magnifique, la lumière est parfaite. De l'attitude la plus vraie pour toi à la moins vraie.",
          o: ["📷 J'en prends des centaines", "🖼️ Quelques-unes, bien choisies", "👀 Aucune, je profite"] },
    en: { q: "Travelling, how many photos do you take?",
          ctx: "A beautiful spot, and the light is perfect. From the truest answer for you to the least true.",
          o: ["📷 Hundreds of them", "🖼️ A few, carefully chosen", "👀 None, I'm just here"] } },
  { id: "am-retard", axis: "vices",
    fr: { q: "Rendez-vous à 20 h : tu arrives quand ?",
          ctx: "Un dîner chez des amis, sans excuse valable. Du plus fréquent chez toi au plus rare.",
          o: ["⏰ Toujours en avance", "🎯 Pile à l'heure", "🐢 Souvent un peu en retard"] },
    en: { q: "Meeting at eight — when do you show up?",
          ctx: "Dinner at a friend's, and you have no good excuse. From what you do most often to least.",
          o: ["⏰ Always early", "🎯 Exactly on time", "🐢 Usually a bit late"] } },
  { id: "am-lecture", axis: "gouts",
    fr: { q: "Un livre entre les mains, tu cherches quoi ?",
          ctx: "On t'en offre un, avec un dimanche pour le lire. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📚 Un roman, pour m'évader", "🧭 Un essai, pour apprendre", "🚫 Pas trop mon truc, en vrai"] },
    en: { q: "A book in your hands — what are you after?",
          ctx: "Someone gives you one, and you have a Sunday to read it. From the truest answer for you to the least true.",
          o: ["📚 A novel, to get away", "🧭 Non-fiction, to learn something", "🚫 Not really my thing, honestly"] } },
  { id: "am-cuisine-monde", axis: "gouts",
    fr: { q: "Une seule cuisine pendant un an : laquelle ?",
          ctx: "Midi et soir, sans exception, douze mois. De celle que tu tiendrais le plus longtemps à celle qui te lasserait en premier.",
          o: ["🍝 Italienne", "🍣 Japonaise", "🌮 Mexicaine"] },
    en: { q: "One cuisine for a whole year — which?",
          ctx: "Lunch and dinner, no exceptions, twelve months. From the one you'd last longest on to the one you'd tire of first.",
          o: ["🍝 Italian", "🍣 Japanese", "🌮 Mexican"] } },
  { id: "am-risque", axis: "rythme",
    fr: { q: "Le risque, tu le prends comment ?",
          ctx: "Parachute, changement de boulot, pari un peu fou : même réflexe. Du plus proche de toi au plus éloigné.",
          o: ["🪂 J'aime l'adrénaline", "⚖️ Calculé, jamais gratuit", "🛡️ Je préfère la sécurité"] },
    en: { q: "How do you handle risk?",
          ctx: "Skydiving, changing jobs, a slightly mad bet — same reflex. From closest to you to furthest.",
          o: ["🪂 I like the adrenaline", "⚖️ Calculated, never for nothing", "🛡️ I'd rather play it safe"] } },
  { id: "am-cafe", axis: "rythme",
    fr: { q: "Une heure rien qu'à toi : tu en fais quoi ?",
          ctx: "Pas de téléphone, pas d'obligation, juste toi. Du moment le plus ressourçant au moins ressourçant.",
          o: ["☕ Terrasse de café à observer", "🎧 Musique et marche", "🛁 À la maison au calme"] },
    en: { q: "One hour entirely yours — what do you do?",
          ctx: "No phone, nothing owed to anyone, just you. From the most restoring to the least.",
          o: ["☕ A café terrace, watching people", "🎧 Music and a long walk", "🛁 At home, in the quiet"] } },
  { id: "am-groupe-taille", axis: "autres",
    fr: { q: "Pour passer un bon moment, vous êtes combien ?",
          ctx: "Une sortie, un dîner, un week-end : le nombre idéal pour toi. De ta taille de groupe préférée à celle que tu aimes le moins.",
          o: ["👫 À deux", "👨‍👩‍👧 4 ou 5", "🎪 Le plus de monde possible"] },
    en: { q: "For a genuinely good time, how many of you?",
          ctx: "An outing, a dinner, a weekend — your ideal number. From your favourite group size to your least.",
          o: ["👫 Just the two of us", "👨‍👩‍👧 Four or five", "🎪 As many people as possible"] } },
  { id: "am-decision", axis: "rythme",
    fr: { q: "Une grosse décision à prendre : tu fais comment ?",
          ctx: "Déménager, changer de travail, dire oui ou non. De la méthode que tu utilises vraiment à celle que tu n'utilises jamais.",
          o: ["🧠 Je liste le pour et le contre", "❤️ Je suis mon instinct", "🗣️ Je demande conseil autour de moi"] },
    en: { q: "A big decision to make — how do you go about it?",
          ctx: "Moving, changing jobs, saying yes or no. From the method you actually use to the one you never use.",
          o: ["🧠 I list the pros and cons", "❤️ I follow my gut", "🗣️ I ask everyone around me"] } },
  { id: "am-competition", axis: "vices",
    fr: { q: "Soirée jeux de société : tu joues pour quoi ?",
          ctx: "Sois honnête, tes amis sont là pour vérifier. De la motivation la plus vraie pour toi à la moins vraie.",
          o: ["🏆 Je joue pour gagner", "😄 Je joue pour l'ambiance", "😈 Je joue pour saboter les autres"] },
    en: { q: "Board game night — what are you playing for?",
          ctx: "Be honest, your friends are right there to check. From the truest motive for you to the least true.",
          o: ["🏆 I play to win", "😄 I play for the atmosphere", "😈 I play to sabotage everyone"] } },
  { id: "am-saison", axis: "gouts",
    fr: { q: "Une seule saison toute l'année : laquelle ?",
          ctx: "Sans changement, avec tout ce que ça implique. De celle que tu choisirais à celle que tu ne supporterais pas.",
          o: ["☀️ Été", "🍂 Automne", "❄️ Hiver"] },
    en: { q: "One season all year round — which?",
          ctx: "No change at all, with everything that implies. From the one you'd choose to the one you couldn't stand.",
          o: ["☀️ Summer", "🍂 Autumn", "❄️ Winter"] } },
  { id: "am-message", axis: "vices",
    fr: { q: "Un ami t'écrit : tu réponds quand ?",
          ctx: "Un message normal, ni urgent ni important. Du délai le plus fréquent chez toi au plus rare.",
          o: ["⚡ Dans la minute", "🕒 Dans la journée", "📭 Quand j'y repense... parfois"] },
    en: { q: "A friend texts you — when do you reply?",
          ctx: "An ordinary message, neither urgent nor important. From your most common delay to your rarest.",
          o: ["⚡ Within the minute", "🕒 Same day", "📭 When I remember… sometimes"] } },
  { id: "am-souvenir", axis: "gouts",
    fr: { q: "De retour de voyage, tu ramènes quoi ?",
          ctx: "La valise a de la place, le budget aussi. De ce que tu rapportes toujours à ce que tu ne rapportes jamais.",
          o: ["🧲 Un objet souvenir", "🍫 De la nourriture locale", "📖 Juste des histoires"] },
    en: { q: "Home from a trip — what did you bring back?",
          ctx: "There's room in the suitcase, and in the budget. From what you always bring back to what you never do.",
          o: ["🧲 A souvenir object", "🍫 Local food", "📖 Just the stories"] } },

  // ---------------------------------------------- lot du 12/09/2026
  // Voir l'en-tête du lot dans piquant.js pour le champ `heat`.

  // --- rythme
  { id: "ry-reveil-sonne", axis: "rythme", heat: 2,
    fr: { q: "Le réveil sonne. Il se passe quoi ?",
          ctx: "Un matin ordinaire, il fait nuit, et le téléphone sonne sur la table de chevet. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["⏰ Debout à la première sonnerie, sans discuter", "😴 Trois snoozes, c'est prévu dans le calcul", "📱 Vingt minutes de scroll dans le noir"] },
    en: { q: "The alarm goes off. What happens?",
          ctx: "An ordinary morning, still dark, and the phone is buzzing on the bedside table. From the truest answer for you to the least true.",
          o: ["⏰ Up on the first alarm, no debate", "😴 Three snoozes, factored into the plan", "📱 Twenty minutes of scrolling in the dark"] } },
  { id: "ry-date-butoir", axis: "rythme", heat: 3,
    fr: { q: "Une démarche à faire avant une date limite",
          ctx: "Un formulaire à renvoyer, avec une date butoir dans un mois. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📬 Le jour même, pour ne plus y penser", "⏳ La veille de la date limite, vers minuit", "📆 Deux jours après, avec la pénalité"] },
    en: { q: "Paperwork with a deadline",
          ctx: "A form to send back, with a deadline a month away. From the truest answer for you to the least true.",
          o: ["📬 Same day, so I stop thinking about it", "⏳ The night before, around midnight", "📆 Two days late, with the penalty"] } },
  { id: "ry-trente-minutes", axis: "rythme", heat: 2,
    fr: { q: "Tu dois partir dans trente minutes",
          ctx: "Sortie prévue, il te reste trente minutes pour être présentable et dehors. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🚪 Déjà sur le pas de la porte, à attendre", "⚡ Huit minutes chrono, largement de quoi traîner", "💨 Je pars en retard, avec une chaussette humide"] },
    en: { q: "You have to leave in thirty minutes",
          ctx: "You're going out, and you have half an hour to be presentable and out the door. From the truest answer for you to the least true.",
          o: ["🚪 Already by the door, waiting", "⚡ Eight minutes flat, plenty of time to spare", "💨 I leave late, wearing one damp sock"] } },
  { id: "ry-vingt-avance", axis: "rythme", heat: 3,
    fr: { q: "Tu arrives vingt minutes en avance. Tu fais quoi ?",
          ctx: "Rendez-vous devant un café, et pour une fois tu es là avec vingt minutes à tuer. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🚶 Trois tours du pâté de maisons, l'air occupé", "☕ Je m'installe et je commande sans attendre", "📱 J'envoie « je suis là ! » pour mettre la pression"] },
    en: { q: "You arrive twenty minutes early. What now?",
          ctx: "Meeting outside a café, and for once you're there with twenty minutes to kill. From the truest answer for you to the least true.",
          o: ["🚶 Three laps of the block, looking busy", "☕ I sit down and order without waiting", "📱 I send « I'm here! » to apply pressure"] } },
  { id: "ry-nouvelle-passion", axis: "rythme", heat: 2,
    fr: { q: "Une nouvelle passion, ça dure combien chez toi ?",
          ctx: "Poterie, course à pied, guitare, échecs : tu viens de te découvrir une passion. Du plus fréquent chez toi au plus rare.",
          o: ["🔥 Trois semaines à fond, puis plus jamais", "🐢 Des années, à toute petite dose", "🛒 Le temps d'acheter tout le matériel"] },
    en: { q: "A new obsession — how long does it last?",
          ctx: "Pottery, running, guitar, chess: you've just discovered a passion. From what happens most often to least.",
          o: ["🔥 Three intense weeks, then never again", "🐢 Years, in very small doses", "🛒 Long enough to buy all the gear"] } },
  { id: "ry-choses-a-faire", axis: "rythme", heat: 1,
    fr: { q: "Tes choses à faire, tu les gères comment ?",
          ctx: "Courses, appel à passer, colis à renvoyer : la semaine s'accumule quelque part. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📝 Une liste, et je coche avec plaisir", "🧠 Tout dans ma tête, j'oublie la moitié", "📱 Trois applis et un post-it sur le frigo"] },
    en: { q: "How do you keep track of what you have to do?",
          ctx: "Shopping, a call to make, a parcel to return: the week piles up somewhere. From the truest answer for you to the least true.",
          o: ["📝 A list, and I tick things off happily", "🧠 All in my head, I forget half of it", "📱 Three apps and a note on the fridge"] } },
  { id: "ry-vitesse-repas", axis: "rythme", heat: 1,
    fr: { q: "Tu manges à quelle vitesse, en général ?",
          ctx: "Un repas à plusieurs, tout le monde est servi en même temps, et ça commence. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🍴 J'ai fini quand les autres commencent", "🐌 Toujours en dernier, l'assiette tiède", "👀 Je cale mon rythme sur celui de la table"] },
    en: { q: "How fast do you eat, generally?",
          ctx: "A meal with others, everyone served at the same time, and off we go. From the truest answer for you to the least true.",
          o: ["🍴 I'm done as the others are starting", "🐌 Always last, plate gone lukewarm", "👀 I match the pace of the table"] } },

  // --- goûts
  { id: "go-gout-defendu", axis: "gouts", heat: 1,
    fr: { q: "Quel goût tu défends contre tout le monde ?",
          ctx: "Quelqu'un fait la grimace devant ce que tu manges, et tu ne changeras pas. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🍍 L'ananas sur la pizza, sans discussion", "🥤 Le ketchup sur les pâtes, depuis toujours", "🍫 Le chocolat blanc, c'est du vrai chocolat"] },
    en: { q: "Which taste do you defend against everyone?",
          ctx: "Someone pulls a face at what you're eating, and you are not backing down. From the truest answer for you to the least true.",
          o: ["🍍 Pineapple on pizza, no debate", "🥤 Ketchup on pasta, always have", "🍫 White chocolate is real chocolate"] } },
  { id: "go-emission-zap", axis: "gouts", heat: 2,
    fr: { q: "Devant quelle émission tu ne zappes jamais ?",
          ctx: "Tu tombes dessus par hasard, un soir, et tu poses la télécommande sans réfléchir. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🌴 La télé-réalité avec villa et jacuzzi", "🍰 Le concours de pâtisserie où tout le monde pleure", "🔪 Le documentaire sur un tueur en série"] },
    en: { q: "Which show do you never switch away from?",
          ctx: "You land on it by accident one evening, and you put the remote down without thinking. From the truest answer for you to the least true.",
          o: ["🌴 Reality TV with a villa and a hot tub", "🍰 The baking contest where everyone cries", "🔪 The documentary about a serial killer"] } },
  { id: "go-tard-telephone", axis: "gouts", heat: 2,
    fr: { q: "Tard le soir, tu regardes quoi sur ton téléphone ?",
          ctx: "Il est tard, tu devrais dormir, et l'algorithme sait exactement quoi te proposer. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🧹 Des gens qui nettoient des tapis très sales", "🎤 Des interviews de gens que je ne connais pas", "🏠 Des visites d'appartements hors de prix"] },
    en: { q: "Late at night, what are you watching on your phone?",
          ctx: "It's late, you should be asleep, and the algorithm knows exactly what to hand you. From the truest answer for you to the least true.",
          o: ["🧹 People deep-cleaning filthy carpets", "🎤 Interviews with people I've never heard of", "🏠 Tours of flats nobody could afford"] } },
  { id: "go-repas-honte", axis: "gouts", heat: 3,
    fr: { q: "Quel repas tu n'avoues à personne ?",
          ctx: "Personne ne regarde, la cuisine est à toi, et le repas n'a rien d'une photo à publier. Du plus fréquent chez toi au plus rare.",
          o: ["🍝 Des pâtes au beurre, debout devant l'évier", "🥣 Des céréales à 23 h, dans le bol du matin", "🧀 Du fromage à même le papier, au couteau"] },
    en: { q: "Which meal do you admit to nobody?",
          ctx: "Nobody's watching, the kitchen is yours, and this is not going on anyone's feed. From what happens most often to least.",
          o: ["🍝 Buttered pasta, standing at the sink", "🥣 Cereal at eleven at night, in the morning bowl", "🧀 Cheese straight off the paper, with a knife"] } },
  { id: "go-mots-par-coeur", axis: "gouts", heat: 3,
    fr: { q: "Tu connais tous les mots de quoi, par cœur ?",
          ctx: "Ça démarre quelque part, et sans le vouloir tu récites tout, du début à la fin. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🎵 Le générique d'un dessin animé", "📺 Une pub qui ne passe plus depuis dix ans", "🎤 Une chanson que je déteste officiellement"] },
    en: { q: "What do you know every single word of?",
          ctx: "It starts somewhere, and without meaning to you recite the whole thing, start to finish. From the truest answer for you to the least true.",
          o: ["🎵 A cartoon theme tune", "📺 An advert that stopped airing ten years ago", "🎤 A song I officially hate"] } },
  { id: "go-collection-secrete", axis: "gouts", heat: 3,
    fr: { q: "Qu'est-ce que tu collectionnes sans l'avouer ?",
          ctx: "Un tiroir, une boîte à chaussures, un coin de placard : ça s'accumule sans que personne le sache. Du plus fréquent chez toi au plus rare.",
          o: ["🧴 Les petits savons et shampoings d'hôtel", "🎫 Les tickets de concert, de musée, de cinéma", "👜 Les sacs en papier des belles boutiques"] },
    en: { q: "What do you collect without admitting it?",
          ctx: "A drawer, a shoebox, a corner of a cupboard: it piles up and nobody knows. From what happens most often to least.",
          o: ["🧴 Tiny hotel soaps and shampoos", "🎫 Tickets from gigs, museums, cinemas", "👜 Paper bags from the nice shops"] } },
];
