// Are We A Match? — pack 👯 Amis.
// Goûts et modes de vie généraux : ça marche avec n'importe qui.
//
// Chaque question :
//   q   — une vraie question, courte, affichée en gros.
//   ctx — la scène en une phrase, puis le critère de classement (« du plus
//         tentant au moins tentant », « du plus « toi » au moins « toi »… »).
//         C'est lui qui lève l'ambiguïté : « préféré » ne veut rien dire pour
//         « face à un désaccord », « ce que tu ferais vraiment » si.
//   o   — 3 options à classer, pensées pour être CLIVANTES (pas d'option
//         « évidemment meilleure ») : c'est ce qui étale les scores de
//         compatibilité et rend les résultats parlants.
//
// RÈGLE DE STABILITÉ — les réponses mémorisées dans les comptes sont des
// classements d'INDEX dans `o`, rangés par `id`. Donc, pour une question
// existante : `id` ne change jamais, et les options gardent leur ORDRE et leur
// SENS (retoucher la formulation est permis, permuter ou remplacer une option
// ne l'est pas — ça fausserait les compatibilités historiques en silence).

module.exports = [
  { id: "am-weekend", q: "C'est quoi, ton week-end parfait ?",
    ctx: "Deux jours libres, météo parfaite, zéro obligation. Du plus tentant au moins tentant.",
    o: ["🏔️ Rando et grand air", "🥐 Brunch puis expo", "🛋️ Canapé, série, zéro contrainte"] },
  { id: "am-soiree", q: "Vendredi soir, on fait quoi ?",
    ctx: "Semaine finie, tout le monde est libre. De la soirée que tu proposes en premier à celle que tu évites.",
    o: ["🕺 Bar bondé et musique forte", "🍲 Dîner à 4 à la maison", "🎬 Ciné puis debrief"] },
  { id: "am-vacances", q: "En vacances, tu fonctionnes comment ?",
    ctx: "Une semaine ailleurs avec les copains. De la façon de faire qui te ressemble le plus à celle qui te ressemble le moins.",
    o: ["🗺️ Tout planifier à l'avance", "🎲 Improviser sur place", "🏖️ Ne rien faire du tout"] },
  { id: "am-reveil", q: "Un matin sans réveil, tu te lèves quand ?",
    ctx: "Personne ne t'attend, rien ne presse. Du réveil qui te ressemble le plus à celui qui te ressemble le moins.",
    o: ["🌅 Debout à 6h, la journée est à moi", "☕ 8h avec un café, tranquille", "😴 Le plus tard possible"] },
  { id: "am-resto", q: "Au resto, tu commandes quoi ?",
    ctx: "Nouvelle adresse, carte inconnue, le serveur attend. Du réflexe le plus « toi » au moins « toi ».",
    o: ["🍜 Un truc que tu n'as jamais goûté", "🥩 Ta valeur sûre habituelle", "🌱 L'option la plus saine"] },
  { id: "am-musique", q: "On te tend l'enceinte : tu mets quoi ?",
    ctx: "Soirée entre amis, la playlist est à toi. De l'ambiance que tu lances en premier à celle que tu évites.",
    o: ["🎸 Rock / guitares", "🎧 Électro / house", "🎤 Variété et sing-along"] },
  { id: "am-transport", q: "Trois heures de trajet : tu voyages comment ?",
    ctx: "Même prix, même heure d'arrivée. De ta façon de voyager préférée à celle que tu subis.",
    o: ["🚗 Voiture, on s'arrête où on veut", "🚆 Train, je lis / je dors", "✈️ Avion, le plus vite possible"] },
  { id: "am-argent", q: "Une prime tombe : tu en fais quoi ?",
    ctx: "Une somme inattendue, sans besoin urgent. Du réflexe le plus « toi » au moins « toi ».",
    o: ["🐿️ J'épargne d'abord", "🎈 Je dépense pour les expériences", "📊 Je calcule et j'optimise tout"] },
  { id: "am-conflit", q: "Un ami t'a blessé : tu réagis comment ?",
    ctx: "Rien de grave, mais ça t'est resté en travers. De ce que tu ferais vraiment à ce que tu ne ferais jamais.",
    o: ["🗣️ On en parle tout de suite", "⏳ Je laisse retomber puis j'en parle", "🤐 J'évite, ça finit par passer"] },
  { id: "am-samedi", q: "Samedi après-midi, rien de prévu : tu fais quoi ?",
    ctx: "Les corvées sont faites, le téléphone est calme. Du plus tentant au moins tentant.",
    o: ["🏃 Du sport", "🛍️ Traîner en ville", "🎮 Jeu vidéo / lecture au calme"] },
  { id: "am-cuisine", q: "Le soir, pour manger, tu fais quoi ?",
    ctx: "Un soir de semaine ordinaire, personne à impressionner. Du plus fréquent chez toi au plus rare.",
    o: ["👨‍🍳 Je cuisine, ça me détend", "🥡 Je commande, la vie est courte", "🍳 Le minimum vital"] },
  { id: "am-anniv", q: "Ton anniversaire, tu le fêtes comment ?",
    ctx: "C'est toi qui décides, personne ne t'impose rien. De ce qui te fait vraiment plaisir à ce que tu redoutes.",
    o: ["🎉 Grosse fête, tout le monde", "🍷 Dîner avec 5 personnes", "🤫 Rien du tout, on n'en parle pas"] },
  { id: "am-sport", q: "Bouger, pour toi, ça ressemble à quoi ?",
    ctx: "Une activité régulière, pas un exploit par an. De ce qui te motive le plus à ce qui te motive le moins.",
    o: ["⚽ Sport collectif", "🏋️ Salle / solo", "🚶 Marcher, c'est déjà bien"] },
  { id: "am-tel", q: "En soirée, ton téléphone est où ?",
    ctx: "Une bonne soirée entre amis, comme celle-ci. De l'attitude la plus honnête à ton sujet à la moins honnête.",
    o: ["📵 Rangé, je suis là", "📸 Je prends des photos", "📱 Je scrolle un peu quand même"] },
  { id: "am-menage", q: "Chez toi, ça ressemble à quoi un mardi soir ?",
    ctx: "Pas le jour où tu reçois : un jour normal. Du plus proche de la réalité au plus éloigné.",
    o: ["🧽 Impeccable en permanence", "🌀 Bordel organisé, je m'y retrouve", "🙈 On verra la semaine prochaine"] },
  { id: "am-film", q: "Film ce soir : tu choisis quoi ?",
    ctx: "Canapé, plaid, la télécommande est à toi. Du genre que tu lances en premier à celui que tu gardes pour une autre fois.",
    o: ["😂 Comédie qui détend", "🧠 Un truc qui fait réfléchir", "💥 Action, pop-corn, zéro prise de tête"] },
  { id: "am-ville", q: "Vivre n'importe où : ce serait où ?",
    ctx: "Le boulot suit, les amis aussi, seul le cadre change. De ce qui te fait rêver à ce qui te fait fuir.",
    o: ["🏙️ Grande ville qui bouge", "🏡 Petite ville tranquille", "🌾 Carrément la campagne"] },
  { id: "am-matin", q: "Le petit-déj, c'est quoi pour toi ?",
    ctx: "Un dimanche matin, avec le temps de le préparer. Du plus tentant au moins tentant.",
    o: ["🥓 Salé et copieux", "🥐 Sucré, viennoiserie", "☕ Juste un café"] },
  { id: "am-cadeau", q: "Quel cadeau te fait le plus plaisir ?",
    ctx: "Même budget, même intention derrière. De celui qui te touche le plus à celui qui te touche le moins.",
    o: ["🎟️ Une expérience à vivre", "📦 Un objet bien choisi", "💌 Quelque chose de fait main"] },
  { id: "am-groupe", q: "Dans une bande d'amis, tu es qui ?",
    ctx: "Sois honnête, pas flatteur. Du rôle que tu tiens le plus souvent à celui que tu tiens le moins.",
    o: ["📣 Celui ou celle qui organise", "🎭 Celui ou celle qui met l'ambiance", "👂 Celui ou celle qui écoute"] },
  { id: "am-boisson", q: "À l'apéro, tu bois quoi ?",
    ctx: "Terrasse, fin de journée, on prend la commande. Du verre que tu demandes en premier au dernier.",
    o: ["🍺 Bière", "🍷 Vin", "🍹 Cocktail"] },
  { id: "am-imprevu", q: "On annule le plan une heure avant : tu ressens quoi ?",
    ctx: "Tu étais prêt, tu allais partir. De la réaction la plus vraie pour toi à la moins vraie.",
    o: ["😤 Ça m'agace vraiment", "🤷 Aucun souci, je m'adapte", "🎉 Secrètement soulagé(e)"] },
  { id: "am-voyage-type", q: "Deux semaines de voyage : tu pars comment ?",
    ctx: "Même destination, même budget, trois manières de la vivre. De celle qui te fait rêver à celle qui te tente le moins.",
    o: ["🎒 Sac à dos, auberges, imprévu", "🏨 Hôtel confortable, tout organisé", "🚐 Van, on dort où on veut"] },
  { id: "am-social", q: "Après une semaine épuisante, il te faut quoi ?",
    ctx: "Vendredi 19 h, batterie à plat. Du besoin le plus urgent pour toi au moins urgent.",
    o: ["🥳 J'ai besoin de voir du monde", "🧘 J'ai besoin d'être seul(e)", "👥 Une ou deux personnes max"] },
  { id: "am-deco", q: "Chez toi, c'est quel genre de déco ?",
    ctx: "Ou celle que tu aurais avec carte blanche. Du style le plus proche de toi au plus éloigné.",
    o: ["🪴 Chaleureux, plein de trucs", "⬜ Minimaliste et épuré", "🎨 Coloré et assumé"] },
  { id: "am-humour", q: "Qu'est-ce qui te fait vraiment rire ?",
    ctx: "Le rire sincère, celui qu'on ne contrôle pas. De ce qui te fait pleurer de rire à ce qui te laisse de marbre.",
    o: ["🙃 Absurde", "🗡️ Sarcastique / cynique", "🤪 Bon gros humour bête"] },
  { id: "am-planning", q: "Ton agenda de la semaine ressemble à quoi ?",
    ctx: "Pas celui du travail : celui de ta vie perso. Du plus proche du tien au plus éloigné.",
    o: ["📅 Rempli et planifié", "✏️ Quelques repères, souple", "🌊 Rien, je vis au jour le jour"] },
  { id: "am-animal", q: "Chez toi, quel animal aurait sa place ?",
    ctx: "Tu as la place, le temps et le budget. De ce qui te fait plaisir à ce que tu refuses.",
    o: ["🐕 Chien", "🐈 Chat", "🚫 Aucun animal chez moi"] },
  { id: "am-debat", q: "Le ton monte à table : tu fais quoi ?",
    ctx: "Un vrai débat, des avis tranchés, personne ne lâche. De l'attitude que tu adoptes le plus à celle que tu adoptes le moins.",
    o: ["🔥 J'adore, je fonce", "🙂 J'écoute et je nuance", "😬 Ça me met mal à l'aise"] },
  { id: "am-vetements", q: "Tu t'habilles comment au quotidien ?",
    ctx: "Un jour normal, ni mariage ni dimanche malade. Du style le plus proche du tien au plus éloigné.",
    o: ["👔 Soigné, ça compte", "👟 Confort avant tout", "🧢 Décontracté mais pensé"] },
  { id: "am-nouveau", q: "Une nouveauté débarque : tu réagis comment ?",
    ctx: "Une appli, un resto, une activité dont tout le monde parle. Du réflexe le plus « toi » au moins « toi ».",
    o: ["🚀 Je teste tout de suite", "🔍 Je me renseigne d'abord", "⏸️ J'attends que d'autres essaient"] },
  { id: "am-fete-fin", q: "Il est 2 h du matin : tu es où ?",
    ctx: "La soirée est bonne mais elle s'étire. Du départ que tu choisis le plus souvent à celui que tu choisis le moins.",
    o: ["🌙 Je pars en premier, sans bruit", "🕐 Je reste jusqu'au bout", "🚕 Je pars quand le groupe part"] },
  { id: "am-serie", q: "Une série te plaît : tu la regardes comment ?",
    ctx: "Huit épisodes viennent de sortir d'un coup. Du rythme le plus proche du tien au plus éloigné.",
    o: ["📺 Je binge tout d'un coup", "🗓️ Un épisode par soir", "⏳ J'attends que la saison soit finie"] },
  { id: "am-photo", q: "En voyage, tu prends combien de photos ?",
    ctx: "Un endroit magnifique, la lumière est parfaite. De l'attitude la plus vraie pour toi à la moins vraie.",
    o: ["📷 J'en prends des centaines", "🖼️ Quelques-unes, bien choisies", "👀 Aucune, je profite"] },
  { id: "am-retard", q: "Rendez-vous à 20 h : tu arrives quand ?",
    ctx: "Un dîner chez des amis, sans excuse valable. Du plus fréquent chez toi au plus rare.",
    o: ["⏰ Toujours en avance", "🎯 Pile à l'heure", "🐢 Souvent un peu en retard"] },
  { id: "am-lecture", q: "Un livre entre les mains, tu cherches quoi ?",
    ctx: "On t'en offre un, avec un dimanche pour le lire. De la réponse la plus vraie pour toi à la moins vraie.",
    o: ["📚 Un roman, pour m'évader", "🧭 Un essai, pour apprendre", "🚫 Pas trop mon truc, en vrai"] },
  { id: "am-cuisine-monde", q: "Une seule cuisine pendant un an : laquelle ?",
    ctx: "Midi et soir, sans exception, douze mois. De celle que tu tiendrais le plus longtemps à celle qui te lasserait en premier.",
    o: ["🍝 Italienne", "🍣 Japonaise", "🌮 Mexicaine"] },
  { id: "am-risque", q: "Le risque, tu le prends comment ?",
    ctx: "Parachute, changement de boulot, pari un peu fou : même réflexe. Du plus proche de toi au plus éloigné.",
    o: ["🪂 J'aime l'adrénaline", "⚖️ Calculé, jamais gratuit", "🛡️ Je préfère la sécurité"] },
  { id: "am-cafe", q: "Une heure rien qu'à toi : tu en fais quoi ?",
    ctx: "Pas de téléphone, pas d'obligation, juste toi. Du moment le plus ressourçant au moins ressourçant.",
    o: ["☕ Terrasse de café à observer", "🎧 Musique et marche", "🛁 À la maison au calme"] },
  { id: "am-groupe-taille", q: "Pour passer un bon moment, vous êtes combien ?",
    ctx: "Une sortie, un dîner, un week-end : le nombre idéal pour toi. De ta taille de groupe préférée à celle que tu aimes le moins.",
    o: ["👫 À deux", "👨‍👩‍👧 4 ou 5", "🎪 Le plus de monde possible"] },
  { id: "am-decision", q: "Une grosse décision à prendre : tu fais comment ?",
    ctx: "Déménager, changer de travail, dire oui ou non. De la méthode que tu utilises vraiment à celle que tu n'utilises jamais.",
    o: ["🧠 Je liste le pour et le contre", "❤️ Je suis mon instinct", "🗣️ Je demande conseil autour de moi"] },
  { id: "am-competition", q: "Soirée jeux de société : tu joues pour quoi ?",
    ctx: "Sois honnête, tes amis sont là pour vérifier. De la motivation la plus vraie pour toi à la moins vraie.",
    o: ["🏆 Je joue pour gagner", "😄 Je joue pour l'ambiance", "😈 Je joue pour saboter les autres"] },
  { id: "am-saison", q: "Une seule saison toute l'année : laquelle ?",
    ctx: "Sans changement, avec tout ce que ça implique. De celle que tu choisirais à celle que tu ne supporterais pas.",
    o: ["☀️ Été", "🍂 Automne", "❄️ Hiver"] },
  { id: "am-message", q: "Un ami t'écrit : tu réponds quand ?",
    ctx: "Un message normal, ni urgent ni important. Du délai le plus fréquent chez toi au plus rare.",
    o: ["⚡ Dans la minute", "🕒 Dans la journée", "📭 Quand j'y repense... parfois"] },
  { id: "am-souvenir", q: "De retour de voyage, tu ramènes quoi ?",
    ctx: "La valise a de la place, le budget aussi. De ce que tu rapportes toujours à ce que tu ne rapportes jamais.",
    o: ["🧲 Un objet souvenir", "🍫 De la nourriture locale", "📖 Juste des histoires"] },
];
