// Are We A Match? — pack 💘 Date.
// Orienté romantique / vie à deux : idéal en tête-à-tête, mais jouable en
// groupe (et souvent très drôle). Options clivantes, jamais de « bonne »
// réponse évidente.

module.exports = [
  { id: "dt-premier-rdv", q: "Le premier rendez-vous idéal", o: ["🍸 Un verre en terrasse", "🖼️ Une expo ou un musée", "🚶 Une longue balade"] },
  { id: "dt-qualite", q: "Ce qui compte le plus chez l'autre", o: ["😂 L'humour", "🧠 La curiosité", "🫂 La douceur"] },
  { id: "dt-dimanche", q: "Un dimanche à deux", o: ["🛌 Grasse matinée sans culpabilité", "🥾 Sortir tôt, bouger", "🍳 Cuisiner ensemble toute la journée"] },
  { id: "dt-amour-langage", q: "Tu te sens aimé(e) quand on te", o: ["💬 Dit les choses", "🎁 Fait des attentions", "🤗 Prend dans les bras"] },
  { id: "dt-dispute", q: "Après une dispute", o: ["🗣️ On règle ça avant de dormir", "🌙 On dort dessus et on reparle demain", "🤍 Un geste vaut mieux qu'un discours"] },
  { id: "dt-soiree-couple", q: "Une soirée à deux, plutôt", o: ["🍽️ Resto qu'on ne connaît pas", "🍿 Plaid et film à la maison", "🎶 Concert ou sortie"] },
  { id: "dt-red-flag", q: "Le plus rédhibitoire", o: ["🙄 Impoli avec les serveurs", "📵 Toujours sur son téléphone", "⏰ Systématiquement en retard"] },
  { id: "dt-voyage-duo", q: "Le voyage à deux qui te fait rêver", o: ["🏝️ Plage et rien faire", "🏛️ City-trip culturel", "⛰️ Aventure et nature"] },
  { id: "dt-rythme", q: "Le rythme d'une relation", o: ["🐇 Vite et intensément", "🐢 Doucement, on construit", "🌀 On verra bien, sans plan"] },
  { id: "dt-espace", q: "L'espace personnel dans un couple", o: ["👯 On fait presque tout ensemble", "⚖️ Un bon équilibre chacun/ensemble", "🚪 Chacun sa bulle, c'est vital"] },
  { id: "dt-surprise", q: "Les surprises", o: ["🎉 J'adore en recevoir", "🎁 Je préfère en faire", "😅 Je déteste ça, préviens-moi"] },
  { id: "dt-social-couple", q: "En couple, le week-end", o: ["👥 On voit du monde", "🏠 On reste tous les deux", "🔀 Un peu des deux"] },
  { id: "dt-ex", q: "Parler de ses ex", o: ["📖 Ouvertement, c'est sain", "🤏 Le strict minimum", "🚫 Jamais, page tournée"] },
  { id: "dt-projet", q: "Le projet à deux le plus excitant", o: ["🏡 Emménager ensemble", "🌍 Partir 6 mois en voyage", "🐕 Adopter un animal"] },
  { id: "dt-cadeau-couple", q: "Le cadeau qui te touche le plus", o: ["✍️ Une lettre", "🎟️ Une expérience à deux", "💍 Un objet qui dure"] },
  { id: "dt-jalousie", q: "Ton rapport à la jalousie", o: ["😌 Aucune, confiance totale", "🌡️ Un peu, c'est humain", "🔥 Assez, je l'assume"] },
  { id: "dt-vie-quotidienne", q: "Au quotidien à deux, tu tiens à", o: ["🍽️ Manger ensemble le soir", "💤 Se coucher en même temps", "☕ Un rituel du matin"] },
  { id: "dt-humour-couple", q: "Dans le couple, l'humour c'est", o: ["🤣 Se vanner en permanence", "😊 Des blagues complices privées", "🙂 Pas central, franchement"] },
  { id: "dt-famille", q: "Rencontrer la famille", o: ["⚡ Vite, autant savoir", "🕰️ Quand c'est sérieux", "😬 Le plus tard possible"] },
  { id: "dt-argent-couple", q: "L'argent à deux", o: ["🏦 Tout en commun", "➗ Chacun le sien, on partage", "🧮 Au prorata des revenus"] },
  { id: "dt-sortie-imprevue", q: "Il ou elle propose un plan à 22 h", o: ["🚀 Je dis oui direct", "🤔 Ça dépend du plan", "🛌 Non, j'étais bien"] },
  { id: "dt-declaration", q: "Dire « je t'aime »", o: ["💨 Le premier qui le sent le dit", "⏳ Ça se mérite, plus tard", "🎭 Je le montre plus que je le dis"] },
  { id: "dt-serie-couple", q: "Regarder une série à deux", o: ["🔒 Interdiction d'avancer sans l'autre", "🤷 Chacun son rythme", "📺 On ne regarde pas les mêmes trucs"] },
  { id: "dt-anniv-couple", q: "Les dates d'anniversaire de couple", o: ["📆 Sacrées, on fête tout", "🎂 Juste la principale", "🙃 On oublie et c'est pas grave"] },
  { id: "dt-conflit-style", q: "En désaccord, tu es plutôt", o: ["🌋 Expressif, ça sort", "🧊 Calme et posé", "🚶 J'ai besoin de sortir marcher"] },
  { id: "dt-routine", q: "La routine dans un couple", o: ["🏠 Rassurante, j'aime ça", "😰 Dangereuse, il faut la casser", "⚖️ Bonne si on garde des surprises"] },
  { id: "dt-reseaux", q: "Le couple sur les réseaux", o: ["📸 On assume, on poste", "🤐 Zéro publication", "🫥 Quelques photos, discret"] },
  { id: "dt-cuisine-couple", q: "À la maison, qui cuisine", o: ["👨‍🍳 Moi, avec plaisir", "🤝 On cuisine à deux", "🛵 Ni l'un ni l'autre, on commande"] },
  { id: "dt-week-surprise", q: "Un week-end surprise organisé pour toi", o: ["😍 Le rêve absolu", "🙂 Sympa si je peux préparer un sac", "😨 L'angoisse, j'aime savoir"] },
  { id: "dt-solitude", q: "Une soirée chacun de son côté", o: ["👍 Sain et nécessaire", "😐 Ok mais pas trop souvent", "😕 Ça me manque tout de suite"] },
  { id: "dt-avenir", q: "Parler d'avenir", o: ["🔭 Tôt et clairement", "🌱 Progressivement", "🎈 Le moins possible, on vit"] },
  { id: "dt-attention", q: "L'attention qui te fait fondre", o: ["☕ Un café apporté au lit", "📩 Un message inattendu dans la journée", "🎧 Une playlist faite pour toi"] },
  { id: "dt-sport-couple", q: "Faire du sport à deux", o: ["💪 Oui, ça soude", "🚫 Non, chacun son truc", "🚶 Juste des balades"] },
  { id: "dt-fete", q: "En soirée avec ton/ta partenaire", o: ["🤝 On reste ensemble", "🦋 Chacun circule, on se retrouve", "👀 On se surveille du coin de l'œil"] },
  { id: "dt-vacances-duo", q: "En vacances à deux", o: ["📋 Programme chargé", "😌 Zéro programme", "🎯 Un ou deux temps forts, sinon libre"] },
  { id: "dt-desaccord-gout", q: "Vous n'aimez pas les mêmes choses", o: ["🎉 Génial, on se découvre", "😬 Compliqué à la longue", "🤷 Chacun ses trucs, on s'en fiche"] },
  { id: "dt-priorite", q: "Ta priorité dans la vie à deux", o: ["🕊️ La liberté de chacun", "🔗 La complicité", "🏗️ Construire quelque chose"] },
  { id: "dt-tendresse", q: "La tendresse au quotidien", o: ["🤲 Beaucoup de contact physique", "🗨️ Des mots et des attentions", "🎯 Des actes concrets"] },
  { id: "dt-sortie-type", q: "Si on te laisse choisir la sortie", o: ["🎭 Théâtre / spectacle", "🍽️ Un bon repas", "🎡 Une activité un peu bête et drôle"] },
  { id: "dt-nuit", q: "Le soir, tu es", o: ["🦉 Couche-tard, la nuit est à moi", "🐓 Couche-tôt sans hésiter", "🔁 Ça dépend complètement"] },
  { id: "dt-partage", q: "Ce que tu partages le plus facilement", o: ["😢 Tes émotions", "🧩 Tes projets et tes idées", "📅 Ton quotidien concret"] },
  { id: "dt-effort", q: "Un couple qui dure, c'est surtout", o: ["🛠️ Du travail volontaire", "🍀 Beaucoup de chance et d'alchimie", "🗣️ De la communication constante"] },
  { id: "dt-cadeau-anniv", q: "Pour son anniversaire, tu offres", o: ["🎁 Un cadeau matériel réfléchi", "🌍 Un week-end quelque part", "🍾 Une soirée organisée avec ses proches"] },
  { id: "dt-rencontre", q: "La plus belle façon de se rencontrer", o: ["🎲 Par hasard dans la vraie vie", "🤝 Par des amis en commun", "📱 Sur une appli, assumé"] },
  { id: "dt-silence", q: "Les silences à deux", o: ["😌 Confortables, j'adore", "😅 Un peu gênants", "🗣️ Je préfère qu'on parle"] },
];
