// Are We A Match? — les scènes sur LE RAPPORT AUX AUTRES.
//
// Le fichier s'appelle encore date.js et son pack garde l'id « date » : cet id
// est la clé sous laquelle les réponses sont rangées dans les profils, il ne
// bouge pas. En revanche le contenu a changé de nature. Il ne s'agit plus de
// vie de couple : toutes les scènes ici passent LE TEST DES TROIS RELATIONS —
// elles ont du sens classées entre toi et ta mère, toi et ton meilleur pote,
// et toi et ton/ta partenaire. Ce qui présupposait un couple (« En couple, le
// week-end », « Dire je t'aime », « L'argent à deux ») est parti.
//
// Format, identique au pack amis :
//   q    — une vraie question, courte, affichée en gros.
//   ctx  — la scène en une phrase, PUIS le sens du classement. Sans lui,
//          « classer » ne veut rien dire, et deux joueurs qui lisent la
//          consigne à l'envers produisent un désaccord qui n'existe pas.
//   o    — 3 options clivantes (aucune socialement « juste »).
//   axis — ce que la scène révèle. Sert au tirage équilibré (games.js).
//
// RÈGLE DE STABILITÉ — les réponses mémorisées sont des classements d'INDEX
// dans `o`, rangés par `id`. Pour une scène existante : `id` ne change jamais,
// et les options gardent leur ORDRE et leur SENS. Une scène réécrite reçoit
// donc un NOUVEL id (ici le préfixe dit l'axe : au- / go- / ry- / ag-), et les
// anciennes réponses sont ignorées proprement plutôt que réinterprétées.

module.exports = [
  { id: "au-accroche", axis: "autres",
    fr: { q: "Chez quelqu'un, qu'est-ce qui te fait accrocher ?",
          ctx: "Pas les cinq premières minutes : ce qui te donne envie de revenir. Du plus décisif pour toi au moins décisif.",
          o: ["😂 L'humour", "🧠 La curiosité", "🫂 La douceur"] },
    en: { q: "What makes you want to see someone again?",
          ctx: "Not the first five minutes — what makes you come back. From most decisive for you to least.",
          o: ["😂 Their humour", "🧠 Their curiosity", "🫂 Their gentleness"] } },
  { id: "au-aime", axis: "autres",
    fr: { q: "Tu te sens aimé quand on te fait quoi ?",
          ctx: "Par un ami, un parent, un amoureux — la question est la même. Du geste qui te touche le plus à celui qui te touche le moins.",
          o: ["💬 On te dit les choses", "🎁 On a des attentions", "🤗 On te prend dans les bras"] },
    en: { q: "You feel loved when someone does what?",
          ctx: "From a friend, a parent, a partner — same question. From the gesture that moves you most to the least.",
          o: ["💬 Says it out loud", "🎁 Does thoughtful things", "🤗 Actually hugs you"] } },
  { id: "au-apres-engueulade", axis: "autres",
    fr: { q: "Vous venez de vous engueuler. Et maintenant ?",
          ctx: "Rien de grave, mais le ton est monté et la soirée est gâchée. Du réflexe le plus vrai pour toi au moins vrai.",
          o: ["🗣️ On règle ça avant de dormir", "🌙 On dort dessus, on en reparle demain", "🤍 Un geste vaut mieux qu'un discours"] },
    en: { q: "You've just had a row. What now?",
          ctx: "Nothing serious, but voices were raised and the evening is ruined. From the truest reflex for you to the least true.",
          o: ["🗣️ We sort it before bed", "🌙 Sleep on it, talk tomorrow", "🤍 A gesture beats a speech"] } },
  { id: "au-desaccord", axis: "autres",
    fr: { q: "En plein désaccord, tu deviens comment ?",
          ctx: "Pas un débat d'idées : un vrai désaccord avec quelqu'un qui compte. Du plus proche de toi au plus éloigné.",
          o: ["🌋 Expressif, ça sort", "🧊 Calme et posé", "🚶 J'ai besoin de sortir marcher"] },
    en: { q: "In a real disagreement, what do you become?",
          ctx: "Not a debate about ideas: a real disagreement with someone who matters. From closest to you to furthest.",
          o: ["🌋 Expressive, it comes out", "🧊 Calm and measured", "🚶 I need to go and walk"] } },
  { id: "au-surprises", axis: "autres",
    fr: { q: "Les surprises, toi, tu en es où ?",
          ctx: "Une fête surprise, un cadeau imprévu, un plan qu'on ne t'a pas annoncé. Du plus proche de toi au plus éloigné.",
          o: ["🎉 J'adore en recevoir", "🎁 Je préfère en faire", "😅 Je déteste ça, préviens-moi"] },
    en: { q: "Surprises — where do you stand?",
          ctx: "A surprise party, an unexpected gift, a plan nobody warned you about. From closest to you to furthest.",
          o: ["🎉 I love being on the receiving end", "🎁 I'd rather be the one doing it", "😅 I hate it, warn me"] } },
  { id: "au-attention", axis: "autres",
    fr: { q: "Quelle attention te fait le plus plaisir ?",
          ctx: "De quelqu'un qui compte, un jour parfaitement ordinaire. De celle qui te touche le plus à celle qui te touche le moins.",
          o: ["☕ Un café apporté au lit", "📩 Un message inattendu dans la journée", "🎧 Une playlist faite pour toi"] },
    en: { q: "Which small gesture means the most?",
          ctx: "From someone who matters, on a completely ordinary day. From the one that moves you most to the least.",
          o: ["☕ A coffee brought to you in bed", "📩 An unexpected message mid-day", "🎧 A playlist made for you"] } },
  { id: "au-gouts-opposes", axis: "autres",
    fr: { q: "Quelqu'un que tu aimes n'aime rien de ce que tu aimes",
          ctx: "Ni tes films, ni ta musique, ni tes restos. De ta vraie réaction à celle que tu n'aurais jamais.",
          o: ["🎉 Génial, on se découvre", "😬 Compliqué à la longue", "🤷 Chacun ses trucs, on s'en fiche"] },
    en: { q: "Someone you love likes none of what you like",
          ctx: "Not your films, not your music, not your restaurants. From your real reaction to the one you'd never have.",
          o: ["🎉 Great, we discover things", "😬 Difficult in the long run", "🤷 Each to their own, who cares"] } },
  { id: "au-priorite", axis: "autres",
    fr: { q: "Dans une relation qui compte, tu tiens à quoi ?",
          ctx: "Amitié, famille, amour : même question. Du plus vital pour toi au moins vital.",
          o: ["🕊️ La liberté de chacun", "🔗 La complicité", "🏗️ Construire quelque chose"] },
    en: { q: "In a relationship that matters, what do you need?",
          ctx: "Friendship, family, love: same question. From most vital for you to least.",
          o: ["🕊️ Room for each of us", "🔗 Being properly in sync", "🏗️ Building something together"] } },
  { id: "au-partage", axis: "autres",
    fr: { q: "Qu'est-ce que tu racontes le plus facilement ?",
          ctx: "À quelqu'un de proche, un soir ordinaire, sans qu'on te tire les vers du nez. Du plus facile à sortir au plus difficile.",
          o: ["😢 Tes émotions", "🧩 Tes projets et tes idées", "📅 Ton quotidien concret"] },
    en: { q: "What do you talk about most easily?",
          ctx: "To someone close, an ordinary evening, with nobody dragging it out of you. From easiest to say to hardest.",
          o: ["😢 Your feelings", "🧩 Your plans and ideas", "📅 The practical details of your day"] } },
  { id: "au-durer", axis: "autres",
    fr: { q: "Une relation qui dure, ça tient à quoi ?",
          ctx: "Une amitié de vingt ans, un couple, une famille. Du plus décisif selon toi au moins décisif.",
          o: ["🛠️ Du travail volontaire", "🍀 De la chance et de l'alchimie", "🗣️ De la communication constante"] },
    en: { q: "What makes a relationship last?",
          ctx: "A twenty-year friendship, a couple, a family. From most decisive in your view to least.",
          o: ["🛠️ Deliberate work", "🍀 Luck and chemistry", "🗣️ Talking, constantly"] } },
  { id: "au-cadeau-offert", axis: "autres",
    fr: { q: "Pour l'anniversaire de quelqu'un, tu offres quoi ?",
          ctx: "Même budget à chaque fois, quelqu'un que tu aimes bien. De ce que tu offres le plus souvent au plus rare.",
          o: ["🎁 Un objet réfléchi", "🌍 Un week-end quelque part", "🍾 Une soirée avec ses proches"] },
    en: { q: "For someone's birthday, what do you give?",
          ctx: "Same budget every time, someone you're fond of. From what you give most often to least.",
          o: ["🎁 A carefully chosen object", "🌍 A weekend somewhere", "🍾 An evening with the people they love"] } },
  { id: "au-silence", axis: "autres",
    fr: { q: "Un silence s'installe. Tu le vis comment ?",
          ctx: "Vous êtes deux, personne n'a parlé depuis une minute. Du plus vrai pour toi au moins vrai.",
          o: ["😌 Confortable, j'adore ça", "😅 Un peu gênant", "🗣️ Je préfère qu'on parle"] },
    en: { q: "A silence settles in. How does it feel?",
          ctx: "There are two of you, and nobody has spoken for a minute. From the truest for you to the least true.",
          o: ["😌 Comfortable, I love it", "😅 A bit awkward", "🗣️ I'd rather we talked"] } },
  { id: "au-verite", axis: "autres",
    fr: { q: "Tu préfères qu'on te dise quoi ?",
          ctx: "Quelque chose que tu ne vas pas aimer entendre, mais que tu devrais savoir. Du plus proche de toi au plus éloigné.",
          o: ["🗡️ La vérité même si ça pique", "🍬 Une version adoucie", "🤷 Rien, si ça ne change rien"] },
    en: { q: "What would you rather be told?",
          ctx: "Something you won't enjoy hearing, but ought to know. From closest to you to furthest.",
          o: ["🗡️ The truth, even if it stings", "🍬 A softened version", "🤷 Nothing, if it changes nothing"] } },
  { id: "au-conseil", axis: "autres",
    fr: { q: "Un proche fait une erreur évidente. Tu fais quoi ?",
          ctx: "Tu le vois venir, lui pas. Il ne t'a rien demandé. Du plus fréquent chez toi au plus rare.",
          o: ["🗣️ Je lui dis franchement", "🤏 Je glisse une allusion", "🤐 Je le laisse apprendre"] },
    en: { q: "Someone close is making an obvious mistake. What do you do?",
          ctx: "You can see it coming, they can't, and they haven't asked you. From what you do most often to least.",
          o: ["🗣️ I tell them straight", "🤏 I drop a hint", "🤐 I let them find out"] } },
  { id: "au-pardon", axis: "autres",
    fr: { q: "Quelqu'un t'a vraiment trahi. Tu pardonnes ?",
          ctx: "Une trahison nette, pas un malentendu, et il s'est excusé. Du plus vrai pour toi au moins vrai.",
          o: ["🕊️ Oui, on est humain", "⏳ Peut-être, avec beaucoup de temps", "⛔ Jamais, c'est terminé"] },
    en: { q: "Someone truly betrayed you. Do you forgive?",
          ctx: "A clear betrayal, not a misunderstanding, and they've apologised. From the truest for you to the least true.",
          o: ["🕊️ Yes, we're all human", "⏳ Maybe, given a lot of time", "⛔ Never, that's the end of it"] } },
  { id: "au-message-nuit", axis: "autres",
    fr: { q: "Un message d'un proche à 3 h du matin",
          ctx: "Tu dormais, ton téléphone vibre, c'est quelqu'un que tu aimes. Du plus fréquent chez toi au plus rare.",
          o: ["📞 J'appelle direct", "💬 Je réponds au réveil", "🔕 Mode avion, on verra"] },
    en: { q: "A message from someone close at 3 a.m.",
          ctx: "You were asleep, your phone buzzes, and it's someone you love. From what you do most often to least.",
          o: ["📞 I call them straight away", "💬 I reply when I wake up", "🔕 Aeroplane mode, deal with it later"] } },
  { id: "au-echec", axis: "autres",
    fr: { q: "Tu viens de te planter devant tout le monde",
          ctx: "Un ratage public, sans excuse possible, et tout le monde l'a vu. Du réflexe le plus vrai pour toi au moins vrai.",
          o: ["😅 J'en fais une blague", "🚪 Je disparais un moment", "💪 Je repars à l'attaque tout de suite"] },
    en: { q: "You've just failed in front of everyone",
          ctx: "A public flop, no excuse available, and everyone saw it. From the truest reflex for you to the least true.",
          o: ["😅 I turn it into a joke", "🚪 I disappear for a while", "💪 I go straight back at it"] } },
  { id: "au-image", axis: "autres",
    fr: { q: "Tu veux qu'on pense quoi de toi ?",
          ctx: "Si on ne devait retenir qu'une chose, après t'avoir bien connu. Du plus important pour toi au moins important.",
          o: ["😎 Que tu es drôle", "🧠 Que tu es brillant", "❤️ Qu'on peut compter sur toi"] },
    en: { q: "What do you want people to think of you?",
          ctx: "If they could only keep one thing, after knowing you well. From most important to you to least.",
          o: ["😎 That you're funny", "🧠 That you're brilliant", "❤️ That you can be counted on"] } },
  { id: "au-compliment", axis: "autres",
    fr: { q: "Quel compliment te fait le plus plaisir ?",
          ctx: "Dit sincèrement, par quelqu'un dont l'avis compte. De celui qui te fait le plus plaisir au moins.",
          o: ["🤣 « Tu me fais trop rire »", "🧠 « T'es vraiment intelligent »", "🫶 « On peut compter sur toi »"] },
    en: { q: "Which compliment lands best?",
          ctx: "Said sincerely, by someone whose opinion counts. From the one that pleases you most to the least.",
          o: ["🤣 “You always make me laugh”", "🧠 “You're seriously clever”", "🫶 “We can always count on you”"] } },
  { id: "au-tabou", axis: "autres",
    fr: { q: "Quel sujet tu évites le plus à table ?",
          ctx: "Repas de famille ou dîner entre amis, quelqu'un lance le sujet. Du plus évité chez toi au moins évité.",
          o: ["💰 L'argent", "🗳️ La politique", "❤️ La vie intime"] },
    en: { q: "Which subject do you dodge most at the table?",
          ctx: "Family meal or dinner with friends, and someone opens the topic. From most dodged by you to least.",
          o: ["💰 Money", "🗳️ Politics", "❤️ Your love life"] } },
  { id: "au-tenue", axis: "autres",
    fr: { q: "Un proche s'habille très mal pour une soirée",
          ctx: "Vous partez dans dix minutes et il est content de lui. Du plus fréquent chez toi au plus rare.",
          o: ["🗣️ Je lui dis avant de sortir", "🤫 Je ne dis rien", "😂 Je me moque gentiment"] },
    en: { q: "Someone close is dressed badly for a night out",
          ctx: "You're leaving in ten minutes and they're pleased with themselves. From what you do most often to least.",
          o: ["🗣️ I say something before we go", "🤫 I say nothing", "😂 I tease them gently"] } },
  { id: "au-karma", axis: "autres",
    fr: { q: "Tu crois au karma ?",
          ctx: "L'idée que ce qu'on fait finit par nous revenir. Du plus proche de ce que tu penses vraiment au plus éloigné.",
          o: ["✨ Complètement", "🤔 Un peu, quand ça m'arrange", "🚫 Pas du tout"] },
    en: { q: "Do you believe in karma?",
          ctx: "The idea that what you do comes back around eventually. From closest to what you actually think to furthest.",
          o: ["✨ Completely", "🤔 A bit, when it suits me", "🚫 Not at all"] } },
  { id: "au-regret", axis: "autres",
    fr: { q: "Qu'est-ce que tu regrettes le plus ?",
          ctx: "En repensant aux dix dernières années, un soir un peu mélancolique. Du regret le plus présent au moins présent.",
          o: ["🚪 Les occasions non saisies", "🗣️ Les mots de trop", "⏰ Le temps perdu avec les mauvaises personnes"] },
    en: { q: "What do you regret most?",
          ctx: "Thinking back over the last ten years, on a slightly melancholy evening. From the regret that's most present to the least.",
          o: ["🚪 The chances you didn't take", "🗣️ The words you shouldn't have said", "⏰ Time lost on the wrong people"] } },
  { id: "go-premiere-fois", axis: "gouts",
    fr: { q: "Vous vous rencontrez pour la première fois : on fait quoi ?",
          ctx: "Vous ne vous connaissez pas encore du tout. Du cadre où tu es le plus à l'aise à celui où tu l'es le moins.",
          o: ["🍸 Un verre en terrasse", "🖼️ Une expo ou un musée", "🚶 Une longue balade"] },
    en: { q: "You're meeting for the first time — what do you do?",
          ctx: "You don't know each other at all yet. From the setting where you're most at ease to the least.",
          o: ["🍸 A drink on a terrace", "🖼️ An exhibition or a museum", "🚶 A long walk"] } },
  { id: "go-soiree-deux", axis: "gouts",
    fr: { q: "Une soirée à deux : tu proposes quoi ?",
          ctx: "Vous avez la soirée entière, aucune contrainte, aucun budget à tenir. Du plan que tu lances en premier à celui que tu évites.",
          o: ["🍽️ Un resto qu'on ne connaît pas", "🍿 Plaid et film à la maison", "🎶 Concert ou sortie"] },
    en: { q: "An evening for two — what do you suggest?",
          ctx: "You have the whole evening, no constraints, no budget to keep to. From the plan you'd offer first to the one you'd avoid.",
          o: ["🍽️ A restaurant neither of us knows", "🍿 Blanket and a film at home", "🎶 A gig or a night out"] } },
  { id: "go-sortie", axis: "gouts",
    fr: { q: "On te laisse choisir la sortie",
          ctx: "Tout le monde suivra sans râler, quoi que tu choisisses. De ce que tu proposes en premier à ce que tu gardes pour une autre fois.",
          o: ["🎭 Théâtre ou spectacle", "🍽️ Un très bon repas", "🎡 Une activité un peu bête et drôle"] },
    en: { q: "You get to choose where everyone goes",
          ctx: "Everyone will go along with it without complaining, whatever you pick. From what you'd suggest first to what you'd save for another time.",
          o: ["🎭 Theatre or a show", "🍽️ A really good meal", "🎡 Something a bit silly and fun"] } },
  { id: "go-rencontre", axis: "gouts",
    fr: { q: "La plus belle façon de rencontrer quelqu'un ?",
          ctx: "Un ami, un amour, peu importe : la rencontre elle-même. De la plus belle selon toi à la moins belle.",
          o: ["🎲 Par hasard, dans la vraie vie", "🤝 Par des amis en commun", "📱 Sur une appli, assumé"] },
    en: { q: "The best way to meet someone?",
          ctx: "A friend, a love, doesn't matter: the meeting itself. From the best in your view to the least good.",
          o: ["🎲 By chance, in real life", "🤝 Through mutual friends", "📱 On an app, no shame"] } },
  { id: "go-plaisir-coupable", axis: "gouts",
    fr: { q: "Ton plaisir coupable, c'est lequel ?",
          ctx: "Celui que tu assumerais si on te posait la question en face. Du plus fréquent chez toi au plus rare.",
          o: ["📺 La télé-réalité", "🎶 La chanson française ringarde", "🍔 Le fast-food à 2 h du matin"] },
    en: { q: "What's your guilty pleasure?",
          ctx: "The one you'd own up to if someone asked you to your face. From what happens most often to least.",
          o: ["📺 Reality TV", "🎶 Cheesy old pop", "🍔 Fast food at two in the morning"] } },
  { id: "ry-dimanche", axis: "rythme",
    fr: { q: "Un dimanche entier à deux, sans obligation",
          ctx: "Peu importe avec qui : un ami, un parent, quelqu'un que tu aimes. Du dimanche que tu proposes en premier à celui que tu gardes pour une autre fois.",
          o: ["🛌 Grasse matinée sans culpabiliser", "🥾 Sortir tôt et bouger", "🍳 Cuisiner ensemble toute la journée"] },
    en: { q: "A whole Sunday together, nothing required",
          ctx: "Doesn't matter who with: a friend, a parent, someone you love. From the Sunday you'd suggest first to the one you'd save for another time.",
          o: ["🛌 A long lie-in, guilt-free", "🥾 Out early and moving", "🍳 Cooking together all day"] } },
  { id: "ry-plan-22h", axis: "rythme",
    fr: { q: "On te propose un plan à 22 h. Tu dis quoi ?",
          ctx: "Tu es chez toi, en pyjama, ta soirée était finie. Du plus fréquent chez toi au plus rare.",
          o: ["🚀 Je dis oui direct", "🤔 Ça dépend complètement du plan", "🛌 Non, j'étais très bien"] },
    en: { q: "Someone suggests a plan at 10 p.m. What do you say?",
          ctx: "You're home, in pyjamas, and your evening was over. From what you do most often to least.",
          o: ["🚀 I say yes immediately", "🤔 Entirely depends on the plan", "🛌 No, I was perfectly happy"] } },
  { id: "ry-routine", axis: "rythme",
    fr: { q: "La routine, ça te fait quoi ?",
          ctx: "Les mêmes gestes, les mêmes jours, les mêmes gens, pendant des années. Du plus vrai pour toi au moins vrai.",
          o: ["🏠 Rassurante, j'aime ça", "😰 Dangereuse, il faut la casser", "⚖️ Bonne si on garde des surprises"] },
    en: { q: "Routine — what does it do to you?",
          ctx: "The same gestures, the same days, the same people, for years. From the truest for you to the least true.",
          o: ["🏠 Reassuring, I like it", "😰 Dangerous, it needs breaking", "⚖️ Fine if we keep some surprises"] } },
  { id: "ry-weekend-surprise", axis: "rythme",
    fr: { q: "On t'organise un week-end surprise",
          ctx: "Destination inconnue, départ dans deux heures, tout est déjà réservé. De la réaction la plus vraie pour toi à la moins vraie.",
          o: ["😍 Le rêve absolu", "🙂 Sympa si je peux préparer un sac", "😨 L'angoisse, j'aime savoir"] },
    en: { q: "Someone plans a surprise weekend for you",
          ctx: "Unknown destination, leaving in two hours, everything already booked. From the truest reaction for you to the least true.",
          o: ["😍 The absolute dream", "🙂 Lovely if I can pack a bag", "😨 Agony, I like to know"] } },
  { id: "ry-avenir", axis: "rythme",
    fr: { q: "Parler de ce qui vient, tu le fais quand ?",
          ctx: "Les projets à un an, ce qu'on veut vraiment, où on se voit. Du plus proche de toi au plus éloigné.",
          o: ["🔭 Tôt et clairement", "🌱 Progressivement", "🎈 Le moins possible, on verra bien"] },
    en: { q: "Talking about what comes next — when do you do it?",
          ctx: "Plans a year out, what you actually want, where you see this going. From closest to you to furthest.",
          o: ["🔭 Early and plainly", "🌱 Gradually", "🎈 As little as possible, we'll see"] } },
  { id: "ry-soir", axis: "rythme",
    fr: { q: "Le soir venu, tu es plutôt quoi ?",
          ctx: "Rien ne t'oblige à te lever tôt demain. Du plus fréquent chez toi au plus rare.",
          o: ["🦉 Couche-tard, la nuit est à moi", "🐓 Couche-tôt sans hésiter", "🔁 Ça dépend complètement"] },
    en: { q: "Come evening, which are you?",
          ctx: "Nothing forces you up early tomorrow. From what you do most often to least.",
          o: ["🦉 Night owl, the night is mine", "🐓 Early to bed, no hesitation", "🔁 Entirely depends"] } },
  { id: "ry-limite-soiree", axis: "rythme",
    fr: { q: "Ta limite en soirée, elle est où ?",
          ctx: "Une bonne soirée, rien de prévu le lendemain. Du plus fréquent chez toi au plus rare.",
          o: ["🕛 Minuit et je disparais", "🌅 Jusqu'au lever du soleil", "🎲 Aucune règle, ça dépend du soir"] },
    en: { q: "Where's your limit on a night out?",
          ctx: "A good night, nothing planned for tomorrow. From what you do most often to least.",
          o: ["🕛 Midnight and I vanish", "🌅 Until the sun comes up", "🎲 No rule, depends on the night"] } },
  { id: "ry-lendemain", axis: "rythme",
    fr: { q: "Le lendemain d'une grosse soirée",
          ctx: "Tu te réveilles à 11 h, la journée est libre. Du plus fréquent chez toi au plus rare.",
          o: ["🍳 Gros brunch réparateur", "🛏️ Journée au lit, complète", "🏃 Du sport pour éliminer"] },
    en: { q: "The day after a big night out",
          ctx: "You wake at eleven and the day is yours. From what you do most often to least.",
          o: ["🍳 A big restorative brunch", "🛏️ A full day in bed", "🏃 Exercise, to sweat it out"] } },
  { id: "ag-redhibitoire", axis: "agace",
    fr: { q: "Qu'est-ce qui te fait fuir quelqu'un ?",
          ctx: "Rien de grave en soi, mais ça te reste en travers et tu n'y reviens pas. Du plus rédhibitoire pour toi au moins rédhibitoire.",
          o: ["🙄 Impoli avec les serveurs", "📵 Toujours sur son téléphone", "⏰ Systématiquement en retard"] },
    en: { q: "What makes you walk away from someone?",
          ctx: "Nothing serious in itself, but it sticks and you don't come back. From most disqualifying for you to least.",
          o: ["🙄 Rude to waiters", "📵 Always on their phone", "⏰ Late every single time"] } },
];
