// Are We A Match? — les scènes sur LE RAPPORT AUX AUTRES.
//
// Le fichier s'appelle encore date.js et son pack garde l'id « date » : cet id
// est la clé sous laquelle les réponses sont rangées dans les profils, il ne
// bouge pas. En revanche le contenu a changé de nature. Il ne s'agit plus de
// vie de couple : toutes les scènes ici passent LE TEST DES TROIS RELATIONS —
// elles ont du sens classées entre toi et ta mère, toi et ton meilleur pote,
// et toi et ton/ta partenaire. Ce qui présupposait un couple (« En couple, le
// week-end », « Dire je t'aime », « L'argent à deux ») est parti.
//
// Format, identique au pack amis :
//   q    — une vraie question, courte, affichée en gros.
//   ctx  — la scène en une phrase, PUIS le sens du classement. Sans lui,
//          « classer » ne veut rien dire, et deux joueurs qui lisent la
//          consigne à l'envers produisent un désaccord qui n'existe pas.
//   o    — 3 options clivantes (aucune socialement « juste »).
//   axis — ce que la scène révèle. Sert au tirage équilibré (games.js).
//
// RÈGLE DE STABILITÉ — les réponses mémorisées sont des classements d'INDEX
// dans `o`, rangés par `id`. Pour une scène existante : `id` ne change jamais,
// et les options gardent leur ORDRE et leur SENS. Une scène réécrite reçoit
// donc un NOUVEL id (ici le préfixe dit l'axe : au- / go- / ry- / ag-), et les
// anciennes réponses sont ignorées proprement plutôt que réinterprétées.

module.exports = [
  { id: "au-accroche", axis: "autres", q: "Chez quelqu'un, qu'est-ce qui te fait accrocher ?",
    ctx: "Pas les cinq premières minutes : ce qui te donne envie de revenir. Du plus décisif pour toi au moins décisif.",
    o: ["😂 L'humour", "🧠 La curiosité", "🫂 La douceur"] },
  { id: "au-aime", axis: "autres", q: "Tu te sens aimé quand on te fait quoi ?",
    ctx: "Par un ami, un parent, un amoureux — la question est la même. Du geste qui te touche le plus à celui qui te touche le moins.",
    o: ["💬 On te dit les choses", "🎁 On a des attentions", "🤗 On te prend dans les bras"] },
  { id: "au-apres-engueulade", q: "Vous venez de vous engueuler. Et maintenant ?", axis: "autres",
    ctx: "Rien de grave, mais le ton est monté et la soirée est gâchée. Du réflexe le plus vrai pour toi au moins vrai.",
    o: ["🗣️ On règle ça avant de dormir", "🌙 On dort dessus, on en reparle demain", "🤍 Un geste vaut mieux qu'un discours"] },
  { id: "au-desaccord", axis: "autres", q: "En plein désaccord, tu deviens comment ?",
    ctx: "Pas un débat d'idées : un vrai désaccord avec quelqu'un qui compte. Du plus proche de toi au plus éloigné.",
    o: ["🌋 Expressif, ça sort", "🧊 Calme et posé", "🚶 J'ai besoin de sortir marcher"] },
  { id: "au-surprises", axis: "autres", q: "Les surprises, toi, tu en es où ?",
    ctx: "Une fête surprise, un cadeau imprévu, un plan qu'on ne t'a pas annoncé. Du plus proche de toi au plus éloigné.",
    o: ["🎉 J'adore en recevoir", "🎁 Je préfère en faire", "😅 Je déteste ça, préviens-moi"] },
  { id: "au-attention", axis: "autres", q: "Quelle attention te fait le plus plaisir ?",
    ctx: "De quelqu'un qui compte, un jour parfaitement ordinaire. De celle qui te touche le plus à celle qui te touche le moins.",
    o: ["☕ Un café apporté au lit", "📩 Un message inattendu dans la journée", "🎧 Une playlist faite pour toi"] },
  { id: "au-gouts-opposes", axis: "autres", q: "Quelqu'un que tu aimes n'aime rien de ce que tu aimes",
    ctx: "Ni tes films, ni ta musique, ni tes restos. De ta vraie réaction à celle que tu n'aurais jamais.",
    o: ["🎉 Génial, on se découvre", "😬 Compliqué à la longue", "🤷 Chacun ses trucs, on s'en fiche"] },
  { id: "au-priorite", axis: "autres", q: "Dans une relation qui compte, tu tiens à quoi ?",
    ctx: "Amitié, famille, amour : même question. Du plus vital pour toi au moins vital.",
    o: ["🕊️ La liberté de chacun", "🔗 La complicité", "🏗️ Construire quelque chose"] },
  { id: "au-partage", axis: "autres", q: "Qu'est-ce que tu racontes le plus facilement ?",
    ctx: "À quelqu'un de proche, un soir ordinaire, sans qu'on te tire les vers du nez. Du plus facile à sortir au plus difficile.",
    o: ["😢 Tes émotions", "🧩 Tes projets et tes idées", "📅 Ton quotidien concret"] },
  { id: "au-durer", axis: "autres", q: "Une relation qui dure, ça tient à quoi ?",
    ctx: "Une amitié de vingt ans, un couple, une famille. Du plus décisif selon toi au moins décisif.",
    o: ["🛠️ Du travail volontaire", "🍀 De la chance et de l'alchimie", "🗣️ De la communication constante"] },
  { id: "au-cadeau-offert", axis: "autres", q: "Pour l'anniversaire de quelqu'un, tu offres quoi ?",
    ctx: "Même budget à chaque fois, quelqu'un que tu aimes bien. De ce que tu offres le plus souvent au plus rare.",
    o: ["🎁 Un objet réfléchi", "🌍 Un week-end quelque part", "🍾 Une soirée avec ses proches"] },
  { id: "au-silence", axis: "autres", q: "Un silence s'installe. Tu le vis comment ?",
    ctx: "Vous êtes deux, personne n'a parlé depuis une minute. Du plus vrai pour toi au moins vrai.",
    o: ["😌 Confortable, j'adore ça", "😅 Un peu gênant", "🗣️ Je préfère qu'on parle"] },
  { id: "au-verite", axis: "autres", q: "Tu préfères qu'on te dise quoi ?",
    ctx: "Quelque chose que tu ne vas pas aimer entendre, mais que tu devrais savoir. Du plus proche de toi au plus éloigné.",
    o: ["🗡️ La vérité même si ça pique", "🍬 Une version adoucie", "🤷 Rien, si ça ne change rien"] },
  { id: "au-conseil", axis: "autres", q: "Un proche fait une erreur évidente. Tu fais quoi ?",
    ctx: "Tu le vois venir, lui pas. Il ne t'a rien demandé. Du plus fréquent chez toi au plus rare.",
    o: ["🗣️ Je lui dis franchement", "🤏 Je glisse une allusion", "🤐 Je le laisse apprendre"] },
  { id: "au-pardon", axis: "autres", q: "Quelqu'un t'a vraiment trahi. Tu pardonnes ?",
    ctx: "Une trahison nette, pas un malentendu, et il s'est excusé. Du plus vrai pour toi au moins vrai.",
    o: ["🕊️ Oui, on est humain", "⏳ Peut-être, avec beaucoup de temps", "⛔ Jamais, c'est terminé"] },
  { id: "au-message-nuit", axis: "autres", q: "Un message d'un proche à 3 h du matin",
    ctx: "Tu dormais, ton téléphone vibre, c'est quelqu'un que tu aimes. Du plus fréquent chez toi au plus rare.",
    o: ["📞 J'appelle direct", "💬 Je réponds au réveil", "🔕 Mode avion, on verra"] },
  { id: "au-echec", axis: "autres", q: "Tu viens de te planter devant tout le monde",
    ctx: "Un ratage public, sans excuse possible, et tout le monde l'a vu. Du réflexe le plus vrai pour toi au moins vrai.",
    o: ["😅 J'en fais une blague", "🚪 Je disparais un moment", "💪 Je repars à l'attaque tout de suite"] },
  { id: "au-image", axis: "autres", q: "Tu veux qu'on pense quoi de toi ?",
    ctx: "Si on ne devait retenir qu'une chose, après t'avoir bien connu. Du plus important pour toi au moins important.",
    o: ["😎 Que tu es drôle", "🧠 Que tu es brillant", "❤️ Qu'on peut compter sur toi"] },
  { id: "au-compliment", axis: "autres", q: "Quel compliment te fait le plus plaisir ?",
    ctx: "Dit sincèrement, par quelqu'un dont l'avis compte. De celui qui te fait le plus plaisir au moins.",
    o: ["🤣 « Tu me fais trop rire »", "🧠 « T'es vraiment intelligent »", "🫶 « On peut compter sur toi »"] },
  { id: "au-tabou", axis: "autres", q: "Quel sujet tu évites le plus à table ?",
    ctx: "Repas de famille ou dîner entre amis, quelqu'un lance le sujet. Du plus évité chez toi au moins évité.",
    o: ["💰 L'argent", "🗳️ La politique", "❤️ La vie intime"] },
  { id: "au-tenue", axis: "autres", q: "Un proche s'habille très mal pour une soirée",
    ctx: "Vous partez dans dix minutes et il est content de lui. Du plus fréquent chez toi au plus rare.",
    o: ["🗣️ Je lui dis avant de sortir", "🤫 Je ne dis rien", "😂 Je me moque gentiment"] },
  { id: "au-karma", axis: "autres", q: "Tu crois au karma ?",
    ctx: "L'idée que ce qu'on fait finit par nous revenir. Du plus proche de ce que tu penses vraiment au plus éloigné.",
    o: ["✨ Complètement", "🤔 Un peu, quand ça m'arrange", "🚫 Pas du tout"] },
  { id: "au-regret", axis: "autres", q: "Qu'est-ce que tu regrettes le plus ?",
    ctx: "En repensant aux dix dernières années, un soir un peu mélancolique. Du regret le plus présent au moins présent.",
    o: ["🚪 Les occasions non saisies", "🗣️ Les mots de trop", "⏰ Le temps perdu avec les mauvaises personnes"] },
  { id: "go-premiere-fois", axis: "gouts", q: "Vous vous rencontrez pour la première fois : on fait quoi ?",
    ctx: "Vous ne vous connaissez pas encore du tout. Du cadre où tu es le plus à l'aise à celui où tu l'es le moins.",
    o: ["🍸 Un verre en terrasse", "🖼️ Une expo ou un musée", "🚶 Une longue balade"] },
  { id: "go-soiree-deux", axis: "gouts", q: "Une soirée à deux : tu proposes quoi ?",
    ctx: "Vous avez la soirée entière, aucune contrainte, aucun budget à tenir. Du plan que tu lances en premier à celui que tu évites.",
    o: ["🍽️ Un resto qu'on ne connaît pas", "🍿 Plaid et film à la maison", "🎶 Concert ou sortie"] },
  { id: "go-sortie", axis: "gouts", q: "On te laisse choisir la sortie",
    ctx: "Tout le monde suivra sans râler, quoi que tu choisisses. De ce que tu proposes en premier à ce que tu gardes pour une autre fois.",
    o: ["🎭 Théâtre ou spectacle", "🍽️ Un très bon repas", "🎡 Une activité un peu bête et drôle"] },
  { id: "go-rencontre", axis: "gouts", q: "La plus belle façon de rencontrer quelqu'un ?",
    ctx: "Un ami, un amour, peu importe : la rencontre elle-même. De la plus belle selon toi à la moins belle.",
    o: ["🎲 Par hasard, dans la vraie vie", "🤝 Par des amis en commun", "📱 Sur une appli, assumé"] },
  { id: "go-plaisir-coupable", axis: "gouts", q: "Ton plaisir coupable, c'est lequel ?",
    ctx: "Celui que tu assumerais si on te posait la question en face. Du plus fréquent chez toi au plus rare.",
    o: ["📺 La télé-réalité", "🎶 La chanson française ringarde", "🍔 Le fast-food à 2 h du matin"] },
  { id: "ry-dimanche", axis: "rythme", q: "Un dimanche entier à deux, sans obligation",
    ctx: "Peu importe avec qui : un ami, un parent, quelqu'un que tu aimes. Du dimanche que tu proposes en premier à celui que tu gardes pour une autre fois.",
    o: ["🛌 Grasse matinée sans culpabiliser", "🥾 Sortir tôt et bouger", "🍳 Cuisiner ensemble toute la journée"] },
  { id: "ry-plan-22h", axis: "rythme", q: "On te propose un plan à 22 h. Tu dis quoi ?",
    ctx: "Tu es chez toi, en pyjama, ta soirée était finie. Du plus fréquent chez toi au plus rare.",
    o: ["🚀 Je dis oui direct", "🤔 Ça dépend complètement du plan", "🛌 Non, j'étais très bien"] },
  { id: "ry-routine", axis: "rythme", q: "La routine, ça te fait quoi ?",
    ctx: "Les mêmes gestes, les mêmes jours, les mêmes gens, pendant des années. Du plus vrai pour toi au moins vrai.",
    o: ["🏠 Rassurante, j'aime ça", "😰 Dangereuse, il faut la casser", "⚖️ Bonne si on garde des surprises"] },
  { id: "ry-weekend-surprise", axis: "rythme", q: "On t'organise un week-end surprise",
    ctx: "Destination inconnue, départ dans deux heures, tout est déjà réservé. De la réaction la plus vraie pour toi à la moins vraie.",
    o: ["😍 Le rêve absolu", "🙂 Sympa si je peux préparer un sac", "😨 L'angoisse, j'aime savoir"] },
  { id: "ry-avenir", axis: "rythme", q: "Parler de ce qui vient, tu le fais quand ?",
    ctx: "Les projets à un an, ce qu'on veut vraiment, où on se voit. Du plus proche de toi au plus éloigné.",
    o: ["🔭 Tôt et clairement", "🌱 Progressivement", "🎈 Le moins possible, on verra bien"] },
  { id: "ry-soir", axis: "rythme", q: "Le soir venu, tu es plutôt quoi ?",
    ctx: "Rien ne t'oblige à te lever tôt demain. Du plus fréquent chez toi au plus rare.",
    o: ["🦉 Couche-tard, la nuit est à moi", "🐓 Couche-tôt sans hésiter", "🔁 Ça dépend complètement"] },
  { id: "ry-limite-soiree", axis: "rythme", q: "Ta limite en soirée, elle est où ?",
    ctx: "Une bonne soirée, rien de prévu le lendemain. Du plus fréquent chez toi au plus rare.",
    o: ["🕛 Minuit et je disparais", "🌅 Jusqu'au lever du soleil", "🎲 Aucune règle, ça dépend du soir"] },
  { id: "ry-lendemain", axis: "rythme", q: "Le lendemain d'une grosse soirée",
    ctx: "Tu te réveilles à 11 h, la journée est libre. Du plus fréquent chez toi au plus rare.",
    o: ["🍳 Gros brunch réparateur", "🛏️ Journée au lit, complète", "🏃 Du sport pour éliminer"] },
  { id: "ag-redhibitoire", axis: "agace", q: "Qu'est-ce qui te fait fuir quelqu'un ?",
    ctx: "Rien de grave en soi, mais ça te reste en travers et tu n'y reviens pas. Du plus rédhibitoire pour toi au moins rédhibitoire.",
    o: ["🙄 Impoli avec les serveurs", "📵 Toujours sur son téléphone", "⏰ Systématiquement en retard"] },
];
