// Are We A Match? — les scènes sur LES PETITS VICES, L'ARGENT et CE QUI AGACE.
//
// Le fichier s'appelle encore piquant.js et son pack garde l'id « piquant » :
// cet id est la clé sous laquelle les réponses sont rangées dans les profils,
// il ne bouge pas. Le contenu, lui, a changé de nature.
//
// « Piquant » ne veut plus dire osé. Un vice, ici, ce n'est pas du sexe : c'est
// la procrastination, les achats compulsifs, juger quelqu'un sur ses
// chaussures, garder une rancune sept ans, annuler à la dernière minute. Et
// c'est braqué sur TOI, jamais sur les défauts des autres — c'est drôle
// justement parce que l'autre voit ta réponse. Tout ce qui relevait de la
// drague ou de la confidence intime (« Flirter, pour toi c'est », « Un crush
// sur un ami du groupe », « Les applis de rencontre ») est parti : ces scènes
// ne passaient pas le test des trois relations, puisqu'une partie se joue
// aussi bien avec sa mère qu'avec son meilleur pote.
//
// Format et règle de stabilité : voir amis.js. Une scène réécrite reçoit un
// NOUVEL id (le préfixe dit l'axe : vi- / ar- / ag- / au-), les anciennes
// réponses sont ignorées proprement plutôt que réinterprétées.

module.exports = [
  // ------------------------------------------------------------ petits vices
  { id: "vi-tentation", axis: "vices",
    fr: { q: "À quoi tu cèdes le plus facilement ?",
          ctx: "Fin de journée, tu es fatigué, personne ne regarde. Du plus fréquent chez toi au plus rare.",
          o: ["🍫 Le placard à sucre", "🛒 Un achat dont tu n'as aucun besoin", "📱 Une heure de scroll qui devait durer cinq minutes"] },
    en: { q: "What do you give in to most easily?",
          ctx: "End of the day, you're tired, nobody's watching. From what happens most often to least.",
          o: ["🍫 The sugar cupboard", "🛒 Buying something you don't need at all", "📱 An hour of scrolling meant to last five minutes"] } },
  { id: "vi-jugement", axis: "vices",
    fr: { q: "Sur quoi tu juges quelqu'un en dix secondes ?",
          ctx: "Tu ne l'assumes pas forcément, mais ça se fait tout seul. Du plus vrai pour toi au moins vrai.",
          o: ["👟 Ce qu'il porte", "🎵 Ce qu'il écoute", "🍽️ Sa façon de se tenir à table"] },
    en: { q: "What do you judge someone on in ten seconds?",
          ctx: "You don't necessarily own up to it, but it happens by itself. From the truest for you to the least true.",
          o: ["👟 What they're wearing", "🎵 What they listen to", "🍽️ How they behave at the table"] } },
  { id: "vi-ragot", axis: "vices",
    fr: { q: "Tu apprends un ragot croustillant sur quelqu'un",
          ctx: "Rien de grave, mais c'est juteux, et personne ne t'a demandé le secret. Du réflexe le plus honnête à ton sujet au moins honnête.",
          o: ["📢 Je le raconte dans l'heure", "🤐 Je le garde, mais j'y pense", "🙄 Ça ne m'intéresse pas vraiment"] },
    en: { q: "You hear a juicy piece of gossip about someone",
          ctx: "Nothing serious, but it's good, and nobody asked you to keep it quiet. From the most honest reflex about you to the least.",
          o: ["📢 I've told someone within the hour", "🤐 I keep it, but I think about it", "🙄 It doesn't really interest me"] } },
  { id: "vi-rancune", axis: "vices",
    fr: { q: "Quelqu'un t'a vexé il y a deux ans. Aujourd'hui ?",
          ctx: "Vous vous recroisez, il ne s'est jamais excusé, il a sans doute oublié. Du plus proche de toi au plus éloigné.",
          o: ["🧊 Poli et distant, à vie", "🤷 J'ai oublié depuis longtemps", "🗣️ Je remets le sujet sur la table"] },
    en: { q: "Someone slighted you two years ago. And today?",
          ctx: "You cross paths again, they never apologised, they've probably forgotten. From closest to you to furthest.",
          o: ["🧊 Polite and distant, for life", "🤷 I forgot about it long ago", "🗣️ I bring it up again"] } },
  { id: "vi-mensonge", axis: "vices",
    fr: { q: "Quel petit mensonge tu fais le plus souvent ?",
          ctx: "Pas un gros : celui qui sort tout seul, sans y penser. Du plus fréquent chez toi au plus rare.",
          o: ["😴 « J'arrive dans cinq minutes »", "📖 « Oui, j'ai lu le contrat »", "😀 « Non non, ça va très bien »"] },
    en: { q: "Which small lie do you tell most often?",
          ctx: "Not a big one: the one that comes out by itself, without thinking. From what happens most often to least.",
          o: ["😴 “I'm five minutes away”", "📖 “Yes, I read the terms”", "😀 “No no, I'm fine”"] } },
  { id: "vi-annuler", axis: "vices",
    fr: { q: "Annuler un plan à la dernière minute, tu le vis comment ?",
          ctx: "Tu avais dit oui, tu n'as plus envie, et tu n'as aucune excuse valable. Du plus vrai pour toi au moins vrai.",
          o: ["📵 Je le fais sans culpabiliser", "😅 Je culpabilise, mais je le fais", "🚫 Je ne le fais jamais, j'y vais"] },
    en: { q: "Cancelling a plan last minute — how does that sit?",
          ctx: "You'd said yes, you no longer want to go, and you have no real excuse. From the truest for you to the least true.",
          o: ["📵 I do it without guilt", "😅 I feel guilty, and do it anyway", "🚫 I never do it, I go"] } },
  { id: "vi-vengeance", axis: "vices",
    fr: { q: "Ta vengeance préférée, c'est laquelle ?",
          ctx: "Quelqu'un t'a fait un coup bas. Tu ne vas rien faire de grave. De ce qui te ressemble le plus au moins.",
          o: ["🧊 L'indifférence totale", "🎭 Une blague bien placée", "🔥 La confrontation directe"] },
    en: { q: "What's your preferred revenge?",
          ctx: "Someone played dirty. You're not going to do anything serious. From most like you to least.",
          o: ["🧊 Complete indifference", "🎭 A well-placed joke", "🔥 Straight confrontation"] } },
  { id: "vi-drama", axis: "vices",
    fr: { q: "Un drama éclate dans le groupe. Tu es qui ?",
          ctx: "Deux personnes que tu aimes bien se prennent la tête devant tout le monde. Du rôle que tu tiens le plus souvent à celui que tu tiens le moins.",
          o: ["🍿 Le spectateur qui adore ça", "🕊️ Le médiateur qui calme", "🔥 Celui qui met de l'huile"] },
    en: { q: "Drama erupts in the group. Who are you?",
          ctx: "Two people you're fond of are having it out in front of everyone. From the role you play most often to the one you play least.",
          o: ["🍿 The spectator, thoroughly enjoying it", "🕊️ The mediator, calming it down", "🔥 The one pouring petrol on it"] } },
  { id: "vi-rire", axis: "vices",
    fr: { q: "Quelqu'un se casse la figure devant toi",
          ctx: "Une vraie gamelle, sans gravité. Du réflexe le plus honnête à ton sujet au moins honnête.",
          o: ["😂 Je ris immédiatement, désolé", "🫣 Je vérifie que ça va, puis je ris", "😟 Je m'inquiète direct"] },
    en: { q: "Someone takes a tumble right in front of you",
          ctx: "A proper fall, nothing broken. From the most honest reflex about you to the least.",
          o: ["😂 I laugh immediately, sorry", "🫣 I check they're fine, then laugh", "😟 I worry straight away"] } },
  { id: "vi-attention", axis: "vices",
    fr: { q: "Être le centre de l'attention, ça te fait quoi ?",
          ctx: "Tout le monde se tourne vers toi, on attend que tu parles. Du plus vrai pour toi au moins vrai.",
          o: ["✨ J'adore, totalement", "🎭 Par moments seulement", "🙈 L'horreur absolue"] },
    en: { q: "Being the centre of attention — how is that for you?",
          ctx: "Everyone turns to you, waiting for you to speak. From the truest for you to the least true.",
          o: ["✨ I love it, completely", "🎭 Only in bursts", "🙈 Absolute horror"] } },
  { id: "vi-portable", axis: "vices",
    fr: { q: "On te demande de laisser fouiller ton téléphone",
          ctx: "Quelqu'un de proche, cinq minutes, sans surveillance. Du plus vrai pour toi au moins vrai.",
          o: ["📱 Aucun problème", "😬 Ça me met mal à l'aise", "🔒 Hors de question"] },
    en: { q: "Someone asks to look through your phone",
          ctx: "Someone close, five minutes, unsupervised. From the truest for you to the least true.",
          o: ["📱 No problem at all", "😬 It makes me uncomfortable", "🔒 Out of the question"] } },
  { id: "vi-photo", axis: "vices",
    fr: { q: "Une photo gênante de toi circule",
          ctx: "Dans le groupe, tout le monde l'a vue, tu viens de la découvrir. De ta vraie réaction à celle que tu n'aurais jamais.",
          o: ["😂 J'en ris et je la repartage", "😐 Je demande qu'on la supprime", "😡 Ça m'énerve vraiment"] },
    en: { q: "An embarrassing photo of you is going round",
          ctx: "In the group chat, everyone has seen it, and you've only just found out. From your real reaction to the one you'd never have.",
          o: ["😂 I laugh and share it again", "😐 I ask them to delete it", "😡 It genuinely annoys me"] } },
  { id: "vi-alcool", axis: "vices",
    fr: { q: "Après deux verres, tu deviens quoi ?",
          ctx: "Une bonne soirée, des gens que tu aimes bien. Du plus vrai pour toi au moins vrai.",
          o: ["🕺 Très fêtard", "🫂 Très affectueux", "🗣️ Très bavard et philosophe"] },
    en: { q: "After two drinks, what do you turn into?",
          ctx: "A good night, people you're fond of. From the truest for you to the least true.",
          o: ["🕺 Very much up for it", "🫂 Very affectionate", "🗣️ Very talkative and philosophical"] } },
  { id: "vi-soiree-role", axis: "vices",
    fr: { q: "En soirée, tu finis toujours où ?",
          ctx: "Trois heures après ton arrivée, sans l'avoir décidé. De l'endroit où tu atterris le plus souvent au plus rare.",
          o: ["🎧 À gérer la musique", "🍳 Dans la cuisine à discuter", "💃 Au milieu de la piste"] },
    en: { q: "At a party, where do you always end up?",
          ctx: "Three hours after arriving, without having decided it. From where you land most often to least.",
          o: ["🎧 In charge of the music", "🍳 In the kitchen, talking", "💃 In the middle of the dancing"] } },
  { id: "vi-gagner", axis: "vices",
    fr: { q: "Tu viens de battre un proche à plate couture",
          ctx: "Un jeu sans enjeu, mais tu as gagné largement, et il le prend mal. Du plus vrai pour toi au moins vrai.",
          o: ["🏆 Je savoure et je le rappelle longtemps", "😊 Content, mais discret", "🤫 Il m'arrive de laisser gagner"] },
    en: { q: "You've just thrashed someone close at a game",
          ctx: "Nothing was at stake, but you won easily, and they're taking it badly. From the truest for you to the least true.",
          o: ["🏆 I savour it and bring it up for months", "😊 Pleased, but quiet about it", "🤫 I have been known to let people win"] } },
  { id: "vi-defaut", axis: "vices",
    fr: { q: "Ton pire défaut, tu l'assumes lequel ?",
          ctx: "Celui que tes proches citeraient en premier, et que tu connais très bien. Du plus vrai pour toi au moins vrai.",
          o: ["😤 Têtu", "🐌 Toujours en retard", "🙃 Sarcastique un peu trop"] },
    en: { q: "Which of your worst traits do you own?",
          ctx: "The one the people close to you would name first, and you know perfectly well. From the truest for you to the least true.",
          o: ["😤 Stubborn", "🐌 Always late", "🙃 Sarcastic, slightly too much"] } },
  { id: "vi-honte", axis: "vices",
    fr: { q: "Quel souvenir gênant te revient encore la nuit ?",
          ctx: "Dix ans après, sans prévenir, pour rien. Du plus souvent au plus rarement.",
          o: ["💃 Une danse en soirée", "📧 Un message envoyé au mauvais destinataire", "🎤 Un karaoké assumé trop fort"] },
    en: { q: "Which cringe memory still comes back at night?",
          ctx: "Ten years later, unannounced, for no reason. From most often to most rarely.",
          o: ["💃 A dance at a party", "📧 A message sent to the wrong person", "🎤 A karaoke performance, far too committed"] } },
  { id: "vi-avouer", axis: "vices",
    fr: { q: "Qu'est-ce qui te serait le plus dur à avouer ?",
          ctx: "À quelqu'un de proche, ce soir, sans y être obligé. Du plus dur pour toi au plus facile.",
          o: ["😬 Une grosse honte publique", "💔 Un sentiment non partagé", "🤥 Un mensonge qui a duré des années"] },
    en: { q: "What would be hardest for you to admit?",
          ctx: "To someone close, tonight, without being made to. From hardest for you to easiest.",
          o: ["😬 A big public humiliation", "💔 Feelings that weren't returned", "🤥 A lie that ran for years"] } },
  { id: "vi-reveal", axis: "vices",
    fr: { q: "Tu dois révéler une chose que personne ne sait",
          ctx: "Un jeu de soirée, tu ne peux pas y couper, mais tu choisis quoi. Du plus facile à lâcher au plus difficile.",
          o: ["🎯 Un échec professionnel", "🙈 Une bêtise jamais avouée", "🤐 Une manie un peu honteuse"] },
    en: { q: "You must reveal something nobody knows",
          ctx: "A party game, you can't get out of it, but you choose what. From easiest to give up to hardest.",
          o: ["🎯 A professional failure", "🙈 Something stupid you never admitted", "🤐 A slightly shameful habit"] } },
  { id: "vi-jalousie", axis: "vices",
    fr: { q: "La jalousie, tu la connais comment ?",
          ctx: "Pas seulement en amour : un ami qui en préfère un autre, ça compte aussi. Du plus honnête à ton sujet au moins honnête.",
          o: ["😌 Aucune, confiance totale", "🌡️ Un peu, c'est humain", "🔥 Pas mal, et je l'assume"] },
    en: { q: "Jealousy — how well do you know it?",
          ctx: "Not only in love: a friend who prefers someone else counts too. From the most honest about you to the least.",
          o: ["😌 None, complete trust", "🌡️ A bit, that's human", "🔥 Quite a lot, and I own it"] } },
  { id: "vi-reseaux", axis: "vices",
    fr: { q: "Ta vie privée sur les réseaux, ça donne quoi ?",
          ctx: "Tes proches, tes soirées, tes vacances. Du plus proche de ce que tu fais vraiment au plus éloigné.",
          o: ["📸 J'assume, je poste", "🫥 Quelques photos, discret", "🤐 Zéro publication"] },
    en: { q: "Your private life on social media — what's the picture?",
          ctx: "The people close to you, your nights out, your holidays. From closest to what you actually do to furthest.",
          o: ["📸 I own it, I post", "🫥 A few photos, discreet", "🤐 Nothing, ever"] } },
  { id: "au-ex-ami", axis: "autres",
    fr: { q: "Rester ami avec un ex, c'est possible ?",
          ctx: "La question de principe, pas ton cas personnel. Du plus proche de ce que tu penses au plus éloigné.",
          o: ["👍 Complètement possible", "😬 Compliqué mais faisable", "🚫 Jamais de la vie"] },
    en: { q: "Can you stay friends with an ex?",
          ctx: "The question in principle, not your own case. From closest to what you think to furthest.",
          o: ["👍 Entirely possible", "😬 Complicated but doable", "🚫 Not in this lifetime"] } },

  // ------------------------------------------------------------ argent
  { id: "ar-preter", axis: "argent",
    fr: { q: "Un proche te demande de lui prêter de l'argent",
          ctx: "Une somme qui compte pour toi, sans date de remboursement annoncée. Du plus proche de toi au plus éloigné.",
          o: ["🤝 Je prête sans hésiter", "📝 Oui, mais avec une date", "🙅 Je ne prête jamais"] },
    en: { q: "Someone close asks to borrow money",
          ctx: "An amount that matters to you, with no repayment date mentioned. From closest to you to furthest.",
          o: ["🤝 I lend it without hesitating", "📝 Yes, but with a date", "🙅 I never lend money"] } },
  { id: "ar-gain", axis: "argent",
    fr: { q: "Tu gagnes beaucoup d'argent d'un coup",
          ctx: "Une somme qui change des choses, personne n'est au courant. Du réflexe le plus vrai pour toi au moins vrai.",
          o: ["🤫 Je ne le dis à personne", "🎁 J'en fais profiter mes proches", "📢 Tout le monde le sait très vite"] },
    en: { q: "You come into a lot of money at once",
          ctx: "An amount that changes things, and nobody knows. From the truest reflex for you to the least true.",
          o: ["🤫 I tell nobody", "🎁 I share it with people close to me", "📢 Everyone knows within a day"] } },
  { id: "ar-addition", axis: "argent",
    fr: { q: "L'addition arrive, vous êtes six",
          ctx: "Certains ont pris une entrée et du vin, d'autres un plat et de l'eau. Du réflexe le plus fréquent chez toi au plus rare.",
          o: ["➗ On divise en parts égales, c'est plus simple", "🧮 Chacun ce qu'il a pris, au centime", "🙋 Je paie tout, on verra la prochaine fois"] },
    en: { q: "The bill arrives, there are six of you",
          ctx: "Some had a starter and wine, others a main and tap water. From your most common reflex to your rarest.",
          o: ["➗ Split it evenly, it's simpler", "🧮 Each pays for what they had, to the cent", "🙋 I get it all, we'll sort it next time"] } },
  { id: "ar-depense", axis: "argent",
    fr: { q: "Sur quoi tu ne regardes jamais le prix ?",
          ctx: "Le poste où ton budget part sans que tu discutes. Du plus vrai pour toi au moins vrai.",
          o: ["🍽️ La bouffe et les restos", "✈️ Les voyages", "🏠 Le confort de chez toi"] },
    en: { q: "What do you never check the price of?",
          ctx: "The one area where your money goes without any argument. From the truest for you to the least true.",
          o: ["🍽️ Food and eating out", "✈️ Travel", "🏠 Making home comfortable"] } },
  { id: "ar-salaire", axis: "argent",
    fr: { q: "Un ami te demande combien tu gagnes",
          ctx: "Sincèrement curieux, sans arrière-pensée, un soir où vous parlez de tout. Du plus proche de toi au plus éloigné.",
          o: ["💬 Je réponds franchement", "🤏 Je donne un ordre d'idée", "🚫 Je change de sujet"] },
    en: { q: "A friend asks what you earn",
          ctx: "Genuinely curious, no agenda, on an evening where you're talking about everything. From closest to you to furthest.",
          o: ["💬 I answer honestly", "🤏 I give a rough idea", "🚫 I change the subject"] } },
  { id: "ar-role", axis: "argent",
    fr: { q: "Dans ton groupe, tu es lequel des trois ?",
          ctx: "Sois honnête, ils sont là pour vérifier. Du plus vrai pour toi au moins vrai.",
          o: ["💸 Celui qui offre les tournées", "🧾 Celui qui compte au centime", "😶 Celui qui laisse les autres gérer"] },
    en: { q: "In your group, which of the three are you?",
          ctx: "Be honest, they're right there to check. From the truest for you to the least true.",
          o: ["💸 The one who buys the round", "🧾 The one counting every last cent", "😶 The one who lets others handle it"] } },
  { id: "ar-achat", axis: "argent",
    fr: { q: "Un objet cher te fait envie. Tu fais quoi ?",
          ctx: "Tu peux te le payer, mais ce n'est pas raisonnable ce mois-ci. Du plus fréquent chez toi au plus rare.",
          o: ["🛒 Je l'achète tout de suite", "⏳ J'attends deux semaines pour voir", "📊 Je compare pendant un mois"] },
    en: { q: "You want something expensive. What do you do?",
          ctx: "You can afford it, but it isn't sensible this month. From what happens most often to least.",
          o: ["🛒 I buy it right away", "⏳ I wait two weeks to see", "📊 I compare for a month"] } },

  // ------------------------------------------------------------ ce qui agace
  { id: "ag-quotidien", axis: "agace",
    fr: { q: "Qu'est-ce qui t'agace le plus dans une journée ?",
          ctx: "Des micro-trucs, tous les jours, qui finissent par user. Du plus insupportable pour toi au moins insupportable.",
          o: ["🔊 Les gens qui parlent fort au téléphone", "🐌 Ceux qui marchent lentement devant toi", "📢 La musique dans les magasins"] },
    en: { q: "What irritates you most in a normal day?",
          ctx: "Tiny things, every day, that wear you down in the end. From most unbearable for you to least.",
          o: ["🔊 People talking loudly on the phone", "🐌 People walking slowly in front of you", "📢 The music in shops"] } },
  { id: "ag-groupe", axis: "agace",
    fr: { q: "Dans une bande, qu'est-ce qui te fatigue le plus ?",
          ctx: "Un groupe que tu aimes bien, malgré tout, et que tu continues de voir. Du plus fatigant pour toi au moins fatigant.",
          o: ["🎙️ Celui qui monopolise la parole", "📅 Celui qui annule toujours", "🤐 Celui qui ne donne jamais son avis"] },
    en: { q: "In a group, what tires you out most?",
          ctx: "A group you're fond of, despite everything, and keep seeing. From most tiring for you to least.",
          o: ["🎙️ The one who does all the talking", "📅 The one who always cancels", "🤐 The one who never gives an opinion"] } },
  { id: "ag-table", axis: "agace",
    fr: { q: "À table, qu'est-ce que tu ne supportes pas ?",
          ctx: "Un dîner normal, avec des gens que tu aimes bien. Tu ne diras rien. Du plus insupportable au moins insupportable.",
          o: ["😋 Qu'on mâche bruyamment", "📱 Qu'on sorte son téléphone", "🍽️ Qu'on commence avant tout le monde"] },
    en: { q: "At the table, what can't you stand?",
          ctx: "An ordinary dinner, with people you're fond of. You won't say anything. From most unbearable to least.",
          o: ["😋 Loud chewing", "📱 Phones coming out", "🍽️ Starting before everyone is served"] } },
  { id: "ag-maison", axis: "agace",
    fr: { q: "Chez quelqu'un, qu'est-ce qui te fait tiquer ?",
          ctx: "Tu es invité, tu ne diras rien, mais tu l'as vu tout de suite. Du plus dérangeant pour toi au moins dérangeant.",
          o: ["🧦 Les chaussures dans le salon", "🧼 L'évier plein de vaisselle", "🌡️ Le chauffage à 25 degrés"] },
    en: { q: "At someone's place, what makes you wince?",
          ctx: "You're a guest, you won't say anything, but you spotted it immediately. From most bothersome for you to least.",
          o: ["🧦 Shoes on in the living room", "🧼 A sink full of washing-up", "🌡️ The heating at 25 degrees"] } },
  { id: "ag-conversation", axis: "agace",
    fr: { q: "Quelle conversation te donne envie de fuir ?",
          ctx: "Vingt minutes debout, impossible de partir poliment. Du plus pénible pour toi au moins pénible.",
          o: ["🏥 Les problèmes de santé en détail", "💼 Le travail de quelqu'un que tu ne connais pas", "🚗 Les histoires de bouchons et de trajets"] },
    en: { q: "Which conversation makes you want to escape?",
          ctx: "Twenty minutes standing up, with no polite way out. From most painful for you to least.",
          o: ["🏥 Health problems in full detail", "💼 The job of someone you've never met", "🚗 Stories about traffic and commutes"] } },
  { id: "ag-attente", axis: "agace",
    fr: { q: "On te fait attendre. Tu craques au bout de combien ?",
          ctx: "Quelqu'un que tu aimes bien, qui n'a pas prévenu, et qui ne répond pas. Du plus proche de toi au plus éloigné.",
          o: ["⏱️ Dix minutes et j'écris déjà", "🕐 Une demi-heure, ça passe", "🧘 Je m'en fiche, j'attends"] },
    en: { q: "You're kept waiting. When do you crack?",
          ctx: "Someone you're fond of, who didn't warn you, and isn't replying. From closest to you to furthest.",
          o: ["⏱️ Ten minutes and I'm already texting", "🕐 Half an hour is survivable", "🧘 I don't mind, I'll wait"] } },

  // ---------------------------------------------- lot du 12/09/2026
  // `heat` (1 à 3) note à quel point la scène demande un aveu. Le champ ne
  // sort pas du serveur : pubQuestion ne recopie que id, q, o, ctx et pack.
  // Il est là pour pouvoir, un jour, filtrer les scènes les plus gênantes
  // dans les parties familiales — la banque est commune à toutes les parties.

  // --- ce qui t'agace (l'axe le plus pauvre : 7 scènes pour 3 ou 4 tirées
  //     à chaque partie, donc toujours les mêmes)
  { id: "ag-vocal-quatre", axis: "agace", heat: 2,
    fr: { q: "Un vocal de quatre minutes vient d'arriver",
          ctx: "Quelqu'un que tu aimes bien t'envoie un vocal de quatre minutes, sans résumé. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🎧 Je l'écoute en vitesse x2 en faisant autre chose", "🙈 Je l'ouvre dans deux jours, peut-être", "📝 Je réponds « tu peux écrire ? »"] },
    en: { q: "A four-minute voice note has just landed",
          ctx: "Someone you're fond of sends a four-minute voice note, with no summary. From the truest answer for you to the least true.",
          o: ["🎧 I play it at double speed while doing something else", "🙈 I'll open it in two days, maybe", "📝 I reply “can you type it?”"] } },
  { id: "ag-petit-bruit", axis: "agace", heat: 1,
    fr: { q: "Quel petit bruit te rend dingue ?",
          ctx: "Tu es à côté de quelqu'un dans un endroit calme, et ça commence. Du plus insupportable au moins insupportable.",
          o: ["🥣 La cuillère qui racle le fond du bol", "💻 Le clavier qu'on tape comme pour le punir", "🍬 Le chewing-gum qui claque sans pause"] },
    en: { q: "Which small noise drives you mad?",
          ctx: "You're sitting next to someone somewhere quiet, and it begins. From most unbearable to least.",
          o: ["🥣 A spoon scraping the bottom of a bowl", "💻 A keyboard being typed on as punishment", "🍬 Chewing gum snapping without pause"] } },
  { id: "ag-coupe-parole", axis: "agace", heat: 2,
    fr: { q: "On te coupe la parole en plein milieu",
          ctx: "Tu racontes quelque chose, et quelqu'un enchaîne sur autre chose avant ta fin. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🔁 Je reprends mot pour mot là où j'en étais", "🤐 Je laisse tomber, tant pis pour eux", "📢 Je continue, juste un peu plus fort"] },
    en: { q: "You get cut off mid-sentence",
          ctx: "You're telling a story, and someone jumps to something else before you finish. From the truest answer for you to the least true.",
          o: ["🔁 I pick up word for word where I left off", "🤐 I drop it, their loss", "📢 I carry on, just a bit louder"] } },
  { id: "ag-histoire-fausse", axis: "agace", heat: 3,
    fr: { q: "On raconte mal une histoire que tu connais",
          ctx: "Quelqu'un raconte une anecdote que tu connais, avec la moitié des détails faux. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📢 Je corrige les détails un par un", "🎭 Je souris et je me venge dans ma tête", "🙃 J'ajoute des détails encore plus faux"] },
    en: { q: "Someone tells a story you know, badly",
          ctx: "Someone recounts an anecdote you know, with half the details wrong. From the truest answer for you to the least true.",
          o: ["📢 I correct the details one by one", "🎭 I smile and take revenge in my head", "🙃 I add details that are even more wrong"] } },
  { id: "ag-trottoir-lent", axis: "agace", heat: 1,
    fr: { q: "Sur le trottoir, quelqu'un marche lentement devant toi",
          ctx: "La personne devant toi avance à deux à l'heure, et tu n'as pas toute la journée. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🏃 Je double en trottinant, avec un « pardon »", "😤 Je reste derrière et je souffle très fort", "📱 Je sors mon téléphone, ça ira comme ça"] },
    en: { q: "Someone is walking slowly in front of you",
          ctx: "The person ahead is moving at a crawl, and you haven't got all day. From the truest answer for you to the least true.",
          o: ["🏃 I overtake at a trot, with a “sorry”", "😤 I stay behind and sigh very loudly", "📱 I get my phone out, this'll do"] } },
  { id: "ag-faut-se-voir", axis: "agace", heat: 2,
    fr: { q: "« Faut qu'on se voie ! » pour la cinquième fois",
          ctx: "Quelqu'un te redit « faut vraiment qu'on se voie » sans jamais proposer de date. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📅 Je propose une date tout de suite, pour voir", "😌 Je dis oui, on sait tous les deux que non", "🪞 Je le dis autant qu'on me le dit"] },
    en: { q: "“We must catch up!” for the fifth time",
          ctx: "Someone tells you again that you really must meet up, without ever suggesting a date. From the truest answer for you to the least true.",
          o: ["📅 I suggest a date right away, to see", "😌 I say yes, we both know it's no", "🪞 I say it as much as it's said to me"] } },
  { id: "ag-reponse-ciel", axis: "agace", heat: 1,
    fr: { q: "Quelle réponse te fait lever les yeux au ciel ?",
          ctx: "Tu as écrit un vrai message, avec une vraie question, et voilà ce qui revient. Du plus insupportable au moins insupportable.",
          o: ["👍 Le pouce bleu, et rien d'autre", "😂 Un « mdr » à une question sérieuse", "👀 Le « vu » qui reste vu pendant trois jours"] },
    en: { q: "Which reply makes you roll your eyes?",
          ctx: "You wrote a real message, with a real question, and this is what comes back. From most unbearable to least.",
          o: ["👍 The thumbs-up, and nothing else", "😂 A “lol” to a serious question", "👀 The “seen” that stays seen for three days"] } },
  { id: "ag-groupe-emballe", axis: "agace", heat: 3,
    fr: { q: "Un groupe de discussion s'emballe : 80 messages",
          ctx: "Un groupe part en vrille pendant une heure sur un sujet qui ne te concerne pas. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🔕 Je mets en sourdine pour un an, minimum", "👀 Je lis tout, je ne réponds jamais rien", "🚪 Je quitte le groupe sans prévenir"] },
    en: { q: "A group chat goes off: 80 messages",
          ctx: "A group chat spirals for an hour over something that doesn't involve you. From the truest answer for you to the least true.",
          o: ["🔕 Muted for a year, minimum", "👀 I read all of it and never reply", "🚪 I leave the group without a word"] } },
  { id: "ag-point-interro", axis: "agace", heat: 2,
    fr: { q: "Tu n'as pas répondu. On t'envoie un « ? »",
          ctx: "Un message attendait depuis hier, et voilà qu'un point d'interrogation débarque. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["😬 Je réponds dans la seconde, la honte", "🙄 Je laisse mariner encore, par principe", "📞 J'appelle direct pour couper court"] },
    en: { q: "You didn't reply. They send you a “?”",
          ctx: "A message has been waiting since yesterday, and now a question mark turns up. From the truest answer for you to the least true.",
          o: ["😬 I reply within the second, mortified", "🙄 I leave it a bit longer, on principle", "📞 I call them to cut it short"] } },
  { id: "ag-explique-connu", axis: "agace", heat: 2,
    fr: { q: "On t'explique un truc que tu connais par cœur",
          ctx: "Quelqu'un t'explique avec passion une chose que tu maîtrises bien mieux que lui. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["😐 J'écoute jusqu'au bout, en hochant la tête", "🤚 Je coupe : « oui, je sais »", "🎓 Je laisse finir, puis je corrige un détail"] },
    en: { q: "Someone explains something you know inside out",
          ctx: "Someone enthusiastically explains a thing you understand far better than they do. From the truest answer for you to the least true.",
          o: ["😐 I listen to the end, nodding along", "🤚 I cut in: “yes, I know”", "🎓 I let them finish, then correct one detail"] } },
  { id: "ag-reve-raconte", axis: "agace", heat: 1,
    fr: { q: "On te raconte un rêve, en détail",
          ctx: "On te raconte un rêve avec des couloirs, des portes et une prof de CM2. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["😴 Je décroche dès la deuxième phrase", "🤔 J'écoute et je cherche ce que ça veut dire", "📢 J'enchaîne avec le mien, plus long"] },
    en: { q: "Someone is telling you their dream, in detail",
          ctx: "You're being told a dream with corridors, doors, and a primary school teacher. From the truest answer for you to the least true.",
          o: ["😴 I switch off by the second sentence", "🤔 I listen and try to work out what it means", "📢 I follow up with mine, which is longer"] } },
  { id: "ag-ok-sec", axis: "agace", heat: 3,
    fr: { q: "On répond « ok » à ton long message",
          ctx: "Tu avais écrit dix lignes avec du cœur, et la réponse tient en deux lettres. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["😑 Je relis mon message, c'était peut-être trop", "🙃 Je réponds « ok » aussi, et on verra", "🤷 Je m'en fiche, c'était juste une info"] },
    en: { q: "They reply “ok” to your long message",
          ctx: "You'd written ten lines with real feeling, and the reply is two letters. From the truest answer for you to the least true.",
          o: ["😑 I reread mine, maybe it was too much", "🙃 I reply “ok” back, and we'll see", "🤷 I don't care, it was just information"] } },
  { id: "ag-mot-repris", axis: "agace", heat: 2,
    fr: { q: "On te reprend sur la prononciation d'un mot",
          ctx: "Devant du monde, on te corrige sur un mot que tu dis comme ça depuis toujours. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["😊 Je dis merci et je corrige tout de suite", "😏 Je continue à le dire à ma façon, exprès", "😳 J'y repense encore le soir dans mon lit"] },
    en: { q: "Someone corrects how you pronounce a word",
          ctx: "In front of people, you're corrected on a word you've said that way your whole life. From the truest answer for you to the least true.",
          o: ["😊 I say thanks and correct it on the spot", "😏 I keep saying it my way, deliberately", "😳 I'm still thinking about it that night in bed"] } },
  { id: "ag-ecoute-ca", axis: "agace", heat: 3,
    fr: { q: "« Écoute ça, tu vas adorer » : tu fais quoi ?",
          ctx: "Quelqu'un lance une chanson, te tend le téléphone et te fixe pendant que tu écoutes. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🎧 J'écoute vingt secondes et je dis « pas mal »", "😊 Je hoche la tête avant même la fin de l'intro", "🙅 Je dis « plus tard », et plus tard n'arrive jamais"] },
    en: { q: "“Listen to this, you'll love it” — what do you do?",
          ctx: "Someone starts a song, hands you the phone, and watches you while you listen. From the truest answer for you to the least true.",
          o: ["🎧 I listen twenty seconds and say “not bad”", "😊 I nod before the intro has even finished", "🙅 I say “later”, and later never comes"] } },

  // --- argent
  { id: "ar-abonnement-fantome", axis: "argent", heat: 2,
    fr: { q: "Un abonnement que tu n'utilises plus se prélève",
          ctx: "Le prélèvement mensuel d'une appli que tu n'ouvres plus vient de passer. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🧾 Je résilie le jour même, avec fierté", "📆 Je me dis « ce mois-ci » depuis mars", "🤷 Je le garde, au cas où je m'y remette"] },
    en: { q: "A subscription you no longer use just charged you",
          ctx: "The monthly payment for an app you never open has just gone out. From the truest answer for you to the least true.",
          o: ["🧾 I cancel the same day, proudly", "📆 I've been saying “this month” since March", "🤷 I keep it, in case I go back to it"] } },
  { id: "ar-sept-euros", axis: "argent", heat: 2,
    fr: { q: "On te doit 7 €. Tu réclames ?",
          ctx: "Quelqu'un a oublié de te rembourser un café et un sandwich, il y a deux semaines. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["💬 Je relance avec un « au fait ! » léger", "🧮 Je ne dis rien mais je n'oublie pas", "🙃 Je laisse tomber, demander me gêne trop"] },
    en: { q: "Someone owes you €7. Do you ask?",
          ctx: "Someone forgot to pay you back for a coffee and a sandwich, two weeks ago. From the truest answer for you to the least true.",
          o: ["💬 I nudge them with a light “by the way!”", "🧮 I say nothing but I don't forget", "🙃 I let it go, asking embarrasses me too much"] } },
  { id: "ar-trois-cinquante", axis: "argent", heat: 3,
    fr: { q: "Tu dois 3,50 € à quelqu'un. Tu fais quoi ?",
          ctx: "On t'a avancé une boisson hier, et personne n'en a reparlé depuis. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📲 Virement dans la minute, libellé « boisson »", "🍕 Je rembourse à la prochaine sortie, promis", "😇 J'attends de voir si la personne s'en souvient"] },
    en: { q: "You owe someone €3.50. What do you do?",
          ctx: "They covered a drink for you yesterday, and nobody has mentioned it since. From the truest answer for you to the least true.",
          o: ["📲 Transfer within the minute, labelled “drink”", "🍕 I'll get it next time we're out, promise", "😇 I wait and see whether they remember"] } },
  { id: "ar-pourboire", axis: "argent", heat: 2,
    fr: { q: "Le repas était bien. Tu laisses un pourboire ?",
          ctx: "Service correct, addition réglée par carte, et tu n'as pas de monnaie sur toi. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["💶 Je laisse des pièces sur la table, toujours", "🙈 Je n'ai jamais de liquide, donc jamais", "🎯 Seulement si le serveur a été vraiment bien"] },
    en: { q: "The meal was good. Do you leave a tip?",
          ctx: "Decent service, bill paid by card, and you've no change on you. From the truest answer for you to the least true.",
          o: ["💶 I always leave coins on the table", "🙈 I never have cash, so never", "🎯 Only if the waiter was genuinely good"] } },
  { id: "ar-etiquette-oubliee", axis: "argent", heat: 2,
    fr: { q: "Qu'est-ce qui traîne encore avec l'étiquette ?",
          ctx: "Tu fais du tri chez toi et tu retombes sur des achats qui n'ont jamais vraiment servi. Du plus fréquent chez toi au plus rare.",
          o: ["👟 Des baskets « pour reprendre le sport »", "🍳 Un appareil de cuisine utilisé une seule fois", "🧥 Une veste pour une version plus stylée de moi"] },
    en: { q: "What's still lying around with the tag on?",
          ctx: "You're having a clear-out and you find purchases that never really got used. From what happens most often to least.",
          o: ["👟 Trainers “for getting back into sport”", "🍳 A kitchen gadget used exactly once", "🧥 A jacket for a more stylish version of me"] } },
  { id: "ar-cagnotte-cadeau", axis: "argent", heat: 3,
    fr: { q: "Une cagnotte cadeau circule. Tu mets combien ?",
          ctx: "Une cagnotte arrive avec un montant conseillé, et tout le monde voit qui a mis quoi. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["💸 Le montant conseillé, pas un centime de plus", "🎁 Un peu plus, puisque tout le monde voit", "🤫 Un peu moins, personne ne compare vraiment"] },
    en: { q: "A group gift pot is going round. How much do you put in?",
          ctx: "The pot arrives with a suggested amount, and everyone can see who gave what. From the truest answer for you to the least true.",
          o: ["💸 The suggested amount, not a cent more", "🎁 A bit more, since everyone can see", "🤫 A bit less, nobody really compares"] } },
  { id: "ar-ticket-oublie", axis: "argent", heat: 3,
    fr: { q: "Un article manque sur ton ticket de caisse",
          ctx: "En rangeant tes courses, tu vois qu'un article n'a pas été scanné. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🏪 Je retourne à la caisse, la conscience légère", "🤫 Cadeau de la maison, je ne dis rien", "🎲 Ça dépend du prix de l'article"] },
    en: { q: "An item is missing from your receipt",
          ctx: "Unpacking the shopping, you see that something wasn't scanned. From the truest answer for you to the least true.",
          o: ["🏪 I go back to the till, conscience clear", "🤫 On the house, I say nothing", "🎲 Depends what the item cost"] } },
  { id: "ar-retour-article", axis: "argent", heat: 3,
    fr: { q: "Un achat te déçoit : tu le ramènes ?",
          ctx: "Un achat à 19 € s'avère inutile une fois chez toi, et tu as encore le ticket. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🧾 Je ramène tout, même un chargeur à 9 €", "📦 Je garde le ticket et je n'y retourne jamais", "🎁 Ça deviendra un cadeau pour quelqu'un"] },
    en: { q: "A purchase disappoints. Do you take it back?",
          ctx: "A €19 purchase turns out to be useless once home, and you still have the receipt. From the truest answer for you to the least true.",
          o: ["🧾 I return everything, even a €9 charger", "📦 I keep the receipt and never go back", "🎁 It'll become a present for someone"] } },
  { id: "ar-appli-banque", axis: "argent", heat: 2,
    fr: { q: "Ton compte en banque, tu le regardes quand ?",
          ctx: "L'appli de ta banque est là, sur l'écran d'accueil, entre deux notifications. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["📲 Dix fois par jour, comme un réseau social", "🙈 Le moins possible : pas vu, pas pris", "📅 Une fois par semaine, calmement"] },
    en: { q: "Your bank balance — when do you look?",
          ctx: "Your banking app is right there on the home screen, between two notifications. From the truest answer for you to the least true.",
          o: ["📲 Ten times a day, like a social network", "🙈 As little as possible: out of sight, out of mind", "📅 Once a week, calmly"] } },
  { id: "ar-frais-de-port", axis: "argent", heat: 1,
    fr: { q: "12 € d'article, 5 € de frais de port",
          ctx: "Tu commandes un petit truc en ligne et la livraison coûte presque la moitié du prix. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🛒 J'ajoute un truc inutile pour la livraison offerte", "💸 Je paie les 5 €, la vie est courte", "🚪 J'abandonne le panier, par principe"] },
    en: { q: "A €12 item, €5 of shipping",
          ctx: "You're ordering something small online and delivery costs almost half the price. From the truest answer for you to the least true.",
          o: ["🛒 I add something useless to get free delivery", "💸 I pay the €5, life is short", "🚪 I abandon the basket, on principle"] } },
  { id: "ar-code-promo", axis: "argent", heat: 1,
    fr: { q: "Avant de payer en ligne, tu fais quoi ?",
          ctx: "Le panier est prêt, la carte est sortie, et il reste ce petit champ « code promo » qui te regarde. Du plus fréquent chez toi au plus rare.",
          o: ["🔎 Je cherche un code pendant vingt minutes", "📧 Je laisse le panier, un mail promo arrivera", "💳 Je paie direct, le temps c'est de l'argent"] },
    en: { q: "Just before paying online, what do you do?",
          ctx: "The basket is ready, the card is out, and that little “promo code” box is staring at you. From what happens most often to least.",
          o: ["🔎 I hunt for a code for twenty minutes", "📧 I leave the basket, a discount email will come", "💳 I pay straight away, time is money"] } },
  { id: "ar-prix-avoue", axis: "argent", heat: 3,
    fr: { q: "« Tu l'as payé combien ? » Tu dis quoi ?",
          ctx: "On te complimente sur un objet, et la question du prix arrive juste derrière. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["💬 Le vrai prix, au centime près", "📉 Un peu moins que le vrai, par réflexe", "📈 Un peu plus que le vrai, par fierté"] },
    en: { q: "“How much did you pay for that?” What do you say?",
          ctx: "Someone compliments something of yours, and the price question follows immediately. From the truest answer for you to the least true.",
          o: ["💬 The real price, to the cent", "📉 A bit less than the truth, by reflex", "📈 A bit more than the truth, out of pride"] } },
  { id: "ar-sous-marque", axis: "argent", heat: 1,
    fr: { q: "Au supermarché, la marque ou la sous-marque ?",
          ctx: "Même rayon, même produit, deux prix : l'emballage connu à côté de celui du magasin. De la réponse la plus vraie pour toi à la moins vraie.",
          o: ["🔖 La sous-marque partout, sans aucune honte", "🧀 La marque pour deux ou trois produits sacrés", "✨ La marque partout, la sous-marque me déprime"] },
    en: { q: "At the supermarket: the brand or the own label?",
          ctx: "Same shelf, same product, two prices: the name you know next to the shop's own. From the truest answer for you to the least true.",
          o: ["🔖 Own label everywhere, no shame at all", "🧀 The brand for two or three sacred products", "✨ The brand everywhere, own label depresses me"] } },
];
