// Are We A Match? — pack 🌶️ Piquant / apéro.
// Version plus osée et provocante, pensée pour une soirée arrosée entre gens
// qui se connaissent. Reste dans le registre « apéro » : ça pique, ça fait
// réagir et débattre, sans être sale ni humiliant.

module.exports = [
  { id: "pq-secret", q: "Le pire secret à apprendre sur un ami", o: ["💸 Il t'a menti sur de l'argent", "💋 Il a embrassé ton ex", "🗣️ Il a répété un truc confidentiel"] },
  { id: "pq-avouer", q: "Le plus difficile à avouer", o: ["😬 Une grosse honte publique", "💔 Un sentiment non partagé", "🤥 Un mensonge qui a duré"] },
  { id: "pq-pire-coloc", q: "Le pire colocataire", o: ["🔊 Celui qui fait du bruit la nuit", "🧼 Celui qui ne nettoie jamais", "💰 Celui qui paie toujours en retard"] },
  { id: "pq-tentation", q: "La tentation à laquelle tu résistes le moins", o: ["🍰 La bouffe", "🛒 Les achats impulsifs", "📱 Le scroll infini"] },
  { id: "pq-vengeance", q: "Ta vengeance préférée", o: ["🧊 L'indifférence totale", "🎭 Une blague bien placée", "🔥 La confrontation directe"] },
  { id: "pq-mytho", q: "Le mensonge que tout le monde fait", o: ["😴 « J'arrive dans 5 minutes »", "📖 « Oui j'ai lu le contrat »", "😀 « Non non ça va très bien »"] },
  { id: "pq-jugement", q: "Ce sur quoi tu juges le plus vite", o: ["🎵 Les goûts musicaux", "🚗 La façon de conduire", "🍽️ Les manières à table"] },
  { id: "pq-honte", q: "Le souvenir le plus gênant", o: ["💃 Une danse en soirée", "📧 Un message envoyé au mauvais destinataire", "🎤 Un karaoké assumé trop fort"] },
  { id: "pq-fesse", q: "Le plaisir coupable le plus assumable", o: ["📺 Télé-réalité", "🎶 Chanson française ringarde", "🍔 Fast-food à 2 h du matin"] },
  { id: "pq-limite", q: "Ta limite en soirée", o: ["🕛 Minuit et je disparais", "🌅 Jusqu'au lever du soleil", "🎲 Aucune règle, ça dépend"] },
  { id: "pq-ex-contact", q: "Rester ami avec un ex", o: ["👍 Complètement possible", "😬 Compliqué mais faisable", "🚫 Jamais de la vie"] },
  { id: "pq-argent-ami", q: "Prêter de l'argent à un ami", o: ["🤝 Sans hésiter", "📝 Oui mais avec une deadline", "🙅 Je ne prête jamais"] },
  { id: "pq-drama", q: "Ton rôle dans un drama de groupe", o: ["🍿 Spectateur qui adore", "🕊️ Médiateur qui calme", "🔥 Celui qui met de l'huile"] },
  { id: "pq-photo-gene", q: "Une photo gênante de toi circule", o: ["😂 J'en ris et je la partage", "😐 Je demande de la supprimer", "😡 Ça me met vraiment en colère"] },
  { id: "pq-boire", q: "Le lendemain de soirée", o: ["🍳 Gros brunch réparateur", "🛏️ Journée au lit complète", "🏃 Sport pour éliminer"] },
  { id: "pq-flirt", q: "Flirter, pour toi c'est", o: ["😏 Un jeu, ça ne coûte rien", "⚠️ Ça dépend du contexte", "🚧 Une ligne à ne pas franchir"] },
  { id: "pq-reveal", q: "Si tu devais révéler un truc sur toi", o: ["🎯 Un échec professionnel", "💘 Un crush inavoué", "🤐 Une bêtise jamais avouée"] },
  { id: "pq-competition-amis", q: "Battre un ami à un jeu", o: ["🏆 Je savoure et je le rappelle", "😊 Content mais discret", "🤫 Je le laisse gagner parfois"] },
  { id: "pq-cancel", q: "Annuler un plan à la dernière minute", o: ["📵 Je le fais sans culpabiliser", "😅 Je culpabilise mais je le fais", "🚫 Je ne le fais jamais"] },
  { id: "pq-verite", q: "Tu préfères qu'on te dise", o: ["🗡️ La vérité même si ça pique", "🍬 Une version adoucie", "🤷 Rien du tout si c'est inutile"] },
  { id: "pq-tabou", q: "Le sujet le plus tabou à table", o: ["💰 L'argent", "🗳️ La politique", "❤️ La vie intime"] },
  { id: "pq-crush", q: "Un crush sur un ami du groupe", o: ["🤐 Je garde ça pour moi à vie", "🗣️ Je finis toujours par le dire", "🍷 Ça sort après trois verres"] },
  { id: "pq-defaut", q: "Ton pire défaut assumé", o: ["😤 Têtu", "🐌 Toujours en retard", "🙃 Sarcastique un peu trop"] },
  { id: "pq-secret-groupe", q: "Le secret le plus dangereux dans un groupe", o: ["💔 Une histoire entre deux membres", "💸 Une dette non remboursée", "🗨️ Ce qu'on dit dans le dos"] },
  { id: "pq-attention", q: "Tu aimes être le centre de l'attention", o: ["✨ Oui, totalement", "🎭 Par moments seulement", "🙈 Jamais, l'horreur"] },
  { id: "pq-rire", q: "Rire de quelqu'un qui tombe", o: ["😂 Immédiatement, désolé", "🫣 Après avoir vérifié que ça va", "😟 Non, je m'inquiète direct"] },
  { id: "pq-pardon", q: "Pardonner une trahison", o: ["🕊️ Oui, on est humain", "⏳ Peut-être, avec du temps", "⛔ Jamais, c'est terminé"] },
  { id: "pq-portable", q: "Laisser quelqu'un fouiller ton téléphone", o: ["📱 Aucun problème", "😬 Ça me met mal à l'aise", "🔒 Hors de question"] },
  { id: "pq-fake", q: "Le pire comportement en société", o: ["🎩 Se la raconter en permanence", "🐍 Être faux avec les gens", "😑 Ne jamais faire d'effort"] },
  { id: "pq-drague", q: "La pire approche possible", o: ["📢 Trop insistante", "🥱 Trop banale", "🤡 Trop de blagues forcées"] },
  { id: "pq-regret", q: "Ce que tu regrettes le plus", o: ["🚪 Les occasions non saisies", "🗣️ Les mots de trop", "⏰ Le temps perdu avec les mauvaises personnes"] },
  { id: "pq-alcool", q: "Sous l'effet de l'alcool, tu deviens", o: ["🕺 Très fêtard", "🫂 Très affectueux", "🗣️ Très bavard et philosophe"] },
  { id: "pq-image", q: "Ce que tu veux qu'on pense de toi", o: ["😎 Que tu es drôle", "🧠 Que tu es brillant", "❤️ Que tu es fiable"] },
  { id: "pq-message-nuit", q: "Un message à 3 h du matin", o: ["📞 J'appelle direct", "💬 Je réponds au réveil", "🔕 Mode avion, on verra"] },
  { id: "pq-echec", q: "Face à un échec public", o: ["😅 J'en fais une blague", "🚪 Je disparais un moment", "💪 Je repars à l'attaque"] },
  { id: "pq-conseil", q: "Un ami fait une erreur évidente", o: ["🗣️ Je lui dis franchement", "🤏 Je glisse une allusion", "🤐 Je le laisse apprendre"] },
  { id: "pq-groupe-quitte", q: "Le pire dans un groupe d'amis", o: ["👥 Les clans qui se forment", "📅 Ceux qui ne viennent jamais", "🎙️ Celui qui monopolise tout"] },
  { id: "pq-argent-gagne", q: "Tu gagnes beaucoup d'argent d'un coup", o: ["🤫 Je ne le dis à personne", "🎁 J'en fais profiter les proches", "📢 Tout le monde le sait vite"] },
  { id: "pq-appli", q: "Les applis de rencontre", o: ["👍 Normal aujourd'hui", "😐 Ça dépanne mais bof", "🚫 Très peu pour moi"] },
  { id: "pq-secret-couple", q: "Dans un couple, on peut garder", o: ["🔐 Son jardin secret", "📖 Rien du tout, transparence", "🤏 Juste les détails sans importance"] },
  { id: "pq-tenue", q: "Un ami s'habille très mal pour une soirée", o: ["🗣️ Je lui dis avant de sortir", "🤫 Je ne dis rien", "😂 Je me moque gentiment"] },
  { id: "pq-karma", q: "Tu crois au karma", o: ["✨ Complètement", "🤔 Un peu, ça arrange", "🚫 Pas du tout"] },
  { id: "pq-premier", q: "La première impression", o: ["🎯 Presque toujours juste", "🔄 Souvent à revoir", "🙅 Je m'en méfie totalement"] },
  { id: "pq-fete-role", q: "En soirée tu finis toujours", o: ["🎧 À gérer la musique", "🍳 Dans la cuisine à discuter", "💃 Au milieu de la piste"] },
  { id: "pq-honnete", q: "Le compliment que tu préfères", o: ["🤣 « Tu me fais trop rire »", "🧠 « T'es vraiment intelligent »", "🫶 « On peut compter sur toi »"] },
];
