// Are We A Match? — pack 🎬 Pop culture.
// Films, séries, musique, jeux, internet. Très clivant par nature (donc
// excellent pour étaler les scores de compatibilité) et consensuel à jouer :
// personne ne se sent attaqué en classant des genres de films.

module.exports = [
  { id: "pc-genre-film", q: "Le genre de film que tu choisis", o: ["😱 Horreur", "😂 Comédie", "🚀 Science-fiction"] },
  { id: "pc-serie-format", q: "Ta série idéale", o: ["🔪 Thriller haletant", "😅 Sitcom réconfortante", "🐉 Grande fresque fantasy"] },
  { id: "pc-musique-genre", q: "Le genre musical qui te définit le mieux", o: ["🎸 Rock", "🎤 Rap", "🎧 Électro"] },
  { id: "pc-saga", q: "La saga que tu défends", o: ["🧙 Harry Potter", "⚔️ Le Seigneur des Anneaux", "🌌 Star Wars"] },
  { id: "pc-marvel-dc", q: "Super-héros", o: ["🕷️ Marvel", "🦇 DC", "🚫 Aucun des deux, merci"] },
  { id: "pc-jeu", q: "Une soirée jeu", o: ["🎮 Jeu vidéo", "🎲 Jeu de société", "🃏 Cartes"] },
  { id: "pc-anime", q: "Les animes japonais", o: ["🍥 J'adore, j'en regarde", "👀 J'en ai vu quelques-uns", "🚫 Pas du tout mon truc"] },
  { id: "pc-film-culte", q: "Le classique que tu remets le plus", o: ["🕴️ Pulp Fiction", "🎩 Le Parrain", "🐟 Le Fabuleux Destin d'Amélie Poulain"] },
  { id: "pc-humour-fr", q: "L'humour français que tu préfères", o: ["🎬 Les Bronzés / Le Père Noël est une ordure", "🗣️ Stand-up moderne", "🎭 OSS 117 / Kaamelott"] },
  { id: "pc-doublage", q: "Un film étranger", o: ["🔤 VOST toujours", "🗣️ VF sans complexe", "🤷 Ça dépend du film"] },
  { id: "pc-cinema", q: "Voir un film", o: ["🍿 Au cinéma, grand écran", "🛋️ À la maison peinard", "💻 Sur un écran, peu importe"] },
  { id: "pc-fin", q: "La fin que tu préfères", o: ["🌈 Happy end", "🌫️ Fin ouverte", "💀 Fin tragique assumée"] },
  { id: "pc-musique-live", q: "La musique en live", o: ["🎪 Gros festival", "🎼 Petite salle intimiste", "🎧 Jamais, je préfère chez moi"] },
  { id: "pc-podcast", q: "En écoute quotidienne", o: ["🎙️ Podcasts", "🎵 Musique", "📻 Radio"] },
  { id: "pc-reseau", q: "Le réseau où tu passes le plus de temps", o: ["📸 Instagram", "🎵 TikTok", "💼 LinkedIn (assume-le)"] },
  { id: "pc-meme", q: "L'humour internet", o: ["🐸 Memes absurdes", "🎞️ Vidéos courtes", "🧵 Threads bien écrits"] },
  { id: "pc-livre-film", q: "Une adaptation d'un livre que tu as aimé", o: ["📖 Le livre est toujours meilleur", "🎬 Le film peut faire mieux", "🤷 Ce sont deux œuvres différentes"] },
  { id: "pc-binge", q: "Une nouvelle saison sort", o: ["🌙 Tout en une nuit", "📆 Un épisode par jour", "⏳ J'attends d'avoir le temps"] },
  { id: "pc-spoiler", q: "Les spoilers", o: ["😡 Crime absolu", "😐 Ça ne me dérange pas", "😈 Parfois je spoile exprès"] },
  { id: "pc-musique-nostalgie", q: "La décennie musicale", o: ["🕺 80s", "📻 90s", "💿 2000s"] },
  { id: "pc-quiz-culture", q: "Ta culture la plus solide", o: ["🎬 Cinéma", "🎵 Musique", "🎮 Jeux vidéo"] },
  { id: "pc-serie-fr", q: "Les productions françaises", o: ["👏 Il y a de très bonnes choses", "😐 Bof, je regarde peu", "🚫 Je préfère l'étranger"] },
  { id: "pc-documentaire", q: "Un documentaire, tu choisis", o: ["🌍 Nature et animaux", "🔎 True crime", "🎨 Portrait d'artiste"] },
  { id: "pc-concert-place", q: "En concert, tu te places", o: ["🔥 Devant dans la fosse", "👀 Au milieu, bonne vue", "🪑 Assis au fond tranquille"] },
  { id: "pc-jeu-video-genre", q: "Le jeu vidéo que tu lances", o: ["🗺️ Aventure / monde ouvert", "🔫 Compétitif en ligne", "🧩 Puzzle / réflexion"] },
  { id: "pc-nostalgie", q: "Ce qui te rend le plus nostalgique", o: ["📼 Les dessins animés d'enfance", "🎮 Les vieilles consoles", "💿 Les CD et les mixtapes"] },
  { id: "pc-star", q: "Rencontrer une célébrité", o: ["🤩 Je fonce lui parler", "📱 Photo discrète de loin", "😎 Je fais comme si de rien"] },
  { id: "pc-remake", q: "Les remakes et reboots", o: ["🎉 Souvent une bonne surprise", "😤 Presque toujours ratés", "🤷 Ça dépend vraiment"] },
  { id: "pc-bd", q: "Lecture illustrée", o: ["📚 BD franco-belge", "🍜 Manga", "🦸 Comics"] },
  { id: "pc-theatre", q: "Une sortie culturelle", o: ["🎭 Théâtre", "🎨 Musée", "🎤 Concert"] },
  { id: "pc-musique-decouverte", q: "Tu découvres de la musique", o: ["🤖 Via les algorithmes", "👥 Via des amis", "🔍 Je cherche activement"] },
  { id: "pc-film-long", q: "Un film de 3 heures", o: ["🍿 Aucun problème si c'est bon", "😬 Il faut vraiment que ce soit justifié", "🚫 Trop long, je zappe"] },
  { id: "pc-ambiance", q: "L'ambiance qui te parle le plus", o: ["🌆 Cyberpunk néon", "🏰 Médiéval fantastique", "🏝️ Feel-good ensoleillé"] },
  { id: "pc-emission", q: "À la télé", o: ["🍳 Émission culinaire", "🏝️ Télé-réalité", "📰 Documentaire / info"] },
  { id: "pc-karaoke", q: "Au karaoké tu prends", o: ["🎤 Un classique que tout le monde chante", "🎸 Un truc rock que tu maîtrises", "🙈 Rien, je regarde"] },
  { id: "pc-heros", q: "Le personnage qui t'attire le plus", o: ["😈 L'anti-héros ambigu", "🦸 Le héros droit", "🃏 Le personnage comique"] },
  { id: "pc-son-film", q: "Ce qui fait un grand film", o: ["📖 L'histoire", "👁️ L'image", "🎼 La musique"] },
  { id: "pc-vieux-films", q: "Les films en noir et blanc", o: ["🎞️ J'adore", "😐 Rarement mais ok", "🚫 Impossible pour moi"] },
  { id: "pc-radio-voiture", q: "En voiture", o: ["🎵 Playlist préparée", "📻 Radio au hasard", "🎙️ Podcast"] },
  { id: "pc-jeu-mobile", q: "Les jeux sur téléphone", o: ["📱 J'en ai toujours un en cours", "🚽 Juste pour patienter", "🚫 Jamais"] },
  { id: "pc-film-peur", q: "Un film d'horreur", o: ["👻 J'adore avoir peur", "🫣 Seulement accompagné", "🙅 Jamais de la vie"] },
  { id: "pc-artiste", q: "Tu suis un artiste", o: ["💽 Pour ses albums uniquement", "🎬 Pour tout ce qu'il fait", "🎧 Je ne suis personne, juste des morceaux"] },
  { id: "pc-culture-debat", q: "Le débat culturel qui t'anime le plus", o: ["🎬 Le meilleur film de tous les temps", "🎵 Le meilleur album", "🎮 Le meilleur jeu"] },
  { id: "pc-serie-fin", q: "Une série que tu aimes se termine mal", o: ["😤 Ça gâche tout rétrospectivement", "🙂 Le voyage comptait plus", "🤷 J'oublie vite"] },
  { id: "pc-guilty", q: "Ton plaisir coupable culturel", o: ["🎶 Une chanson honteuse en boucle", "📺 Une émission gênante", "🎬 Un film noté 2/10 que tu adores"] },
];
