// QuizzMaster — thème 🇨🇳 Chine. 143 questions.

module.exports = [
  { text: "Quelle est la capitale de la Chine ?", options: ["Shanghai","Pékin","Canton","Hong Kong"], correct: 1 },
  { text: "Quelle est la monnaie officielle de la Chine ?", options: ["Yen","Won","Yuan","Baht"], correct: 2 },
  { text: "Quel est le plus long fleuve de Chine ?", options: ["Yangtsé","Fleuve Jaune","Mékong","Amour"], correct: 0 },
  { text: "Quel fleuve est surnommé le « fleuve Jaune » ?", options: ["Yangtsé","Huang He","Mékong","Perle"], correct: 1 },
  { text: "Quelle ville chinoise est la capitale économique et le plus grand port ?", options: ["Pékin","Shanghai","Shenzhen","Canton"], correct: 1 },
  { text: "Combien d'habitants compte la Chine (ordre de grandeur) ?", options: ["800 millions","1,4 milliard","2 milliards","500 millions"], correct: 1 },
  { text: "Quelle région autonome abrite l'Everest côté nord ?", options: ["Xinjiang","Tibet","Mongolie-Intérieure","Yunnan"], correct: 1 },
  { text: "Quel désert occupe le nord de la Chine ?", options: ["Sahara","Gobi","Atacama","Thar"], correct: 1 },
  { text: "Quelle ville a été une colonie portugaise jusqu'en 1999 ?", options: ["Hong Kong","Macao","Canton","Shenzhen"], correct: 1 },
  { text: "Quelle ville a été britannique jusqu'en 1997 ?", options: ["Macao","Hong Kong","Shanghai","Canton"], correct: 1 },
  { text: "Quel détroit sépare la Chine continentale de Taïwan ?", options: ["Malacca","Détroit de Formose","Bohaï","Corée"], correct: 1 },
  { text: "Quelle dynastie a unifié la Chine en -221 ?", options: ["Han","Qin","Tang","Ming"], correct: 1 },
  { text: "Quelle dynastie a bâti l'essentiel de la Grande Muraille actuelle ?", options: ["Han","Tang","Ming","Qing"], correct: 2 },
  { text: "En quelle année la République populaire de Chine a-t-elle été proclamée ?", options: ["1945","1949","1953","1959"], correct: 1 },
  { text: "Qui a proclamé la République populaire de Chine en 1949 ?", options: ["Sun Yat-sen","Mao Zedong","Deng Xiaoping","Tchang Kaï-chek"], correct: 1 },
  { text: "Quel dirigeant a lancé l'ouverture économique à partir de 1978 ?", options: ["Mao","Deng Xiaoping","Jiang Zemin","Hu Jintao"], correct: 1 },
  { text: "Quelle a été la dernière dynastie impériale chinoise ?", options: ["Ming","Qing","Yuan","Song"], correct: 1 },
  { text: "Près du tombeau de quel empereur a-t-on trouvé l'armée de terre cuite ?", options: ["Qin Shi Huang","Wu Zetian","Kangxi","Hongwu"], correct: 0 },
  { text: "Quelle « Révolution » Mao a-t-il lancée en 1966 ?", options: ["Révolution agraire","Révolution culturelle","Révolution verte","Grand Bond"], correct: 1 },
  { text: "Quelle langue parle la majorité des Chinois ?", options: ["Cantonais","Mandarin","Hakka","Tibétain"], correct: 1 },
  { text: "Combien de tons compte le mandarin standard ?", options: ["2","4","5 (avec le neutre)","8"], correct: 2 },
  { text: "Que représente le yin et le yang ?", options: ["Le bien et le mal","L'équilibre des contraires","Le passé et le futur","Deux empereurs"], correct: 1 },
  { text: "Quel signe ouvre le cycle astrologique chinois de 12 ans ?", options: ["Tigre","Dragon","Rat","Lapin"], correct: 2 },
  { text: "Quelle fête marque le Nouvel An chinois ?", options: ["Fête de la lune","Fête du printemps","Mi-automne","Bateaux-dragons"], correct: 1 },
  { text: "Quel art martial chinois signifie « boxe de l'ombre » ?", options: ["Kung-fu","Tai-chi","Wing Chun","Sanda"], correct: 1 },
  { text: "Quel animal est un symbole national de la Chine, noir et blanc ?", options: ["Tigre","Panda géant","Dragon","Grue"], correct: 1 },
  { text: "Quelle entreprise chinoise possède Alipay ?", options: ["Tencent","Baidu","Alibaba","JD"], correct: 2 },
  { text: "Quelle messagerie « tout-en-un » domine en Chine ?", options: ["Line","WeChat","KakaoTalk","Telegram"], correct: 1 },
  { text: "Quel barrage chinois est le plus puissant au monde ?", options: ["Itaipu","Barrage des Trois-Gorges","Hoover","Assouan"], correct: 1 },
  { text: "Quel canard rôti est la spécialité de Pékin ?", options: ["Canard à l'orange","Canard laqué","Canard caramélisé","Canard de Nankin"], correct: 1 },
  { text: "Comment s'appellent les raviolis chinois cuits vapeur ou poêlés ?", options: ["Bao","Jiaozi","Wonton","Nem"], correct: 1 },
  { text: "Quel alcool blanc fort est typiquement chinois ?", options: ["Sake","Soju","Baijiu","Tequila"], correct: 2 },
  { text: "Quel thé est le plus exporté par la Chine ?", options: ["Thé vert","Thé noir","Thé blanc","Pu-erh"], correct: 0 },
  { text: "Quelle place de Pékin est mondialement connue ?", options: ["Place Rouge","Place Tian'anmen","Place du Peuple","Place de la Concorde"], correct: 1 },
  { text: "Quel ancien palais impérial se trouve au cœur de Pékin ?", options: ["Cité interdite","Palais d'été","Temple du Ciel","Tour de la Cloche"], correct: 0 },
  { text: "Quelle est la longueur approximative de la Grande Muraille ?", options: ["2 000 km","6 000 km","21 000 km","50 000 km"], correct: 2 },
  { text: "Quel jeu de stratégie chinois se joue avec des pierres noires et blanches ?", options: ["Mah-jong","Go (weiqi)","Xiangqi","Dames"], correct: 1 },
  { text: "Quelle philosophie chinoise est attribuée à Confucius ?", options: ["Bouddhisme","Confucianisme","Taoïsme","Légisme"], correct: 1 },
  { text: "Quel penseur est associé au Tao Te King ?", options: ["Confucius","Laozi","Sun Tzu","Mencius"], correct: 1 },
  { text: "Quel stratège chinois a écrit L'Art de la guerre ?", options: ["Confucius","Sun Tzu","Laozi","Han Fei"], correct: 1 },
  { text: "Quelle est la capitale de la province du Sichuan ?", options: ["Chongqing","Chengdu","Wuhan","Xi'an"], correct: 1 },
  { text: "Quelle ville abrite l'armée de terre cuite ?", options: ["Pékin","Xi'an","Nankin","Luoyang"], correct: 1 },
  { text: "Quelle ville chinoise est un grand pôle technologique près de Hong Kong ?", options: ["Hangzhou","Shenzhen","Suzhou","Dalian"], correct: 1 },
  { text: "Quelle invention majeure est attribuée à la Chine ancienne ?", options: ["La roue","La poudre à canon","Le téléphone","La vapeur"], correct: 1 },
  { text: "Laquelle de ces inventions vient de Chine ?", options: ["Le papier","Le verre","L'alphabet","Le béton"], correct: 0 },
  { text: "Quel instrument de navigation a été inventé en Chine ?", options: ["Le sextant","La boussole","Le GPS","Le radar"], correct: 1 },
  { text: "Quel grand voyageur vénitien aurait visité la Chine au XIIIe siècle ?", options: ["Magellan","Marco Polo","Vasco de Gama","Colomb"], correct: 1 },
  { text: "Quel empereur mongol a fondé la dynastie Yuan en Chine ?", options: ["Gengis Khan","Kubilai Khan","Tamerlan","Ögödei"], correct: 1 },
  { text: "Quelle est la deuxième économie mondiale (PIB) ?", options: ["Japon","Chine","Allemagne","Inde"], correct: 1 },
  { text: "Quel grand fleuve se jette près de Shanghai ?", options: ["Fleuve Jaune","Yangtsé","Mékong","Perle"], correct: 1 },
  { text: "Quelle ville du sud est traversée par la rivière des Perles ?", options: ["Pékin","Canton","Wuhan","Harbin"], correct: 1 },
  { text: "Quel océan borde l'est de la Chine ?", options: ["Atlantique","Pacifique","Indien","Arctique"], correct: 1 },
  { text: "Combien de provinces compte environ la Chine continentale ?", options: ["12","23","34","45"], correct: 1 },
  { text: "Quelle ville chinoise est célèbre pour ses gratte-ciels du Bund ?", options: ["Pékin","Shanghai","Canton","Xi'an"], correct: 1 },
  { text: "Quel animal mythique est un symbole impérial chinois ?", options: ["Le phénix","Le dragon","Le tigre","La tortue"], correct: 1 },
  { text: "Quelle couleur est traditionnellement associée à la chance en Chine ?", options: ["Le blanc","Le rouge","Le noir","Le bleu"], correct: 1 },
  { text: "Quel plat chinois consiste à cuire des ingrédients dans un bouillon partagé ?", options: ["Dim sum","Hot pot","Chow mein","Baozi"], correct: 1 },
  { text: "Quelles petites bouchées cantonaises se mangent à la vapeur en petits paniers ?", options: ["Ramen","Dim sum","Pho","Bibimbap"], correct: 1 },
  { text: "Quelle fête chinoise célèbre la pleine lune d'automne avec des gâteaux de lune ?", options: ["Nouvel An","Fête de la mi-automne","Qingming","Duanwu"], correct: 1 },
  { text: "Quelle muraille est visible comme un monument emblématique de la Chine ?", options: ["Mur d'Hadrien","La Grande Muraille","Mur de Berlin","Les Grands Murs"], correct: 1 },
  { text: "Quelle est la capitale de la province du Hubei ?", options: ["Changsha","Wuhan","Nanchang","Hefei"], correct: 1 },
  { text: "Quelle est la capitale de la province du Guangdong ?", options: ["Shenzhen","Canton (Guangzhou)","Zhuhai","Foshan"], correct: 1 },
  { text: "Quelle est la capitale du Zhejiang, ville des lacs ?", options: ["Ningbo","Hangzhou","Wenzhou","Shaoxing"], correct: 1 },
  { text: "Quelle est la capitale du Shaanxi, ancienne capitale impériale ?", options: ["Lanzhou","Xi'an","Taiyuan","Yinchuan"], correct: 1 },
  { text: "Quelle est la capitale de la région autonome du Tibet ?", options: ["Xining","Lhassa","Urumqi","Hohhot"], correct: 1 },
  { text: "Quelle ville du nord-est est connue pour son festival de glace ?", options: ["Dalian","Harbin","Shenyang","Changchun"], correct: 1 },
  { text: "Quel symbole du zodiaque chinois est un animal mythique ?", options: ["Le cochon","Le dragon","Le chien","Le coq"], correct: 1 },
  { text: "Quelle est la plus grande place publique au monde, à Pékin ?", options: ["Place du Peuple","Place Tian'anmen","Place Rouge","Trafalgar"], correct: 1 },
  { text: "Quel philosophe chinois prônait l'harmonie sociale et le respect des aînés ?", options: ["Sun Tzu","Confucius","Laozi","Bouddha"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : l'Anhui ?", options: ["Canton (Guangzhou)","Hefei","Changsha","Jinan"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Fujian ?", options: ["Changsha","Fuzhou","Jinan","Yinchuan"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Gansu ?", options: ["Jinan","Lanzhou","Yinchuan","Guiyang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Guangdong ?", options: ["Yinchuan","Canton (Guangzhou)","Guiyang","Nankin (Nanjing)"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Guizhou ?", options: ["Nankin (Nanjing)","Guiyang","Taiyuan","Lhassa"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hainan ?", options: ["Nankin (Nanjing)","Haikou","Taiyuan","Lhassa"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hebei ?", options: ["Taiyuan","Shijiazhuang","Lhassa","Haikou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Heilongjiang ?", options: ["Lhassa","Harbin","Haikou","Nanchang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Henan ?", options: ["Haikou","Zhengzhou","Nanchang","Chengdu"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hubei ?", options: ["Nanchang","Wuhan","Chengdu","Urumqi"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hunan ?", options: ["Chengdu","Changsha","Urumqi","Shijiazhuang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Jiangsu ?", options: ["Urumqi","Nankin (Nanjing)","Shijiazhuang","Changchun"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Jiangxi ?", options: ["Shijiazhuang","Nanchang","Changchun","Kunming"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Jilin ?", options: ["Kunming","Changchun","Hefei","Harbin"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Liaoning ?", options: ["Kunming","Shenyang","Hefei","Harbin"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Qinghai ?", options: ["Hefei","Xining","Harbin","Shenyang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Shaanxi ?", options: ["Harbin","Xi'an","Shenyang","Hangzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Shandong ?", options: ["Shenyang","Jinan","Hangzhou","Fuzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Shanxi ?", options: ["Hangzhou","Taiyuan","Fuzhou","Zhengzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Sichuan ?", options: ["Fuzhou","Chengdu","Zhengzhou","Xining"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Yunnan ?", options: ["Zhengzhou","Kunming","Xining","Nanning"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Zhejiang ?", options: ["Xining","Hangzhou","Nanning","Lanzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Guangxi ?", options: ["Lanzhou","Nanning","Wuhan","Xi'an"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : la Mongolie-Intérieure ?", options: ["Lanzhou","Hohhot","Wuhan","Xi'an"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Ningxia ?", options: ["Wuhan","Yinchuan","Xi'an","Hohhot"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Tibet ?", options: ["Xi'an","Lhassa","Hohhot","Canton (Guangzhou)"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Xinjiang ?", options: ["Hohhot","Urumqi","Canton (Guangzhou)","Changsha"], correct: 1 },
  { text: "Quel animal vient juste après le Rat dans le zodiaque chinois ?", options: ["Tigre","Buffle","Dragon","Cheval"], correct: 1 },
  { text: "Quel animal mythique figure dans le zodiaque chinois ?", options: ["Le phénix","Le dragon","La licorne","Le griffon"], correct: 1 },
  { text: "Combien d'animaux compte le zodiaque chinois ?", options: ["10","12","14","24"], correct: 1 },
  { text: "Quelle est la plus haute montagne à la frontière Chine-Népal ?", options: ["K2","Everest","Annapurna","Makalu"], correct: 1 },
  { text: "Quel parti dirige la Chine depuis 1949 ?", options: ["Parti républicain","Parti communiste chinois","Kuomintang","Parti socialiste"], correct: 1 },
  { text: "Quelle île revendiquée par Pékin a son propre gouvernement ?", options: ["Hainan","Taïwan","Macao","Hong Kong"], correct: 1 },
  { text: "Quelle ancienne route commerciale reliait la Chine à l'Occident ?", options: ["Route de l'ambre","Route de la soie","Route des épices","Route du thé seule"], correct: 1 },
  { text: "Quel produit de luxe la Chine exportait-elle via la route de la soie ?", options: ["Le coton","La soie","Le lin","La laine"], correct: 1 },
  { text: "Quel grand philosophe est né vers 551 av. J.-C. en Chine ?", options: ["Bouddha","Confucius","Laozi","Sun Tzu"], correct: 1 },
  { text: "Quelle religion venue d'Inde s'est répandue en Chine ?", options: ["L'islam","Le bouddhisme","Le christianisme","L'hindouisme"], correct: 1 },
  { text: "Quel empereur a ordonné un autodafé et l'unification de l'écriture ?", options: ["Qin Shi Huang","Wudi","Kangxi","Taizong"], correct: 0 },
  { text: "Quelle dynastie est considérée comme un âge d'or de la poésie chinoise ?", options: ["Qin","Tang","Yuan","Qing"], correct: 1 },
  { text: "Quelle dynastie a précédé la dynastie Ming ?", options: ["Tang","Song","Yuan","Qin"], correct: 2 },
  { text: "Quel explorateur chinois a mené de grandes expéditions maritimes au XVe siècle ?", options: ["Zheng He","Confucius","Laozi","Marco Polo"], correct: 0 },
  { text: "Quel système d'écriture la Chine utilise-t-elle ?", options: ["Un alphabet","Des caractères (sinogrammes)","Le cyrillique","Des hiéroglyphes"], correct: 1 },
  { text: "Comment dit-on « bonjour » en mandarin ?", options: ["Arigato","Ni hao","Annyeong","Sawasdee"], correct: 1 },
  { text: "Comment dit-on « merci » en mandarin ?", options: ["Xie xie","Arigato","Gracias","Kamsa"], correct: 0 },
  { text: "Quelle ville est la capitale financière du sud, ex-village de pêcheurs devenu mégapole ?", options: ["Shenzhen","Lhassa","Harbin","Xining"], correct: 0 },
  { text: "Quel symbole rouge à cinq étoiles figure sur le drapeau chinois ?", options: ["Des étoiles jaunes","Un dragon","Un panda","Une muraille"], correct: 0 },
  { text: "De quelle couleur est le drapeau de la Chine ?", options: ["Bleu","Rouge","Vert","Blanc"], correct: 1 },
  { text: "Quel plat de nouilles sautées est typiquement chinois ?", options: ["Pad thaï","Chow mein","Ramen","Pho"], correct: 1 },
  { text: "Quel condiment fermenté à base de soja est très utilisé en cuisine chinoise ?", options: ["Le wasabi","La sauce soja","Le curry","Le tahini"], correct: 1 },
  { text: "Quelle céréale est la base de l'alimentation dans le sud de la Chine ?", options: ["Le blé","Le riz","Le maïs","L'orge"], correct: 1 },
  { text: "Quelle boisson chaude est emblématique de la culture chinoise ?", options: ["Le café","Le thé","Le chocolat","Le maté"], correct: 1 },
  { text: "Quel sport de table la Chine domine au niveau mondial ?", options: ["Le tennis","Le tennis de table","Le badminton seul","Le squash"], correct: 1 },
  { text: "Quelle mégapole du centre est surnommée « la fournaise » et compte plus de 30 millions d'habitants ?", options: ["Wuhan","Chongqing","Chengdu","Xi'an"], correct: 1 },
  { text: "Quel fleuve chinois se jette dans la mer de Bohai au nord ?", options: ["Yangtsé","Fleuve Jaune","Mékong","Perle"], correct: 1 },
  { text: "Quelle chaîne montagneuse borde le sud-ouest de la Chine (Tibet) ?", options: ["Les Andes","L'Himalaya","Les Alpes","L'Oural"], correct: 1 },
  { text: "Quelle est la superficie de la Chine la classe-t-elle dans le monde ?", options: ["1re","Parmi les plus vastes (3e-4e)","La plus petite","10e"], correct: 1 },
  { text: "Quelle monnaie chinoise est aussi appelée « renminbi » ?", options: ["Le yen","Le yuan","Le won","Le ringgit"], correct: 1 },
  { text: "Quel festival chinois implique des courses de bateaux-dragons ?", options: ["Nouvel An","Duanwu (bateaux-dragons)","Mi-automne","Qingming"], correct: 1 },
  { text: "Quel animal en voie de protection vit dans les forêts de bambous du Sichuan ?", options: ["Le tigre","Le panda géant","Le léopard des neiges","Le gibbon"], correct: 1 },
  { text: "Quel mur visible depuis... est un mythe : il n'est PAS visible à l'œil nu depuis l'espace. De quoi parle-t-on ?", options: ["Cité interdite","Grande Muraille","Barrage des Trois-Gorges","Tian'anmen"], correct: 1 },
  { text: "Quelle ville côtière du nord-est est un grand port industriel ?", options: ["Dalian","Lhassa","Kunming","Guiyang"], correct: 0 },
  { text: "Quel grand barrage se trouve sur le Yangtsé ?", options: ["Barrage d'Assouan","Barrage des Trois-Gorges","Barrage Hoover","Itaipu"], correct: 1 },
  { text: "Quelle dynastie a vu l'invention de la boussole et de la poudre se développer ?", options: ["Song","Qing","Yuan","Shang"], correct: 0 },
  { text: "Quel jeu de tuiles est très populaire en Chine ?", options: ["Le mah-jong","Le backgammon","Les dominos seuls","Le tarot"], correct: 0 },
  { text: "Quel temple emblématique se trouve à Pékin ?", options: ["Temple d'Or","Temple du Ciel","Temple Borobudur","Temple d'Angkor"], correct: 1 },
  { text: "Quel jardin impérial se trouve près de Pékin ?", options: ["Le Palais d'été","Versailles","Le Taj Mahal","Le Kremlin"], correct: 0 },
  { text: "Quel grand penseur militaire chinois a influencé la stratégie mondiale ?", options: ["Confucius","Sun Tzu","Laozi","Mencius"], correct: 1 },
  { text: "Quelle est la langue officielle écrite standardisée en Chine ?", options: ["Le cantonais","Le mandarin (chinois standard)","Le tibétain","L'ouïghour"], correct: 1 },
  { text: "Quelle grande exposition s'est tenue à Shanghai en 2010 ?", options: ["Les JO","L'Exposition universelle","La Coupe du monde","Le G20"], correct: 1 },
  { text: "Quelle ville chinoise a accueilli les Jeux olympiques d'été en 2008 ?", options: ["Shanghai","Pékin","Canton","Nankin"], correct: 1 },
  { text: "Quelle ville chinoise a accueilli les JO d'hiver en 2022 ?", options: ["Shanghai","Pékin","Harbin","Changchun"], correct: 1 },
  { text: "Quelle grande compagnie chinoise fabrique des télécoms et des smartphones ?", options: ["Sony","Huawei","Samsung","LG"], correct: 1 },
  { text: "Quel constructeur chinois de véhicules électriques est un leader mondial ?", options: ["Toyota","BYD","Tesla","Volkswagen"], correct: 1 },
  { text: "Quelle plateforme vidéo courte est d'origine chinoise (ByteDance) ?", options: ["Instagram","TikTok (Douyin)","Snapchat","YouTube"], correct: 1 },
];
