// QuizzMaster — thème 🇨🇳 Chine. 300 questions.

module.exports = [
  { text: "Quelle est la capitale de la Chine ?", options: ["Shanghai","Pékin","Canton","Hong Kong"], correct: 1 },
  { text: "Quelle est la monnaie officielle de la Chine ?", options: ["Yen","Won","Yuan","Baht"], correct: 2 },
  { text: "Quel est le plus long fleuve de Chine ?", options: ["Yangtsé","Fleuve Jaune","Mékong","Amour"], correct: 0 },
  { text: "Quel fleuve est surnommé le « fleuve Jaune » ?", options: ["Yangtsé","Huang He","Mékong","Perle"], correct: 1 },
  { text: "Quelle ville chinoise est la capitale économique et le plus grand port ?", options: ["Pékin","Shanghai","Shenzhen","Canton"], correct: 1 },
  { text: "Combien d'habitants compte la Chine (ordre de grandeur) ?", options: ["800 millions","1,4 milliard","2 milliards","500 millions"], correct: 1 },
  { text: "Quelle région autonome abrite l'Everest côté nord ?", options: ["Xinjiang","Tibet","Mongolie-Intérieure","Yunnan"], correct: 1 },
  { text: "Quel désert occupe le nord de la Chine ?", options: ["Sahara","Gobi","Atacama","Thar"], correct: 1 },
  { text: "Quelle ville a été une colonie portugaise jusqu'en 1999 ?", options: ["Hong Kong","Macao","Canton","Shenzhen"], correct: 1 },
  { text: "Quelle ville a été britannique jusqu'en 1997 ?", options: ["Macao","Hong Kong","Shanghai","Canton"], correct: 1 },
  { text: "Quel détroit sépare la Chine continentale de Taïwan ?", options: ["Malacca","Détroit de Formose","Bohaï","Corée"], correct: 1 },
  { text: "Quelle dynastie a unifié la Chine en -221 ?", options: ["Han","Qin","Tang","Ming"], correct: 1 },
  { text: "Quelle dynastie a bâti l'essentiel de la Grande Muraille actuelle ?", options: ["Han","Tang","Ming","Qing"], correct: 2 },
  { text: "En quelle année la République populaire de Chine a-t-elle été proclamée ?", options: ["1945","1949","1953","1959"], correct: 1 },
  { text: "Qui a proclamé la République populaire de Chine en 1949 ?", options: ["Sun Yat-sen","Mao Zedong","Deng Xiaoping","Tchang Kaï-chek"], correct: 1 },
  { text: "Quel dirigeant a lancé l'ouverture économique à partir de 1978 ?", options: ["Mao","Deng Xiaoping","Jiang Zemin","Hu Jintao"], correct: 1 },
  { text: "Quelle a été la dernière dynastie impériale chinoise ?", options: ["Ming","Qing","Yuan","Song"], correct: 1 },
  { text: "Près du tombeau de quel empereur a-t-on trouvé l'armée de terre cuite ?", options: ["Qin Shi Huang","Wu Zetian","Kangxi","Hongwu"], correct: 0 },
  { text: "Quelle « Révolution » Mao a-t-il lancée en 1966 ?", options: ["Révolution agraire","Révolution culturelle","Révolution verte","Grand Bond"], correct: 1 },
  { text: "Quelle langue parle la majorité des Chinois ?", options: ["Cantonais","Mandarin","Hakka","Tibétain"], correct: 1 },
  { text: "Combien de tons compte le mandarin standard ?", options: ["2","4","5 (avec le neutre)","8"], correct: 2 },
  { text: "Que représente le yin et le yang ?", options: ["Le bien et le mal","L'équilibre des contraires","Le passé et le futur","Deux empereurs"], correct: 1 },
  { text: "Quel signe ouvre le cycle astrologique chinois de 12 ans ?", options: ["Tigre","Dragon","Rat","Lapin"], correct: 2 },
  { text: "Quelle fête marque le Nouvel An chinois ?", options: ["Fête de la lune","Fête du printemps","Mi-automne","Bateaux-dragons"], correct: 1 },
  { text: "Quel art martial chinois signifie « boxe de l'ombre » ?", options: ["Kung-fu","Tai-chi","Wing Chun","Sanda"], correct: 1 },
  { text: "Quel animal est un symbole national de la Chine, noir et blanc ?", options: ["Tigre","Panda géant","Dragon","Grue"], correct: 1 },
  { text: "Quelle entreprise chinoise possède Alipay ?", options: ["Tencent","Baidu","Alibaba","JD"], correct: 2 },
  { text: "Quelle messagerie « tout-en-un » domine en Chine ?", options: ["Line","WeChat","KakaoTalk","Telegram"], correct: 1 },
  { text: "Quel barrage chinois est le plus puissant au monde ?", options: ["Itaipu","Barrage des Trois-Gorges","Hoover","Assouan"], correct: 1 },
  { text: "Quel canard rôti est la spécialité de Pékin ?", options: ["Canard à l'orange","Canard laqué","Canard caramélisé","Canard de Nankin"], correct: 1 },
  { text: "Comment s'appellent les raviolis chinois cuits vapeur ou poêlés ?", options: ["Bao","Jiaozi","Wonton","Nem"], correct: 1 },
  { text: "Quel alcool blanc fort est typiquement chinois ?", options: ["Sake","Soju","Baijiu","Tequila"], correct: 2 },
  { text: "Quel thé est le plus exporté par la Chine ?", options: ["Thé vert","Thé noir","Thé blanc","Pu-erh"], correct: 0 },
  { text: "Quelle place de Pékin est mondialement connue ?", options: ["Place Rouge","Place Tian'anmen","Place du Peuple","Place de la Concorde"], correct: 1 },
  { text: "Quel ancien palais impérial se trouve au cœur de Pékin ?", options: ["Cité interdite","Palais d'été","Temple du Ciel","Tour de la Cloche"], correct: 0 },
  { text: "Quelle est la longueur approximative de la Grande Muraille ?", options: ["2 000 km","6 000 km","21 000 km","50 000 km"], correct: 2 },
  { text: "Quel jeu de stratégie chinois se joue avec des pierres noires et blanches ?", options: ["Mah-jong","Go (weiqi)","Xiangqi","Dames"], correct: 1 },
  { text: "Quelle philosophie chinoise est attribuée à Confucius ?", options: ["Bouddhisme","Confucianisme","Taoïsme","Légisme"], correct: 1 },
  { text: "Quel penseur est associé au Tao Te King ?", options: ["Confucius","Laozi","Sun Tzu","Mencius"], correct: 1 },
  { text: "Quel stratège chinois a écrit L'Art de la guerre ?", options: ["Confucius","Sun Tzu","Laozi","Han Fei"], correct: 1 },
  { text: "Quelle est la capitale de la province du Sichuan ?", options: ["Chongqing","Chengdu","Wuhan","Xi'an"], correct: 1 },
  { text: "Quelle ville abrite l'armée de terre cuite ?", options: ["Pékin","Xi'an","Nankin","Luoyang"], correct: 1 },
  { text: "Quelle ville chinoise est un grand pôle technologique près de Hong Kong ?", options: ["Hangzhou","Shenzhen","Suzhou","Dalian"], correct: 1 },
  { text: "Quelle invention majeure est attribuée à la Chine ancienne ?", options: ["La roue","La poudre à canon","Le téléphone","La vapeur"], correct: 1 },
  { text: "Laquelle de ces inventions vient de Chine ?", options: ["Le papier","Le verre","L'alphabet","Le béton"], correct: 0 },
  { text: "Quel instrument de navigation a été inventé en Chine ?", options: ["Le sextant","La boussole","Le GPS","Le radar"], correct: 1 },
  { text: "Quel grand voyageur vénitien aurait visité la Chine au XIIIe siècle ?", options: ["Magellan","Marco Polo","Vasco de Gama","Colomb"], correct: 1 },
  { text: "Quel empereur mongol a fondé la dynastie Yuan en Chine ?", options: ["Gengis Khan","Kubilai Khan","Tamerlan","Ögödei"], correct: 1 },
  { text: "Quelle est la deuxième économie mondiale (PIB) ?", options: ["Japon","Chine","Allemagne","Inde"], correct: 1 },
  { text: "Quel grand fleuve se jette près de Shanghai ?", options: ["Fleuve Jaune","Yangtsé","Mékong","Perle"], correct: 1 },
  { text: "Quelle ville du sud est traversée par la rivière des Perles ?", options: ["Pékin","Canton","Wuhan","Harbin"], correct: 1 },
  { text: "Quel océan borde l'est de la Chine ?", options: ["Atlantique","Pacifique","Indien","Arctique"], correct: 1 },
  { text: "Combien de provinces compte environ la Chine continentale ?", options: ["12","23","34","45"], correct: 1 },
  { text: "Quelle ville chinoise est célèbre pour ses gratte-ciels du Bund ?", options: ["Pékin","Shanghai","Canton","Xi'an"], correct: 1 },
  { text: "Quel animal mythique est un symbole impérial chinois ?", options: ["Le phénix","Le dragon","Le tigre","La tortue"], correct: 1 },
  { text: "Quelle couleur est traditionnellement associée à la chance en Chine ?", options: ["Le blanc","Le rouge","Le noir","Le bleu"], correct: 1 },
  { text: "Quel plat chinois consiste à cuire des ingrédients dans un bouillon partagé ?", options: ["Dim sum","Hot pot","Chow mein","Baozi"], correct: 1 },
  { text: "Quelles petites bouchées cantonaises se mangent à la vapeur en petits paniers ?", options: ["Ramen","Dim sum","Pho","Bibimbap"], correct: 1 },
  { text: "Quelle fête chinoise célèbre la pleine lune d'automne avec des gâteaux de lune ?", options: ["Nouvel An","Fête de la mi-automne","Qingming","Duanwu"], correct: 1 },
  { text: "Quelle muraille est visible comme un monument emblématique de la Chine ?", options: ["Mur d'Hadrien","La Grande Muraille","Mur de Berlin","Les Grands Murs"], correct: 1 },
  { text: "Quelle est la capitale de la province du Hubei ?", options: ["Changsha","Wuhan","Nanchang","Hefei"], correct: 1 },
  { text: "Quelle est la capitale de la province du Guangdong ?", options: ["Shenzhen","Canton (Guangzhou)","Zhuhai","Foshan"], correct: 1 },
  { text: "Quelle est la capitale du Zhejiang, ville des lacs ?", options: ["Ningbo","Hangzhou","Wenzhou","Shaoxing"], correct: 1 },
  { text: "Quelle est la capitale du Shaanxi, ancienne capitale impériale ?", options: ["Lanzhou","Xi'an","Taiyuan","Yinchuan"], correct: 1 },
  { text: "Quelle est la capitale de la région autonome du Tibet ?", options: ["Xining","Lhassa","Urumqi","Hohhot"], correct: 1 },
  { text: "Quelle ville du nord-est est connue pour son festival de glace ?", options: ["Dalian","Harbin","Shenyang","Changchun"], correct: 1 },
  { text: "Quel symbole du zodiaque chinois est un animal mythique ?", options: ["Le cochon","Le dragon","Le chien","Le coq"], correct: 1 },
  { text: "Quelle est la plus grande place publique au monde, à Pékin ?", options: ["Place du Peuple","Place Tian'anmen","Place Rouge","Trafalgar"], correct: 1 },
  { text: "Quel philosophe chinois prônait l'harmonie sociale et le respect des aînés ?", options: ["Sun Tzu","Confucius","Laozi","Bouddha"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : l'Anhui ?", options: ["Canton (Guangzhou)","Hefei","Changsha","Jinan"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Fujian ?", options: ["Changsha","Fuzhou","Jinan","Yinchuan"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Gansu ?", options: ["Jinan","Lanzhou","Yinchuan","Guiyang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Guangdong ?", options: ["Yinchuan","Canton (Guangzhou)","Guiyang","Nankin (Nanjing)"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Guizhou ?", options: ["Nankin (Nanjing)","Guiyang","Taiyuan","Lhassa"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hainan ?", options: ["Nankin (Nanjing)","Haikou","Taiyuan","Lhassa"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hebei ?", options: ["Taiyuan","Shijiazhuang","Lhassa","Haikou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Heilongjiang ?", options: ["Lhassa","Harbin","Haikou","Nanchang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Henan ?", options: ["Haikou","Zhengzhou","Nanchang","Chengdu"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hubei ?", options: ["Nanchang","Wuhan","Chengdu","Urumqi"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Hunan ?", options: ["Chengdu","Changsha","Urumqi","Shijiazhuang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Jiangsu ?", options: ["Urumqi","Nankin (Nanjing)","Shijiazhuang","Changchun"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Jiangxi ?", options: ["Shijiazhuang","Nanchang","Changchun","Kunming"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Jilin ?", options: ["Kunming","Changchun","Hefei","Harbin"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Liaoning ?", options: ["Kunming","Shenyang","Hefei","Harbin"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Qinghai ?", options: ["Hefei","Xining","Harbin","Shenyang"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Shaanxi ?", options: ["Harbin","Xi'an","Shenyang","Hangzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Shandong ?", options: ["Shenyang","Jinan","Hangzhou","Fuzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Shanxi ?", options: ["Hangzhou","Taiyuan","Fuzhou","Zhengzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Sichuan ?", options: ["Fuzhou","Chengdu","Zhengzhou","Xining"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Yunnan ?", options: ["Zhengzhou","Kunming","Xining","Nanning"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Zhejiang ?", options: ["Xining","Hangzhou","Nanning","Lanzhou"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Guangxi ?", options: ["Lanzhou","Nanning","Wuhan","Xi'an"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : la Mongolie-Intérieure ?", options: ["Lanzhou","Hohhot","Wuhan","Xi'an"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Ningxia ?", options: ["Wuhan","Yinchuan","Xi'an","Hohhot"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Tibet ?", options: ["Xi'an","Lhassa","Hohhot","Canton (Guangzhou)"], correct: 1 },
  { text: "Quelle est la capitale de la province chinoise : le Xinjiang ?", options: ["Hohhot","Urumqi","Canton (Guangzhou)","Changsha"], correct: 1 },
  { text: "Quel animal vient juste après le Rat dans le zodiaque chinois ?", options: ["Tigre","Buffle","Dragon","Cheval"], correct: 1 },
  { text: "Quel animal mythique figure dans le zodiaque chinois ?", options: ["Le phénix","Le dragon","La licorne","Le griffon"], correct: 1 },
  { text: "Combien d'animaux compte le zodiaque chinois ?", options: ["10","12","14","24"], correct: 1 },
  { text: "Quelle est la plus haute montagne à la frontière Chine-Népal ?", options: ["K2","Everest","Annapurna","Makalu"], correct: 1 },
  { text: "Quel parti dirige la Chine depuis 1949 ?", options: ["Parti républicain","Parti communiste chinois","Kuomintang","Parti socialiste"], correct: 1 },
  { text: "Quelle île revendiquée par Pékin a son propre gouvernement ?", options: ["Hainan","Taïwan","Macao","Hong Kong"], correct: 1 },
  { text: "Quelle ancienne route commerciale reliait la Chine à l'Occident ?", options: ["Route de l'ambre","Route de la soie","Route des épices","Route du thé seule"], correct: 1 },
  { text: "Quel produit de luxe la Chine exportait-elle via la route de la soie ?", options: ["Le coton","La soie","Le lin","La laine"], correct: 1 },
  { text: "Quel grand philosophe est né vers 551 av. J.-C. en Chine ?", options: ["Bouddha","Confucius","Laozi","Sun Tzu"], correct: 1 },
  { text: "Quelle religion venue d'Inde s'est répandue en Chine ?", options: ["L'islam","Le bouddhisme","Le christianisme","L'hindouisme"], correct: 1 },
  { text: "Quel empereur a ordonné un autodafé et l'unification de l'écriture ?", options: ["Qin Shi Huang","Wudi","Kangxi","Taizong"], correct: 0 },
  { text: "Quelle dynastie est considérée comme un âge d'or de la poésie chinoise ?", options: ["Qin","Tang","Yuan","Qing"], correct: 1 },
  { text: "Quelle dynastie a précédé la dynastie Ming ?", options: ["Tang","Song","Yuan","Qin"], correct: 2 },
  { text: "Quel explorateur chinois a mené de grandes expéditions maritimes au XVe siècle ?", options: ["Zheng He","Confucius","Laozi","Marco Polo"], correct: 0 },
  { text: "Quel système d'écriture la Chine utilise-t-elle ?", options: ["Un alphabet","Des caractères (sinogrammes)","Le cyrillique","Des hiéroglyphes"], correct: 1 },
  { text: "Comment dit-on « bonjour » en mandarin ?", options: ["Arigato","Ni hao","Annyeong","Sawasdee"], correct: 1 },
  { text: "Comment dit-on « merci » en mandarin ?", options: ["Xie xie","Arigato","Gracias","Kamsa"], correct: 0 },
  { text: "Quelle ville est la capitale financière du sud, ex-village de pêcheurs devenu mégapole ?", options: ["Shenzhen","Lhassa","Harbin","Xining"], correct: 0 },
  { text: "De quelle couleur sont les cinq étoiles du drapeau chinois ?", options: ["Rouges","Jaunes","Blanches","Bleues"], correct: 1 },
  { text: "De quelle couleur est le drapeau de la Chine ?", options: ["Bleu","Rouge","Vert","Blanc"], correct: 1 },
  { text: "Quel plat de nouilles sautées est typiquement chinois ?", options: ["Pad thaï","Chow mein","Ramen","Pho"], correct: 1 },
  { text: "Quel condiment fermenté à base de soja est très utilisé en cuisine chinoise ?", options: ["Le wasabi","La sauce soja","Le curry","Le tahini"], correct: 1 },
  { text: "Quelle céréale est la base de l'alimentation dans le sud de la Chine ?", options: ["Le blé","Le riz","Le maïs","L'orge"], correct: 1 },
  { text: "Quelle boisson chaude est emblématique de la culture chinoise ?", options: ["Le café","Le thé","Le chocolat","Le maté"], correct: 1 },
  { text: "Quel sport de table la Chine domine au niveau mondial ?", options: ["Le squash","Le tennis de table","Le badminton","Le billard"], correct: 1 },
  { text: "Quelle mégapole du centre est surnommée « la fournaise » et compte plus de 30 millions d'habitants ?", options: ["Wuhan","Chongqing","Chengdu","Xi'an"], correct: 1 },
  { text: "Quel fleuve chinois se jette dans la mer de Bohai au nord ?", options: ["Yangtsé","Fleuve Jaune","Mékong","Perle"], correct: 1 },
  { text: "Quelle chaîne montagneuse borde le sud-ouest de la Chine (Tibet) ?", options: ["Les Andes","L'Himalaya","Les Alpes","L'Oural"], correct: 1 },
  { text: "Quelle monnaie chinoise est aussi appelée « renminbi » ?", options: ["Le yen","Le yuan","Le won","Le ringgit"], correct: 1 },
  { text: "Quel festival chinois implique des courses de bateaux-dragons ?", options: ["Nouvel An","Duanwu (bateaux-dragons)","Mi-automne","Qingming"], correct: 1 },
  { text: "Quel animal en voie de protection vit dans les forêts de bambous du Sichuan ?", options: ["Le tigre","Le panda géant","Le léopard des neiges","Le gibbon"], correct: 1 },
  { text: "Quelle ville côtière du nord-est est un grand port industriel ?", options: ["Dalian","Lhassa","Kunming","Guiyang"], correct: 0 },
  { text: "Quel grand barrage se trouve sur le Yangtsé ?", options: ["Barrage d'Assouan","Barrage des Trois-Gorges","Barrage Hoover","Itaipu"], correct: 1 },
  { text: "Quelle dynastie a vu l'invention de la boussole et de la poudre se développer ?", options: ["Song","Qing","Yuan","Shang"], correct: 0 },
  { text: "Quel jeu de tuiles est très populaire en Chine ?", options: ["Le mah-jong","Le backgammon","Les dominos seuls","Le tarot"], correct: 0 },
  { text: "Quel temple emblématique se trouve à Pékin ?", options: ["Temple d'Or","Temple du Ciel","Temple Borobudur","Temple d'Angkor"], correct: 1 },
  { text: "Quel jardin impérial se trouve près de Pékin ?", options: ["Le Palais d'été","Versailles","Le Taj Mahal","Le Kremlin"], correct: 0 },
  { text: "Quel grand penseur militaire chinois a influencé la stratégie mondiale ?", options: ["Confucius","Sun Tzu","Laozi","Mencius"], correct: 1 },
  { text: "Quelle est la langue officielle écrite standardisée en Chine ?", options: ["Le cantonais","Le mandarin (chinois standard)","Le tibétain","L'ouïghour"], correct: 1 },
  { text: "Quelle grande exposition s'est tenue à Shanghai en 2010 ?", options: ["Les JO","L'Exposition universelle","La Coupe du monde","Le G20"], correct: 1 },
  { text: "Quelle ville chinoise a accueilli les Jeux olympiques d'été en 2008 ?", options: ["Shanghai","Pékin","Canton","Nankin"], correct: 1 },
  { text: "Quelle ville chinoise a accueilli les JO d'hiver en 2022 ?", options: ["Shanghai","Pékin","Harbin","Changchun"], correct: 1 },
  { text: "Quelle grande compagnie chinoise fabrique des télécoms et des smartphones ?", options: ["Sony","Huawei","Samsung","LG"], correct: 1 },
  { text: "Quel constructeur chinois de véhicules électriques est un leader mondial ?", options: ["Toyota","BYD","Tesla","Volkswagen"], correct: 1 },
  { text: "Quelle plateforme vidéo courte est d'origine chinoise (ByteDance) ?", options: ["Instagram","TikTok (Douyin)","Snapchat","YouTube"], correct: 1 },
  { text: "Hefei est la capitale de quelle province chinoise ?", options: ["le Heilongjiang","l'Anhui","le Jiangxi","le Shandong"], correct: 1 },
  { text: "Fuzhou est la capitale de quelle province chinoise ?", options: ["le Jiangxi","le Fujian","le Shandong","le Guangxi"], correct: 1 },
  { text: "Lanzhou est la capitale de quelle province chinoise ?", options: ["le Shandong","le Gansu","le Guangxi","l'Anhui"], correct: 1 },
  { text: "Canton (Guangzhou) est la capitale de quelle province chinoise ?", options: ["le Guangxi","le Guangdong","l'Anhui","le Hainan"], correct: 1 },
  { text: "Guiyang est la capitale de quelle province chinoise ?", options: ["l'Anhui","le Guizhou","le Hainan","le Hunan"], correct: 1 },
  { text: "Haikou est la capitale de quelle province chinoise ?", options: ["le Hunan","le Hainan","le Qinghai","le Yunnan"], correct: 1 },
  { text: "Shijiazhuang est la capitale de quelle province chinoise ?", options: ["le Hunan","le Hebei","le Qinghai","le Yunnan"], correct: 1 },
  { text: "Harbin est la capitale de quelle province chinoise ?", options: ["le Qinghai","le Heilongjiang","le Yunnan","le Tibet"], correct: 1 },
  { text: "Zhengzhou est la capitale de quelle province chinoise ?", options: ["le Yunnan","le Henan","le Tibet","le Guangdong"], correct: 1 },
  { text: "Wuhan est la capitale de quelle province chinoise ?", options: ["le Tibet","le Hubei","le Guangdong","le Henan"], correct: 1 },
  { text: "Changsha est la capitale de quelle province chinoise ?", options: ["le Guangdong","le Hunan","le Henan","le Jilin"], correct: 1 },
  { text: "Nankin (Nanjing) est la capitale de quelle province chinoise ?", options: ["le Henan","le Jiangsu","le Jilin","le Shanxi"], correct: 1 },
  { text: "Nanchang est la capitale de quelle province chinoise ?", options: ["le Jilin","le Jiangxi","le Shanxi","la Mongolie-Intérieure"], correct: 1 },
  { text: "Changchun est la capitale de quelle province chinoise ?", options: ["le Shanxi","le Jilin","la Mongolie-Intérieure","le Fujian"], correct: 1 },
  { text: "Shenyang est la capitale de quelle province chinoise ?", options: ["la Mongolie-Intérieure","le Liaoning","le Fujian","le Hebei"], correct: 1 },
  { text: "Xining est la capitale de quelle province chinoise ?", options: ["le Fujian","le Qinghai","le Hebei","le Jiangsu"], correct: 1 },
  { text: "Xi'an est la capitale de quelle province chinoise ?", options: ["le Hebei","le Shaanxi","le Jiangsu","le Zhejiang"], correct: 1 },
  { text: "Jinan est la capitale de quelle province chinoise ?", options: ["le Jiangsu","le Shandong","le Shaanxi","le Zhejiang"], correct: 1 },
  { text: "Taiyuan est la capitale de quelle province chinoise ?", options: ["le Shaanxi","le Shanxi","le Zhejiang","le Xinjiang"], correct: 1 },
  { text: "Chengdu est la capitale de quelle province chinoise ?", options: ["le Zhejiang","le Sichuan","le Xinjiang","le Guizhou"], correct: 1 },
  { text: "Kunming est la capitale de quelle province chinoise ?", options: ["le Xinjiang","le Yunnan","le Guizhou","le Hubei"], correct: 1 },
  { text: "Hangzhou est la capitale de quelle province chinoise ?", options: ["le Guizhou","le Zhejiang","le Hubei","le Liaoning"], correct: 1 },
  { text: "Nanning est la capitale de quelle province chinoise ?", options: ["le Hubei","le Guangxi","le Liaoning","le Sichuan"], correct: 1 },
  { text: "Hohhot est la capitale de quelle province chinoise ?", options: ["le Liaoning","la Mongolie-Intérieure","le Sichuan","le Ningxia"], correct: 1 },
  { text: "Yinchuan est la capitale de quelle province chinoise ?", options: ["le Sichuan","le Ningxia","le Gansu","le Heilongjiang"], correct: 1 },
  { text: "Lhassa est la capitale de quelle province chinoise ?", options: ["le Ningxia","le Tibet","le Gansu","le Heilongjiang"], correct: 1 },
  { text: "Urumqi est la capitale de quelle province chinoise ?", options: ["le Gansu","le Xinjiang","le Heilongjiang","le Jiangxi"], correct: 1 },
  { text: "Quel grand chantier relie le nord et le sud de la Chine par voie d'eau ?", options: ["Le canal de Suez","Le Grand Canal","Le canal de Panama","Le canal de Corinthe"], correct: 1 },
  { text: "Quelle religion philosophique chinoise valorise le « non-agir » (wu wei) ?", options: ["Confucianisme","Taoïsme","Bouddhisme","Légisme"], correct: 1 },
  { text: "Quel empereur a fait construire la première version de la Grande Muraille ?", options: ["Qin Shi Huang","Kangxi","Wudi","Taizong"], correct: 0 },
  { text: "Quelle ville côtière abrite la tour de télévision « Perle de l'Orient » ?", options: ["Pékin","Shanghai","Canton","Shenzhen"], correct: 1 },
  { text: "Quel grand fleuve traverse Wuhan ?", options: ["Le fleuve Jaune","Le Yangtsé","Le Mékong","La rivière des Perles"], correct: 1 },
  { text: "Quelle est la plus grande ville de Chine par population urbaine ?", options: ["Pékin","Shanghai","Chongqing","Canton"], correct: 1 },
  { text: "Quel plat de Sichuan est connu pour être très épicé (poivre du Sichuan) ?", options: ["Canard laqué","Mapo tofu","Dim sum","Riz cantonais"], correct: 1 },
  { text: "Quelle épice engourdissante est typique de la cuisine du Sichuan ?", options: ["Cannelle","Poivre du Sichuan","Cumin","Safran"], correct: 1 },
  { text: "Quel animal est le 1er signe du zodiaque chinois ?", options: ["Le buffle","Le rat","Le tigre","Le dragon"], correct: 1 },
  { text: "Quel animal du zodiaque chinois suit le dragon ?", options: ["Le serpent","Le cheval","Le singe","Le coq"], correct: 0 },
  { text: "Quelle est la plus grande chaîne de montagnes du Tibet et du Népal ?", options: ["Andes","Himalaya","Alpes","Caucase"], correct: 1 },
  { text: "Comment écrit-on « Pékin » en romanisation pinyin (forme internationale) ?", options: ["Nanjing","Beijing","Shanghai","Tianjin"], correct: 1 },
  { text: "Quel ancien nom occidental désignait la ville de Guangzhou ?", options: ["Canton","Hangzhou","Nankin","Xiamen"], correct: 0 },
  { text: "Quel philosophe a fondé une école rivale du confucianisme, prônant l'amour universel ?", options: ["Mozi","Confucius","Laozi","Sun Tzu"], correct: 0 },
  { text: "Quelle dynastie mongole a dirigé la Chine de 1271 à 1368 ?", options: ["Song","Yuan","Ming","Qing"], correct: 1 },
  { text: "Quelle dynastie chinoise a vu Confucius vivre (période) ?", options: ["Zhou","Tang","Ming","Qing"], correct: 0 },
  { text: "Quel objet en porcelaine fine est une exportation chinoise célèbre ?", options: ["Le verre de Murano","La porcelaine (china)","Le cristal","La faïence de Delft"], correct: 1 },
  { text: "Quel tissu précieux la Chine produisait-elle en secret pendant des siècles ?", options: ["Le coton","La soie","Le lin","Le velours"], correct: 1 },
  { text: "Quel grand explorateur chinois a navigué jusqu'en Afrique au XVe siècle ?", options: ["Zheng He","Xuanzang","Marco Polo","Ibn Battuta"], correct: 0 },
  { text: "Quelle est la 2e langue par nombre de locuteurs en Chine après le mandarin ?", options: ["Le tibétain","Le cantonais (yue)","Le mongol","L'ouïghour"], correct: 1 },
  { text: "Quelle muraille protégeait contre les invasions venues du nord ?", options: ["Mur d'Hadrien","La Grande Muraille","Le limes","Le mur de Berlin"], correct: 1 },
  { text: "Quel symbole yin-yang représente l'équilibre dans la pensée chinoise ?", options: ["Le taijitu","La croix","Le croissant","L'étoile"], correct: 0 },
  { text: "Quelle céréale domine l'alimentation du nord de la Chine ?", options: ["Le riz","Le blé (nouilles, pains)","Le maïs","Le millet seul"], correct: 1 },
  { text: "Quel festival chinois est aussi appelé Fête de la Lune ?", options: ["Nouvel An","Mi-automne","Qingming","Duanwu"], correct: 1 },
  { text: "Quel matériau précieux vert est très prisé dans l'art chinois ?", options: ["Le rubis","Le jade","Le saphir","L'ambre"], correct: 1 },
  { text: "Quelle ville est le grand centre manufacturier surnommé « usine du monde » (région) ?", options: ["Lhassa","Le delta de la rivière des Perles","Xining","Harbin"], correct: 1 },
  { text: "Quel océan borde Shanghai ?", options: ["Atlantique","Pacifique (mer de Chine)","Indien","Arctique"], correct: 1 },
  { text: "Quelle est la troisième plus longue rivière de Chine, dite « du sud » ?", options: ["La rivière des Perles","Le Yangtsé","Le fleuve Jaune","Le Mékong"], correct: 0 },
  { text: "Quel animal en porcelaine ou pierre garde souvent l'entrée des temples ?", options: ["L'aigle","Le lion gardien","L'ours","Le cerf"], correct: 1 },
  { text: "Quel calendrier traditionnel chinois est basé sur la lune ?", options: ["Grégorien","Lunaire (lunisolaire)","Julien","Solaire pur"], correct: 1 },
  { text: "Quelle dynastie a établi le système des examens impériaux (mandarins) ?", options: ["Han/Sui","Yuan","Qing seule","Shang"], correct: 0 },
  { text: "Quel grand mur naturel/artificiel est inscrit au patrimoine de l'UNESCO en Chine ?", options: ["Le mur de Berlin","La Grande Muraille","Le limes","Le mur des Lamentations"], correct: 1 },
  { text: "Quelle invention chinoise a révolutionné la diffusion du savoir ?", options: ["Le verre","L'imprimerie","La machine à vapeur","Le télégraphe"], correct: 1 },
  { text: "Quelle est la capitale politique de la Chine (centre du pouvoir) ?", options: ["Shanghai","Pékin","Canton","Nankin"], correct: 1 },
  { text: "Quel plat de rue chinois consiste en brochettes épicées (Xinjiang) ?", options: ["Yakitori","Chuanr (brochettes)","Satay","Kebab turc"], correct: 1 },
  { text: "Quelle boisson alcoolisée de riz est consommée en Asie de l'Est, version chinoise ?", options: ["Le baijiu","Le soju","Le sake","Le makgeolli"], correct: 0 },
  { text: "Quelle grande exposition universelle la Chine a-t-elle accueillie en 2010 ?", options: ["Osaka","Shanghai","Pékin","Séoul"], correct: 1 },
  { text: "Quel pont/ouvrage chinois figure parmi les plus longs du monde ?", options: ["Golden Gate","Le pont Danyang-Kunshan","Le viaduc de Millau","Le pont de Brooklyn"], correct: 1 },
  { text: "Quel symbole monétaire représente le yuan/renminbi ?", options: ["$","¥","£","€"], correct: 1 },
  { text: "Quelle grande fête entraîne la plus grande migration humaine annuelle au monde ?", options: ["Le Nouvel An chinois","Noël","Thanksgiving","Diwali"], correct: 0 },
  { text: "Quelle ville historique fut la capitale de plusieurs dynasties, près de l'armée de terre cuite ?", options: ["Pékin","Xi'an","Nankin","Luoyang"], correct: 1 },
  { text: "Quel animal aquatique très rare vivait dans le Yangtsé (dauphin) ?", options: ["Le béluga","Le dauphin du Yangtsé (baiji)","Le marsouin commun","L'orque"], correct: 1 },
  { text: "Quel philosophe est associé au « légisme », doctrine de l'ordre par la loi ?", options: ["Han Fei","Confucius","Laozi","Mozi"], correct: 0 },
  { text: "Quel grand lac d'eau douce se trouve en Chine de l'est ?", options: ["Lac Baïkal","Lac Poyang","Lac Léman","Lac Victoria"], correct: 1 },
  { text: "Quelle minorité vit majoritairement au Xinjiang ?", options: ["Les Han","Les Ouïghours","Les Tibétains","Les Mongols"], correct: 1 },
  { text: "Quel animal symbolise la longévité dans la culture chinoise ?", options: ["Le tigre","La grue","Le loup","Le renard"], correct: 1 },
  { text: "Quelle couleur est portée traditionnellement lors des mariages chinois ?", options: ["Le blanc","Le rouge","Le noir","Le vert"], correct: 1 },
  { text: "Quel art chinois consiste à tracer de beaux caractères au pinceau ?", options: ["L'origami","La calligraphie","L'ikebana","La gravure"], correct: 1 },
  { text: "Quel grand barrage a nécessité le déplacement de plus d'un million de personnes ?", options: ["Assouan","Les Trois-Gorges","Hoover","Itaipu"], correct: 1 },
  { text: "Quel empire a précédé la fondation de la RPC, dirigé par Tchang Kaï-chek ?", options: ["L'Empire Qing","La République de Chine","La dynastie Ming","La dynastie Yuan"], correct: 1 },
  { text: "Quelle est la fête des morts/du nettoyage des tombes en Chine ?", options: ["Qingming","Duanwu","Mi-automne","Nouvel An"], correct: 0 },
  { text: "Quel produit technologique la Chine fabrique-t-elle massivement aujourd'hui ?", options: ["Voitures à vapeur","Smartphones et électronique","Montres à coucou","Gramophones"], correct: 1 },
  { text: "Quelle ville chinoise est un centre de la finance et un port franc du sud ?", options: ["Hong Kong","Lhassa","Xining","Hohhot"], correct: 0 },
  { text: "Quel personnage historique a unifié les poids, mesures et l'écriture en Chine ?", options: ["Confucius","Qin Shi Huang","Mao","Sun Yat-sen"], correct: 1 },
  { text: "Quel type de bateau traditionnel chinois a des voiles nervurées ?", options: ["La gondole","La jonque","La pirogue","Le drakkar"], correct: 1 },
  { text: "Quel animal en peluche géant est offert par la Chine en « diplomatie » ?", options: ["Le tigre","Le panda","Le singe","Le dragon de Komodo"], correct: 1 },
  { text: "Quel pays partage la plus longue frontière avec la Chine au nord ?", options: ["Inde","Mongolie","Russie","Kazakhstan"], correct: 2 },
  { text: "Quel pays himalayen borde la Chine au sud-ouest ?", options: ["Thaïlande","Népal","Japon","Philippines"], correct: 1 },
  { text: "Quelle mer borde la Chine à l'est près de Shanghai ?", options: ["Mer Noire","Mer de Chine orientale","Mer Rouge","Mer Baltique"], correct: 1 },
  { text: "Quel océan borde globalement la Chine ?", options: ["Atlantique","Pacifique","Indien","Arctique"], correct: 1 },
  { text: "Quelle est la langue écrite commune en Chine ?", options: ["Un alphabet latin","Des caractères (hanzi)","Le cyrillique","Des hiéroglyphes"], correct: 1 },
  { text: "Comment dit-on « au revoir » en mandarin ?", options: ["Sayonara","Zàijiàn","Annyeong","Ciao"], correct: 1 },
  { text: "Quel animal du zodiaque chinois précède le rat (fin de cycle) ?", options: ["Le buffle","Le cochon","Le chien","Le coq"], correct: 1 },
  { text: "Quel est le 12e et dernier animal du zodiaque chinois ?", options: ["Le rat","Le cochon","Le chien","Le tigre"], correct: 1 },
  { text: "Quelle est la plus longue muraille du monde ?", options: ["Mur d'Hadrien","La Grande Muraille de Chine","Le limes","Le mur de Berlin"], correct: 1 },
  { text: "Quel ancien chemin commercial reliait la Chine à Rome ?", options: ["La route de l'ambre","La route de la soie","La route du sel","La route des Indes"], correct: 1 },
  { text: "Quelle dynastie a immédiatement suivi la dynastie Qin ?", options: ["Han","Tang","Song","Ming"], correct: 0 },
  { text: "Quelle dynastie a précédé les Qing ?", options: ["Ming","Yuan","Song","Tang"], correct: 0 },
  { text: "Quel empereur a unifié la Chine et standardisé l'écriture ?", options: ["Wudi","Qin Shi Huang","Kangxi","Taizong"], correct: 1 },
  { text: "Quelle invention chinoise a permis de fabriquer des feux d'artifice ?", options: ["Le papier","La poudre à canon","La boussole","La soie"], correct: 1 },
  { text: "Quelle invention chinoise aidait les marins à s'orienter ?", options: ["Le sextant","La boussole","Le GPS","Le radar"], correct: 1 },
  { text: "Quel matériau d'écriture a été inventé en Chine ?", options: ["Le parchemin","Le papier","Le papyrus","L'argile"], correct: 1 },
  { text: "Quel insecte produit le fil utilisé pour la soie ?", options: ["L'abeille","Le ver à soie","L'araignée","La fourmi"], correct: 1 },
  { text: "Quel temple de Pékin servait aux prières impériales pour les récoltes ?", options: ["Temple d'Or","Temple du Ciel","Temple de Jade","Temple Shaolin"], correct: 1 },
  { text: "Quel monastère est associé aux moines pratiquant le kung-fu ?", options: ["Wudang","Shaolin","Potala","Lama"], correct: 1 },
  { text: "Quelle philosophie met l'accent sur le respect des aînés et l'ordre social ?", options: ["Taoïsme","Confucianisme","Bouddhisme","Légisme"], correct: 1 },
  { text: "Quel texte fondateur est attribué à Laozi ?", options: ["L'Art de la guerre","Le Tao Te King","Les Entretiens","Le Yi King"], correct: 1 },
  { text: "Quel recueil rassemble les enseignements de Confucius ?", options: ["Le Tao Te King","Les Entretiens (Lunyu)","L'Art de la guerre","Le Livre des Mutations"], correct: 1 },
  { text: "Quel grand stratège a écrit un traité militaire toujours étudié ?", options: ["Confucius","Sun Tzu","Laozi","Mencius"], correct: 1 },
  { text: "Quelle mégapole du centre est l'une des plus peuplées de Chine ?", options: ["Lhassa","Chongqing","Hohhot","Xining"], correct: 1 },
  { text: "Quelle ville chinoise est un grand centre technologique du sud ?", options: ["Shenzhen","Lhassa","Urumqi","Harbin"], correct: 0 },
  { text: "Quelle ville chinoise est la capitale et le cœur politique ?", options: ["Shanghai","Pékin","Canton","Nankin"], correct: 1 },
  { text: "Quel grand fleuve traverse Shanghai pour se jeter dans la mer ?", options: ["Le fleuve Jaune","Le Yangtsé","Le Mékong","La rivière des Perles"], correct: 1 },
  { text: "Quelle rivière donne son nom au delta industriel du sud ?", options: ["Le Yangtsé","La rivière des Perles","Le fleuve Jaune","Le Mékong"], correct: 1 },
  { text: "Quel grand barrage chinois est sur le Yangtsé ?", options: ["Assouan","Les Trois-Gorges","Hoover","Itaipu"], correct: 1 },
  { text: "Quelle chaîne de montagnes sépare la Chine du sous-continent indien ?", options: ["Les Andes","L'Himalaya","Les Alpes","L'Oural"], correct: 1 },
  { text: "Quel plateau de haute altitude est surnommé « le toit du monde » ?", options: ["Le plateau du Tibet","Le plateau iranien","Le plateau anatolien","Les Andes"], correct: 0 },
  { text: "Quelle religion indienne s'est largement répandue en Chine ?", options: ["L'islam","Le bouddhisme","Le judaïsme","Le christianisme"], correct: 1 },
  { text: "Quel animal noir et blanc, symbole de la Chine, mange du bambou ?", options: ["Le koala","Le panda géant","Le tapir","Le raton laveur"], correct: 1 },
  { text: "Quelle pierre verte est très prisée dans l'artisanat chinois ?", options: ["Le rubis","Le jade","Le saphir","Le diamant"], correct: 1 },
  { text: "Quelle couleur porte chance en Chine et orne les enveloppes du Nouvel An ?", options: ["Le blanc","Le rouge","Le noir","Le gris"], correct: 1 },
  { text: "Quel art consiste à tracer de beaux caractères au pinceau et à l'encre ?", options: ["L'origami","La calligraphie","La gravure","La marqueterie"], correct: 1 },
  { text: "Quel jeu de plateau millénaire se joue avec des pierres sur un quadrillage ?", options: ["Les échecs","Le go (weiqi)","Le backgammon","Les dames"], correct: 1 },
  { text: "Quel jeu de tuiles à quatre joueurs est très populaire en Chine ?", options: ["Le domino","Le mah-jong","Le tarot","Le rummy"], correct: 1 },
  { text: "Quel plat consiste à cuire soi-même ses aliments dans un bouillon bouillant ?", options: ["Le dim sum","Le hot pot","Le canard laqué","Le baozi"], correct: 1 },
  { text: "Quelles petites bouchées cantonaises se servent en paniers vapeur ?", options: ["Les ramen","Les dim sum","Les nems","Les onigiri"], correct: 1 },
  { text: "Quel pain chinois fourré est cuit à la vapeur ?", options: ["Le bao (baozi)","Le naan","La pita","La focaccia"], correct: 0 },
  { text: "Quelle céréale est l'aliment de base du sud de la Chine ?", options: ["Le blé","Le riz","Le maïs","Le seigle"], correct: 1 },
  { text: "Quelle boisson chaude est au cœur de la culture chinoise ?", options: ["Le café","Le thé","Le chocolat","Le maté"], correct: 1 },
  { text: "Quel thé fermenté sombre est une spécialité chinoise ?", options: ["Le matcha","Le pu-erh","Le rooibos","L'oolong est vert"], correct: 1 },
  { text: "Quel alcool blanc fort est servi lors des banquets chinois ?", options: ["Le saké","Le baijiu","Le soju","La vodka"], correct: 1 },
  { text: "Quel festival chinois illumine la fin du Nouvel An avec des lanternes ?", options: ["La fête des lanternes","Halloween","Qingming","Duanwu"], correct: 0 },
  { text: "Quelle fête chinoise honore les ancêtres en nettoyant les tombes ?", options: ["Qingming","Nouvel An","Mi-automne","Duanwu"], correct: 0 },
  { text: "Quel dessert se mange pendant la fête de la mi-automne ?", options: ["Le mooncake (gâteau de lune)","Le mochi","Le baklava","Le donut"], correct: 0 },
  { text: "Quel symbole circulaire représente l'équilibre du yin et du yang ?", options: ["La croix","Le taijitu","Le croissant","L'étoile"], correct: 1 },
  { text: "Quel pays a été uni sous Mao Zedong en 1949 ?", options: ["La Corée","La Chine","Le Vietnam","La Mongolie"], correct: 1 },
  { text: "Quel dirigeant a ouvert la Chine à l'économie de marché après 1978 ?", options: ["Mao","Deng Xiaoping","Sun Yat-sen","Jiang Zemin"], correct: 1 },
  { text: "Quelle place de Pékin est l'une des plus grandes places publiques du monde ?", options: ["Place Rouge","Tian'anmen","Place du Peuple","Trafalgar"], correct: 1 },
  { text: "Quel ancien complexe palatial impérial se trouve au centre de Pékin ?", options: ["Le Kremlin","La Cité interdite","Le Potala","Le Taj Mahal"], correct: 1 },
  { text: "Quelle entreprise chinoise est un géant du e-commerce (fondée par Jack Ma) ?", options: ["Tencent","Alibaba","Baidu","Huawei"], correct: 1 },
  { text: "Quelle entreprise chinoise édite WeChat ?", options: ["Alibaba","Tencent","Baidu","Xiaomi"], correct: 1 },
  { text: "Quel constructeur chinois est un leader des voitures électriques ?", options: ["Toyota","BYD","Renault","Ford"], correct: 1 },
  { text: "Quelle application vidéo courte appartient au chinois ByteDance ?", options: ["Instagram","TikTok","Snapchat","Vine"], correct: 1 },
  { text: "Quel fabricant chinois de smartphones et télécoms est mondialement connu ?", options: ["Sony","Huawei","Nokia","Ericsson"], correct: 1 },
  { text: "Quelle ville chinoise a accueilli les Jeux olympiques d'été de 2008 ?", options: ["Shanghai","Pékin","Canton","Nankin"], correct: 1 },
  { text: "Quelle ville a accueilli l'Exposition universelle de 2010 ?", options: ["Pékin","Shanghai","Shenzhen","Wuhan"], correct: 1 },
  { text: "Quel symbole monétaire désigne le yuan ?", options: ["$","¥","£","₩"], correct: 1 },
  { text: "Quel grand mur figure parmi les monuments les plus visités de Chine ?", options: ["Le mur des Lamentations","La Grande Muraille","Le mur de Berlin","Le limes"], correct: 1 },
  { text: "Quelle ville historique abrite l'armée de terre cuite ?", options: ["Pékin","Xi'an","Nankin","Luoyang"], correct: 1 },
  { text: "Quel matériau translucide raffiné, exporté par la Chine, porte le nom anglais « china » ?", options: ["Le verre","La porcelaine","Le cristal","Le jade"], correct: 1 },
  { text: "Quelle ancienne capitale impériale se trouve sur le fleuve Yangtsé (« capitale du Sud ») ?", options: ["Pékin","Nankin","Canton","Wuhan"], correct: 1 },
  { text: "Quel grand canal historique relie le nord et le sud de la Chine ?", options: ["Le canal de Suez","Le Grand Canal","Le canal de Panama","Le canal de Corinthe"], correct: 1 },
  { text: "Quel type de voilier traditionnel chinois a des voiles à lattes ?", options: ["La gondole","La jonque","Le catamaran","Le drakkar"], correct: 1 },
  { text: "Quelle médecine traditionnelle chinoise utilise des aiguilles ?", options: ["L'homéopathie","L'acupuncture","La chiropraxie","L'ostéopathie"], correct: 1 },
  { text: "Quel exercice lent de santé associe mouvements et respiration ?", options: ["Le judo","Le tai-chi","Le karaté","La boxe"], correct: 1 },
  { text: "Quelle grande fête provoque la plus grande migration humaine annuelle ?", options: ["Noël","Le Nouvel An chinois","Thanksgiving","Pâques"], correct: 1 },
  { text: "Quel pays a dépassé la Chine comme pays le plus peuplé du monde en 2023 ?", options: ["L'Inde","Le Brésil","Les États-Unis","La Russie"], correct: 0 },
  { text: "Quelle est la monnaie chinoise, aussi appelée renminbi ?", options: ["Le yen","Le yuan","Le won","Le bath"], correct: 1 },
  { text: "Quel grand lac d'eau douce se trouve dans l'est de la Chine ?", options: ["Lac Baïkal","Lac Poyang","Lac Léman","Lac Tanganyika"], correct: 1 },
  { text: "Quelle minorité musulmane vit surtout au Xinjiang ?", options: ["Les Han","Les Ouïghours","Les Tibétains","Les Hui seuls"], correct: 1 },
  { text: "Quel animal mythique à écailles symbolise l'empereur de Chine ?", options: ["Le phénix","Le dragon","La licorne","Le tigre"], correct: 1 },
  { text: "Quel oiseau mythique symbolise l'impératrice dans la culture chinoise ?", options: ["Le corbeau","Le phénix","L'aigle","La grue"], correct: 1 },
];
