// QuizzMaster — thème 🧠 Culture générale. 209 questions.

module.exports = [
  { text: "Combien de continents y a-t-il sur Terre ?", options: ["5","6","7","8"], correct: 2 },
  { text: "Combien de couleurs dans un arc-en-ciel ?", options: ["5","6","7","8"], correct: 2 },
  { text: "Quelle est la couleur obtenue en mélangeant bleu et jaune ?", options: ["Vert","Orange","Violet","Marron"], correct: 0 },
  { text: "Quelle est la couleur obtenue en mélangeant rouge et bleu ?", options: ["Vert","Violet","Orange","Gris"], correct: 1 },
  { text: "Combien de jours dans une année non bissextile ?", options: ["364","365","366","360"], correct: 1 },
  { text: "Combien de jours dans une année bissextile ?", options: ["365","366","367","364"], correct: 1 },
  { text: "Combien de mois comptent 31 jours ?", options: ["6","7","5","8"], correct: 1 },
  { text: "Combien de cartes dans un jeu classique (sans jokers) ?", options: ["48","52","54","60"], correct: 1 },
  { text: "Combien de cases sur un échiquier ?", options: ["49","64","81","100"], correct: 1 },
  { text: "Combien de joueurs dans une équipe de football sur le terrain ?", options: ["9","10","11","12"], correct: 2 },
  { text: "Combien de joueurs sur un terrain de basket par équipe ?", options: ["5","6","7","11"], correct: 0 },
  { text: "Quel sport se joue à Wimbledon ?", options: ["Golf","Tennis","Cricket","Polo"], correct: 1 },
  { text: "Combien de cordes a une guitare classique ?", options: ["4","5","6","12"], correct: 2 },
  { text: "Combien de touches blanches et noires a un piano standard ?", options: ["76","82","88","96"], correct: 2 },
  { text: "Quel instrument possède des touches noires et blanches ?", options: ["Violon","Piano","Flûte","Harpe"], correct: 1 },
  { text: "Quelle note de musique vient après le « do » ?", options: ["Mi","Ré","Fa","Sol"], correct: 1 },
  { text: "Combien de notes dans une gamme de do à do (incluse) ?", options: ["6","7","8","9"], correct: 2 },
  { text: "Quel est le plus grand mammifère terrestre ?", options: ["Rhinocéros","Éléphant d'Afrique","Hippopotame","Girafe"], correct: 1 },
  { text: "Quel est l'animal le plus grand du monde ?", options: ["Éléphant","Baleine bleue","Cachalot","Requin-baleine"], correct: 1 },
  { text: "Quel oiseau ne vole pas et court très vite ?", options: ["Aigle","Autruche","Hibou","Cygne"], correct: 1 },
  { text: "Quel animal est le meilleur ami de l'homme ?", options: ["Le chat","Le chien","Le cheval","Le lapin"], correct: 1 },
  { text: "Comment appelle-t-on le petit de la vache ?", options: ["Poulain","Veau","Agneau","Chevreau"], correct: 1 },
  { text: "Comment appelle-t-on le petit du mouton ?", options: ["Veau","Agneau","Poulain","Chevreau"], correct: 1 },
  { text: "Quel animal vit dans une ruche ?", options: ["La fourmi","L'abeille","La guêpe","Le moustique"], correct: 1 },
  { text: "Quel est le roi des animaux selon la tradition ?", options: ["Le tigre","Le lion","L'ours","L'aigle"], correct: 1 },
  { text: "Quelle planète habitons-nous ?", options: ["Mars","La Terre","Vénus","Jupiter"], correct: 1 },
  { text: "Quel astre éclaire la Terre le jour ?", options: ["La Lune","Le Soleil","Vénus","Mars"], correct: 1 },
  { text: "Quel astre voit-on briller la nuit, satellite de la Terre ?", options: ["Le Soleil","La Lune","Mars","Une comète"], correct: 1 },
  { text: "Combien de saisons y a-t-il dans l'année ?", options: ["2","3","4","5"], correct: 2 },
  { text: "Quelle saison vient après l'hiver ?", options: ["L'été","Le printemps","L'automne","La mousson"], correct: 1 },
  { text: "En quelle saison tombent généralement les feuilles des arbres ?", options: ["Printemps","Été","Automne","Hiver"], correct: 2 },
  { text: "Quel métal précieux est jaune et brillant ?", options: ["L'argent","L'or","Le fer","Le cuivre"], correct: 1 },
  { text: "Quelle pierre précieuse est rouge ?", options: ["Émeraude","Rubis","Saphir","Diamant"], correct: 1 },
  { text: "Quelle pierre précieuse est verte ?", options: ["Rubis","Émeraude","Saphir","Topaze"], correct: 1 },
  { text: "Quelle est la pierre la plus dure ?", options: ["Le quartz","Le diamant","Le marbre","Le granite"], correct: 1 },
  { text: "Quelle langue est la plus parlée au monde (langue maternelle) ?", options: ["Anglais","Mandarin","Espagnol","Hindi"], correct: 1 },
  { text: "Quelle langue est officielle au Brésil ?", options: ["Espagnol","Portugais","Français","Italien"], correct: 1 },
  { text: "Quelle langue parle-t-on principalement au Mexique ?", options: ["Portugais","Espagnol","Anglais","Maya"], correct: 1 },
  { text: "Dans quel pays parle-t-on le japonais ?", options: ["Chine","Japon","Corée","Thaïlande"], correct: 1 },
  { text: "Quelle est la monnaie commune à de nombreux pays européens ?", options: ["Le dollar","L'euro","La livre","Le franc"], correct: 1 },
  { text: "Quelle est la monnaie des États-Unis ?", options: ["L'euro","Le dollar","La livre","Le peso"], correct: 1 },
  { text: "Quelle est la monnaie du Royaume-Uni ?", options: ["L'euro","La livre sterling","Le dollar","Le franc"], correct: 1 },
  { text: "Combien de minutes dans une heure ?", options: ["30","45","60","100"], correct: 2 },
  { text: "Combien d'heures dans une journée ?", options: ["12","24","36","48"], correct: 1 },
  { text: "Combien de semaines dans une année (environ) ?", options: ["48","50","52","56"], correct: 2 },
  { text: "Quel est le premier mois de l'année ?", options: ["Décembre","Janvier","Mars","Février"], correct: 1 },
  { text: "Quel jour vient après le lundi ?", options: ["Dimanche","Mardi","Mercredi","Jeudi"], correct: 1 },
  { text: "Quelle est la forme de la Terre ?", options: ["Plate","Quasi sphérique","Cubique","Conique"], correct: 1 },
  { text: "Quel symbole représente l'amour sur une carte à jouer ?", options: ["Le pique","Le cœur","Le trèfle","Le carreau"], correct: 1 },
  { text: "Combien de roues a une voiture classique ?", options: ["2","3","4","6"], correct: 2 },
  { text: "Combien de roues a une moto ?", options: ["1","2","3","4"], correct: 1 },
  { text: "Quel véhicule vole dans les airs avec des ailes ?", options: ["Le bateau","L'avion","Le train","Le sous-marin"], correct: 1 },
  { text: "Quel véhicule navigue sous l'eau ?", options: ["Le ferry","Le sous-marin","Le voilier","Le kayak"], correct: 1 },
  { text: "Quel moyen de transport roule sur des rails ?", options: ["L'avion","Le train","Le bus","Le bateau"], correct: 1 },
  { text: "Quelle est la capitale de l'Italie ?", options: ["Milan","Rome","Venise","Naples"], correct: 1 },
  { text: "Quelle est la capitale de l'Espagne ?", options: ["Barcelone","Madrid","Séville","Valence"], correct: 1 },
  { text: "Quelle est la capitale de l'Allemagne ?", options: ["Munich","Berlin","Francfort","Hambourg"], correct: 1 },
  { text: "Quelle tour penchée se trouve en Italie ?", options: ["Tour Eiffel","Tour de Pise","Big Ben","Tour de Londres"], correct: 1 },
  { text: "Quel monument se trouve à Paris ?", options: ["Big Ben","La tour Eiffel","Le Colisée","La Sagrada Familia"], correct: 1 },
  { text: "Quel monument antique se trouve à Rome ?", options: ["Le Parthénon","Le Colisée","Les Pyramides","Le Taj Mahal"], correct: 1 },
  { text: "Dans quel pays se trouve le Taj Mahal ?", options: ["Pakistan","Inde","Iran","Népal"], correct: 1 },
  { text: "Dans quel pays se trouvent les pyramides de Gizeh ?", options: ["Mexique","Égypte","Soudan","Grèce"], correct: 1 },
  { text: "Quel océan sépare l'Europe de l'Amérique ?", options: ["Pacifique","Atlantique","Indien","Arctique"], correct: 1 },
  { text: "Quel est le plus grand pays du monde ?", options: ["Chine","Russie","Canada","États-Unis"], correct: 1 },
  { text: "Quel est le plus petit État du monde ?", options: ["Monaco","Vatican","Nauru","Malte"], correct: 1 },
  { text: "Qui a peint la Joconde ?", options: ["Michel-Ange","Léonard de Vinci","Raphaël","Picasso"], correct: 1 },
  { text: "Dans quel musée se trouve la Joconde ?", options: ["Le Prado","Le Louvre","Le British Museum","Les Offices"], correct: 1 },
  { text: "Qui a écrit Roméo et Juliette ?", options: ["Molière","Shakespeare","Hugo","Goethe"], correct: 1 },
  { text: "Quel auteur a créé Sherlock Holmes ?", options: ["Agatha Christie","Arthur Conan Doyle","Edgar Poe","Maurice Leblanc"], correct: 1 },
  { text: "Quel auteur a créé Harry Potter ?", options: ["Tolkien","J.K. Rowling","Roald Dahl","C.S. Lewis"], correct: 1 },
  { text: "Quel personnage de conte perd une pantoufle de verre ?", options: ["Blanche-Neige","Cendrillon","Raiponce","La Belle"], correct: 1 },
  { text: "Quel conte met en scène un petit chaperon et un loup ?", options: ["Le Petit Poucet","Le Petit Chaperon rouge","Hansel et Gretel","Pinocchio"], correct: 1 },
  { text: "Quel pantin de bois voit son nez s'allonger quand il ment ?", options: ["Pinocchio","Gepetto","Peter Pan","Aladdin"], correct: 0 },
  { text: "Quel est le contraire de « chaud » ?", options: ["Tiède","Froid","Doux","Brûlant"], correct: 1 },
  { text: "Quel est le contraire de « grand » ?", options: ["Long","Petit","Large","Haut"], correct: 1 },
  { text: "Combien font une douzaine ?", options: ["10","12","13","20"], correct: 1 },
  { text: "Combien d'unités dans une centaine ?", options: ["10","100","1000","50"], correct: 1 },
  { text: "Quel est le chiffre romain pour 10 ?", options: ["V","X","L","C"], correct: 1 },
  { text: "Quel est le chiffre romain pour 100 ?", options: ["X","L","C","M"], correct: 2 },
  { text: "Quel chiffre romain représente 5 ?", options: ["I","V","X","L"], correct: 1 },
  { text: "Quel est le résultat de 5 + 7 ?", options: ["10","11","12","13"], correct: 2 },
  { text: "Quel est le double de 25 ?", options: ["40","50","52","55"], correct: 1 },
  { text: "Quelle est la moitié de 100 ?", options: ["25","40","50","60"], correct: 2 },
  { text: "Quel fruit est jaune et a une peau qu'on épluche ?", options: ["Pomme","Banane","Cerise","Raisin"], correct: 1 },
  { text: "Quel fruit est associé à Isaac Newton et la gravité ?", options: ["Poire","Pomme","Orange","Prune"], correct: 1 },
  { text: "Quel légume fait pleurer quand on le coupe ?", options: ["La carotte","L'oignon","La tomate","Le poivron"], correct: 1 },
  { text: "Quel aliment est fabriqué par les abeilles ?", options: ["Le lait","Le miel","Le beurre","Le sucre"], correct: 1 },
  { text: "De quel animal provient le lait le plus consommé en France ?", options: ["La chèvre","La vache","La brebis","La jument"], correct: 1 },
  { text: "Quelle boisson chaude est faite à partir de grains torréfiés ?", options: ["Le thé","Le café","Le chocolat","La tisane"], correct: 1 },
  { text: "Quelle boisson est faite à partir de feuilles infusées ?", options: ["Le café","Le thé","Le lait","Le jus"], correct: 1 },
  { text: "Quel repas se prend le matin ?", options: ["Le déjeuner","Le petit-déjeuner","Le dîner","Le goûter"], correct: 1 },
  { text: "Quel ustensile sert à manger la soupe ?", options: ["La fourchette","La cuillère","Le couteau","La pince"], correct: 1 },
  { text: "Quel vêtement protège la tête du froid ?", options: ["L'écharpe","Le bonnet","Les gants","Les chaussettes"], correct: 1 },
  { text: "Sur quel doigt porte-t-on traditionnellement l'alliance ?", options: ["Le pouce","L'annulaire","L'index","L'auriculaire"], correct: 1 },
  { text: "Quel organe permet de respirer ?", options: ["Le cœur","Les poumons","Le foie","L'estomac"], correct: 1 },
  { text: "Combien de doigts a une main humaine ?", options: ["4","5","6","10"], correct: 1 },
  { text: "Combien d'yeux a un être humain ?", options: ["1","2","3","4"], correct: 1 },
  { text: "Quelle couleur a le ciel par temps clair ?", options: ["Vert","Bleu","Rouge","Jaune"], correct: 1 },
  { text: "De quelle couleur est l'herbe en bonne santé ?", options: ["Bleue","Verte","Rouge","Jaune"], correct: 1 },
  { text: "Quelle couleur obtient-on avec rouge + jaune ?", options: ["Vert","Orange","Violet","Gris"], correct: 1 },
  { text: "Quel temps fait-il quand il y a des nuages et de l'eau qui tombe ?", options: ["Ensoleillé","Pluvieux","Venteux","Neigeux"], correct: 1 },
  { text: "Que tombe-t-il du ciel en hiver quand il fait très froid ?", options: ["La pluie","La neige","La grêle uniquement","Le brouillard"], correct: 1 },
  { text: "Quel appareil indique l'heure ?", options: ["Le thermomètre","La montre","La boussole","La balance"], correct: 1 },
  { text: "Quel appareil indique la direction (nord/sud) ?", options: ["La montre","La boussole","Le thermomètre","Le baromètre"], correct: 1 },
  { text: "Quel appareil sert à peser ?", options: ["La boussole","La balance","La règle","Le compas"], correct: 1 },
  { text: "Quel outil sert à planter un clou ?", options: ["Le tournevis","Le marteau","La pince","La scie"], correct: 1 },
  { text: "Quel outil sert à couper le bois ?", options: ["Le marteau","La scie","La clé","La perceuse"], correct: 1 },
  { text: "Quel métier soigne les animaux ?", options: ["Médecin","Vétérinaire","Pharmacien","Dentiste"], correct: 1 },
  { text: "Quel métier éteint les incendies ?", options: ["Policier","Pompier","Facteur","Boulanger"], correct: 1 },
  { text: "Quel métier fait le pain ?", options: ["Boucher","Boulanger","Épicier","Pâtissier"], correct: 1 },
  { text: "Quel professionnel pilote un avion ?", options: ["Le steward","Le pilote","Le mécanicien","Le contrôleur"], correct: 1 },
  { text: "Quel professionnel défend en justice ?", options: ["Le juge","L'avocat","Le notaire","Le greffier"], correct: 1 },
  { text: "Quelle planète est surnommée la planète bleue ?", options: ["Mars","La Terre","Neptune","Vénus"], correct: 1 },
  { text: "Quel est le satellite naturel de la Terre ?", options: ["Mars","La Lune","Vénus","Titan"], correct: 1 },
  { text: "Combien de planètes telluriques (rocheuses) proches du Soleil ?", options: ["2","3","4","5"], correct: 2 },
  { text: "Quelle est la galaxie qui contient le système solaire ?", options: ["Andromède","La Voie lactée","Le Triangle","Le Sombrero"], correct: 1 },
  { text: "Quel scientifique célèbre a la formule E=mc² ?", options: ["Newton","Einstein","Galilée","Darwin"], correct: 1 },
  { text: "Qui a peint Guernica ?", options: ["Dalí","Picasso","Miró","Velázquez"], correct: 1 },
  { text: "De quel pays vient la pizza ?", options: ["France","Italie","Espagne","Grèce"], correct: 1 },
  { text: "De quel pays viennent les sushis ?", options: ["Chine","Japon","Corée","Thaïlande"], correct: 1 },
  { text: "De quel pays vient la paella ?", options: ["Italie","Espagne","Portugal","Mexique"], correct: 1 },
  { text: "Quel pays est célèbre pour ses tulipes et ses moulins ?", options: ["Belgique","Pays-Bas","Danemark","Suède"], correct: 1 },
  { text: "Quel pays a la forme d'une botte ?", options: ["Espagne","Italie","Grèce","Croatie"], correct: 1 },
  { text: "Dans quel pays se trouve la statue de la Liberté ?", options: ["France","États-Unis","Canada","Royaume-Uni"], correct: 1 },
  { text: "Quel océan est le plus grand ?", options: ["Atlantique","Pacifique","Indien","Arctique"], correct: 1 },
  { text: "Quel est le plus long fleuve du monde (Afrique) ?", options: ["Amazone","Nil","Congo","Niger"], correct: 1 },
  { text: "Quel désert est le plus grand désert chaud ?", options: ["Gobi","Sahara","Kalahari","Mojave"], correct: 1 },
  { text: "Quelle est la plus haute montagne du monde ?", options: ["Mont Blanc","Everest","K2","Kilimandjaro"], correct: 1 },
  { text: "Quel animal symbolise la sagesse et porte des lunettes dans les dessins ?", options: ["Le renard","Le hibou","Le corbeau","Le paon"], correct: 1 },
  { text: "Quel animal change de couleur pour se camoufler ?", options: ["Le caméléon","Le zèbre","Le panda","Le koala"], correct: 0 },
  { text: "Quel animal porte sa maison sur son dos ?", options: ["La tortue","Le lièvre","Le crabe","Le hérisson"], correct: 0 },
  { text: "Quel insecte se transforme en papillon ?", options: ["La fourmi","La chenille","L'abeille","La sauterelle"], correct: 1 },
  { text: "Quel est le contraire de « jour » ?", options: ["Matin","Nuit","Soir","Midi"], correct: 1 },
  { text: "Quel est le contraire de « vrai » ?", options: ["Juste","Faux","Réel","Sûr"], correct: 1 },
  { text: "Quel est le contraire de « rapide » ?", options: ["Vif","Lent","Pressé","Léger"], correct: 1 },
  { text: "Combien de pattes a un chien ?", options: ["2","4","6","8"], correct: 1 },
  { text: "Combien de bosses a un dromadaire ?", options: ["0","1","2","3"], correct: 1 },
  { text: "Combien de bosses a un chameau ?", options: ["1","2","3","0"], correct: 1 },
  { text: "Quel animal rugit dans la savane ?", options: ["Le loup","Le lion","Le renard","Le cerf"], correct: 1 },
  { text: "Quel oiseau est le symbole de la paix ?", options: ["L'aigle","La colombe","Le corbeau","Le moineau"], correct: 1 },
  { text: "Quelle est la couleur du drapeau français (3 couleurs) ?", options: ["Vert-blanc-rouge","Bleu-blanc-rouge","Bleu-jaune-rouge","Noir-rouge-or"], correct: 1 },
  { text: "Combien d'étoiles sur le drapeau de l'Union européenne ?", options: ["10","12","15","27"], correct: 1 },
  { text: "Quel pays a un drapeau avec une feuille d'érable ?", options: ["États-Unis","Canada","Mexique","Brésil"], correct: 1 },
  { text: "Quel pays a un soleil rouge sur fond blanc sur son drapeau ?", options: ["Chine","Japon","Corée","Vietnam"], correct: 1 },
  { text: "Quel sport utilise un ballon ovale ?", options: ["Football","Rugby","Basket","Volley"], correct: 1 },
  { text: "Quel sport se pratique sur la glace avec un palet ?", options: ["Curling","Hockey sur glace","Patinage","Bobsleigh"], correct: 1 },
  { text: "Quel sport consiste à nager ?", options: ["L'aviron","La natation","Le surf","La plongée"], correct: 1 },
  { text: "Combien de joueurs dans une équipe de volley sur le terrain ?", options: ["5","6","7","11"], correct: 1 },
  { text: "Quel jeu utilise un roi, une reine et des pions ?", options: ["Les dames","Les échecs","Le backgammon","Le go"], correct: 1 },
  { text: "Quel jeu de société se joue avec des lettres pour former des mots ?", options: ["Monopoly","Scrabble","Cluedo","Risk"], correct: 1 },
  { text: "Quelle planète est connue pour ses anneaux ?", options: ["Mars","Saturne","Vénus","Mercure"], correct: 1 },
  { text: "Quel gaz respirons-nous pour vivre ?", options: ["Azote","Oxygène","CO₂","Hélium"], correct: 1 },
  { text: "Quelle est la formule chimique de l'eau ?", options: ["O₂","H₂O","CO₂","H₂"], correct: 1 },
  { text: "Combien de pôles a la Terre ?", options: ["1","2","3","4"], correct: 1 },
  { text: "Comment s'appelle la ligne imaginaire qui sépare la Terre en deux hémisphères ?", options: ["Le méridien","L'équateur","Le tropique","Le parallèle nul"], correct: 1 },
  { text: "Quel est le sang « donneur universel » ?", options: ["AB+","O-","A+","B-"], correct: 1 },
  { text: "Quel organe pense et contrôle le corps ?", options: ["Le cœur","Le cerveau","Le foie","L'estomac"], correct: 1 },
  { text: "Quelle vitamine trouve-t-on surtout dans les oranges ?", options: ["A","C","D","K"], correct: 1 },
  { text: "Quel aliment est une bonne source de calcium ?", options: ["Le pain","Le lait","La viande","Le riz"], correct: 1 },
  { text: "Quelle est la capitale du Portugal ?", options: ["Porto","Lisbonne","Madrid","Faro"], correct: 1 },
  { text: "Quelle est la capitale de la Belgique ?", options: ["Anvers","Bruxelles","Bruges","Gand"], correct: 1 },
  { text: "Quelle est la capitale de la Suisse ?", options: ["Genève","Berne","Zurich","Bâle"], correct: 1 },
  { text: "Quelle est la capitale du Royaume-Uni ?", options: ["Manchester","Londres","Édimbourg","Liverpool"], correct: 1 },
  { text: "Quelle est la capitale du Canada ?", options: ["Toronto","Ottawa","Montréal","Vancouver"], correct: 1 },
  { text: "Quelle est la capitale du Japon ?", options: ["Osaka","Tokyo","Kyoto","Nagoya"], correct: 1 },
  { text: "Quelle est la capitale de la Russie ?", options: ["Saint-Pétersbourg","Moscou","Kiev","Minsk"], correct: 1 },
  { text: "Quelle est la capitale de la Grèce ?", options: ["Thessalonique","Athènes","Sparte","Corinthe"], correct: 1 },
  { text: "Quelle est la capitale de l'Égypte ?", options: ["Alexandrie","Le Caire","Louxor","Gizeh"], correct: 1 },
  { text: "Quelle est la capitale des États-Unis ?", options: ["New York","Washington","Chicago","Boston"], correct: 1 },
  { text: "Combien de côtés a un triangle ?", options: ["2","3","4","5"], correct: 1 },
  { text: "Combien de côtés a un carré ?", options: ["3","4","5","6"], correct: 1 },
  { text: "Combien de côtés a un rectangle ?", options: ["3","4","5","6"], correct: 1 },
  { text: "Quelle figure n'a pas d'angle ?", options: ["Carré","Cercle","Triangle","Losange"], correct: 1 },
  { text: "Combien de minutes dans un quart d'heure ?", options: ["10","15","20","25"], correct: 1 },
  { text: "Combien de minutes dans une demi-heure ?", options: ["20","30","40","45"], correct: 1 },
  { text: "Combien font 3 fois 4 ?", options: ["7","12","9","16"], correct: 1 },
  { text: "Combien font 10 fois 10 ?", options: ["20","50","100","1000"], correct: 2 },
  { text: "Quel est le tiers de 90 ?", options: ["20","30","45","60"], correct: 1 },
  { text: "Quel nombre vient juste après 99 ?", options: ["98","100","101","199"], correct: 1 },
  { text: "Quel est le plus grand : un kilomètre ou un mètre ?", options: ["Un mètre","Un kilomètre","Égaux","Indéterminé"], correct: 1 },
  { text: "Combien de grammes dans un kilogramme ?", options: ["100","500","1000","10000"], correct: 2 },
  { text: "Combien de centimètres dans un mètre ?", options: ["10","100","1000","50"], correct: 1 },
  { text: "Combien de millilitres dans un litre ?", options: ["10","100","1000","500"], correct: 2 },
  { text: "Quelle unité mesure la distance ?", options: ["Le litre","Le mètre","Le gramme","Le watt"], correct: 1 },
  { text: "Quelle unité mesure la masse ?", options: ["Le mètre","Le gramme","Le litre","Le volt"], correct: 1 },
  { text: "Quelle unité mesure le volume liquide ?", options: ["Le mètre","Le litre","Le gramme","Le watt"], correct: 1 },
  { text: "Quel est le premier homme à avoir marché sur la Lune ?", options: ["Gagarine","Armstrong","Aldrin","Glenn"], correct: 1 },
  { text: "Qui a peint les Tournesols (et s'est coupé l'oreille) ?", options: ["Monet","Van Gogh","Gauguin","Cézanne"], correct: 1 },
  { text: "Quel compositeur sourd a écrit la 9e symphonie ?", options: ["Mozart","Beethoven","Bach","Chopin"], correct: 1 },
  { text: "Quel compositeur autrichien enfant prodige a écrit Don Giovanni ?", options: ["Bach","Mozart","Haydn","Schubert"], correct: 1 },
  { text: "De quel pays vient le tango ?", options: ["Brésil","Argentine","Espagne","Cuba"], correct: 1 },
  { text: "De quel pays vient le flamenco ?", options: ["Italie","Espagne","Portugal","Mexique"], correct: 1 },
  { text: "Quel pays a inventé les Jeux olympiques (antiquité) ?", options: ["Rome","Grèce","Égypte","Perse"], correct: 1 },
  { text: "Tous les combien d'années ont lieu les JO d'été ?", options: ["2 ans","3 ans","4 ans","5 ans"], correct: 2 },
  { text: "Quel pays a gagné le plus de Coupes du monde de football ?", options: ["Allemagne","Brésil","Italie","Argentine"], correct: 1 },
  { text: "Quel sport pratique-t-on à Roland-Garros ?", options: ["Golf","Tennis","Pétanque","Rugby"], correct: 1 },
  { text: "Quelle planète est la nôtre ?", options: ["Vénus","La Terre","Mars","Mercure"], correct: 1 },
  { text: "Quel est l'animal national de l'Australie connu pour sauter ?", options: ["Koala","Kangourou","Émeu","Wombat"], correct: 1 },
  { text: "Quel grand félin a une crinière (le mâle) ?", options: ["Le tigre","Le lion","Le léopard","Le guépard"], correct: 1 },
  { text: "Quel animal marin a huit bras ?", options: ["Le calmar","La pieuvre","La méduse","L'étoile de mer"], correct: 1 },
  { text: "Quel oiseau marche sur la banquise et ne vole pas ?", options: ["Le pingouin volant","Le manchot","Le héron","Le cygne"], correct: 1 },
  { text: "Quelle est la plus grande ville de France ?", options: ["Marseille","Paris","Lyon","Toulouse"], correct: 1 },
  { text: "Quel fleuve traverse Londres ?", options: ["La Seine","La Tamise","Le Rhin","Le Danube"], correct: 1 },
  { text: "Quel fleuve traverse Rome ?", options: ["Le Pô","Le Tibre","L'Arno","L'Adige"], correct: 1 },
  { text: "Quelle est la langue officielle de l'Argentine ?", options: ["Portugais","Espagnol","Italien","Anglais"], correct: 1 },
  { text: "Quel continent abrite le Sahara ?", options: ["Asie","Afrique","Océanie","Amérique"], correct: 1 },
  { text: "Sur quel continent vivent les kangourous à l'état sauvage ?", options: ["Afrique","Océanie (Australie)","Asie","Amérique"], correct: 1 },
  { text: "Quel océan borde la côte est du Brésil ?", options: ["Pacifique","Atlantique","Indien","Arctique"], correct: 1 },
  { text: "Combien de couleurs primaires en peinture (modèle classique) ?", options: ["2","3","4","5"], correct: 1 },
];
