// QuizzMaster — thème ✍️ Docusign & signature électronique (UE). 110 questions.
// Couvre : la société DocuSign, principes techniques de la signature
// électronique, règlement eIDAS (1 & 2), cadre juridique France/UE et
// cas d'usage.

module.exports = [
  // ---------- La société DocuSign (1-30) ----------
  { text: "En quelle année DocuSign a-t-elle été fondée ?", options: ["2001","2003","2005","2007"], correct: 1 },
  { text: "Dans quelle ville se trouve le siège mondial de DocuSign ?", options: ["Seattle","New York","San Francisco","Austin"], correct: 2 },
  { text: "Dans quel État américain DocuSign a-t-elle son siège ?", options: ["Texas","Californie","Washington","New York"], correct: 1 },
  { text: "Sur quelle bourse DocuSign est-elle cotée depuis son IPO ?", options: ["NYSE","AMEX","NASDAQ","LSE"], correct: 2 },
  { text: "Quel est le ticker boursier de DocuSign ?", options: ["DSG","DOCU","DSN","DCS"], correct: 1 },
  { text: "Quel est le produit phare de DocuSign ?", options: ["DocuSign CLM","eSignature","Insight","Notary"], correct: 1 },
  { text: "Qui est l'un des fondateurs historiques de DocuSign ?", options: ["Bill Gates","Tom Gonser","Marc Benioff","Larry Ellison"], correct: 1 },
  { text: "En 2018, quelle société DocuSign a-t-elle rachetée pour renforcer son offre CLM ?", options: ["SpringCM","Adobe Sign","HelloSign","PandaDoc"], correct: 0 },
  { text: "En 2020, DocuSign a acquis Seal Software, spécialisée dans…", options: ["la biométrie","l'analyse IA des contrats","la notarisation","la facturation"], correct: 1 },
  { text: "En 2020, DocuSign a acquis Liveoak Technologies, spécialisée dans…", options: ["le CLM","la notarisation à distance (RON)","la blockchain","le KYC"], correct: 1 },
  { text: "Combien DocuSign compte-t-elle approximativement de clients payants ?", options: ["~100 000","~500 000","~1,6 million","~10 millions"], correct: 2 },
  { text: "Quel acronyme désigne le produit DocuSign de gestion du cycle de vie des contrats ?", options: ["CRM","ERP","CLM","HRM"], correct: 2 },
  { text: "Quel concurrent majeur de DocuSign appartient au groupe Adobe ?", options: ["Yousign","Adobe Acrobat Sign","SignNow","PandaDoc"], correct: 1 },
  { text: "Quel concurrent français de DocuSign est basé à Paris ?", options: ["PandaDoc","Adobe Sign","Yousign","HelloSign"], correct: 2 },
  { text: "Quel concurrent de DocuSign a été racheté par Dropbox (devenu Dropbox Sign) ?", options: ["Yousign","HelloSign","PandaDoc","SignNow"], correct: 1 },
  { text: "Quel est l'ordre de grandeur du chiffre d'affaires annuel de DocuSign récemment ?", options: ["~100 M$","~500 M$","~1 Md$","~2,5 Md$"], correct: 3 },
  { text: "En 2024, DocuSign a annoncé l'acquisition de Lexion, société utilisant…", options: ["la blockchain","l'IA générative pour les contrats","le KYC","l'IoT"], correct: 1 },
  { text: "Quel sigle désigne la notarisation électronique à distance pour notaires US ?", options: ["RON","CLM","CMS","PKI"], correct: 0 },
  { text: "DocuSign sert principalement quel marché ?", options: ["B2C uniquement","B2B et particuliers","Jeux vidéo","Réseaux sociaux"], correct: 1 },
  { text: "Quel domaine ne fait PAS partie de DocuSign Insight ?", options: ["Recherche IA dans les contrats","Extraction de clauses","Hébergement vidéo","Analyse de risque"], correct: 2 },
  { text: "En quelle année DocuSign a-t-elle réalisé son introduction en bourse (IPO) ?", options: ["2014","2016","2018","2020"], correct: 2 },
  { text: "Quel ancien CEO de DocuSign a dirigé l'entreprise de 2017 à 2022 ?", options: ["Keith Krach","Dan Springer","Bill McDermott","Steve Ballmer"], correct: 1 },
  { text: "Qui était CEO de DocuSign avant Dan Springer ?", options: ["Tom Gonser","Keith Krach","Marc Benioff","Eric Yuan"], correct: 1 },
  { text: "Avant DocuSign, Tom Gonser avait fondé…", options: ["un site de poker","NetUpdate","Tumblr","Quora"], correct: 1 },
  { text: "DocuSign accepte-t-elle nativement les paiements en cryptomonnaie pour ses abonnements ?", options: ["Oui depuis 2017","Non, monnaies fiat principalement","Uniquement Bitcoin","Uniquement Ethereum"], correct: 1 },
  { text: "Combien d'employés DocuSign compte-t-elle environ ?", options: ["~500","~2 000","~6 000-7 000","~50 000"], correct: 2 },
  { text: "Dans combien de pays DocuSign est-elle juridiquement utilisable ?", options: ["~10","~50","plus de 180","uniquement aux USA"], correct: 2 },
  { text: "En combien de langues l'interface DocuSign est-elle disponible ?", options: ["~5","~15","plus de 40","uniquement anglais"], correct: 2 },
  { text: "Quel niveau eIDAS le plus élevé DocuSign propose-t-elle aussi en Europe ?", options: ["Simple uniquement","Avancée uniquement","Qualifiée (QES)","Aucun"], correct: 2 },
  { text: "DocuSign propose la signature qualifiée européenne…", options: ["seule","en partenariat avec des QTSP","via Microsoft","via Adobe"], correct: 1 },

  // ---------- Principes techniques de la signature électronique (31-60) ----------
  { text: "La signature électronique repose principalement sur la…", options: ["cryptographie asymétrique","stéganographie","compression vidéo","intelligence artificielle"], correct: 0 },
  { text: "Le sigle PKI signifie en cryptographie :", options: ["Personal Key Identity","Public Key Infrastructure","Private Key Internal","Public Key Interface"], correct: 1 },
  { text: "Dans une signature numérique, le signataire utilise sa…", options: ["clé publique","clé privée","clé symétrique","clé wifi"], correct: 1 },
  { text: "Le destinataire vérifie une signature numérique avec la…", options: ["clé privée du signataire","clé publique du signataire","clé publique du destinataire","clé partagée"], correct: 1 },
  { text: "Quel rôle joue une fonction de hachage (hash) ?", options: ["Compresser le fichier","Produire une empreinte unique du document","Chiffrer le fichier","Convertir en PDF"], correct: 1 },
  { text: "Lequel est un algorithme de hachage cryptographique ?", options: ["AES","RSA","SHA-256","JPEG"], correct: 2 },
  { text: "Lequel est un algorithme de signature à clé publique ?", options: ["RSA","AES","MD5","JPEG"], correct: 0 },
  { text: "Quel algorithme est utilisé pour la signature à courbes elliptiques ?", options: ["AES-256","ECDSA","HMAC","Triple DES"], correct: 1 },
  { text: "Qu'est-ce qu'un certificat numérique X.509 contient toujours ?", options: ["La clé publique et l'identité","La clé privée","Le mot de passe","L'IP du serveur"], correct: 0 },
  { text: "Qui délivre un certificat numérique ?", options: ["L'utilisateur","Une autorité de certification (AC)","Le navigateur","Microsoft Office"], correct: 1 },
  { text: "Que garantit un horodatage qualifié ?", options: ["L'identité du signataire","La date/heure du document scellé","Le contenu","Le chiffrement"], correct: 1 },
  { text: "Une signature scannée image collée dans un PDF est-elle juridiquement aussi forte qu'une signature qualifiée en UE ?", options: ["Oui","Non, elle est bien plus faible","Identique","Sans différence"], correct: 1 },
  { text: "Quel principe garantit qu'un signataire ne peut pas nier avoir signé ?", options: ["Confidentialité","Intégrité","Non-répudiation","Disponibilité"], correct: 2 },
  { text: "Qu'est-ce que l'intégrité d'un document signé ?", options: ["Que le contenu n'a pas été modifié depuis la signature","Qu'il est crypté","Qu'il est imprimable","Qu'il est unique"], correct: 0 },
  { text: "Quel format de signature ETSI est dédié aux fichiers PDF ?", options: ["XAdES","CAdES","PAdES","JAdES"], correct: 2 },
  { text: "Quel format de signature ETSI s'applique au XML ?", options: ["CAdES","XAdES","PAdES","JAdES"], correct: 1 },
  { text: "Quel format de signature ETSI s'applique aux messages CMS ?", options: ["XAdES","PAdES","CAdES","JAdES"], correct: 2 },
  { text: "Que désigne le format ASiC en signature ETSI ?", options: ["Un type de hash","Un conteneur associé à une ou plusieurs signatures","Un certificat","Un algorithme"], correct: 1 },
  { text: "Quelle est la nuance signature électronique vs signature numérique ?", options: ["Aucune (synonymes)","Électronique = juridique, numérique = technique","L'inverse","Elles n'existent pas"], correct: 1 },
  { text: "Quelle preuve est typiquement conservée dans le dossier de preuve d'une signature électronique ?", options: ["Identité du signataire","Horodatage","Hash du document","Toutes ces réponses"], correct: 3 },
  { text: "Une signature électronique a pour but de remplacer…", options: ["une signature manuscrite","un sceau d'entreprise","un timbre fiscal","un cachet notarial"], correct: 0 },
  { text: "Le scellement d'un document signé empêche…", options: ["L'envoi par email","Toute modification post-signature","L'impression","La sauvegarde"], correct: 1 },
  { text: "Une signature « à la volée » (one-shot) délivre un certificat…", options: ["à usage unique pour la session","permanent valable 10 ans","stocké chez l'utilisateur","sans autorité"], correct: 0 },
  { text: "Quelle technologie d'identification renforce souvent la signature qualifiée à distance ?", options: ["Vérification vidéo + pièce d'identité (KYC)","Empreinte tactile","Reconnaissance d'écriture","Mot de passe simple"], correct: 0 },
  { text: "Quel acronyme désigne la procédure de vérification d'identité du client ?", options: ["CRM","KYC","CSRF","HTTP"], correct: 1 },
  { text: "Quel acronyme désigne un module matériel de sécurité ?", options: ["HSM","SSD","RAM","RAID"], correct: 0 },
  { text: "Que signifie HSM ?", options: ["Hash Security Module","Hardware Security Module","High Speed Memory","Hosted Service Manager"], correct: 1 },
  { text: "Quelle propriété un hash cryptographique doit-il avoir ?", options: ["Réversible facilement","Résistant aux collisions","Compressible","Lisible par humain"], correct: 1 },
  { text: "Lequel est aujourd'hui considéré obsolète pour la signature ?", options: ["SHA-256","SHA-3","SHA-1","SHA-512"], correct: 2 },
  { text: "Quel élément lie un certificat à une personne physique ?", options: ["Le mot de passe","Le DN (Distinguished Name) et le KYC","L'adresse IP","La taille du fichier"], correct: 1 },

  // ---------- eIDAS et Union européenne (61-90) ----------
  { text: "Le règlement européen sur la signature électronique se nomme…", options: ["GDPR","eIDAS","RGPD","PSD2"], correct: 1 },
  { text: "Quel est le numéro officiel du règlement eIDAS (eIDAS 1) ?", options: ["2014/123/UE","910/2014","910/2016","679/2016"], correct: 1 },
  { text: "En quelle année le règlement eIDAS a-t-il été adopté ?", options: ["2012","2014","2016","2018"], correct: 1 },
  { text: "À partir de quelle date la partie signature d'eIDAS s'applique-t-elle ?", options: ["Janvier 2014","Mai 2016","Juillet 2016","Mai 2018"], correct: 2 },
  { text: "eIDAS définit combien de niveaux de signature électronique ?", options: ["2","3","4","5"], correct: 1 },
  { text: "Quel est le niveau le plus faible défini par eIDAS ?", options: ["Simple (SES)","Avancée","Qualifiée","Authentique"], correct: 0 },
  { text: "Quel niveau eIDAS garantit l'identification unique du signataire et la détection des modifications ?", options: ["Simple","Avancée (AES/AdES)","Qualifiée","Aucun"], correct: 1 },
  { text: "Quel niveau eIDAS a la même valeur juridique qu'une signature manuscrite dans toute l'UE ?", options: ["Simple","Avancée","Qualifiée (QES)","Notariale"], correct: 2 },
  { text: "Quel article d'eIDAS pose l'équivalence QES ↔ signature manuscrite ?", options: ["Art. 13","Art. 21","Art. 25","Art. 41"], correct: 2 },
  { text: "Que désigne l'acronyme QTSP en eIDAS ?", options: ["Quick Transfer Service Provider","Qualified Trust Service Provider","Quality Tested Software Patent","Quoted Trading Server Protocol"], correct: 1 },
  { text: "Qu'est-ce qu'un TSP au sens d'eIDAS ?", options: ["Tax Service Plan","Trust Service Provider","Total Storage Pack","Time Series Provider"], correct: 1 },
  { text: "Qu'est-ce qu'une Trusted List (TSL) en eIDAS ?", options: ["La liste publique des QTSP par État","La liste des clients","La liste noire","La liste blanche IP"], correct: 0 },
  { text: "Qui audite et qualifie les QTSP en France ?", options: ["L'ANSSI","La CNIL","L'AMF","Bercy"], correct: 0 },
  { text: "Quel sigle désigne l'agence française de cybersécurité ?", options: ["CNIL","ANSSI","INPI","ARCEP"], correct: 1 },
  { text: "Où peut-on consulter la liste de confiance européenne agrégée (LOTL) ?", options: ["Sur Google","Sur le site de la Commission européenne","Sur Wikipédia","Sur LinkedIn"], correct: 1 },
  { text: "Quelle organisation publie les normes PAdES, XAdES, CAdES… ?", options: ["ITU","ETSI","IETF","IEEE"], correct: 1 },
  { text: "Combien d'États membres de l'UE eIDAS couvre-t-il ?", options: ["15","27","40","195"], correct: 1 },
  { text: "Le règlement eIDAS s'applique-t-il aussi en Norvège, Islande, Liechtenstein (EEE) ?", options: ["Non","Oui","Seulement Norvège","Seulement Liechtenstein"], correct: 1 },
  { text: "eIDAS 2 (révision adoptée en 2024) introduit principalement…", options: ["une crypto monnaie EU","le portefeuille européen d'identité numérique (EUDI Wallet)","une TVA digitale","un visa électronique"], correct: 1 },
  { text: "Quel acronyme désigne le portefeuille européen d'identité numérique ?", options: ["CIE Wallet","EUDI Wallet","EU-ID","eIDpass"], correct: 1 },
  { text: "Quel est le numéro du règlement eIDAS 2 ?", options: ["910/2014","679/2016","2024/1183","2022/2065"], correct: 2 },
  { text: "Échéance prévue pour la mise à disposition de l'EUDI Wallet par les États membres ?", options: ["2025","2026-2027","2030","2040"], correct: 1 },
  { text: "Un QTSP fournit obligatoirement…", options: ["des services de confiance qualifiés","des comptes bancaires","du cloud","de la 5G"], correct: 0 },
  { text: "Le certificat qualifié de signature électronique est délivré à…", options: ["une organisation uniquement","une personne physique","un objet IoT","un domaine"], correct: 1 },
  { text: "Le cachet électronique qualifié (qualified e-seal) est lié à…", options: ["une personne physique","une personne morale","un État","un objet"], correct: 1 },
  { text: "Quel dispositif matériel est souvent requis pour générer une signature qualifiée ?", options: ["Clé USB ordinaire","HSM ou carte à puce qualifiée","Disque dur externe","Webcam HD"], correct: 1 },
  { text: "Une signature avancée nécessite-t-elle systématiquement un certificat qualifié ?", options: ["Oui","Non (le qualifié est exigé pour la QES)","Seulement en France","Seulement aux Pays-Bas"], correct: 1 },
  { text: "Quelle directive européenne sur la signature électronique précédait eIDAS ?", options: ["1999/93/CE","95/46/CE","2000/31/CE","2002/58/CE"], correct: 0 },
  { text: "Quel pays européen est pionnier en eID (cartes ID depuis 2002, vote électronique en 2005) ?", options: ["France","Estonie","Espagne","Portugal"], correct: 1 },
  { text: "Quel système italien d'identité numérique est largement utilisé ?", options: ["SPID","FranceConnect+","BankID","MyKad"], correct: 0 },

  // ---------- Cadre juridique France / UE et cas d'usage (91-110) ----------
  { text: "Quel article du Code civil français pose l'équivalence écrit électronique / écrit papier ?", options: ["Art. 1109","Art. 1240","Art. 1366","Art. 1382"], correct: 2 },
  { text: "Quel article du Code civil définit la signature électronique ?", options: ["1366","1367","1368","1369"], correct: 1 },
  { text: "Peut-on signer un testament olographe par signature électronique en France ?", options: ["Oui","Non, il doit être entièrement manuscrit","Seulement qualifiée","Seulement à l'étranger"], correct: 1 },
  { text: "Un acte authentique notarié peut-il être signé électroniquement en France ?", options: ["Jamais","Oui via l'acte authentique électronique (AAE)","Seulement à l'étranger","Seulement entre notaires"], correct: 1 },
  { text: "Un contrat de travail en France peut-il être signé électroniquement ?", options: ["Non","Oui","Seulement CDI","Seulement par signature qualifiée"], correct: 1 },
  { text: "Le RGPD s'applique-t-il aux données collectées lors d'une signature électronique ?", options: ["Non","Oui","Seulement si stockées hors UE","Seulement aux QTSP"], correct: 1 },
  { text: "En cas de litige, à qui revient la charge de démontrer la fiabilité d'une signature non qualifiée ?", options: ["À celui qui s'en prévaut","Au juge","Au QTSP","À personne, c'est automatique"], correct: 0 },
  { text: "La signature qualifiée bénéficie d'une présomption de…", options: ["méfiance","fiabilité","falsification","nullité"], correct: 1 },
  { text: "Quel système d'authentification eID belge est très utilisé pour signer ?", options: ["eID belge / itsme","FranceConnect+","BankID","MyKad"], correct: 0 },
  { text: "En France, FranceConnect+ permet de…", options: ["s'authentifier au niveau substantiel/élevé pour des démarches","payer ses impôts","acheter en ligne","voter électroniquement"], correct: 0 },
  { text: "Lequel n'est PAS un cas d'usage typique d'eSignature ?", options: ["Contrat fournisseur","Bail d'habitation","Mariage civil en mairie","NDA"], correct: 2 },
  { text: "Le Code monétaire et financier autorise la signature électronique pour…", options: ["aucune opération bancaire","de nombreux contrats bancaires","uniquement les comptes pro","uniquement le crédit immobilier"], correct: 1 },
  { text: "La directive PSD2 et eIDAS se rejoignent surtout sur…", options: ["le RGPD","l'authentification forte (SCA / 2FA)","la carte d'identité","le minage"], correct: 1 },
  { text: "Lequel n'est PAS un facteur d'authentification forte (SCA) ?", options: ["Quelque chose que je sais","Quelque chose que je possède","Quelque chose que je suis","Quelque chose que j'aime"], correct: 3 },
  { text: "Le standard OpenPGP de courriels signés est-il « qualifié » au sens eIDAS ?", options: ["Oui","Non, il n'est pas qualifié au sens eIDAS","Si, depuis 2020","Seulement avec Outlook"], correct: 1 },
  { text: "Quel terme désigne le procès-verbal consolidé des preuves d'une signature ?", options: ["Hash","Dossier de preuve / Audit Trail","Sceau","Certificat racine"], correct: 1 },
  { text: "Un Audit Trail DocuSign contient typiquement…", options: ["identité, horodatages, IP, événements","le PIN du signataire","le mot de passe email","aucune information"], correct: 0 },
  { text: "Quel niveau eIDAS est généralement suffisant pour un NDA standard B2B ?", options: ["Pas de signature","Simple ou avancée","Toujours qualifiée","Notariale uniquement"], correct: 1 },
  { text: "La signature électronique DocuSign de base correspond généralement à quel niveau eIDAS ?", options: ["Simple (SES)","Avancée (AES)","Qualifiée (QES)","Hors eIDAS"], correct: 0 },
  { text: "Lequel n'est PAS un QTSP européen connu ?", options: ["Microsoft Excel","Universign (Oodrive)","InfoCert","Buypass"], correct: 0 },
];
