// QuizzMaster — thème 🇫🇷 France. 300 questions.

module.exports = [
  { text: "Quelle est la capitale de la France ?", options: ["Lyon","Paris","Marseille","Nice"], correct: 1 },
  { text: "Quel est le plus long fleuve de France ?", options: ["La Seine","La Loire","Le Rhône","La Garonne"], correct: 1 },
  { text: "Quelle est la plus haute montagne de France ?", options: ["Mont Aiguille","Pic du Midi","Mont Blanc","Mont Ventoux"], correct: 2 },
  { text: "Combien de régions compte la France métropolitaine depuis 2016 ?", options: ["12","13","14","22"], correct: 1 },
  { text: "Quel fleuve traverse Paris ?", options: ["La Loire","La Marne","La Seine","L'Oise"], correct: 2 },
  { text: "Quelle rivière rejoint le Rhône à Lyon ?", options: ["La Saône","La Loire","Le Doubs","L'Ain"], correct: 0 },
  { text: "Quel massif sépare la France de l'Espagne ?", options: ["Les Alpes","Le Jura","Les Pyrénées","Les Vosges"], correct: 2 },
  { text: "Quelle île française est en Méditerranée ?", options: ["Ré","Oléron","Corse","Belle-Île"], correct: 2 },
  { text: "Quelle mer borde Nice ?", options: ["Atlantique","Manche","Méditerranée","Mer du Nord"], correct: 2 },
  { text: "Quel océan borde Biarritz ?", options: ["Méditerranée","Atlantique","Indien","Pacifique"], correct: 1 },
  { text: "Quel détroit sépare la France de l'Angleterre ?", options: ["Gibraltar","Pas-de-Calais","Bering","Ormuz"], correct: 1 },
  { text: "Quelle est la deuxième ville de France par population ?", options: ["Lyon","Marseille","Toulouse","Nice"], correct: 1 },
  { text: "Quel volcan d'Auvergne est le plus célèbre ?", options: ["Puy Mary","Puy de Dôme","Cantal","Mont-Dore"], correct: 1 },
  { text: "Quelle ville est surnommée la Venise des Alpes ?", options: ["Chambéry","Annecy","Grenoble","Gap"], correct: 1 },
  { text: "Quelle chaîne de montagnes borde l'Alsace ?", options: ["Les Alpes","Le Jura","Les Vosges","Le Massif central"], correct: 2 },
  { text: "Quel est le plus grand lac naturel de France ?", options: ["Lac d'Annecy","Lac du Bourget","Lac Léman (côté français)","Serre-Ponçon"], correct: 1 },
  { text: "En quelle année a eu lieu la prise de la Bastille ?", options: ["1789","1792","1799","1804"], correct: 0 },
  { text: "Qui était le Roi-Soleil ?", options: ["Louis XIII","Louis XIV","Louis XV","Henri IV"], correct: 1 },
  { text: "Qui a été sacré empereur des Français en 1804 ?", options: ["Louis XVIII","Napoléon Bonaparte","Charles X","Louis-Philippe"], correct: 1 },
  { text: "Quelle bataille marque la chute de Napoléon en 1815 ?", options: ["Austerlitz","Waterloo","Iéna","Wagram"], correct: 1 },
  { text: "Quel roi a signé l'édit de Nantes en 1598 ?", options: ["François Ier","Henri IV","Louis XIII","Charles IX"], correct: 1 },
  { text: "Qui a appelé à résister depuis Londres en 1940 ?", options: ["Pétain","De Gaulle","Leclerc","Jean Moulin"], correct: 1 },
  { text: "En quelle année a eu lieu le débarquement de Normandie ?", options: ["1943","1944","1945","1942"], correct: 1 },
  { text: "Quelle reine a été guillotinée en 1793 ?", options: ["Catherine de Médicis","Marie-Antoinette","Anne d'Autriche","Marie de Médicis"], correct: 1 },
  { text: "Quel roi franc s'est converti au christianisme ?", options: ["Charlemagne","Clovis","Dagobert","Charles Martel"], correct: 1 },
  { text: "Quel empereur a été couronné en l'an 800 ?", options: ["Clovis","Charlemagne","Hugues Capet","Charles le Chauve"], correct: 1 },
  { text: "En quelle année François Ier a-t-il gagné Marignan ?", options: ["1515","1453","1610","1492"], correct: 0 },
  { text: "Quel cardinal était ministre de Louis XIII ?", options: ["Mazarin","Richelieu","Fleury","Dubois"], correct: 1 },
  { text: "Quelle République a été proclamée en 1958 ?", options: ["IIIe","IVe","Ve","IIe"], correct: 2 },
  { text: "En quelle année les Françaises ont-elles voté pour la première fois ?", options: ["1936","1944","1946","1924"], correct: 1 },
  { text: "Qui fut le premier président de la Ve République ?", options: ["Vincent Auriol","Charles de Gaulle","René Coty","Georges Pompidou"], correct: 1 },
  { text: "Combien d'années dure le mandat présidentiel depuis 2002 ?", options: ["4","5","6","7"], correct: 1 },
  { text: "Quel président a précédé Emmanuel Macron ?", options: ["Nicolas Sarkozy","François Hollande","Jacques Chirac","Alain Juppé"], correct: 1 },
  { text: "Où réside le président de la République ?", options: ["Matignon","Palais de l'Élysée","Palais Bourbon","Luxembourg"], correct: 1 },
  { text: "Où siège l'Assemblée nationale ?", options: ["Luxembourg","Palais Bourbon","Élysée","Matignon"], correct: 1 },
  { text: "Où siège le Sénat ?", options: ["Palais Bourbon","Palais du Luxembourg","Matignon","Palais-Royal"], correct: 1 },
  { text: "Combien de députés à l'Assemblée nationale ?", options: ["348","400","577","925"], correct: 2 },
  { text: "Qui réside à l'hôtel Matignon ?", options: ["Le président","Le Premier ministre","Le président du Sénat","Le maire de Paris"], correct: 1 },
  { text: "Quelle est la devise de la République française ?", options: ["Liberté, Égalité, Fraternité","Travail, Famille, Patrie","Unité, Force, Paix","Honneur et Patrie"], correct: 0 },
  { text: "Quel est l'hymne national français ?", options: ["Le Chant du départ","La Marseillaise","La Marche d'Henri IV","L'Internationale"], correct: 1 },
  { text: "Quelle est la fête nationale française ?", options: ["1er mai","8 mai","14 juillet","11 novembre"], correct: 2 },
  { text: "Combien de sénateurs siègent au Sénat ?", options: ["348","400","577","500"], correct: 0 },
  { text: "Qui a écrit Les Misérables ?", options: ["Émile Zola","Victor Hugo","Balzac","Flaubert"], correct: 1 },
  { text: "Qui a écrit Le Petit Prince ?", options: ["Camus","Saint-Exupéry","Gide","Malraux"], correct: 1 },
  { text: "Qui a écrit Madame Bovary ?", options: ["Flaubert","Stendhal","Maupassant","Zola"], correct: 0 },
  { text: "Qui a écrit À la recherche du temps perdu ?", options: ["Proust","Gide","Valéry","Aragon"], correct: 0 },
  { text: "Qui a écrit Germinal ?", options: ["Hugo","Zola","Balzac","Daudet"], correct: 1 },
  { text: "Qui a écrit Le Comte de Monte-Cristo ?", options: ["Jules Verne","Alexandre Dumas","Victor Hugo","Stendhal"], correct: 1 },
  { text: "Qui a écrit L'Étranger ?", options: ["Sartre","Camus","Malraux","Céline"], correct: 1 },
  { text: "Qui a écrit Cyrano de Bergerac ?", options: ["Molière","Edmond Rostand","Corneille","Racine"], correct: 1 },
  { text: "Qui a écrit Le Misanthrope ?", options: ["Racine","Molière","Corneille","Beaumarchais"], correct: 1 },
  { text: "Qui a écrit Vingt Mille Lieues sous les mers ?", options: ["Jules Verne","Alexandre Dumas","H.G. Wells","Maupassant"], correct: 0 },
  { text: "Qui a écrit Les Fleurs du mal ?", options: ["Rimbaud","Baudelaire","Verlaine","Mallarmé"], correct: 1 },
  { text: "Qui a écrit Le Rouge et le Noir ?", options: ["Stendhal","Balzac","Flaubert","Zola"], correct: 0 },
  { text: "Qui a écrit Candide ?", options: ["Rousseau","Voltaire","Diderot","Montesquieu"], correct: 1 },
  { text: "Qui a écrit Le Deuxième Sexe ?", options: ["George Sand","Simone de Beauvoir","Colette","Marguerite Duras"], correct: 1 },
  { text: "Qui a peint La Liberté guidant le peuple ?", options: ["Delacroix","Géricault","David","Ingres"], correct: 0 },
  { text: "Quel peintre est associé aux Nymphéas ?", options: ["Manet","Monet","Renoir","Degas"], correct: 1 },
  { text: "Quel mouvement est né en France fin XIXe siècle ?", options: ["Cubisme","Impressionnisme","Surréalisme","Romantisme"], correct: 1 },
  { text: "Qui a sculpté Le Penseur ?", options: ["Rodin","Camille Claudel","Maillol","Bourdelle"], correct: 0 },
  { text: "Qui a peint Le Radeau de la Méduse ?", options: ["Delacroix","Géricault","David","Courbet"], correct: 1 },
  { text: "Quel musée parisien expose la Joconde ?", options: ["Orsay","Le Louvre","Pompidou","Grand Palais"], correct: 1 },
  { text: "Quel musée parisien est dédié à l'impressionnisme ?", options: ["Le Louvre","Le musée d'Orsay","Pompidou","Musée Rodin"], correct: 1 },
  { text: "Quel festival de cinéma a lieu sur la Croisette ?", options: ["Venise","Cannes","Berlin","Deauville"], correct: 1 },
  { text: "Qui a réalisé Le Fabuleux Destin d'Amélie Poulain ?", options: ["Besson","Jeunet","Kassovitz","Audiard"], correct: 1 },
  { text: "Quelle récompense du cinéma français est annuelle ?", options: ["L'Oscar","Le César","Le Lion d'or","La Palme"], correct: 1 },
  { text: "Qui a chanté La Vie en rose ?", options: ["Dalida","Édith Piaf","Mireille Mathieu","Barbara"], correct: 1 },
  { text: "Quel groupe électro français a sorti Discovery ?", options: ["Justice","Daft Punk","Air","Phoenix"], correct: 1 },
  { text: "Qui a chanté Aux Champs-Élysées ?", options: ["Claude François","Joe Dassin","Sardou","Polnareff"], correct: 1 },
  { text: "Qui a découvert le vaccin contre la rage ?", options: ["Pasteur","Curie","Lavoisier","Pascal"], correct: 0 },
  { text: "Quelle scientifique a eu deux prix Nobel ?", options: ["Marie Curie","Rosalind Franklin","Ada Lovelace","Irène Joliot-Curie"], correct: 0 },
  { text: "Qui est le père de la chimie moderne ?", options: ["Pasteur","Lavoisier","Berthelot","Curie"], correct: 1 },
  { text: "Quels frères ont inventé le cinématographe ?", options: ["Montgolfier","Lumière","Wright","Goncourt"], correct: 1 },
  { text: "Qui a inventé la montgolfière ?", options: ["Les frères Lumière","Les frères Montgolfier","Clément Ader","Blériot"], correct: 1 },
  { text: "Qui a traversé la Manche en avion en 1909 ?", options: ["Mermoz","Blériot","Saint-Exupéry","Guynemer"], correct: 1 },
  { text: "Qui a formulé « Je pense donc je suis » ?", options: ["Descartes","Pascal","Voltaire","Rousseau"], correct: 0 },
  { text: "Quelle équipe a gagné la Coupe du monde 1998 ?", options: ["Brésil","France","Italie","Allemagne"], correct: 1 },
  { text: "En quelle année la France a-t-elle gagné sa 2e Coupe du monde ?", options: ["2014","2016","2018","2022"], correct: 2 },
  { text: "Quel tournoi du Grand Chelem se joue à Paris ?", options: ["Wimbledon","Roland-Garros","US Open","Open d'Australie"], correct: 1 },
  { text: "Quelle surface à Roland-Garros ?", options: ["Gazon","Terre battue","Dur","Moquette"], correct: 1 },
  { text: "Quel club a gagné la Ligue des champions 1993 ?", options: ["PSG","Olympique de Marseille","Monaco","Saint-Étienne"], correct: 1 },
  { text: "Combien de joueurs au rugby à XV sur le terrain ?", options: ["11","13","15","18"], correct: 2 },
  { text: "Quelle marque produit la Twingo ?", options: ["Peugeot","Renault","Citroën","DS"], correct: 1 },
  { text: "Quel groupe de luxe possède Louis Vuitton ?", options: ["Kering","LVMH","Richemont","Hermès"], correct: 1 },
  { text: "Quelle marque a le Bibendum comme mascotte ?", options: ["Continental","Michelin","Goodyear","Pirelli"], correct: 1 },
  { text: "Quel oiseau symbolise la France ?", options: ["L'aigle","Le coq","La colombe","Le faucon"], correct: 1 },
  { text: "Quel monument date de l'Exposition universelle de 1889 ?", options: ["Arc de Triomphe","Tour Eiffel","Sacré-Cœur","Opéra Garnier"], correct: 1 },
  { text: "Quelle statue offerte par la France est à New York ?", options: ["La Liberté éclairant le monde","La Pietà","Le David","La Victoire"], correct: 0 },
  { text: "De quelle région vient le cassoulet ?", options: ["Bretagne","Sud-Ouest","Alsace","Provence"], correct: 1 },
  { text: "Quel fromage est typique de Normandie ?", options: ["Roquefort","Camembert","Comté","Cantal"], correct: 1 },
  { text: "Quel plat marseillais est une soupe de poisson ?", options: ["Cassoulet","Bouillabaisse","Choucroute","Aligot"], correct: 1 },
  { text: "La choucroute vient de quelle région ?", options: ["Bretagne","Alsace","Provence","Normandie"], correct: 1 },
  { text: "Quel vin rouge primeur se boit en novembre ?", options: ["Bordeaux","Beaujolais","Sancerre","Chinon"], correct: 1 },
  { text: "Quelle ville est la capitale gastronomique selon la tradition ?", options: ["Paris","Lyon","Bordeaux","Dijon"], correct: 1 },
  { text: "Combien de lettres dans l'alphabet français ?", options: ["24","25","26","28"], correct: 2 },
  { text: "Que signifie « poser un lapin » ?", options: ["Faire un cadeau","Ne pas venir au rendez-vous","Mentir","Surprendre"], correct: 1 },
  { text: "Que signifie « avoir le cafard » ?", options: ["Être chanceux","Être déprimé","Être pressé","Avoir faim"], correct: 1 },
  { text: "Quelle est la monnaie de la France depuis 2002 ?", options: ["Le franc","L'euro","Le centime","L'écu"], correct: 1 },
  { text: "Quel est l'indicatif téléphonique de la France ?", options: ["+44","+33","+34","+49"], correct: 1 },
  { text: "Quelle langue régionale est parlée en Bretagne ?", options: ["Le basque","Le breton","L'occitan","Le corse"], correct: 1 },
  { text: "Quelle avenue parisienne est célèbre pour ses magasins ?", options: ["Rue de Rivoli","Champs-Élysées","Bd Haussmann","Rue Saint-Honoré"], correct: 1 },
  { text: "Quel pont est le plus ancien de Paris ?", options: ["Pont Neuf","Pont des Arts","Pont Alexandre III","Pont de Bir-Hakeim"], correct: 0 },
  { text: "Quelle cathédrale parisienne a brûlé en 2019 ?", options: ["Saint-Sulpice","Notre-Dame","La Madeleine","Sacré-Cœur"], correct: 1 },
  { text: "Quel château est célèbre pour sa galerie des Glaces ?", options: ["Chambord","Versailles","Fontainebleau","Chenonceau"], correct: 1 },
  { text: "Quel château de la Loire enjambe le Cher ?", options: ["Chambord","Chenonceau","Amboise","Blois"], correct: 1 },
  { text: "Quelle ville accueille le Parlement européen côté France ?", options: ["Lyon","Strasbourg","Bordeaux","Metz"], correct: 1 },
  { text: "Quelle est la préfecture de l'Ain ?", options: ["Gap","Bourg-en-Bresse","La Rochelle","Évreux"], correct: 1 },
  { text: "Quelle est la préfecture de l'Aisne ?", options: ["La Rochelle","Laon","Évreux","Grenoble"], correct: 1 },
  { text: "Quelle est la préfecture de l'Allier ?", options: ["Évreux","Moulins","Grenoble","Angers"], correct: 1 },
  { text: "Quelle est la préfecture de les Alpes-Maritimes ?", options: ["Grenoble","Nice","Angers","Beauvais"], correct: 1 },
  { text: "Quelle est la préfecture de les Hautes-Alpes ?", options: ["Angers","Gap","Beauvais","Mâcon"], correct: 1 },
  { text: "Quelle est la préfecture de l'Ardèche ?", options: ["Beauvais","Privas","Mâcon","Toulon"], correct: 1 },
  { text: "Quelle est la préfecture de les Ardennes ?", options: ["Mâcon","Charleville-Mézières","Toulon","Bourg-en-Bresse"], correct: 1 },
  { text: "Quelle est la préfecture de l'Ariège ?", options: ["Toulon","Foix","Bourg-en-Bresse","Marseille"], correct: 1 },
  { text: "Quelle est la préfecture de l'Aube ?", options: ["Bourg-en-Bresse","Troyes","Marseille","Guéret"], correct: 1 },
  { text: "Quelle est la préfecture de l'Aude ?", options: ["Marseille","Carcassonne","Guéret","Montpellier"], correct: 1 },
  { text: "Quelle est la préfecture de l'Aveyron ?", options: ["Guéret","Rodez","Montpellier","Orléans"], correct: 1 },
  { text: "Quelle est la préfecture de les Bouches-du-Rhône ?", options: ["Montpellier","Marseille","Orléans","Vannes"], correct: 1 },
  { text: "Quelle est la préfecture de le Calvados ?", options: ["Orléans","Caen","Vannes","Strasbourg"], correct: 1 },
  { text: "Quelle est la préfecture de le Cantal ?", options: ["Vannes","Aurillac","Strasbourg","Niort"], correct: 1 },
  { text: "Quelle est la préfecture de la Charente ?", options: ["Strasbourg","Angoulême","Niort","Belfort"], correct: 1 },
  { text: "Quelle est la préfecture de la Charente-Maritime ?", options: ["Niort","La Rochelle","Belfort","Foix"], correct: 1 },
  { text: "Quelle est la préfecture de le Cher ?", options: ["Belfort","Bourges","Foix","Ajaccio"], correct: 1 },
  { text: "Quelle est la préfecture de la Corrèze ?", options: ["Foix","Tulle","Ajaccio","Nîmes"], correct: 1 },
  { text: "Quelle est la préfecture de la Corse-du-Sud ?", options: ["Nîmes","Ajaccio","Blois","Chaumont"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Corse ?", options: ["Nîmes","Bastia","Blois","Chaumont"], correct: 1 },
  { text: "Quelle est la préfecture de la Côte-d'Or ?", options: ["Blois","Dijon","Chaumont","Clermont-Ferrand"], correct: 1 },
  { text: "Quelle est la préfecture de les Côtes-d'Armor ?", options: ["Chaumont","Saint-Brieuc","Clermont-Ferrand","Annecy"], correct: 1 },
  { text: "Quelle est la préfecture de la Creuse ?", options: ["Clermont-Ferrand","Guéret","Annecy","Poitiers"], correct: 1 },
  { text: "Quelle est la préfecture de la Dordogne ?", options: ["Annecy","Périgueux","Poitiers","Nice"], correct: 1 },
  { text: "Quelle est la préfecture de le Doubs ?", options: ["Poitiers","Besançon","Nice","Angoulême"], correct: 1 },
  { text: "Quelle est la préfecture de la Drôme ?", options: ["Nice","Valence","Angoulême","Tours"], correct: 1 },
  { text: "Quelle est la préfecture de l'Eure ?", options: ["Angoulême","Évreux","Valence","Tours"], correct: 1 },
  { text: "Quelle est la préfecture de l'Eure-et-Loir ?", options: ["Valence","Chartres","Tours","Mende"], correct: 1 },
  { text: "Quelle est la préfecture de le Finistère ?", options: ["Tours","Quimper","Mende","Lille"], correct: 1 },
  { text: "Quelle est la préfecture de le Gard ?", options: ["Mende","Nîmes","Lille","Vesoul"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Garonne ?", options: ["Lille","Toulouse","Vesoul","Montauban"], correct: 1 },
  { text: "Quelle est la préfecture de le Gers ?", options: ["Vesoul","Auch","Montauban","Créteil"], correct: 1 },
  { text: "Quelle est la préfecture de la Gironde ?", options: ["Montauban","Bordeaux","Créteil","Rodez"], correct: 1 },
  { text: "Quelle est la préfecture de l'Hérault ?", options: ["Créteil","Montpellier","Rodez","Saint-Brieuc"], correct: 1 },
  { text: "Quelle est la préfecture de l'Ille-et-Vilaine ?", options: ["Rodez","Rennes","Saint-Brieuc","Bordeaux"], correct: 1 },
  { text: "Quelle est la préfecture de l'Indre ?", options: ["Saint-Brieuc","Châteauroux","Bordeaux","Nantes"], correct: 1 },
  { text: "Quelle est la préfecture de l'Indre-et-Loire ?", options: ["Bordeaux","Tours","Nantes","Bar-le-Duc"], correct: 1 },
  { text: "Quelle est la préfecture de l'Isère ?", options: ["Nantes","Grenoble","Bar-le-Duc","Perpignan"], correct: 1 },
  { text: "Quelle est la préfecture de le Jura ?", options: ["Bar-le-Duc","Lons-le-Saunier","Perpignan","Versailles"], correct: 1 },
  { text: "Quelle est la préfecture de les Landes ?", options: ["Perpignan","Mont-de-Marsan","Versailles","Auxerre"], correct: 1 },
  { text: "Quelle est la préfecture de le Loir-et-Cher ?", options: ["Versailles","Blois","Auxerre","Charleville-Mézières"], correct: 1 },
  { text: "Quelle est la préfecture de la Loire ?", options: ["Auxerre","Saint-Étienne","Charleville-Mézières","Tulle"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Loire ?", options: ["Charleville-Mézières","Le Puy-en-Velay","Tulle","Quimper"], correct: 1 },
  { text: "Quelle est la préfecture de la Loire-Atlantique ?", options: ["Tulle","Nantes","Quimper","Mont-de-Marsan"], correct: 1 },
  { text: "Quelle est la préfecture de le Loiret ?", options: ["Quimper","Orléans","Mont-de-Marsan","Châlons-en-Champagne"], correct: 1 },
  { text: "Quelle est la préfecture de le Lot ?", options: ["Mont-de-Marsan","Cahors","Châlons-en-Champagne","Arras"], correct: 1 },
  { text: "Quelle est la préfecture de le Lot-et-Garonne ?", options: ["Châlons-en-Champagne","Agen","Arras","Chambéry"], correct: 1 },
  { text: "Quelle est la préfecture de la Lozère ?", options: ["Arras","Mende","Chambéry","La Roche-sur-Yon"], correct: 1 },
  { text: "Quelle est la préfecture de le Maine-et-Loire ?", options: ["Chambéry","Angers","La Roche-sur-Yon","Moulins"], correct: 1 },
  { text: "Quelle est la préfecture de la Manche ?", options: ["La Roche-sur-Yon","Saint-Lô","Moulins","Aurillac"], correct: 1 },
  { text: "Quelle est la préfecture de la Marne ?", options: ["Moulins","Châlons-en-Champagne","Aurillac","Besançon"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Marne ?", options: ["Aurillac","Chaumont","Besançon","Châteauroux"], correct: 1 },
  { text: "Quelle est la préfecture de la Mayenne ?", options: ["Besançon","Laval","Châteauroux","Agen"], correct: 1 },
  { text: "Quelle est la préfecture de la Meurthe-et-Moselle ?", options: ["Châteauroux","Nancy","Agen","Nevers"], correct: 1 },
  { text: "Quelle est la préfecture de la Meuse ?", options: ["Agen","Bar-le-Duc","Nevers","Lyon"], correct: 1 },
  { text: "Quelle est la préfecture de le Morbihan ?", options: ["Nevers","Vannes","Lyon","Albi"], correct: 1 },
  { text: "Quelle est la préfecture de la Moselle ?", options: ["Lyon","Metz","Albi","Bobigny"], correct: 1 },
  { text: "Quelle est la préfecture de la Nièvre ?", options: ["Albi","Nevers","Bobigny","Carcassonne"], correct: 1 },
  { text: "Quelle est la préfecture de le Nord ?", options: ["Bobigny","Lille","Carcassonne","Dijon"], correct: 1 },
  { text: "Quelle est la préfecture de l'Oise ?", options: ["Carcassonne","Beauvais","Dijon","Auch"], correct: 1 },
  { text: "Quelle est la préfecture de l'Orne ?", options: ["Dijon","Alençon","Auch","Le Puy-en-Velay"], correct: 1 },
  { text: "Quelle est la préfecture de le Pas-de-Calais ?", options: ["Auch","Arras","Le Puy-en-Velay","Nancy"], correct: 1 },
  { text: "Quelle est la préfecture de le Puy-de-Dôme ?", options: ["Le Puy-en-Velay","Clermont-Ferrand","Nancy","Tarbes"], correct: 1 },
  { text: "Quelle est la préfecture de les Pyrénées-Atlantiques ?", options: ["Nancy","Pau","Tarbes","Melun"], correct: 1 },
  { text: "Quelle est la préfecture de les Hautes-Pyrénées ?", options: ["Melun","Tarbes","Épinal","Privas"], correct: 1 },
  { text: "Quelle est la préfecture de les Pyrénées-Orientales ?", options: ["Melun","Perpignan","Épinal","Privas"], correct: 1 },
  { text: "Quelle est la préfecture de le Bas-Rhin ?", options: ["Épinal","Strasbourg","Privas","Bourges"], correct: 1 },
  { text: "Quelle est la préfecture de le Haut-Rhin ?", options: ["Privas","Colmar","Bourges","Chartres"], correct: 1 },
  { text: "Quelle est la préfecture de le Rhône ?", options: ["Bourges","Lyon","Chartres","Lons-le-Saunier"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Saône ?", options: ["Chartres","Vesoul","Lons-le-Saunier","Saint-Lô"], correct: 1 },
  { text: "Quelle est la préfecture de la Saône-et-Loire ?", options: ["Lons-le-Saunier","Mâcon","Saint-Lô","Alençon"], correct: 1 },
  { text: "Quelle est la préfecture de la Sarthe ?", options: ["Saint-Lô","Le Mans","Alençon","Avignon"], correct: 1 },
  { text: "Quelle est la préfecture de la Savoie ?", options: ["Alençon","Chambéry","Le Mans","Avignon"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Savoie ?", options: ["Le Mans","Annecy","Avignon","Laon"], correct: 1 },
  { text: "Quelle est la préfecture de la Seine-Maritime ?", options: ["Avignon","Rouen","Laon","Caen"], correct: 1 },
  { text: "Quelle est la préfecture de la Seine-et-Marne ?", options: ["Laon","Melun","Caen","Périgueux"], correct: 1 },
  { text: "Quelle est la préfecture de les Yvelines ?", options: ["Caen","Versailles","Périgueux","Rennes"], correct: 1 },
  { text: "Quelle est la préfecture de les Deux-Sèvres ?", options: ["Périgueux","Niort","Rennes","Cahors"], correct: 1 },
  { text: "Quelle est la préfecture de la Somme ?", options: ["Rennes","Amiens","Cahors","Metz"], correct: 1 },
  { text: "Quelle est la préfecture de le Tarn ?", options: ["Cahors","Albi","Metz","Colmar"], correct: 1 },
  { text: "Quelle est la préfecture de le Tarn-et-Garonne ?", options: ["Metz","Montauban","Colmar","Amiens"], correct: 1 },
  { text: "Quelle est la préfecture de le Var ?", options: ["Colmar","Toulon","Amiens","Nanterre"], correct: 1 },
  { text: "Quelle est la préfecture de le Vaucluse ?", options: ["Amiens","Avignon","Nanterre","Troyes"], correct: 1 },
  { text: "Quelle est la préfecture de la Vendée ?", options: ["Nanterre","La Roche-sur-Yon","Troyes","Bastia"], correct: 1 },
  { text: "Quelle est la préfecture de la Vienne ?", options: ["Troyes","Poitiers","Bastia","Toulouse"], correct: 1 },
  { text: "Quelle est la préfecture de la Haute-Vienne ?", options: ["Bastia","Limoges","Toulouse","Saint-Étienne"], correct: 1 },
  { text: "Quelle est la préfecture de les Vosges ?", options: ["Toulouse","Épinal","Saint-Étienne","Laval"], correct: 1 },
  { text: "Quelle est la préfecture de l'Yonne ?", options: ["Saint-Étienne","Auxerre","Laval","Pau"], correct: 1 },
  { text: "Quelle est la préfecture de le Territoire de Belfort ?", options: ["Laval","Belfort","Pau","Rouen"], correct: 1 },
  { text: "Quelle est la préfecture de les Hauts-de-Seine ?", options: ["Pau","Nanterre","Rouen","Limoges"], correct: 1 },
  { text: "Quelle est la préfecture de la Seine-Saint-Denis ?", options: ["Rouen","Bobigny","Limoges","Gap"], correct: 1 },
  { text: "Quelle est la préfecture de le Val-de-Marne ?", options: ["Limoges","Créteil","Gap","La Rochelle"], correct: 1 },
  { text: "Bourg-en-Bresse est la préfecture de quel département ?", options: ["la Sarthe","l'Ain","la Vienne","l'Ardèche"], correct: 1 },
  { text: "Laon est la préfecture de quel département ?", options: ["la Vienne","l'Aisne","l'Ardèche","la Corse-du-Sud"], correct: 1 },
  { text: "Moulins est la préfecture de quel département ?", options: ["l'Ardèche","l'Allier","la Corse-du-Sud","le Gers"], correct: 1 },
  { text: "Nice est la préfecture de quel département ?", options: ["la Corse-du-Sud","les Alpes-Maritimes","le Gers","le Loiret"], correct: 1 },
  { text: "Gap est la préfecture de quel département ?", options: ["le Gers","les Hautes-Alpes","le Loiret","la Nièvre"], correct: 1 },
  { text: "Privas est la préfecture de quel département ?", options: ["le Loiret","l'Ardèche","la Nièvre","la Saône-et-Loire"], correct: 1 },
  { text: "Charleville-Mézières est la préfecture de quel département ?", options: ["la Nièvre","les Ardennes","la Saône-et-Loire","la Vendée"], correct: 1 },
  { text: "Foix est la préfecture de quel département ?", options: ["la Saône-et-Loire","l'Ariège","la Vendée","les Hautes-Alpes"], correct: 1 },
  { text: "Troyes est la préfecture de quel département ?", options: ["la Vendée","l'Aube","les Hautes-Alpes","la Corrèze"], correct: 1 },
  { text: "Carcassonne est la préfecture de quel département ?", options: ["les Hautes-Alpes","l'Aude","la Corrèze","la Haute-Garonne"], correct: 1 },
  { text: "Rodez est la préfecture de quel département ?", options: ["la Corrèze","l'Aveyron","la Haute-Garonne","la Loire-Atlantique"], correct: 1 },
  { text: "Marseille est la préfecture de quel département ?", options: ["la Haute-Garonne","les Bouches-du-Rhône","la Loire-Atlantique","la Moselle"], correct: 1 },
  { text: "Caen est la préfecture de quel département ?", options: ["la Loire-Atlantique","le Calvados","la Moselle","la Haute-Saône"], correct: 1 },
  { text: "Aurillac est la préfecture de quel département ?", options: ["la Moselle","le Cantal","la Haute-Saône","le Vaucluse"], correct: 1 },
  { text: "Angoulême est la préfecture de quel département ?", options: ["la Haute-Saône","la Charente","le Vaucluse","les Alpes-Maritimes"], correct: 1 },
  { text: "La Rochelle est la préfecture de quel département ?", options: ["le Vaucluse","la Charente-Maritime","les Alpes-Maritimes","le Cher"], correct: 1 },
  { text: "Bourges est la préfecture de quel département ?", options: ["les Alpes-Maritimes","le Cher","le Gard","la Haute-Loire"], correct: 1 },
  { text: "Tulle est la préfecture de quel département ?", options: ["le Cher","la Corrèze","le Gard","la Haute-Loire"], correct: 1 },
  { text: "Ajaccio est la préfecture de quel département ?", options: ["le Gard","la Corse-du-Sud","la Haute-Loire","le Morbihan"], correct: 1 },
  { text: "Bastia est la préfecture de quel département ?", options: ["la Haute-Loire","la Haute-Corse","le Morbihan","le Rhône"], correct: 1 },
  { text: "Dijon est la préfecture de quel département ?", options: ["le Morbihan","la Côte-d'Or","le Rhône","le Var"], correct: 1 },
  { text: "Saint-Brieuc est la préfecture de quel département ?", options: ["le Rhône","les Côtes-d'Armor","le Var","l'Allier"], correct: 1 },
  { text: "Guéret est la préfecture de quel département ?", options: ["le Var","la Creuse","l'Allier","la Charente-Maritime"], correct: 1 },
  { text: "Périgueux est la préfecture de quel département ?", options: ["l'Allier","la Dordogne","la Charente-Maritime","le Finistère"], correct: 1 },
  { text: "Besançon est la préfecture de quel département ?", options: ["la Charente-Maritime","le Doubs","le Finistère","la Loire"], correct: 1 },
  { text: "Valence est la préfecture de quel département ?", options: ["le Finistère","la Drôme","la Loire","la Meuse"], correct: 1 },
  { text: "Évreux est la préfecture de quel département ?", options: ["la Loire","l'Eure","la Meuse","le Haut-Rhin"], correct: 1 },
  { text: "Chartres est la préfecture de quel département ?", options: ["la Meuse","l'Eure-et-Loir","le Haut-Rhin","le Tarn-et-Garonne"], correct: 1 },
  { text: "Quimper est la préfecture de quel département ?", options: ["le Haut-Rhin","le Finistère","le Tarn-et-Garonne","l'Aisne"], correct: 1 },
  { text: "Nîmes est la préfecture de quel département ?", options: ["le Tarn-et-Garonne","le Gard","l'Aisne","la Charente"], correct: 1 },
  { text: "Toulouse est la préfecture de quel département ?", options: ["l'Aisne","la Haute-Garonne","la Charente","l'Eure-et-Loir"], correct: 1 },
  { text: "Auch est la préfecture de quel département ?", options: ["la Charente","le Gers","l'Eure-et-Loir","le Loir-et-Cher"], correct: 1 },
  { text: "Bordeaux est la préfecture de quel département ?", options: ["l'Eure-et-Loir","la Gironde","le Loir-et-Cher","la Meurthe-et-Moselle"], correct: 1 },
  { text: "Montpellier est la préfecture de quel département ?", options: ["le Loir-et-Cher","l'Hérault","la Meurthe-et-Moselle","le Bas-Rhin"], correct: 1 },
  { text: "Rennes est la préfecture de quel département ?", options: ["la Meurthe-et-Moselle","l'Ille-et-Vilaine","le Bas-Rhin","le Tarn"], correct: 1 },
  { text: "Châteauroux est la préfecture de quel département ?", options: ["le Bas-Rhin","l'Indre","le Tarn","l'Ain"], correct: 1 },
  { text: "Tours est la préfecture de quel département ?", options: ["le Tarn","l'Indre-et-Loire","l'Ain","le Cantal"], correct: 1 },
  { text: "Grenoble est la préfecture de quel département ?", options: ["l'Ain","l'Isère","le Cantal","l'Eure"], correct: 1 },
  { text: "Lons-le-Saunier est la préfecture de quel département ?", options: ["le Cantal","le Jura","l'Eure","les Landes"], correct: 1 },
  { text: "Mont-de-Marsan est la préfecture de quel département ?", options: ["l'Eure","les Landes","la Mayenne","les Pyrénées-Orientales"], correct: 1 },
  { text: "Blois est la préfecture de quel département ?", options: ["les Landes","le Loir-et-Cher","la Mayenne","les Pyrénées-Orientales"], correct: 1 },
  { text: "Saint-Étienne est la préfecture de quel département ?", options: ["la Mayenne","la Loire","les Pyrénées-Orientales","la Somme"], correct: 1 },
  { text: "Le Puy-en-Velay est la préfecture de quel département ?", options: ["les Pyrénées-Orientales","la Haute-Loire","la Somme","le Val-de-Marne"], correct: 1 },
  { text: "Nantes est la préfecture de quel département ?", options: ["la Somme","la Loire-Atlantique","le Val-de-Marne","le Calvados"], correct: 1 },
  { text: "Orléans est la préfecture de quel département ?", options: ["le Val-de-Marne","le Loiret","le Calvados","la Drôme"], correct: 1 },
  { text: "Cahors est la préfecture de quel département ?", options: ["le Calvados","le Lot","la Drôme","le Jura"], correct: 1 },
  { text: "Agen est la préfecture de quel département ?", options: ["la Drôme","le Lot-et-Garonne","le Jura","la Haute-Marne"], correct: 1 },
  { text: "Mende est la préfecture de quel département ?", options: ["le Jura","la Lozère","la Haute-Marne","les Hautes-Pyrénées"], correct: 1 },
  { text: "Angers est la préfecture de quel département ?", options: ["la Haute-Marne","le Maine-et-Loire","les Hautes-Pyrénées","les Deux-Sèvres"], correct: 1 },
  { text: "Saint-Lô est la préfecture de quel département ?", options: ["les Hautes-Pyrénées","la Manche","les Deux-Sèvres","la Seine-Saint-Denis"], correct: 1 },
  { text: "Châlons-en-Champagne est la préfecture de quel département ?", options: ["les Deux-Sèvres","la Marne","la Seine-Saint-Denis","les Bouches-du-Rhône"], correct: 1 },
  { text: "Chaumont est la préfecture de quel département ?", options: ["la Seine-Saint-Denis","la Haute-Marne","les Bouches-du-Rhône","le Doubs"], correct: 1 },
  { text: "Laval est la préfecture de quel département ?", options: ["les Bouches-du-Rhône","la Mayenne","le Doubs","l'Isère"], correct: 1 },
  { text: "Nancy est la préfecture de quel département ?", options: ["le Doubs","la Meurthe-et-Moselle","l'Isère","la Marne"], correct: 1 },
  { text: "Bar-le-Duc est la préfecture de quel département ?", options: ["l'Isère","la Meuse","la Marne","les Pyrénées-Atlantiques"], correct: 1 },
  { text: "Vannes est la préfecture de quel département ?", options: ["la Marne","le Morbihan","les Pyrénées-Atlantiques","les Yvelines"], correct: 1 },
  { text: "Metz est la préfecture de quel département ?", options: ["les Pyrénées-Atlantiques","la Moselle","les Yvelines","les Hauts-de-Seine"], correct: 1 },
  { text: "Nevers est la préfecture de quel département ?", options: ["les Yvelines","la Nièvre","les Hauts-de-Seine","l'Aveyron"], correct: 1 },
  { text: "Lille est la préfecture de quel département ?", options: ["les Hauts-de-Seine","le Nord","l'Aveyron","la Dordogne"], correct: 1 },
  { text: "Beauvais est la préfecture de quel département ?", options: ["l'Aveyron","l'Oise","la Dordogne","l'Indre-et-Loire"], correct: 1 },
  { text: "Alençon est la préfecture de quel département ?", options: ["la Dordogne","l'Orne","l'Indre-et-Loire","la Manche"], correct: 1 },
  { text: "Arras est la préfecture de quel département ?", options: ["l'Indre-et-Loire","le Pas-de-Calais","la Manche","le Puy-de-Dôme"], correct: 1 },
  { text: "Clermont-Ferrand est la préfecture de quel département ?", options: ["la Manche","le Puy-de-Dôme","la Seine-et-Marne","le Territoire de Belfort"], correct: 1 },
  { text: "Pau est la préfecture de quel département ?", options: ["le Puy-de-Dôme","les Pyrénées-Atlantiques","la Seine-et-Marne","le Territoire de Belfort"], correct: 1 },
  { text: "Tarbes est la préfecture de quel département ?", options: ["la Seine-et-Marne","les Hautes-Pyrénées","le Territoire de Belfort","l'Aude"], correct: 1 },
  { text: "Perpignan est la préfecture de quel département ?", options: ["le Territoire de Belfort","les Pyrénées-Orientales","l'Aude","la Creuse"], correct: 1 },
  { text: "Strasbourg est la préfecture de quel département ?", options: ["l'Aude","le Bas-Rhin","la Creuse","l'Indre"], correct: 1 },
  { text: "Colmar est la préfecture de quel département ?", options: ["la Creuse","le Haut-Rhin","l'Indre","le Maine-et-Loire"], correct: 1 },
  { text: "Lyon est la préfecture de quel département ?", options: ["l'Indre","le Rhône","le Maine-et-Loire","le Pas-de-Calais"], correct: 1 },
  { text: "Vesoul est la préfecture de quel département ?", options: ["le Maine-et-Loire","la Haute-Saône","le Pas-de-Calais","la Seine-Maritime"], correct: 1 },
  { text: "Mâcon est la préfecture de quel département ?", options: ["le Pas-de-Calais","la Saône-et-Loire","la Seine-Maritime","l'Yonne"], correct: 1 },
  { text: "Le Mans est la préfecture de quel département ?", options: ["la Seine-Maritime","la Sarthe","l'Yonne","l'Aube"], correct: 1 },
  { text: "Chambéry est la préfecture de quel département ?", options: ["l'Yonne","la Savoie","l'Aube","les Côtes-d'Armor"], correct: 1 },
  { text: "Annecy est la préfecture de quel département ?", options: ["l'Aube","la Haute-Savoie","les Côtes-d'Armor","l'Ille-et-Vilaine"], correct: 1 },
  { text: "Rouen est la préfecture de quel département ?", options: ["les Côtes-d'Armor","la Seine-Maritime","l'Ille-et-Vilaine","la Lozère"], correct: 1 },
  { text: "Melun est la préfecture de quel département ?", options: ["l'Ille-et-Vilaine","la Seine-et-Marne","la Lozère","l'Orne"], correct: 1 },
  { text: "Versailles est la préfecture de quel département ?", options: ["la Lozère","les Yvelines","l'Orne","la Haute-Savoie"], correct: 1 },
  { text: "Niort est la préfecture de quel département ?", options: ["l'Orne","les Deux-Sèvres","la Haute-Savoie","les Vosges"], correct: 1 },
  { text: "Amiens est la préfecture de quel département ?", options: ["la Haute-Savoie","la Somme","les Vosges","l'Ariège"], correct: 1 },
  { text: "Albi est la préfecture de quel département ?", options: ["les Vosges","le Tarn","l'Ariège","la Côte-d'Or"], correct: 1 },
  { text: "Montauban est la préfecture de quel département ?", options: ["l'Ariège","le Tarn-et-Garonne","la Côte-d'Or","l'Hérault"], correct: 1 },
  { text: "Toulon est la préfecture de quel département ?", options: ["la Côte-d'Or","le Var","l'Hérault","le Lot-et-Garonne"], correct: 1 },
  { text: "Avignon est la préfecture de quel département ?", options: ["l'Hérault","le Vaucluse","le Lot-et-Garonne","l'Oise"], correct: 1 },
  { text: "La Roche-sur-Yon est la préfecture de quel département ?", options: ["le Lot-et-Garonne","la Vendée","l'Oise","la Savoie"], correct: 1 },
  { text: "Poitiers est la préfecture de quel département ?", options: ["l'Oise","la Vienne","la Savoie","la Haute-Vienne"], correct: 1 },
  { text: "Limoges est la préfecture de quel département ?", options: ["la Savoie","la Haute-Vienne","les Ardennes","la Haute-Corse"], correct: 1 },
  { text: "Épinal est la préfecture de quel département ?", options: ["la Haute-Vienne","les Vosges","les Ardennes","la Haute-Corse"], correct: 1 },
  { text: "Auxerre est la préfecture de quel département ?", options: ["les Ardennes","l'Yonne","la Haute-Corse","la Gironde"], correct: 1 },
  { text: "Belfort est la préfecture de quel département ?", options: ["la Haute-Corse","le Territoire de Belfort","la Gironde","le Lot"], correct: 1 },
  { text: "Nanterre est la préfecture de quel département ?", options: ["la Gironde","les Hauts-de-Seine","le Lot","le Nord"], correct: 1 },
  { text: "Bobigny est la préfecture de quel département ?", options: ["le Lot","la Seine-Saint-Denis","le Nord","la Sarthe"], correct: 1 },
  { text: "Créteil est la préfecture de quel département ?", options: ["le Nord","le Val-de-Marne","la Sarthe","la Vienne"], correct: 1 },
  { text: "Quelle ville française accueille le festival de la BD ?", options: ["Angoulême","Cannes","Avignon","Deauville"], correct: 0 },
  { text: "Quel parc d'attractions près de Paris a ouvert en 1992 ?", options: ["Astérix","Disneyland Paris","Futuroscope","Walibi"], correct: 1 },
  { text: "Quel pont géant franchit le Tarn près de Millau ?", options: ["Pont de Normandie","Viaduc de Millau","Pont de Tancarville","Pont d'Aquitaine"], correct: 1 },
  { text: "Quelle est la plus longue autoroute de liaison Paris-Marseille ?", options: ["A1","A7 (via A6)","A10","A4"], correct: 1 },
  { text: "Quel TGV relie Paris à Lyon en environ 2 heures ?", options: ["Le RER","Le TGV","Le Transilien","Le TER"], correct: 1 },
  { text: "Quelle est la plus grande agglomération française ?", options: ["Lyon","Paris","Marseille","Lille"], correct: 1 },
  { text: "Quel est le plus haut sommet des Pyrénées françaises ?", options: ["Mont Blanc","Vignemale","Aneto","Mont Perdu"], correct: 1 },
  { text: "Quelle est la région la plus au sud de la métropole ?", options: ["Bretagne","Provence-Alpes-Côte d'Azur","Normandie","Grand Est"], correct: 1 },
  { text: "Quelle ville est connue pour sa cathédrale gothique et ses bulles (Champagne) ?", options: ["Reims","Lyon","Nantes","Tours"], correct: 0 },
  { text: "Quelle ville bretonne est un grand port militaire ?", options: ["Rennes","Brest","Quimper","Vannes"], correct: 1 },
];
