// QuizzMaster — thème 🍷 Gastronomie & Vins. 300 questions.

module.exports = [
  { text: "Quel cépage rouge domine en Bourgogne ?", options: ["Cabernet Sauvignon","Pinot Noir","Merlot","Syrah"], correct: 1 },
  { text: "Quel cépage blanc règne à Chablis ?", options: ["Sauvignon","Chardonnay","Riesling","Viognier"], correct: 1 },
  { text: "Quelle région produit le Sancerre ?", options: ["Bourgogne","Loire","Bordeaux","Alsace"], correct: 1 },
  { text: "Quel cépage donne le Beaujolais ?", options: ["Gamay","Pinot Noir","Syrah","Grenache"], correct: 0 },
  { text: "Quel vin doux est produit dans le Sauternais ?", options: ["Banyuls","Sauternes","Muscat","Pineau"], correct: 1 },
  { text: "Quel cépage produit l'Hermitage rouge (Rhône nord) ?", options: ["Grenache","Mourvèdre","Syrah","Cinsault"], correct: 2 },
  { text: "Que désigne le « millésime » d'un vin ?", options: ["Le degré d'alcool","L'année de récolte","Le sol","Le nombre de bouteilles"], correct: 1 },
  { text: "Quelle est la contenance d'une bouteille de vin standard ?", options: ["50 cl","70 cl","75 cl","100 cl"], correct: 2 },
  { text: "Quel cépage blanc évoque le pamplemousse et le buis ?", options: ["Chardonnay","Sauvignon Blanc","Riesling","Viognier"], correct: 1 },
  { text: "Quel vin pétillant français est associé aux fêtes ?", options: ["Bordeaux","Champagne","Beaujolais","Sancerre"], correct: 1 },
  { text: "Quel département produit le plus de Champagne ?", options: ["Aube","Marne","Aisne","Haute-Marne"], correct: 1 },
  { text: "Quelle ville est la capitale des vins de Bordeaux ?", options: ["Bordeaux","Lyon","Dijon","Reims"], correct: 0 },
  { text: "Quel fromage bleu est affiné dans des grottes de l'Aveyron ?", options: ["Bleu d'Auvergne","Roquefort","Fourme d'Ambert","Bleu de Bresse"], correct: 1 },
  { text: "Le Comté est un fromage au lait de…", options: ["Brebis","Chèvre","Vache","Bufflonne"], correct: 2 },
  { text: "Quel fromage normand a une croûte fleurie blanche ?", options: ["Comté","Camembert","Roquefort","Cantal"], correct: 1 },
  { text: "Le Roquefort est un fromage au lait de…", options: ["Vache","Brebis","Chèvre","Jument"], correct: 1 },
  { text: "De quel pays vient la mozzarella di bufala ?", options: ["France","Italie","Grèce","Suisse"], correct: 1 },
  { text: "Quel fromage suisse est fondu pour la raclette ?", options: ["Gruyère","Emmental","Raclette","Tomme"], correct: 2 },
  { text: "Le Beaufort est un fromage de quel massif ?", options: ["Vosges","Pyrénées","Alpes","Massif central"], correct: 2 },
  { text: "Quelle est l'origine du bœuf bourguignon ?", options: ["Lyon","Bourgogne","Provence","Normandie"], correct: 1 },
  { text: "Quels ingrédients composent la pâte à choux ?", options: ["Levure","Beurre, œufs, farine, eau","Pommes de terre","Crème"], correct: 1 },
  { text: "Quelle sauce mère est à base de roux blanc et de lait ?", options: ["Béchamel","Hollandaise","Espagnole","Velouté"], correct: 0 },
  { text: "Quel chef est associé à la nouvelle cuisine et à Lyon ?", options: ["Escoffier","Paul Bocuse","Robuchon","Ducasse"], correct: 1 },
  { text: "Le kouign-amann est une spécialité de quelle région ?", options: ["Alsace","Bretagne","Provence","Auvergne"], correct: 1 },
  { text: "Quel poisson entre dans la quenelle lyonnaise ?", options: ["Sole","Brochet","Truite","Saumon"], correct: 1 },
  { text: "De quel pays vient le sushi ?", options: ["Chine","Japon","Corée","Thaïlande"], correct: 1 },
  { text: "Quel plat espagnol mêle riz, safran et fruits de mer ?", options: ["Risotto","Paella","Couscous","Tajine"], correct: 1 },
  { text: "De quel pays vient le ceviche ?", options: ["Mexique","Pérou","Chili","Brésil"], correct: 1 },
  { text: "Le pho est un plat traditionnel de quel pays ?", options: ["Thaïlande","Cambodge","Vietnam","Laos"], correct: 2 },
  { text: "Le falafel est à base de…", options: ["Pois chiches ou fèves","Lentilles","Quinoa","Haricots noirs"], correct: 0 },
  { text: "De quel pays vient la pizza ?", options: ["Grèce","Italie","Espagne","Turquie"], correct: 1 },
  { text: "De quel pays viennent les tacos (origine) ?", options: ["Espagne","Mexique","Pérou","Cuba"], correct: 1 },
  { text: "De quel pays vient le couscous (Maghreb) ?", options: ["Liban","Maghreb","Turquie","Iran"], correct: 1 },
  { text: "À partir de quoi est distillé le calvados ?", options: ["Raisin","Pommes (cidre)","Poire","Prune"], correct: 1 },
  { text: "Quel cocktail mêle rhum, citron vert et menthe ?", options: ["Daiquiri","Mojito","Caipirinha","Piña Colada"], correct: 1 },
  { text: "Le saké est obtenu par fermentation de…", options: ["Raisin","Orge","Riz","Pomme"], correct: 2 },
  { text: "« Mise en place » signifie en cuisine…", options: ["Servir l'assiette","Préparer les ingrédients avant cuisson","Dresser la table","Goûter"], correct: 1 },
  { text: "Quel fruit est la base du chutney indien classique ?", options: ["Pomme","Mangue","Banane","Tomate"], correct: 1 },
  { text: "Quelle pâte fine sert à faire les baklavas ?", options: ["Brisée","Phyllo (filo)","Sablée","Sucrée"], correct: 1 },
  { text: "Quel plat alsacien associe choux et charcuterie ?", options: ["Cassoulet","Choucroute","Aligot","Tartiflette"], correct: 1 },
  { text: "Quel plat savoyard mêle pommes de terre, reblochon et lardons ?", options: ["Raclette","Tartiflette","Fondue","Aligot"], correct: 1 },
  { text: "Quel plat du Sud-Ouest associe haricots et confit ?", options: ["Choucroute","Cassoulet","Pot-au-feu","Aligot"], correct: 1 },
  { text: "Quelle spécialité aveyronnaise mêle purée et tome fraîche filante ?", options: ["Aligot","Truffade","Gratin","Tartiflette"], correct: 0 },
  { text: "Quel dessert français est une crème renversée au caramel ?", options: ["Île flottante","Crème caramel (flan)","Clafoutis","Tarte Tatin"], correct: 1 },
  { text: "Quelle tarte aux pommes est cuite à l'envers ?", options: ["Tarte Bourdaloue","Tarte Tatin","Tarte normande","Tarte fine"], correct: 1 },
  { text: "Quel petit gâteau bordelais est cannelé et caramélisé ?", options: ["Madeleine","Canelé","Macaron","Financier"], correct: 1 },
  { text: "Quel biscuit en forme de coquillage est lié à Commercy ?", options: ["Canelé","Madeleine","Financier","Tuile"], correct: 1 },
  { text: "Quelle pâtisserie ronde à deux coques colorées est française ?", options: ["Le macaron","Le cupcake","Le donut","Le brownie"], correct: 0 },
  { text: "Quel vin rouge primeur sort le 3e jeudi de novembre ?", options: ["Bordeaux nouveau","Beaujolais nouveau","Côtes-du-Rhône","Chinon"], correct: 1 },
  { text: "Quelle boisson anisée du Sud se boit avec de l'eau ?", options: ["Le pastis","Le cidre","Le kir","Le calva"], correct: 0 },
  { text: "Quel apéritif mêle vin blanc et crème de cassis ?", options: ["Le kir","Le spritz","Le pastis","Le porto"], correct: 0 },
  { text: "Quel alcool écossais est distillé à partir d'orge maltée ?", options: ["Le cognac","Le whisky","La vodka","Le gin"], correct: 1 },
  { text: "Le cognac est produit en France à partir de…", options: ["Pommes","Raisin","Orge","Seigle"], correct: 1 },
  { text: "Quel champagne sans année est dit…", options: ["Brut sans année","Millésimé","Rosé seulement","Demi-sec"], correct: 0 },
  { text: "Quelle région produit le vin de Bordeaux ?", options: ["Aquitaine/Gironde","Alsace","Savoie","Provence"], correct: 0 },
  { text: "Quel cépage emblématique compose souvent le Bordeaux rouge ?", options: ["Pinot Noir","Cabernet Sauvignon / Merlot","Gamay","Syrah"], correct: 1 },
  { text: "Quelle est la température idéale de service d'un Champagne ?", options: ["18 °C","8 °C","25 °C","2 °C"], correct: 1 },
  { text: "Quel vin sert traditionnellement avec les huîtres ?", options: ["Vin rouge corsé","Muscadet / vin blanc sec","Porto","Vin doux"], correct: 1 },
  { text: "Quel fromage italien dur s'affine 12 mois minimum ?", options: ["Mozzarella","Parmigiano Reggiano","Ricotta","Burrata"], correct: 1 },
  { text: "Quel fromage grec est utilisé dans la salade grecque ?", options: ["Mozzarella","Feta","Cheddar","Gouda"], correct: 1 },
  { text: "Quel fromage néerlandais est jaune et doux ?", options: ["Gouda","Roquefort","Brie","Comté"], correct: 0 },
  { text: "Quel fromage anglais orange est très connu ?", options: ["Cheddar","Stilton","Brie","Edam"], correct: 0 },
  { text: "Quel plat italien est composé de pâtes longues et fines ?", options: ["Lasagnes","Spaghetti","Gnocchi","Risotto"], correct: 1 },
  { text: "Quel riz italien crémeux est cuit lentement ?", options: ["Paella","Risotto","Pilaf","Riz cantonais"], correct: 1 },
  { text: "Quelle herbe aromatique parfume le pesto ?", options: ["Persil","Basilic","Coriandre","Menthe"], correct: 1 },
  { text: "Quelle épice rouge et chère provient d'un crocus ?", options: ["Paprika","Safran","Curcuma","Piment"], correct: 1 },
  { text: "Quelle épice jaune colore le curry ?", options: ["Cannelle","Curcuma","Cumin","Gingembre"], correct: 1 },
  { text: "Quel agrume est utilisé pour le limoncello ?", options: ["Orange","Citron","Pamplemousse","Mandarine"], correct: 1 },
  { text: "Quel plat japonais est composé de poisson cru sans riz ?", options: ["Sushi","Sashimi","Maki","Tempura"], correct: 1 },
  { text: "Quel beignet japonais de légumes ou crevettes est frit ?", options: ["Gyoza","Tempura","Ramen","Onigiri"], correct: 1 },
  { text: "Quelle soupe de nouilles japonaise est très populaire ?", options: ["Pho","Ramen","Laksa","Tom yum"], correct: 1 },
  { text: "Quel plat coréen est du riz mélangé avec légumes et œuf ?", options: ["Kimchi","Bibimbap","Bulgogi","Japchae"], correct: 1 },
  { text: "Quel chou fermenté épicé est emblématique de la Corée ?", options: ["Choucroute","Kimchi","Wasabi","Miso"], correct: 1 },
  { text: "Quelle pâte de soja fermentée parfume la soupe japonaise ?", options: ["Le tofu","Le miso","Le tahini","Le houmous"], correct: 1 },
  { text: "De quel pays vient le tiramisu ?", options: ["France","Italie","Espagne","Grèce"], correct: 1 },
  { text: "Quel ingrédient amer aromatise le tiramisu ?", options: ["Le thé","Le café","Le chocolat blanc","La vanille"], correct: 1 },
  { text: "Quel dessert espagnol est une crème aux œufs caramélisée ?", options: ["Tiramisu","Crème catalane","Panna cotta","Tarte"], correct: 1 },
  { text: "Quel dessert italien est une crème prise à la gélatine ?", options: ["Tiramisu","Panna cotta","Cannoli","Gelato"], correct: 1 },
  { text: "Quel plat indien est un poulet en sauce épicée orangée ?", options: ["Pad thaï","Poulet tikka massala","Bibimbap","Pho"], correct: 1 },
  { text: "Quel pain indien plat est cuit au four tandoor ?", options: ["Pita","Naan","Tortilla","Baguette"], correct: 1 },
  { text: "Quel plat thaïlandais est une soupe épicée et acidulée ?", options: ["Pad thaï","Tom yum","Pho","Laksa"], correct: 1 },
  { text: "Quel plat mexicain est une grande tortilla de blé garnie et roulée ?", options: ["Taco","Burrito","Paella","Empanada"], correct: 1 },
  { text: "Quel avocat écrasé épicé est une spécialité mexicaine ?", options: ["Salsa","Guacamole","Houmous","Tzatziki"], correct: 1 },
  { text: "Quelle sauce grecque mêle yaourt, concombre et ail ?", options: ["Houmous","Tzatziki","Pesto","Aïoli"], correct: 1 },
  { text: "Quelle purée de pois chiches est typique du Moyen-Orient ?", options: ["Tzatziki","Houmous","Guacamole","Pesto"], correct: 1 },
  { text: "Quel plat marocain mijote dans un plat conique en terre ?", options: ["Couscous","Tajine","Méchoui","Pastilla"], correct: 1 },
  { text: "Quel mélange d'épices est typique du Maghreb ?", options: ["Garam masala","Ras el-hanout","Cinq-épices","Curry"], correct: 1 },
  { text: "Quel pain plat est utilisé dans le kebab/döner ?", options: ["Baguette","Pain pita","Brioche","Ciabatta"], correct: 1 },
  { text: "Quel plat vietnamien est un rouleau de printemps frais ?", options: ["Nem frit","Gỏi cuốn (rouleau frais)","Bao","Gyoza"], correct: 1 },
  { text: "Quelle viande n'est pas consommée dans la cuisine hindoue traditionnelle ?", options: ["Le poulet","Le bœuf","Le poisson","L'agneau"], correct: 1 },
  { text: "Quelle boisson chaude est faite de feuilles infusées ?", options: ["Le café","Le thé","Le cacao","Le lait"], correct: 1 },
  { text: "Quelle boisson est issue de grains torréfiés et moulus ?", options: ["Le thé","Le café","Le cidre","Le jus"], correct: 1 },
  { text: "Quel fruit sert à faire le vin ?", options: ["La pomme","Le raisin","La poire","La prune"], correct: 1 },
  { text: "Quel fruit sert à faire le cidre ?", options: ["Le raisin","La pomme","La cerise","La fraise"], correct: 1 },
  { text: "Quel produit de la ruche est un édulcorant naturel ?", options: ["Le sucre","Le miel","Le sirop d'érable","La mélasse"], correct: 1 },
  { text: "De quel arbre vient le sirop d'érable ?", options: ["Le chêne","L'érable","Le bouleau","Le pin"], correct: 1 },
  { text: "Quel ustensile sert à fouetter les blancs en neige ?", options: ["La spatule","Le fouet","La louche","La maryse"], correct: 1 },
  { text: "À quelle température cuit-on généralement un gâteau au four (th. moyen) ?", options: ["120 °C","180 °C","250 °C","90 °C"], correct: 1 },
  { text: "Quel mode de cuisson utilise de l'eau bouillante ?", options: ["La friture","L'ébullition","Le rôtissage","Le grill"], correct: 1 },
  { text: "Quel mode de cuisson plonge l'aliment dans l'huile chaude ?", options: ["La friture","La vapeur","Le pochage","Le braisage"], correct: 0 },
  { text: "Quelle viande compose le steak tartare (cru) ?", options: ["Porc","Bœuf","Poulet","Agneau"], correct: 1 },
  { text: "Quel poisson gras et rose est souvent fumé ?", options: ["Cabillaud","Saumon","Sole","Merlu"], correct: 1 },
  { text: "Quel mollusque se déguste cru avec du citron ?", options: ["La moule","L'huître","La palourde","Le bulot"], correct: 1 },
  { text: "Quel fruit de mer rose se pêche et se déguste en plateau ?", options: ["La crevette","Le concombre de mer","L'anguille","Le calmar séché"], correct: 0 },
  { text: "Quel champignon noir et rare est très prisé en cuisine ?", options: ["Le cèpe","La truffe","La girolle","Le shiitaké"], correct: 1 },
  { text: "Quelle viande est l'ingrédient principal du foie gras ?", options: ["Le porc","Le canard ou l'oie","Le bœuf","Le poulet"], correct: 1 },
  { text: "Quel pain français long et croustillant est emblématique ?", options: ["La brioche","La baguette","Le pain de mie","Le bagel"], correct: 1 },
  { text: "Quelle viennoiserie est faite de pâte feuilletée en croissant ?", options: ["Le pain au lait","Le croissant","La brioche","Le chausson"], correct: 1 },
  { text: "Quel plat italien superpose pâtes, sauce et béchamel ?", options: ["Risotto","Lasagnes","Gnocchi","Polenta"], correct: 1 },
  { text: "Quelle céréale sert à faire la polenta ?", options: ["Le blé","Le maïs","Le riz","L'avoine"], correct: 1 },
  { text: "Quel alcool mexicain est tiré de l'agave ?", options: ["Le rhum","La tequila","Le pisco","Le mezcal seul"], correct: 1 },
  { text: "Quel alcool cubain est à base de canne à sucre ?", options: ["La vodka","Le rhum","Le gin","Le whisky"], correct: 1 },
  { text: "Quel vin portugais muté est célèbre (ville de Porto) ?", options: ["Le xérès","Le porto","Le madère","Le marsala"], correct: 1 },
  { text: "Quel vin espagnol muté vient d'Andalousie ?", options: ["Le porto","Le xérès (sherry)","Le marsala","Le tokaji"], correct: 1 },
  { text: "Quel vin rouge prestigieux vient de la région de Bordeaux (rive gauche) ?", options: ["Médoc","Chablis","Sancerre","Chinon"], correct: 0 },
  { text: "Quelle appellation de Bourgogne rouge est très réputée ?", options: ["Médoc","Gevrey-Chambertin","Sancerre","Cahors"], correct: 1 },
  { text: "Quel vin blanc liquoreux accompagne le foie gras ?", options: ["Muscadet","Sauternes","Chablis","Sancerre"], correct: 1 },
  { text: "Quel cépage blanc est typique de l'Alsace, sec et minéral ?", options: ["Riesling","Gamay","Merlot","Syrah"], correct: 0 },
  { text: "Quel cépage noir domine dans les Côtes-du-Rhône méridionales ?", options: ["Grenache","Pinot Noir","Chardonnay","Riesling"], correct: 0 },
  { text: "Quel cépage produit le Muscadet (Loire) ?", options: ["Melon de Bourgogne","Gamay","Syrah","Merlot"], correct: 0 },
  { text: "Quel cépage blanc fait le Pouilly-Fumé ?", options: ["Chardonnay","Sauvignon Blanc","Riesling","Sémillon"], correct: 1 },
  { text: "Quelle région viticole entoure la ville de Beaune ?", options: ["Bordeaux","Bourgogne","Alsace","Champagne"], correct: 1 },
  { text: "Quel vin effervescent espagnol ressemble au champagne ?", options: ["Prosecco","Cava","Lambrusco","Crémant"], correct: 1 },
  { text: "Quel vin effervescent italien est souvent utilisé dans le spritz ?", options: ["Cava","Prosecco","Champagne","Asti"], correct: 1 },
  { text: "Quelle région d'Italie produit le Chianti ?", options: ["Toscane","Sicile","Piémont","Vénétie"], correct: 0 },
  { text: "Quel vin rouge italien prestigieux vient du Piémont ?", options: ["Chianti","Barolo","Lambrusco","Soave"], correct: 1 },
  { text: "Quel cépage est à la base du Barolo ?", options: ["Sangiovese","Nebbiolo","Merlot","Primitivo"], correct: 1 },
  { text: "Quel cépage est à la base du Chianti ?", options: ["Nebbiolo","Sangiovese","Barbera","Montepulciano"], correct: 1 },
  { text: "Quelle boisson anisée grecque est servie en apéritif ?", options: ["Ouzo","Raki","Pastis","Sambuca"], correct: 0 },
  { text: "Quel alcool turc anisé devient blanc avec de l'eau ?", options: ["Ouzo","Raki","Arak","Pastis"], correct: 1 },
  { text: "Quel digestif italien aux herbes est amer ?", options: ["Limoncello","Amaro","Grappa","Sambuca"], correct: 1 },
  { text: "Quel alcool italien est distillé à partir de marc de raisin ?", options: ["Limoncello","Grappa","Amaretto","Sambuca"], correct: 1 },
  { text: "Quel fromage italien filant est utilisé sur la pizza ?", options: ["Parmesan","Mozzarella","Gorgonzola","Pecorino"], correct: 1 },
  { text: "Quel fromage italien bleu et persillé est célèbre ?", options: ["Mozzarella","Gorgonzola","Pecorino","Burrata"], correct: 1 },
  { text: "Quel fromage italien est fait au lait de brebis ?", options: ["Parmesan","Pecorino","Mozzarella","Mascarpone"], correct: 1 },
  { text: "Quel fromage frais italien sert au tiramisu ?", options: ["Ricotta","Mascarpone","Burrata","Stracciatella"], correct: 1 },
  { text: "Quel fromage français à pâte persillée vient du Massif central ?", options: ["Comté","Bleu d'Auvergne","Reblochon","Munster"], correct: 1 },
  { text: "Quel fromage alsacien à l'odeur forte est lavé en croûte ?", options: ["Munster","Comté","Cantal","Brie"], correct: 0 },
  { text: "Quel fromage savoyard entre dans la tartiflette ?", options: ["Comté","Reblochon","Beaufort","Tomme"], correct: 1 },
  { text: "Quel fromage de chèvre en bûche cendrée vient de la Loire ?", options: ["Crottin","Sainte-Maure de Touraine","Rocamadour","Banon"], correct: 1 },
  { text: "Quel fromage à croûte fleurie vient de la Brie ?", options: ["Camembert","Brie de Meaux","Coulommiers","Neufchâtel"], correct: 1 },
  { text: "Quel plat français mijoté associe coq et vin rouge ?", options: ["Bœuf bourguignon","Coq au vin","Blanquette","Pot-au-feu"], correct: 1 },
  { text: "Quel plat français est une blanquette à base de…", options: ["Bœuf","Veau","Porc","Agneau"], correct: 1 },
  { text: "Quel plat provençal mêle légumes mijotés (aubergine, courgette, tomate) ?", options: ["Cassoulet","Ratatouille","Aligot","Tartiflette"], correct: 1 },
  { text: "Quelle soupe froide espagnole est à base de tomate ?", options: ["Gaspacho","Bouillabaisse","Minestrone","Vichyssoise"], correct: 0 },
  { text: "Quelle soupe italienne aux légumes et pâtes est connue ?", options: ["Gaspacho","Minestrone","Bortsch","Pho"], correct: 1 },
  { text: "Quelle soupe d'Europe de l'Est est rouge (betterave) ?", options: ["Minestrone","Bortsch","Gaspacho","Goulash"], correct: 1 },
  { text: "Quel ragoût hongrois est épicé au paprika ?", options: ["Goulash","Bortsch","Cassoulet","Tajine"], correct: 0 },
  { text: "Quel plat allemand associe saucisse et chou fermenté ?", options: ["Goulash","Choucroute (Sauerkraut)","Schnitzel","Bretzel"], correct: 1 },
  { text: "Quelle escalope panée est typiquement viennoise/allemande ?", options: ["Schnitzel","Goulash","Strudel","Bretzel"], correct: 0 },
  { text: "Quel dessert autrichien est un gâteau roulé aux pommes ?", options: ["Sachertorte","Strudel","Linzer","Kouglof"], correct: 1 },
  { text: "Quel gâteau au chocolat est une spécialité de Vienne ?", options: ["Forêt-Noire","Sachertorte","Brownie","Opéra"], correct: 1 },
  { text: "Quel gâteau allemand à la crème et aux cerises est célèbre ?", options: ["Forêt-Noire","Sachertorte","Stollen","Strudel"], correct: 0 },
  { text: "Quel plat britannique associe poisson frit et frites ?", options: ["Shepherd's pie","Fish and chips","Haggis","Pudding"], correct: 1 },
  { text: "Quel plat écossais est à base d'abats de mouton ?", options: ["Haggis","Fish and chips","Shepherd's pie","Black pudding"], correct: 0 },
  { text: "Quel petit-déjeuner anglais comprend œufs, bacon et haricots ?", options: ["Brunch","English breakfast","Continental","Porridge"], correct: 1 },
  { text: "Quel plat américain est un pain de viande ?", options: ["Hot-dog","Meatloaf","Burger","Chili"], correct: 1 },
  { text: "Quel plat texan/mexicain est un ragoût épicé de viande et haricots ?", options: ["Chili con carne","Burrito","Fajitas","Quesadilla"], correct: 0 },
  { text: "Quelle galette mexicaine est faite de maïs ou de blé ?", options: ["Pita","Tortilla","Naan","Crêpe"], correct: 1 },
  { text: "Quel plat japonais est une boulette de riz souvent triangulaire ?", options: ["Mochi","Onigiri","Gyoza","Edamame"], correct: 1 },
  { text: "Quel dessert japonais est une pâte de riz gluant sucrée ?", options: ["Mochi","Dorayaki","Taiyaki","Onigiri"], correct: 0 },
  { text: "Quel bouillon de nouilles est emblématique du Japon ?", options: ["Pho","Ramen","Udon seulement","Laksa"], correct: 1 },
  { text: "Quelles grosses nouilles japonaises épaisses connais-tu ?", options: ["Soba","Udon","Ramen","Vermicelle"], correct: 1 },
  { text: "Quel plat indien est un riz épicé mélangé à de la viande/légumes ?", options: ["Dal","Biryani","Naan","Samosa"], correct: 1 },
  { text: "Quel beignet indien triangulaire est farci d'épices ?", options: ["Samosa","Naan","Pakora","Papadum"], correct: 0 },
  { text: "Quelle lentille épicée est un plat de base indien ?", options: ["Dal","Curry","Massala","Korma"], correct: 0 },
  { text: "Quel plat brésilien est un ragoût de haricots noirs et viandes ?", options: ["Feijoada","Churrasco","Moqueca","Acarajé"], correct: 0 },
  { text: "Quel mode de cuisson brésilien grille la viande à la broche ?", options: ["Feijoada","Churrasco","Moqueca","Ceviche"], correct: 1 },
  { text: "Quel alcool brésilien à base de canne sert dans la caipirinha ?", options: ["Rhum","Cachaça","Pisco","Tequila"], correct: 1 },
  { text: "Quel alcool péruvien/chilien sert dans le pisco sour ?", options: ["Cachaça","Pisco","Rhum","Mezcal"], correct: 1 },
  { text: "Quel fruit exotique jaune et acidulé pousse en climat tropical ?", options: ["La pomme","L'ananas","La poire","La cerise"], correct: 1 },
  { text: "Quel fruit rouge en grappe sert à faire le vin ?", options: ["La fraise","Le raisin","La groseille","La mûre"], correct: 1 },
  { text: "Quel agrume est utilisé pour le jus du matin le plus courant ?", options: ["Le citron","L'orange","Le pamplemousse","La lime"], correct: 1 },
  { text: "Quelle céréale sert à faire le pain classique ?", options: ["Le riz","Le blé","Le maïs","L'orge"], correct: 1 },
  { text: "Quelle céréale sert à faire le risotto ?", options: ["Le blé","Le riz","Le maïs","L'avoine"], correct: 1 },
  { text: "Quelle céréale est la base de la bière (maltée) ?", options: ["Le riz","L'orge","Le maïs","Le seigle"], correct: 1 },
  { text: "Quel légume orange est riche en bêta-carotène ?", options: ["La betterave","La carotte","Le navet","Le radis"], correct: 1 },
  { text: "Quel légume vert se présente en bouquets (fleurettes) ?", options: ["Le chou-fleur","Le brocoli","L'épinard","La courgette"], correct: 1 },
  { text: "Quel champignon est cultivé en cave et très courant ?", options: ["Le cèpe","Le champignon de Paris","La morille","La truffe"], correct: 1 },
  { text: "Quelle herbe parfume le taboulé et le couscous ?", options: ["Le basilic","La menthe et le persil","L'estragon","L'aneth"], correct: 1 },
  { text: "Quelle épice est obtenue à partir d'une écorce d'arbre, en bâton ?", options: ["La cannelle","Le poivre","Le clou de girofle","La muscade"], correct: 0 },
  { text: "Quelle épice noire est le « roi des épices » en grains ?", options: ["Le poivre","Le sel","Le curcuma","Le paprika"], correct: 0 },
  { text: "Quel condiment japonais vert et très piquant accompagne les sushis ?", options: ["Le gingembre","Le wasabi","Le miso","Le soja"], correct: 1 },
  { text: "Quelle sauce piquante mexicaine accompagne tacos et nachos ?", options: ["La salsa","Le pesto","L'aïoli","La béarnaise"], correct: 0 },
  { text: "Quelle sauce française au beurre et à l'estragon accompagne la viande ?", options: ["Béchamel","Béarnaise","Mayonnaise","Vinaigrette"], correct: 1 },
  { text: "Quelle sauce froide est faite d'huile, jaune d'œuf et moutarde ?", options: ["Mayonnaise","Béchamel","Hollandaise","Velouté"], correct: 0 },
  { text: "Quel pain juif tressé est traditionnel le shabbat ?", options: ["Bagel","Hallah","Pita","Matzo"], correct: 1 },
  { text: "Quel pain rond percé d'un trou est new-yorkais d'origine juive ?", options: ["Bretzel","Bagel","Donut","Muffin"], correct: 1 },
  { text: "Quelle pâtisserie ronde et glacée est trouée au centre ?", options: ["Le muffin","Le donut","Le cookie","Le brownie"], correct: 1 },
  { text: "Quel gâteau américain au chocolat est dense et carré ?", options: ["Cookie","Brownie","Cupcake","Muffin"], correct: 1 },
  { text: "Quelle viennoiserie française est fourrée au chocolat ?", options: ["Croissant","Pain au chocolat","Chausson","Brioche"], correct: 1 },
  { text: "Quel dessert français est une pâte à choux garnie de crème (en couronne ou éclair) ?", options: ["Mille-feuille","Éclair","Tarte","Madeleine"], correct: 1 },
  { text: "Quel dessert feuilleté alterne crème pâtissière et pâte ?", options: ["Éclair","Mille-feuille","Paris-Brest","Tarte Tatin"], correct: 1 },
  { text: "Quelle boisson chaude épicée se boit à Noël (vin + épices) ?", options: ["Le grog","Le vin chaud","Le punch","Le cidre"], correct: 1 },
  { text: "Quel plat suisse consiste à tremper du pain dans du fromage fondu ?", options: ["La raclette","La fondue savoyarde","La tartiflette","Le gratin"], correct: 1 },
  { text: "Quelle viande est interdite dans la cuisine halal et casher ?", options: ["Le bœuf","Le porc","Le poulet","L'agneau"], correct: 1 },
  { text: "Quel poisson est l'ingrédient principal des fish sticks/bâtonnets panés ?", options: ["Le saumon","Le cabillaud (poisson blanc)","Le thon","La sardine"], correct: 1 },
  { text: "Quel crustacé rouge se déguste souvent à la mayonnaise ?", options: ["La moule","Le homard","L'huître","La palourde"], correct: 1 },
  { text: "Quelle viande blanche est la volaille la plus consommée ?", options: ["Le canard","Le poulet","La dinde","La pintade"], correct: 1 },
  { text: "Quel mets de luxe est composé d'œufs d'esturgeon ?", options: ["Le foie gras","Le caviar","La truffe","Le homard"], correct: 1 },
  { text: "Quel plat italien froid est composé de fines tranches de bœuf cru ?", options: ["Carpaccio","Risotto","Osso buco","Vitello"], correct: 0 },
  { text: "Quel plat milanais est un jarret de veau braisé ?", options: ["Carpaccio","Osso buco","Risotto","Polenta"], correct: 1 },
  { text: "Quel pain plat italien est garni puis cuit (proche de la pizza) ?", options: ["Focaccia","Ciabatta","Grissini","Panettone"], correct: 0 },
  { text: "Quel gâteau italien de Noël est une brioche aux fruits confits ?", options: ["Panettone","Tiramisu","Cannoli","Panna cotta"], correct: 0 },
  { text: "Quelle pâtisserie sicilienne est un tube croustillant fourré de ricotta ?", options: ["Cannoli","Tiramisu","Panettone","Sfogliatella"], correct: 0 },
  { text: "Quel ingrédient principal compose le pain ?", options: ["Le riz","La farine","Le maïs","La pomme de terre"], correct: 1 },
  { text: "Quel ingrédient fait lever le pain ?", options: ["Le sel","La levure","Le sucre","L'huile"], correct: 1 },
  { text: "Quel produit laitier sert à faire le beurre ?", options: ["Le lait/la crème","L'eau","L'œuf","La farine"], correct: 0 },
  { text: "Quel produit laitier fermenté est souvent mangé au petit-déjeuner ?", options: ["Le beurre","Le yaourt","La crème","Le lait en poudre"], correct: 1 },
  { text: "De quel animal vient majoritairement le lait consommé en France ?", options: ["La chèvre","La vache","La brebis","La jument"], correct: 1 },
  { text: "Quel fruit sert à faire le jus d'orange ?", options: ["Le citron","L'orange","Le pamplemousse","La mandarine"], correct: 1 },
  { text: "Quel fruit jaune et courbé se pèle à la main ?", options: ["La pomme","La banane","La poire","La pêche"], correct: 1 },
  { text: "Quel légume vert allongé se mange en salade ou cru ?", options: ["La carotte","Le concombre","La betterave","Le navet"], correct: 1 },
  { text: "Quel légume rouge est souvent confondu avec un fruit ?", options: ["La pomme de terre","La tomate","L'oignon","Le poireau"], correct: 1 },
  { text: "Quel féculent est la base des frites ?", options: ["Le riz","La pomme de terre","Les pâtes","Le pain"], correct: 1 },
  { text: "Quelle viande provient du porc ?", options: ["Le steak","Le jambon","Le gigot","L'escalope de dinde"], correct: 1 },
  { text: "Quelle viande provient de l'agneau (jeune mouton) ?", options: ["Le jambon","Le gigot","Le magret","Le filet de porc"], correct: 1 },
  { text: "Quel poisson rose est souvent fumé et servi sur des toasts ?", options: ["Le cabillaud","Le saumon","La sardine","Le merlu"], correct: 1 },
  { text: "Quel fruit de mer se déguste cru avec un filet de citron ?", options: ["La crevette cuite","L'huître","La moule cuite","Le bulot"], correct: 1 },
  { text: "Quel plat italien consiste en pâtes plates superposées avec sauce et fromage ?", options: ["Spaghetti","Lasagnes","Risotto","Gnocchi"], correct: 1 },
  { text: "Quelles pâtes italiennes sont longues et fines ?", options: ["Penne","Spaghetti","Ravioli","Gnocchi"], correct: 1 },
  { text: "Quelles petites pâtes italiennes sont à base de pomme de terre ?", options: ["Penne","Gnocchi","Tagliatelles","Macaroni"], correct: 1 },
  { text: "Quelle sauce italienne rouge accompagne souvent les pâtes ?", options: ["Béchamel","Sauce tomate","Hollandaise","Mayonnaise"], correct: 1 },
  { text: "Quelle herbe verte parfume traditionnellement le pesto ?", options: ["Persil","Basilic","Aneth","Estragon"], correct: 1 },
  { text: "Quel fromage râpé saupoudre-t-on sur les pâtes (Italie) ?", options: ["Cheddar","Parmesan","Gouda","Feta"], correct: 1 },
  { text: "Quelle pâtisserie française est une fine crêpe pliée ?", options: ["Le gaufre","La crêpe","Le beignet","Le churros"], correct: 1 },
  { text: "Quelle galette bretonne salée est faite de farine de sarrasin ?", options: ["La crêpe sucrée","La galette","Le blini","La tortilla"], correct: 1 },
  { text: "Quel gâteau breton très beurré et caramélisé connais-tu ?", options: ["Le canelé","Le kouign-amann","Le far","Le financier"], correct: 1 },
  { text: "Quel flan breton aux pruneaux est traditionnel ?", options: ["Le far breton","Le clafoutis","La tarte","Le pudding"], correct: 0 },
  { text: "Quel dessert français aux cerises est cuit dans une pâte à flan ?", options: ["Le far","Le clafoutis","La tarte Tatin","Le baba"], correct: 1 },
  { text: "Quel petit gâteau moelleux en forme de coquillage est célèbre ?", options: ["Le canelé","La madeleine","Le financier","Le macaron"], correct: 1 },
  { text: "Quel dessert glacé est servi en boules ?", options: ["Le sorbet/la glace","La mousse","Le flan","La crème brûlée"], correct: 0 },
  { text: "Quelle crème dessert a une couche de sucre caramélisé sur le dessus ?", options: ["La crème brûlée","La mousse au chocolat","Le riz au lait","Le flan nature"], correct: 0 },
  { text: "Quel dessert au chocolat est aérien et léger ?", options: ["La mousse au chocolat","La tarte","Le sablé","Le cookie"], correct: 0 },
  { text: "Quel gâteau d'anniversaire porte souvent des bougies ?", options: ["Le pain","Le gâteau","La quiche","La pizza"], correct: 1 },
  { text: "Quelle tarte salée lorraine contient lardons et œufs ?", options: ["La pissaladière","La quiche lorraine","La tarte flambée","La pizza"], correct: 1 },
  { text: "Quelle spécialité alsacienne est une fine tarte à la crème et aux lardons ?", options: ["La quiche","La tarte flambée (flammekueche)","La pissaladière","La fougasse"], correct: 1 },
  { text: "Quel pain plat provençal aux olives et oignons connais-tu ?", options: ["La fougasse","Le bagel","La pita","Le naan"], correct: 0 },
  { text: "Quelle boisson chaude noire se prépare avec des grains moulus ?", options: ["Le thé","Le café","Le chocolat","La tisane"], correct: 1 },
  { text: "Quelle boisson chaude se prépare en infusant des feuilles ?", options: ["Le café","Le thé","Le lait","Le jus"], correct: 1 },
  { text: "Quelle boisson chaude réconfortante est à base de cacao ?", options: ["Le café","Le chocolat chaud","Le thé","La tisane"], correct: 1 },
  { text: "Quel ustensile sert à éplucher les légumes ?", options: ["La louche","L'économe (épluche-légumes)","La passoire","Le fouet"], correct: 1 },
  { text: "Quel ustensile sert à égoutter les pâtes ?", options: ["La poêle","La passoire","La louche","La spatule"], correct: 1 },
  { text: "Quel ustensile sert à retourner une crêpe ?", options: ["La louche","La spatule","Le fouet","La râpe"], correct: 1 },
  { text: "Dans quoi cuit-on traditionnellement une omelette ?", options: ["Une casserole","Une poêle","Un four","Une cocotte"], correct: 1 },
  { text: "Quel mode de cuisson utilise la vapeur d'eau ?", options: ["La friture","La cuisson vapeur","Le grill","Le rôtissage"], correct: 1 },
  { text: "Quel mode de cuisson dore la viande au four ?", options: ["Le pochage","Le rôtissage","La cuisson vapeur","La marinade"], correct: 1 },
  { text: "Quelle céréale sert à faire la semoule du couscous ?", options: ["Le riz","Le blé dur","Le maïs","L'orge"], correct: 1 },
  { text: "Quel plat nord-africain associe semoule, légumes et viande ?", options: ["La paella","Le couscous","Le risotto","Le pilaf"], correct: 1 },
  { text: "Quel plat mijoté cuit dans un plat conique en terre (Maghreb) ?", options: ["Le couscous","Le tajine","Le méchoui","La pastilla"], correct: 1 },
  { text: "Quelle pâtisserie orientale au miel et fruits secs est en couches fines ?", options: ["Le baklava","Le macaron","Le mille-feuille","Le cannelé"], correct: 0 },
  { text: "Quel plat japonais associe riz vinaigré et poisson cru ?", options: ["Le ramen","Le sushi","Le gyoza","Le tempura"], correct: 1 },
  { text: "Quel condiment vert et piquant accompagne les sushis ?", options: ["Le gingembre","Le wasabi","Le miso","La sauce soja"], correct: 1 },
  { text: "Quelle sauce salée à base de soja est très utilisée en Asie ?", options: ["La sauce tomate","La sauce soja","La béchamel","Le ketchup"], correct: 1 },
  { text: "Quel plat mexicain est une galette de maïs garnie et pliée ?", options: ["La pizza","Le taco","La crêpe","Le naan"], correct: 1 },
  { text: "Quelle préparation mexicaine écrase l'avocat avec des épices ?", options: ["La salsa","Le guacamole","Le houmous","Le pesto"], correct: 1 },
  { text: "Quelle soupe espagnole froide est à base de tomate ?", options: ["Le minestrone","Le gaspacho","Le bortsch","Le velouté"], correct: 1 },
  { text: "Quel plat espagnol au riz et au safran contient souvent des fruits de mer ?", options: ["Le risotto","La paella","Le couscous","Le pilaf"], correct: 1 },
  { text: "Quel jambon cru espagnol est très réputé ?", options: ["Le jambon de Paris","Le jambon ibérique (Pata Negra)","Le jambon blanc","Le bacon"], correct: 1 },
  { text: "Quel jambon cru italien se sert en fines tranches ?", options: ["Le prosciutto","Le bacon","Le jambon de York","Le jambon cuit"], correct: 0 },
  { text: "Quel fromage grec blanc se conserve traditionnellement en saumure ?", options: ["La mozzarella","La feta","Le cheddar","Le gouda"], correct: 1 },
  { text: "Quel fromage suisse à trous est célèbre ?", options: ["Le brie","L'emmental","Le roquefort","Le camembert"], correct: 1 },
  { text: "Quel plat suisse consiste à faire fondre du fromage à racler ?", options: ["La fondue","La raclette","La tartiflette","Le gratin"], correct: 1 },
  { text: "Quel vin doit-on généralement servir frais ?", options: ["Le vin rouge corsé","Le vin blanc","Le porto rouge","Le vin chaud"], correct: 1 },
  { text: "Quel vin accompagne traditionnellement le fromage et la viande rouge ?", options: ["Le vin blanc sec","Le vin rouge","Le rosé pétillant","Le cidre"], correct: 1 },
  { text: "Quelle boisson alcoolisée est faite à partir d'orge et de houblon ?", options: ["Le vin","La bière","Le cidre","Le rhum"], correct: 1 },
  { text: "Quel ingrédient amer donne son goût à la bière ?", options: ["Le houblon","Le miel","La cannelle","Le café"], correct: 0 },
  { text: "Quelle boisson alcoolisée est distillée à partir de canne à sucre ?", options: ["Le whisky","Le rhum","Le gin","La vodka"], correct: 1 },
  { text: "Quelle céréale est à la base de la plupart des vodkas et whiskies ?", options: ["Le riz","Les céréales (orge, seigle, blé)","Le maïs uniquement","Le raisin"], correct: 1 },
  { text: "Quel agrume est utilisé pour parfumer le thé Earl Grey ?", options: ["Le citron","La bergamote","L'orange","Le pamplemousse"], correct: 1 },
  { text: "Quelle épice rouge et douce est faite de poivrons séchés ?", options: ["Le curcuma","Le paprika","Le safran","Le cumin"], correct: 1 },
  { text: "Quelle épice jaune vif colore le riz et le curry ?", options: ["Le paprika","Le curcuma","La cannelle","Le clou de girofle"], correct: 1 },
  { text: "Quelle épice est la plus chère au monde (pistils de crocus) ?", options: ["La vanille","Le safran","La cardamome","Le poivre"], correct: 1 },
  { text: "Quelle gousse parfumée est utilisée dans les desserts et les glaces ?", options: ["La cannelle","La vanille","Le gingembre","La muscade"], correct: 1 },
  { text: "Quel condiment jaune fort accompagne souvent les viandes ?", options: ["Le ketchup","La moutarde","La mayonnaise","Le miel"], correct: 1 },
  { text: "Quelle ville française est réputée pour sa moutarde ?", options: ["Lyon","Dijon","Reims","Nantes"], correct: 1 },
  { text: "Quelle viande est traditionnellement utilisée pour le bœuf bourguignon ?", options: ["Le porc","Le bœuf","Le poulet","L'agneau"], correct: 1 },
  { text: "Quel plat français associe pommes de terre, reblochon et lardons ?", options: ["La raclette","La tartiflette","L'aligot","Le gratin dauphinois"], correct: 1 },
  { text: "Quel gratin français de pommes de terre à la crème est célèbre ?", options: ["La tartiflette","Le gratin dauphinois","L'aligot","La purée"], correct: 1 },
  { text: "Quel plat du Sud-Ouest associe haricots blancs, saucisse et confit ?", options: ["La choucroute","Le cassoulet","La ratatouille","Le pot-au-feu"], correct: 1 },
  { text: "Quel ragoût provençal mêle aubergines, courgettes, poivrons et tomates ?", options: ["Le cassoulet","La ratatouille","La bouillabaisse","Le pot-au-feu"], correct: 1 },
  { text: "Quelle soupe de poissons est la spécialité de Marseille ?", options: ["La bisque","La bouillabaisse","Le velouté","Le bortsch"], correct: 1 },
  { text: "Quel plat traditionnel français mijote viande et légumes dans un bouillon ?", options: ["La ratatouille","Le pot-au-feu","La quiche","La fondue"], correct: 1 },
  { text: "Quelle viande blanche et maigre est la volaille la plus consommée ?", options: ["Le canard","Le poulet","La dinde","La pintade"], correct: 1 },
  { text: "Quel produit de luxe est composé du foie engraissé d'un canard ou d'une oie ?", options: ["Le caviar","Le foie gras","La truffe","Le homard"], correct: 1 },
  { text: "Quel mets noir rare est un champignon souterrain très cher ?", options: ["Le cèpe","La truffe","La morille","Le shiitaké"], correct: 1 },
  { text: "Quels œufs noirs constituent le caviar ?", options: ["Œufs de saumon","Œufs d'esturgeon","Œufs de truite","Œufs de hareng"], correct: 1 },
  { text: "Quel crustacé à grosses pinces est un mets de fête ?", options: ["La crevette","Le homard","La moule","La palourde"], correct: 1 },
  { text: "Quel coquillage produit parfois une perle ?", options: ["La moule","L'huître","La coquille Saint-Jacques","Le bulot"], correct: 1 },
  { text: "Quel pain français long et fin est emblématique du pays ?", options: ["La brioche","La baguette","Le pain de mie","Le bagel"], correct: 1 },
  { text: "Quelle viennoiserie feuilletée a la forme d'un croissant ?", options: ["Le pain au lait","Le croissant","La brioche","Le chausson"], correct: 1 },
  { text: "Quelle pâte à base d'eau, beurre, farine et œufs sert aux éclairs ?", options: ["La pâte brisée","La pâte à choux","La pâte feuilletée","La pâte sablée"], correct: 1 },
  { text: "Quel dessert français long est fourré de crème et glacé ?", options: ["Le mille-feuille","L'éclair","La tarte","Le sablé"], correct: 1 },
  { text: "Quelle pâtisserie ronde à deux coques et une garniture est typiquement française ?", options: ["Le macaron","Le cupcake","Le brownie","Le donut"], correct: 0 },
  { text: "Quelle confiserie est faite de sucre cuit et étiré, souvent colorée ?", options: ["Le chocolat","Le bonbon","Le biscuit","Le gâteau"], correct: 1 },
  { text: "Quel produit sucré tartine-t-on souvent sur les tartines au petit-déjeuner ?", options: ["La moutarde","La confiture","La mayonnaise","Le ketchup"], correct: 1 },
  { text: "Quelle pâte à tartiner mêle chocolat et noisettes ?", options: ["La confiture","La pâte de noisettes chocolatée","Le beurre","Le miel"], correct: 1 },
  { text: "Quel fromage à pâte dure du Jura est affiné longtemps ?", options: ["Le camembert","Le comté","Le roquefort","Le munster"], correct: 1 },
  { text: "Quel mode de conservation par le froid garde les aliments longtemps ?", options: ["La friture","La congélation","Le fumage","La marinade"], correct: 1 },
  { text: "Quelle technique conserve poissons et viandes par la fumée ?", options: ["Le fumage","La congélation","La friture","Le pochage"], correct: 0 },
];
