// QuizzMaster — thème 🍷 Gastronomie & Vins. 114 questions.

module.exports = [
  { text: "Quel cépage rouge domine en Bourgogne ?", options: ["Cabernet Sauvignon","Pinot Noir","Merlot","Syrah"], correct: 1 },
  { text: "Quel cépage blanc règne à Chablis ?", options: ["Sauvignon","Chardonnay","Riesling","Viognier"], correct: 1 },
  { text: "Quelle région produit le Sancerre ?", options: ["Bourgogne","Loire","Bordeaux","Alsace"], correct: 1 },
  { text: "Quel cépage donne le Beaujolais ?", options: ["Gamay","Pinot Noir","Syrah","Grenache"], correct: 0 },
  { text: "Quel vin doux est produit dans le Sauternais ?", options: ["Banyuls","Sauternes","Muscat","Pineau"], correct: 1 },
  { text: "Quel cépage produit l'Hermitage rouge (Rhône nord) ?", options: ["Grenache","Mourvèdre","Syrah","Cinsault"], correct: 2 },
  { text: "Que désigne le « millésime » d'un vin ?", options: ["Le degré d'alcool","L'année de récolte","Le sol","Le nombre de bouteilles"], correct: 1 },
  { text: "Quelle est la contenance d'une bouteille de vin standard ?", options: ["50 cl","70 cl","75 cl","100 cl"], correct: 2 },
  { text: "Quel cépage blanc évoque le pamplemousse et le buis ?", options: ["Chardonnay","Sauvignon Blanc","Riesling","Viognier"], correct: 1 },
  { text: "Quel vin pétillant français est associé aux fêtes ?", options: ["Bordeaux","Champagne","Beaujolais","Sancerre"], correct: 1 },
  { text: "Quel département produit le plus de Champagne ?", options: ["Aube","Marne","Aisne","Haute-Marne"], correct: 1 },
  { text: "Quelle ville est la capitale des vins de Bordeaux ?", options: ["Bordeaux","Lyon","Dijon","Reims"], correct: 0 },
  { text: "Quel fromage bleu est affiné dans des grottes de l'Aveyron ?", options: ["Bleu d'Auvergne","Roquefort","Fourme d'Ambert","Bleu de Bresse"], correct: 1 },
  { text: "Le Comté est un fromage au lait de…", options: ["Brebis","Chèvre","Vache","Bufflonne"], correct: 2 },
  { text: "Quel fromage normand a une croûte fleurie blanche ?", options: ["Comté","Camembert","Roquefort","Cantal"], correct: 1 },
  { text: "Le Roquefort est un fromage au lait de…", options: ["Vache","Brebis","Chèvre","Jument"], correct: 1 },
  { text: "De quel pays vient la mozzarella di bufala ?", options: ["France","Italie","Grèce","Suisse"], correct: 1 },
  { text: "Quel fromage suisse est fondu pour la raclette ?", options: ["Gruyère","Emmental","Raclette","Tomme"], correct: 2 },
  { text: "Le Beaufort est un fromage de quel massif ?", options: ["Vosges","Pyrénées","Alpes","Massif central"], correct: 2 },
  { text: "Quelle est l'origine du bœuf bourguignon ?", options: ["Lyon","Bourgogne","Provence","Normandie"], correct: 1 },
  { text: "Quels ingrédients composent la pâte à choux ?", options: ["Levure","Beurre, œufs, farine, eau","Pommes de terre","Crème"], correct: 1 },
  { text: "Quelle sauce mère est à base de roux blanc et de lait ?", options: ["Béchamel","Hollandaise","Espagnole","Velouté"], correct: 0 },
  { text: "Quel chef est associé à la nouvelle cuisine et à Lyon ?", options: ["Escoffier","Paul Bocuse","Robuchon","Ducasse"], correct: 1 },
  { text: "Le kouign-amann est une spécialité de quelle région ?", options: ["Alsace","Bretagne","Provence","Auvergne"], correct: 1 },
  { text: "Quel poisson entre dans la quenelle lyonnaise ?", options: ["Sole","Brochet","Truite","Saumon"], correct: 1 },
  { text: "De quel pays vient le sushi ?", options: ["Chine","Japon","Corée","Thaïlande"], correct: 1 },
  { text: "Quel plat espagnol mêle riz, safran et fruits de mer ?", options: ["Risotto","Paella","Couscous","Tajine"], correct: 1 },
  { text: "De quel pays vient le ceviche ?", options: ["Mexique","Pérou","Chili","Brésil"], correct: 1 },
  { text: "Le pho est un plat traditionnel de quel pays ?", options: ["Thaïlande","Cambodge","Vietnam","Laos"], correct: 2 },
  { text: "Le falafel est à base de…", options: ["Pois chiches ou fèves","Lentilles","Quinoa","Haricots noirs"], correct: 0 },
  { text: "De quel pays vient la pizza ?", options: ["Grèce","Italie","Espagne","Turquie"], correct: 1 },
  { text: "De quel pays viennent les tacos (origine) ?", options: ["Espagne","Mexique","Pérou","Cuba"], correct: 1 },
  { text: "De quel pays vient le couscous (Maghreb) ?", options: ["Liban","Maghreb","Turquie","Iran"], correct: 1 },
  { text: "À partir de quoi est distillé le calvados ?", options: ["Raisin","Pommes (cidre)","Poire","Prune"], correct: 1 },
  { text: "Quel cocktail mêle rhum, citron vert et menthe ?", options: ["Daiquiri","Mojito","Caipirinha","Piña Colada"], correct: 1 },
  { text: "Le saké est obtenu par fermentation de…", options: ["Raisin","Orge","Riz","Pomme"], correct: 2 },
  { text: "« Mise en place » signifie en cuisine…", options: ["Servir l'assiette","Préparer les ingrédients avant cuisson","Dresser la table","Goûter"], correct: 1 },
  { text: "Quel fruit est la base du chutney indien classique ?", options: ["Pomme","Mangue","Banane","Tomate"], correct: 1 },
  { text: "Quelle pâte fine sert à faire les baklavas ?", options: ["Brisée","Phyllo (filo)","Sablée","Sucrée"], correct: 1 },
  { text: "Quel plat alsacien associe choux et charcuterie ?", options: ["Cassoulet","Choucroute","Aligot","Tartiflette"], correct: 1 },
  { text: "Quel plat savoyard mêle pommes de terre, reblochon et lardons ?", options: ["Raclette","Tartiflette","Fondue","Aligot"], correct: 1 },
  { text: "Quel plat du Sud-Ouest associe haricots et confit ?", options: ["Choucroute","Cassoulet","Pot-au-feu","Aligot"], correct: 1 },
  { text: "Quelle spécialité aveyronnaise mêle purée et tome fraîche filante ?", options: ["Aligot","Truffade","Gratin","Tartiflette"], correct: 0 },
  { text: "Quel dessert français est une crème renversée au caramel ?", options: ["Île flottante","Crème caramel (flan)","Clafoutis","Tarte Tatin"], correct: 1 },
  { text: "Quelle tarte aux pommes est cuite à l'envers ?", options: ["Tarte Bourdaloue","Tarte Tatin","Tarte normande","Tarte fine"], correct: 1 },
  { text: "Quel petit gâteau bordelais est cannelé et caramélisé ?", options: ["Madeleine","Canelé","Macaron","Financier"], correct: 1 },
  { text: "Quel biscuit en forme de coquillage est lié à Commercy ?", options: ["Canelé","Madeleine","Financier","Tuile"], correct: 1 },
  { text: "Quelle pâtisserie ronde à deux coques colorées est française ?", options: ["Le macaron","Le cupcake","Le donut","Le brownie"], correct: 0 },
  { text: "Quel vin rouge primeur sort le 3e jeudi de novembre ?", options: ["Bordeaux nouveau","Beaujolais nouveau","Côtes-du-Rhône","Chinon"], correct: 1 },
  { text: "Quelle boisson anisée du Sud se boit avec de l'eau ?", options: ["Le pastis","Le cidre","Le kir","Le calva"], correct: 0 },
  { text: "Quel apéritif mêle vin blanc et crème de cassis ?", options: ["Le kir","Le spritz","Le pastis","Le porto"], correct: 0 },
  { text: "Quel alcool écossais est distillé à partir d'orge maltée ?", options: ["Le cognac","Le whisky","La vodka","Le gin"], correct: 1 },
  { text: "Le cognac est produit en France à partir de…", options: ["Pommes","Raisin","Orge","Seigle"], correct: 1 },
  { text: "Quel champagne sans année est dit…", options: ["Brut sans année","Millésimé","Rosé seulement","Demi-sec"], correct: 0 },
  { text: "Quelle région produit le vin de Bordeaux ?", options: ["Aquitaine/Gironde","Alsace","Savoie","Provence"], correct: 0 },
  { text: "Quel cépage emblématique compose souvent le Bordeaux rouge ?", options: ["Pinot Noir","Cabernet Sauvignon / Merlot","Gamay","Syrah"], correct: 1 },
  { text: "Quelle est la température idéale de service d'un Champagne ?", options: ["18 °C","8 °C","25 °C","2 °C"], correct: 1 },
  { text: "Quel vin sert traditionnellement avec les huîtres ?", options: ["Vin rouge corsé","Muscadet / vin blanc sec","Porto","Vin doux"], correct: 1 },
  { text: "Quel fromage italien dur s'affine 12 mois minimum ?", options: ["Mozzarella","Parmigiano Reggiano","Ricotta","Burrata"], correct: 1 },
  { text: "Quel fromage grec est utilisé dans la salade grecque ?", options: ["Mozzarella","Feta","Cheddar","Gouda"], correct: 1 },
  { text: "Quel fromage néerlandais est jaune et doux ?", options: ["Gouda","Roquefort","Brie","Comté"], correct: 0 },
  { text: "Quel fromage anglais orange est très connu ?", options: ["Cheddar","Stilton","Brie","Edam"], correct: 0 },
  { text: "Quel plat italien est composé de pâtes longues et fines ?", options: ["Lasagnes","Spaghetti","Gnocchi","Risotto"], correct: 1 },
  { text: "Quel riz italien crémeux est cuit lentement ?", options: ["Paella","Risotto","Pilaf","Riz cantonais"], correct: 1 },
  { text: "Quelle herbe aromatique parfume le pesto ?", options: ["Persil","Basilic","Coriandre","Menthe"], correct: 1 },
  { text: "Quelle épice rouge et chère provient d'un crocus ?", options: ["Paprika","Safran","Curcuma","Piment"], correct: 1 },
  { text: "Quelle épice jaune colore le curry ?", options: ["Cannelle","Curcuma","Cumin","Gingembre"], correct: 1 },
  { text: "Quel agrume est utilisé pour le limoncello ?", options: ["Orange","Citron","Pamplemousse","Mandarine"], correct: 1 },
  { text: "Quel plat japonais est composé de poisson cru sans riz ?", options: ["Sushi","Sashimi","Maki","Tempura"], correct: 1 },
  { text: "Quel beignet japonais de légumes ou crevettes est frit ?", options: ["Gyoza","Tempura","Ramen","Onigiri"], correct: 1 },
  { text: "Quelle soupe de nouilles japonaise est très populaire ?", options: ["Pho","Ramen","Laksa","Tom yum"], correct: 1 },
  { text: "Quel plat coréen est du riz mélangé avec légumes et œuf ?", options: ["Kimchi","Bibimbap","Bulgogi","Japchae"], correct: 1 },
  { text: "Quel chou fermenté épicé est emblématique de la Corée ?", options: ["Choucroute","Kimchi","Wasabi","Miso"], correct: 1 },
  { text: "Quelle pâte de soja fermentée parfume la soupe japonaise ?", options: ["Le tofu","Le miso","Le tahini","Le houmous"], correct: 1 },
  { text: "De quel pays vient le tiramisu ?", options: ["France","Italie","Espagne","Grèce"], correct: 1 },
  { text: "Quel ingrédient amer aromatise le tiramisu ?", options: ["Le thé","Le café","Le chocolat blanc","La vanille"], correct: 1 },
  { text: "Quel dessert espagnol est une crème aux œufs caramélisée ?", options: ["Tiramisu","Crème catalane","Panna cotta","Tarte"], correct: 1 },
  { text: "Quel dessert italien est une crème prise à la gélatine ?", options: ["Tiramisu","Panna cotta","Cannoli","Gelato"], correct: 1 },
  { text: "Quel plat indien est un poulet en sauce épicée orangée ?", options: ["Pad thaï","Poulet tikka massala","Bibimbap","Pho"], correct: 1 },
  { text: "Quel pain indien plat est cuit au four tandoor ?", options: ["Pita","Naan","Tortilla","Baguette"], correct: 1 },
  { text: "Quel plat thaïlandais est une soupe épicée et acidulée ?", options: ["Pad thaï","Tom yum","Pho","Laksa"], correct: 1 },
  { text: "Quel plat mexicain est une galette de maïs garnie et roulée ?", options: ["Taco","Burrito","Paella","Empanada"], correct: 1 },
  { text: "Quel avocat écrasé épicé est une spécialité mexicaine ?", options: ["Salsa","Guacamole","Houmous","Tzatziki"], correct: 1 },
  { text: "Quelle sauce grecque mêle yaourt, concombre et ail ?", options: ["Houmous","Tzatziki","Pesto","Aïoli"], correct: 1 },
  { text: "Quelle purée de pois chiches est typique du Moyen-Orient ?", options: ["Tzatziki","Houmous","Guacamole","Pesto"], correct: 1 },
  { text: "Quel plat marocain mijote dans un plat conique en terre ?", options: ["Couscous","Tajine","Méchoui","Pastilla"], correct: 1 },
  { text: "Quel mélange d'épices est typique du Maghreb ?", options: ["Garam masala","Ras el-hanout","Cinq-épices","Curry"], correct: 1 },
  { text: "Quel pain plat est utilisé dans le kebab/döner ?", options: ["Baguette","Pain pita","Brioche","Ciabatta"], correct: 1 },
  { text: "Quel plat vietnamien est un rouleau de printemps frais ?", options: ["Nem frit","Gỏi cuốn (rouleau frais)","Bao","Gyoza"], correct: 1 },
  { text: "Quelle viande n'est pas consommée dans la cuisine hindoue traditionnelle ?", options: ["Le poulet","Le bœuf","Le poisson","L'agneau"], correct: 1 },
  { text: "Quelle boisson chaude est faite de feuilles infusées ?", options: ["Le café","Le thé","Le cacao","Le lait"], correct: 1 },
  { text: "Quelle boisson est issue de grains torréfiés et moulus ?", options: ["Le thé","Le café","Le cidre","Le jus"], correct: 1 },
  { text: "Quel fruit sert à faire le vin ?", options: ["La pomme","Le raisin","La poire","La prune"], correct: 1 },
  { text: "Quel fruit sert à faire le cidre ?", options: ["Le raisin","La pomme","La cerise","La fraise"], correct: 1 },
  { text: "Quel produit de la ruche est un édulcorant naturel ?", options: ["Le sucre","Le miel","Le sirop d'érable","La mélasse"], correct: 1 },
  { text: "De quel arbre vient le sirop d'érable ?", options: ["Le chêne","L'érable","Le bouleau","Le pin"], correct: 1 },
  { text: "Quel ustensile sert à fouetter les blancs en neige ?", options: ["La spatule","Le fouet","La louche","La maryse"], correct: 1 },
  { text: "À quelle température cuit-on généralement un gâteau au four (th. moyen) ?", options: ["120 °C","180 °C","250 °C","90 °C"], correct: 1 },
  { text: "Quel mode de cuisson utilise de l'eau bouillante ?", options: ["La friture","L'ébullition","Le rôtissage","Le grill"], correct: 1 },
  { text: "Quel mode de cuisson plonge l'aliment dans l'huile chaude ?", options: ["La friture","La vapeur","Le pochage","Le braisage"], correct: 0 },
  { text: "Quelle viande compose le steak tartare (cru) ?", options: ["Porc","Bœuf","Poulet","Agneau"], correct: 1 },
  { text: "Quel poisson gras et rose est souvent fumé ?", options: ["Cabillaud","Saumon","Sole","Merlu"], correct: 1 },
  { text: "Quel mollusque se déguste cru avec du citron ?", options: ["La moule","L'huître","La palourde","Le bulot"], correct: 1 },
  { text: "Quel fruit de mer rose se pêche et se déguste en plateau ?", options: ["La crevette","Le concombre de mer","L'anguille","Le calmar séché"], correct: 0 },
  { text: "Quel champignon noir et rare est très prisé en cuisine ?", options: ["Le cèpe","La truffe","La girolle","Le shiitaké"], correct: 1 },
  { text: "Quelle viande est l'ingrédient principal du foie gras ?", options: ["Le porc","Le canard ou l'oie","Le bœuf","Le poulet"], correct: 1 },
  { text: "Quel pain français long et croustillant est emblématique ?", options: ["La brioche","La baguette","Le pain de mie","Le bagel"], correct: 1 },
  { text: "Quelle viennoiserie est faite de pâte feuilletée en croissant ?", options: ["Le pain au lait","Le croissant","La brioche","Le chausson"], correct: 1 },
  { text: "Quel plat italien superpose pâtes, sauce et béchamel ?", options: ["Risotto","Lasagnes","Gnocchi","Polenta"], correct: 1 },
  { text: "Quelle céréale sert à faire la polenta ?", options: ["Le blé","Le maïs","Le riz","L'avoine"], correct: 1 },
  { text: "Quel alcool mexicain est tiré de l'agave ?", options: ["Le rhum","La tequila","Le pisco","Le mezcal seul"], correct: 1 },
  { text: "Quel alcool cubain est à base de canne à sucre ?", options: ["La vodka","Le rhum","Le gin","Le whisky"], correct: 1 },
  { text: "Quel vin portugais muté est célèbre (ville de Porto) ?", options: ["Le xérès","Le porto","Le madère","Le marsala"], correct: 1 },
  { text: "Quel vin espagnol muté vient d'Andalousie ?", options: ["Le porto","Le xérès (sherry)","Le marsala","Le tokaji"], correct: 1 },
];
