// QuizzMaster — thème 🌍 Géographie. 300 questions.

module.exports = [
  { text: "Quelle est la capitale de la France ?", options: ["Londres","Paris","Bucarest","Le Caire"], correct: 1 },
  { text: "Quelle est la capitale de l'Allemagne ?", options: ["Bucarest","Berlin","Le Caire","Washington"], correct: 1 },
  { text: "Quelle est la capitale de l'Espagne ?", options: ["Le Caire","Madrid","Washington","Tokyo"], correct: 1 },
  { text: "Quelle est la capitale de l'Italie ?", options: ["Washington","Rome","Tokyo","Riyad"], correct: 1 },
  { text: "Quelle est la capitale de le Portugal ?", options: ["Tokyo","Lisbonne","Riyad","Dacca"], correct: 1 },
  { text: "Quelle est la capitale de le Royaume-Uni ?", options: ["Riyad","Londres","Dacca","Abou Dabi"], correct: 1 },
  { text: "Quelle est la capitale de l'Irlande ?", options: ["Dacca","Dublin","Abou Dabi","Tripoli"], correct: 1 },
  { text: "Quelle est la capitale de la Belgique ?", options: ["Abou Dabi","Bruxelles","Tripoli","Vienne"], correct: 1 },
  { text: "Quelle est la capitale de les Pays-Bas ?", options: ["Tripoli","Amsterdam","Vienne","Belgrade"], correct: 1 },
  { text: "Quelle est la capitale de la Suisse ?", options: ["Vienne","Berne","Belgrade","Pretoria"], correct: 1 },
  { text: "Quelle est la capitale de l'Autriche ?", options: ["Belgrade","Vienne","Pretoria","Buenos Aires"], correct: 1 },
  { text: "Quelle est la capitale de la Grèce ?", options: ["Pretoria","Athènes","Buenos Aires","Bangkok"], correct: 1 },
  { text: "Quelle est la capitale de la Suède ?", options: ["Buenos Aires","Stockholm","Bangkok","Kaboul"], correct: 1 },
  { text: "Quelle est la capitale de la Norvège ?", options: ["Bangkok","Oslo","Kaboul","Riga"], correct: 1 },
  { text: "Quelle est la capitale de le Danemark ?", options: ["Kaboul","Copenhague","Riga","Astana"], correct: 1 },
  { text: "Quelle est la capitale de la Finlande ?", options: ["Riga","Helsinki","Astana","Madrid"], correct: 1 },
  { text: "Quelle est la capitale de la Pologne ?", options: ["Astana","Varsovie","Madrid","Helsinki"], correct: 1 },
  { text: "Quelle est la capitale de la Hongrie ?", options: ["Madrid","Budapest","Helsinki","Rabat"], correct: 1 },
  { text: "Quelle est la capitale de la Roumanie ?", options: ["Helsinki","Bucarest","Rabat","Kinshasa"], correct: 1 },
  { text: "Quelle est la capitale de la Bulgarie ?", options: ["Rabat","Sofia","Kinshasa","Montevideo"], correct: 1 },
  { text: "Quelle est la capitale de la République tchèque ?", options: ["Kinshasa","Prague","Montevideo","Singapour"], correct: 1 },
  { text: "Quelle est la capitale de la Slovaquie ?", options: ["Montevideo","Bratislava","Singapour","Naypyidaw"], correct: 1 },
  { text: "Quelle est la capitale de la Croatie ?", options: ["Singapour","Zagreb","Naypyidaw","La Valette"], correct: 1 },
  { text: "Quelle est la capitale de la Serbie ?", options: ["Naypyidaw","Belgrade","La Valette","Lusaka"], correct: 1 },
  { text: "Quelle est la capitale de la Russie ?", options: ["La Valette","Moscou","Lusaka","Bruxelles"], correct: 1 },
  { text: "Quelle est la capitale de l'Ukraine ?", options: ["Lusaka","Kiev","Bruxelles","Prague"], correct: 1 },
  { text: "Quelle est la capitale de la Turquie ?", options: ["Bruxelles","Ankara","Prague","Yamoussoukro"], correct: 1 },
  { text: "Quelle est la capitale de la Géorgie ?", options: ["Prague","Tbilissi","Yamoussoukro","Mexico"], correct: 1 },
  { text: "Quelle est la capitale de le Maroc ?", options: ["Yamoussoukro","Rabat","Mexico","Pyongyang"], correct: 1 },
  { text: "Quelle est la capitale de l'Algérie ?", options: ["Mexico","Alger","Pyongyang","Amman"], correct: 1 },
  { text: "Quelle est la capitale de la Tunisie ?", options: ["Pyongyang","Tunis","Amman","Luxembourg"], correct: 1 },
  { text: "Quelle est la capitale de l'Égypte ?", options: ["Amman","Le Caire","Luxembourg","Mascate"], correct: 1 },
  { text: "Quelle est la capitale de le Sénégal ?", options: ["Luxembourg","Dakar","Mascate","Kampala"], correct: 1 },
  { text: "Quelle est la capitale de la Côte d'Ivoire ?", options: ["Mascate","Yamoussoukro","Kampala","Stockholm"], correct: 1 },
  { text: "Quelle est la capitale de le Nigeria ?", options: ["Kampala","Abuja","Stockholm","Kiev"], correct: 1 },
  { text: "Quelle est la capitale de le Kenya ?", options: ["Stockholm","Nairobi","Kiev","Accra"], correct: 1 },
  { text: "Quelle est la capitale de l'Afrique du Sud ?", options: ["Kiev","Pretoria","Accra","Lima"], correct: 1 },
  { text: "Quelle est la capitale de l'Éthiopie ?", options: ["Accra","Addis-Abeba","Lima","Jakarta"], correct: 1 },
  { text: "Quelle est la capitale de le Ghana ?", options: ["Lima","Accra","Jakarta","Wellington"], correct: 1 },
  { text: "Quelle est la capitale de le Mali ?", options: ["Jakarta","Bamako","Wellington","Minsk"], correct: 1 },
  { text: "Quelle est la capitale de le Cameroun ?", options: ["Wellington","Yaoundé","Minsk","Bakou"], correct: 1 },
  { text: "Quelle est la capitale de la RD Congo ?", options: ["Minsk","Kinshasa","Bakou","Lisbonne"], correct: 1 },
  { text: "Quelle est la capitale de l'Angola ?", options: ["Bakou","Luanda","Lisbonne","Budapest"], correct: 1 },
  { text: "Quelle est la capitale de la Tanzanie ?", options: ["Lisbonne","Dodoma","Budapest","Tunis"], correct: 1 },
  { text: "Quelle est la capitale de les États-Unis ?", options: ["Budapest","Washington","Tunis","Dodoma"], correct: 1 },
  { text: "Quelle est la capitale de le Canada ?", options: ["Tunis","Ottawa","Dodoma","Pékin"], correct: 1 },
  { text: "Quelle est la capitale de le Mexique ?", options: ["Dodoma","Mexico","Pékin","Bagdad"], correct: 1 },
  { text: "Quelle est la capitale de Cuba ?", options: ["Pékin","La Havane","Bagdad","Katmandou"], correct: 1 },
  { text: "Quelle est la capitale de le Brésil ?", options: ["Bagdad","Brasilia","Katmandou","Doha"], correct: 1 },
  { text: "Quelle est la capitale de l'Argentine ?", options: ["Katmandou","Buenos Aires","Doha","Antananarivo"], correct: 1 },
  { text: "Quelle est la capitale de le Chili ?", options: ["Doha","Santiago","Antananarivo","Berne"], correct: 1 },
  { text: "Quelle est la capitale de le Pérou ?", options: ["Antananarivo","Lima","Berne","Zagreb"], correct: 1 },
  { text: "Quelle est la capitale de la Colombie ?", options: ["Berne","Bogota","Zagreb","Nairobi"], correct: 1 },
  { text: "Quelle est la capitale de le Venezuela ?", options: ["Zagreb","Caracas","Nairobi","Brasilia"], correct: 1 },
  { text: "Quelle est la capitale de l'Uruguay ?", options: ["Nairobi","Montevideo","Brasilia","Islamabad"], correct: 1 },
  { text: "Quelle est la capitale de la Bolivie ?", options: ["Brasilia","La Paz","Islamabad","Damas"], correct: 1 },
  { text: "Quelle est la capitale de la Chine ?", options: ["Islamabad","Pékin","Damas","Vilnius"], correct: 1 },
  { text: "Quelle est la capitale de le Japon ?", options: ["Damas","Tokyo","Vilnius","Oulan-Bator"], correct: 1 },
  { text: "Quelle est la capitale de la Corée du Sud ?", options: ["Vilnius","Séoul","Oulan-Bator","Berlin"], correct: 1 },
  { text: "Quelle est la capitale de la Corée du Nord ?", options: ["Oulan-Bator","Pyongyang","Berlin","Copenhague"], correct: 1 },
  { text: "Quelle est la capitale de l'Inde ?", options: ["Berlin","New Delhi","Copenhague","Tbilissi"], correct: 1 },
  { text: "Quelle est la capitale de le Pakistan ?", options: ["Copenhague","Islamabad","Tbilissi","Yaoundé"], correct: 1 },
  { text: "Quelle est la capitale de la Thaïlande ?", options: ["Tbilissi","Bangkok","Yaoundé","Caracas"], correct: 1 },
  { text: "Quelle est la capitale de le Vietnam ?", options: ["Yaoundé","Hanoï","Caracas","Kuala Lumpur"], correct: 1 },
  { text: "Quelle est la capitale de l'Indonésie ?", options: ["Caracas","Jakarta","Kuala Lumpur","Vientiane"], correct: 1 },
  { text: "Quelle est la capitale de les Philippines ?", options: ["Kuala Lumpur","Manille","Vientiane","Nicosie"], correct: 1 },
  { text: "Quelle est la capitale de la Malaisie ?", options: ["Vientiane","Kuala Lumpur","Nicosie","Harare"], correct: 1 },
  { text: "Quelle est la capitale de Singapour ?", options: ["Nicosie","Singapour","Harare","Dublin"], correct: 1 },
  { text: "Quelle est la capitale de l'Iran ?", options: ["Harare","Téhéran","Dublin","Sofia"], correct: 1 },
  { text: "Quelle est la capitale de l'Irak ?", options: ["Dublin","Bagdad","Sofia","Dakar"], correct: 1 },
  { text: "Quelle est la capitale de l'Arabie saoudite ?", options: ["Sofia","Riyad","Dakar","Ottawa"], correct: 1 },
  { text: "Quelle est la capitale de Israël ?", options: ["Dakar","Jérusalem","Ottawa","Séoul"], correct: 1 },
  { text: "Quelle est la capitale de la Jordanie ?", options: ["Ottawa","Amman","Séoul","Jérusalem"], correct: 1 },
  { text: "Quelle est la capitale de le Liban ?", options: ["Séoul","Beyrouth","Jérusalem","Reykjavik"], correct: 1 },
  { text: "Quelle est la capitale de la Syrie ?", options: ["Jérusalem","Damas","Reykjavik","Koweït"], correct: 1 },
  { text: "Quelle est la capitale de l'Afghanistan ?", options: ["Reykjavik","Kaboul","Koweït","Khartoum"], correct: 1 },
  { text: "Quelle est la capitale de l'Australie ?", options: ["Koweït","Canberra","Khartoum","Athènes"], correct: 1 },
  { text: "Quelle est la capitale de la Nouvelle-Zélande ?", options: ["Khartoum","Wellington","Athènes","Moscou"], correct: 1 },
  { text: "Quelle est la capitale de le Cambodge ?", options: ["Athènes","Phnom Penh","Moscou","Addis-Abeba"], correct: 1 },
  { text: "Quelle est la capitale de le Laos ?", options: ["Moscou","Vientiane","Addis-Abeba","Santiago"], correct: 1 },
  { text: "Quelle est la capitale de la Birmanie ?", options: ["Addis-Abeba","Naypyidaw","Santiago","Hanoï"], correct: 1 },
  { text: "Quelle est la capitale de le Sri Lanka ?", options: ["Santiago","Colombo","Hanoï","Canberra"], correct: 1 },
  { text: "Quelle est la capitale de le Népal ?", options: ["Hanoï","Katmandou","Canberra","Tallinn"], correct: 1 },
  { text: "Quelle est la capitale de le Bangladesh ?", options: ["Canberra","Dacca","Tallinn","Tachkent"], correct: 1 },
  { text: "Quelle est la capitale de l'Islande ?", options: ["Tallinn","Reykjavik","Tachkent","Rome"], correct: 1 },
  { text: "Quelle est la capitale de le Luxembourg ?", options: ["Tachkent","Luxembourg","Rome","Varsovie"], correct: 1 },
  { text: "Quelle est la capitale de la Slovénie ?", options: ["Rome","Ljubljana","Varsovie","Alger"], correct: 1 },
  { text: "Quelle est la capitale de la Lituanie ?", options: ["Varsovie","Vilnius","Alger","Luanda"], correct: 1 },
  { text: "Quelle est la capitale de la Lettonie ?", options: ["Alger","Riga","Luanda","La Paz"], correct: 1 },
  { text: "Quelle est la capitale de l'Estonie ?", options: ["Luanda","Tallinn","La Paz","Téhéran"], correct: 1 },
  { text: "Quelle est la capitale de la Biélorussie ?", options: ["La Paz","Minsk","Téhéran","Colombo"], correct: 1 },
  { text: "Quelle est la capitale de l'Albanie ?", options: ["Téhéran","Tirana","Colombo","Monaco"], correct: 1 },
  { text: "Quelle est la capitale de Chypre ?", options: ["Colombo","Nicosie","Monaco","Maputo"], correct: 1 },
  { text: "Quelle est la capitale de Malte ?", options: ["Monaco","La Valette","Maputo","Amsterdam"], correct: 1 },
  { text: "Quelle est la capitale de Monaco ?", options: ["Maputo","Monaco","Amsterdam","Bratislava"], correct: 1 },
  { text: "Quelle est la capitale de le Qatar ?", options: ["Amsterdam","Doha","Bratislava","Abuja"], correct: 1 },
  { text: "Quelle est la capitale de les Émirats arabes unis ?", options: ["Bratislava","Abou Dabi","Abuja","La Havane"], correct: 1 },
  { text: "Quelle est la capitale de le Koweït ?", options: ["Abuja","Koweït","La Havane","New Delhi"], correct: 1 },
  { text: "Quelle est la capitale de Oman ?", options: ["La Havane","Mascate","New Delhi","Beyrouth"], correct: 1 },
  { text: "Quelle est la capitale de le Yémen ?", options: ["New Delhi","Sanaa","Beyrouth","Ljubljana"], correct: 1 },
  { text: "Quelle est la capitale de la Mongolie ?", options: ["Beyrouth","Oulan-Bator","Ljubljana","Sanaa"], correct: 1 },
  { text: "Quelle est la capitale de le Kazakhstan ?", options: ["Ljubljana","Astana","Sanaa","Paris"], correct: 1 },
  { text: "Quelle est la capitale de l'Ouzbékistan ?", options: ["Sanaa","Tachkent","Paris","Oslo"], correct: 1 },
  { text: "Quelle est la capitale de l'Azerbaïdjan ?", options: ["Paris","Bakou","Oslo","Ankara"], correct: 1 },
  { text: "Quelle est la capitale de l'Arménie ?", options: ["Oslo","Erevan","Ankara","Bamako"], correct: 1 },
  { text: "Quelle est la capitale de le Zimbabwe ?", options: ["Ankara","Harare","Bamako","Bogota"], correct: 1 },
  { text: "Quelle est la capitale de la Zambie ?", options: ["Bamako","Lusaka","Bogota","Manille"], correct: 1 },
  { text: "Quelle est la capitale de le Mozambique ?", options: ["Bogota","Maputo","Manille","Phnom Penh"], correct: 1 },
  { text: "Quelle est la capitale de Madagascar ?", options: ["Manille","Antananarivo","Phnom Penh","Tirana"], correct: 1 },
  { text: "Quelle est la capitale de la Libye ?", options: ["Phnom Penh","Tripoli","Tirana","Erevan"], correct: 1 },
  { text: "Quelle est la capitale de le Soudan ?", options: ["Tirana","Khartoum","Erevan","Londres"], correct: 1 },
  { text: "Quelle est la capitale de l'Ouganda ?", options: ["Erevan","Kampala","Londres","Bucarest"], correct: 1 },
  { text: "Sur quel continent se trouve le Brésil ?", options: ["Europe","Amérique du Sud","Asie","Afrique"], correct: 1 },
  { text: "Sur quel continent se trouve le Nigeria ?", options: ["Europe","Afrique","Asie","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve le Japon ?", options: ["Europe","Asie","Afrique","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve l'Australie ?", options: ["Europe","Océanie","Asie","Afrique"], correct: 1 },
  { text: "Sur quel continent se trouve le Canada ?", options: ["Europe","Amérique du Nord","Asie","Afrique"], correct: 1 },
  { text: "Sur quel continent se trouve l'Égypte ?", options: ["Europe","Afrique","Asie","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve l'Inde ?", options: ["Europe","Asie","Afrique","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve l'Allemagne ?", options: ["Asie","Europe","Afrique","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve le Chili ?", options: ["Europe","Amérique du Sud","Asie","Afrique"], correct: 1 },
  { text: "Sur quel continent se trouve le Kenya ?", options: ["Europe","Afrique","Asie","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve la Thaïlande ?", options: ["Europe","Asie","Afrique","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve la Norvège ?", options: ["Asie","Europe","Afrique","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve le Mexique ?", options: ["Europe","Amérique du Nord","Asie","Afrique"], correct: 1 },
  { text: "Sur quel continent se trouve l'Afrique du Sud ?", options: ["Europe","Afrique","Asie","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve la Mongolie ?", options: ["Europe","Asie","Afrique","Amérique du Nord"], correct: 1 },
  { text: "Sur quel continent se trouve la Nouvelle-Zélande ?", options: ["Europe","Océanie","Asie","Afrique"], correct: 1 },
  { text: "Quel est le plus long fleuve du monde ?", options: ["Nil","Amazone","Yangtsé","Mississippi"], correct: 0 },
  { text: "Quel est le plus grand océan ?", options: ["Atlantique","Indien","Pacifique","Arctique"], correct: 2 },
  { text: "Quel est le plus haut sommet du monde ?", options: ["K2","Everest","Mont Blanc","Kilimandjaro"], correct: 1 },
  { text: "Quel est le plus grand désert chaud ?", options: ["Gobi","Sahara","Kalahari","Atacama"], correct: 1 },
  { text: "Quel pays est le plus vaste du monde ?", options: ["Chine","Canada","Russie","États-Unis"], correct: 2 },
  { text: "Quel est le plus grand pays d'Amérique du Sud ?", options: ["Argentine","Brésil","Pérou","Colombie"], correct: 1 },
  { text: "Quelle est la plus grande île du monde ?", options: ["Bornéo","Groenland","Madagascar","Nouvelle-Guinée"], correct: 1 },
  { text: "Quel détroit sépare l'Europe de l'Afrique ?", options: ["Bosphore","Gibraltar","Bering","Ormuz"], correct: 1 },
  { text: "Quel canal relie la Méditerranée à la mer Rouge ?", options: ["Canal de Panama","Canal de Suez","Canal de Kiel","Canal de Corinthe"], correct: 1 },
  { text: "Quelle chaîne sépare l'Europe de l'Asie ?", options: ["Alpes","Oural","Caucase","Carpates"], correct: 1 },
  { text: "Quel est le plus grand lac d'eau douce par superficie ?", options: ["Lac Victoria","Lac Supérieur","Lac Baïkal","Mer Caspienne"], correct: 1 },
  { text: "Quel pays compte le plus d'habitants (2024) ?", options: ["Chine","Inde","États-Unis","Indonésie"], correct: 1 },
  { text: "Quelle est la plus petite nation du monde ?", options: ["Monaco","Vatican","Nauru","Saint-Marin"], correct: 1 },
  { text: "Quel fleuve traverse Le Caire ?", options: ["Tigre","Nil","Congo","Niger"], correct: 1 },
  { text: "Quelle mer est la plus salée ?", options: ["Mer Rouge","Mer Morte","Méditerranée","Mer Caspienne"], correct: 1 },
  { text: "Combien y a-t-il de continents ?", options: ["5","6","7","8"], correct: 2 },
  { text: "Quel pays a la forme d'une botte ?", options: ["Grèce","Italie","Croatie","Norvège"], correct: 1 },
  { text: "Quelle ville s'étend sur deux continents ?", options: ["Le Caire","Istanbul","Moscou","Athènes"], correct: 1 },
  { text: "Quel est le plus grand pays d'Afrique par superficie ?", options: ["Algérie","RD Congo","Soudan","Libye"], correct: 0 },
  { text: "Quelle est la capitale des États-Unis ?", options: ["New York","Washington","Los Angeles","Boston"], correct: 1 },
  { text: "Quel pays possède le plus de fuseaux horaires ?", options: ["Russie","France","États-Unis","Chine"], correct: 1 },
  { text: "Quel fleuve d'Amérique du Sud a le plus grand débit ?", options: ["Orénoque","Amazone","Paraná","Magdalena"], correct: 1 },
  { text: "Quelle est la plus grande métropole du Japon ?", options: ["Osaka","Tokyo","Kyoto","Nagoya"], correct: 1 },
  { text: "Quel pays est entouré par l'Afrique du Sud ?", options: ["Botswana","Lesotho","Namibie","Zimbabwe"], correct: 1 },
  { text: "Quel pays est à la fois en Europe et en Asie majoritairement en Asie ?", options: ["Turquie","Grèce","Chypre","Géorgie"], correct: 0 },
  { text: "Quel océan borde la côte ouest des États-Unis ?", options: ["Atlantique","Pacifique","Indien","Arctique"], correct: 1 },
  { text: "Quelle est la plus longue chaîne de montagnes du monde ?", options: ["Himalaya","Andes","Rocheuses","Alpes"], correct: 1 },
  { text: "Quel pays nordique n'a pas de littoral sur l'Atlantique ?", options: ["Norvège","Suède","Finlande","Islande"], correct: 2 },
  { text: "Quelle ville est la capitale du Canada ?", options: ["Toronto","Ottawa","Montréal","Vancouver"], correct: 1 },
  { text: "Paris est la capitale de quel pays ?", options: ["l'Inde","la France","la Nouvelle-Zélande","Monaco"], correct: 1 },
  { text: "Berlin est la capitale de quel pays ?", options: ["la Nouvelle-Zélande","l'Allemagne","Monaco","l'Ouganda"], correct: 1 },
  { text: "Madrid est la capitale de quel pays ?", options: ["Monaco","l'Espagne","l'Ouganda","la Pologne"], correct: 1 },
  { text: "Rome est la capitale de quel pays ?", options: ["l'Ouganda","l'Italie","la Pologne","la Côte d'Ivoire"], correct: 1 },
  { text: "Lisbonne est la capitale de quel pays ?", options: ["la Pologne","le Portugal","la Côte d'Ivoire","le Chili"], correct: 1 },
  { text: "Londres est la capitale de quel pays ?", options: ["la Côte d'Ivoire","le Royaume-Uni","le Chili","Singapour"], correct: 1 },
  { text: "Dublin est la capitale de quel pays ?", options: ["le Chili","l'Irlande","Singapour","l'Islande"], correct: 1 },
  { text: "Bruxelles est la capitale de quel pays ?", options: ["Singapour","la Belgique","l'Islande","le Kazakhstan"], correct: 1 },
  { text: "Amsterdam est la capitale de quel pays ?", options: ["l'Islande","les Pays-Bas","le Kazakhstan","l'Irlande"], correct: 1 },
  { text: "Berne est la capitale de quel pays ?", options: ["le Kazakhstan","la Suisse","l'Irlande","la Serbie"], correct: 1 },
  { text: "Vienne est la capitale de quel pays ?", options: ["l'Irlande","l'Autriche","la Serbie","le Cameroun"], correct: 1 },
  { text: "Athènes est la capitale de quel pays ?", options: ["la Serbie","la Grèce","le Cameroun","le Japon"], correct: 1 },
  { text: "Stockholm est la capitale de quel pays ?", options: ["le Cameroun","la Suède","le Japon","la Syrie"], correct: 1 },
  { text: "Oslo est la capitale de quel pays ?", options: ["le Japon","la Norvège","la Syrie","l'Albanie"], correct: 1 },
  { text: "Copenhague est la capitale de quel pays ?", options: ["la Syrie","le Danemark","l'Albanie","Madagascar"], correct: 1 },
  { text: "Helsinki est la capitale de quel pays ?", options: ["l'Albanie","la Finlande","Madagascar","la Norvège"], correct: 1 },
  { text: "Varsovie est la capitale de quel pays ?", options: ["Madagascar","la Pologne","la Norvège","la Tunisie"], correct: 1 },
  { text: "Budapest est la capitale de quel pays ?", options: ["la Norvège","la Hongrie","la Tunisie","Cuba"], correct: 1 },
  { text: "Bucarest est la capitale de quel pays ?", options: ["la Tunisie","la Roumanie","Cuba","l'Indonésie"], correct: 1 },
  { text: "Sofia est la capitale de quel pays ?", options: ["Cuba","la Bulgarie","l'Indonésie","le Sri Lanka"], correct: 1 },
  { text: "Prague est la capitale de quel pays ?", options: ["l'Indonésie","la République tchèque","le Sri Lanka","Oman"], correct: 1 },
  { text: "Bratislava est la capitale de quel pays ?", options: ["le Sri Lanka","la Slovaquie","Oman","l'Italie"], correct: 1 },
  { text: "Zagreb est la capitale de quel pays ?", options: ["Oman","la Croatie","l'Italie","la République tchèque"], correct: 1 },
  { text: "Belgrade est la capitale de quel pays ?", options: ["l'Italie","la Serbie","la République tchèque","l'Éthiopie"], correct: 1 },
  { text: "Moscou est la capitale de quel pays ?", options: ["la République tchèque","la Russie","l'Éthiopie","l'Uruguay"], correct: 1 },
  { text: "Kiev est la capitale de quel pays ?", options: ["l'Éthiopie","l'Ukraine","l'Uruguay","Israël"], correct: 1 },
  { text: "Ankara est la capitale de quel pays ?", options: ["l'Uruguay","la Turquie","Israël","la Lettonie"], correct: 1 },
  { text: "Tbilissi est la capitale de quel pays ?", options: ["Israël","la Géorgie","la Lettonie","le Zimbabwe"], correct: 1 },
  { text: "Rabat est la capitale de quel pays ?", options: ["la Lettonie","le Maroc","le Zimbabwe","l'Autriche"], correct: 1 },
  { text: "Alger est la capitale de quel pays ?", options: ["le Zimbabwe","l'Algérie","l'Autriche","la Géorgie"], correct: 1 },
  { text: "Tunis est la capitale de quel pays ?", options: ["l'Autriche","la Tunisie","la Géorgie","les États-Unis"], correct: 1 },
  { text: "Le Caire est la capitale de quel pays ?", options: ["la Géorgie","l'Égypte","les États-Unis","le Pakistan"], correct: 1 },
  { text: "Dakar est la capitale de quel pays ?", options: ["les États-Unis","le Sénégal","le Pakistan","le Cambodge"], correct: 1 },
  { text: "Yamoussoukro est la capitale de quel pays ?", options: ["le Pakistan","la Côte d'Ivoire","le Cambodge","le Qatar"], correct: 1 },
  { text: "Abuja est la capitale de quel pays ?", options: ["le Cambodge","le Nigeria","le Qatar","la France"], correct: 1 },
  { text: "Nairobi est la capitale de quel pays ?", options: ["le Qatar","le Kenya","la France","la Hongrie"], correct: 1 },
  { text: "Pretoria est la capitale de quel pays ?", options: ["la France","l'Afrique du Sud","la Hongrie","le Nigeria"], correct: 1 },
  { text: "Addis-Abeba est la capitale de quel pays ?", options: ["la Hongrie","l'Éthiopie","le Nigeria","le Pérou"], correct: 1 },
  { text: "Accra est la capitale de quel pays ?", options: ["le Nigeria","le Ghana","le Pérou","l'Iran"], correct: 1 },
  { text: "Bamako est la capitale de quel pays ?", options: ["le Pérou","le Mali","l'Iran","le Luxembourg"], correct: 1 },
  { text: "Yaoundé est la capitale de quel pays ?", options: ["l'Iran","le Cameroun","le Luxembourg","l'Ouzbékistan"], correct: 1 },
  { text: "Kinshasa est la capitale de quel pays ?", options: ["le Luxembourg","la RD Congo","l'Ouzbékistan","la Belgique"], correct: 1 },
  { text: "Luanda est la capitale de quel pays ?", options: ["l'Ouzbékistan","l'Angola","la Belgique","la Russie"], correct: 1 },
  { text: "Dodoma est la capitale de quel pays ?", options: ["la Belgique","la Tanzanie","la Russie","la RD Congo"], correct: 1 },
  { text: "Washington est la capitale de quel pays ?", options: ["la Russie","les États-Unis","la RD Congo","la Corée du Sud"], correct: 1 },
  { text: "Ottawa est la capitale de quel pays ?", options: ["la RD Congo","le Canada","la Corée du Sud","l'Afghanistan"], correct: 1 },
  { text: "Mexico est la capitale de quel pays ?", options: ["la Corée du Sud","le Mexique","l'Afghanistan","Chypre"], correct: 1 },
  { text: "La Havane est la capitale de quel pays ?", options: ["l'Afghanistan","Cuba","Chypre","la Libye"], correct: 1 },
  { text: "Brasilia est la capitale de quel pays ?", options: ["Chypre","le Brésil","la Libye","le Danemark"], correct: 1 },
  { text: "Buenos Aires est la capitale de quel pays ?", options: ["la Libye","l'Argentine","le Danemark","l'Égypte"], correct: 1 },
  { text: "Santiago est la capitale de quel pays ?", options: ["le Danemark","le Chili","l'Égypte","le Brésil"], correct: 1 },
  { text: "Lima est la capitale de quel pays ?", options: ["l'Égypte","le Pérou","le Brésil","les Philippines"], correct: 1 },
  { text: "Bogota est la capitale de quel pays ?", options: ["le Brésil","la Colombie","les Philippines","le Népal"], correct: 1 },
  { text: "Caracas est la capitale de quel pays ?", options: ["les Philippines","le Venezuela","le Népal","le Yémen"], correct: 1 },
  { text: "Montevideo est la capitale de quel pays ?", options: ["le Népal","l'Uruguay","le Yémen","le Portugal"], correct: 1 },
  { text: "La Paz est la capitale de quel pays ?", options: ["le Yémen","la Bolivie","le Portugal","la Slovaquie"], correct: 1 },
  { text: "Pékin est la capitale de quel pays ?", options: ["le Portugal","la Chine","la Slovaquie","le Ghana"], correct: 1 },
  { text: "Tokyo est la capitale de quel pays ?", options: ["la Slovaquie","le Japon","le Ghana","la Bolivie"], correct: 1 },
  { text: "Séoul est la capitale de quel pays ?", options: ["le Ghana","la Corée du Sud","la Bolivie","la Jordanie"], correct: 1 },
  { text: "Pyongyang est la capitale de quel pays ?", options: ["la Bolivie","la Corée du Nord","la Jordanie","l'Estonie"], correct: 1 },
  { text: "New Delhi est la capitale de quel pays ?", options: ["la Jordanie","l'Inde","l'Estonie","la Zambie"], correct: 1 },
  { text: "Islamabad est la capitale de quel pays ?", options: ["l'Estonie","le Pakistan","la Zambie","la Grèce"], correct: 1 },
  { text: "Bangkok est la capitale de quel pays ?", options: ["la Zambie","la Thaïlande","la Grèce","le Maroc"], correct: 1 },
  { text: "Hanoï est la capitale de quel pays ?", options: ["la Grèce","le Vietnam","le Maroc","le Canada"], correct: 1 },
  { text: "Jakarta est la capitale de quel pays ?", options: ["le Maroc","l'Indonésie","le Canada","la Thaïlande"], correct: 1 },
  { text: "Manille est la capitale de quel pays ?", options: ["le Canada","les Philippines","la Thaïlande","le Laos"], correct: 1 },
  { text: "Kuala Lumpur est la capitale de quel pays ?", options: ["la Thaïlande","la Malaisie","le Laos","les Émirats arabes unis"], correct: 1 },
  { text: "Singapour est la capitale de quel pays ?", options: ["le Laos","Singapour","les Émirats arabes unis","l'Allemagne"], correct: 1 },
  { text: "Téhéran est la capitale de quel pays ?", options: ["les Émirats arabes unis","l'Iran","l'Allemagne","la Roumanie"], correct: 1 },
  { text: "Bagdad est la capitale de quel pays ?", options: ["l'Allemagne","l'Irak","la Roumanie","le Kenya"], correct: 1 },
  { text: "Riyad est la capitale de quel pays ?", options: ["la Roumanie","l'Arabie saoudite","le Kenya","la Colombie"], correct: 1 },
  { text: "Jérusalem est la capitale de quel pays ?", options: ["le Kenya","Israël","la Colombie","l'Irak"], correct: 1 },
  { text: "Amman est la capitale de quel pays ?", options: ["la Colombie","la Jordanie","l'Irak","la Slovénie"], correct: 1 },
  { text: "Beyrouth est la capitale de quel pays ?", options: ["l'Irak","le Liban","la Slovénie","l'Azerbaïdjan"], correct: 1 },
  { text: "Damas est la capitale de quel pays ?", options: ["la Slovénie","la Syrie","l'Azerbaïdjan","les Pays-Bas"], correct: 1 },
  { text: "Kaboul est la capitale de quel pays ?", options: ["l'Azerbaïdjan","l'Afghanistan","les Pays-Bas","l'Ukraine"], correct: 1 },
  { text: "Canberra est la capitale de quel pays ?", options: ["les Pays-Bas","l'Australie","l'Ukraine","l'Angola"], correct: 1 },
  { text: "Wellington est la capitale de quel pays ?", options: ["l'Ukraine","la Nouvelle-Zélande","l'Angola","la Corée du Nord"], correct: 1 },
  { text: "Phnom Penh est la capitale de quel pays ?", options: ["l'Angola","le Cambodge","la Corée du Nord","l'Australie"], correct: 1 },
  { text: "Vientiane est la capitale de quel pays ?", options: ["la Corée du Nord","le Laos","l'Australie","Malte"], correct: 1 },
  { text: "Naypyidaw est la capitale de quel pays ?", options: ["l'Australie","la Birmanie","Malte","le Soudan"], correct: 1 },
  { text: "Colombo est la capitale de quel pays ?", options: ["Malte","le Sri Lanka","le Soudan","la Finlande"], correct: 1 },
  { text: "Katmandou est la capitale de quel pays ?", options: ["le Soudan","le Népal","la Finlande","le Sénégal"], correct: 1 },
  { text: "Dacca est la capitale de quel pays ?", options: ["la Finlande","le Bangladesh","le Sénégal","l'Argentine"], correct: 1 },
  { text: "Reykjavik est la capitale de quel pays ?", options: ["le Sénégal","l'Islande","l'Argentine","la Malaisie"], correct: 1 },
  { text: "Luxembourg est la capitale de quel pays ?", options: ["l'Argentine","le Luxembourg","la Malaisie","le Bangladesh"], correct: 1 },
  { text: "Ljubljana est la capitale de quel pays ?", options: ["la Malaisie","la Slovénie","le Bangladesh","la Mongolie"], correct: 1 },
  { text: "Vilnius est la capitale de quel pays ?", options: ["le Bangladesh","la Lituanie","la Mongolie","le Royaume-Uni"], correct: 1 },
  { text: "Riga est la capitale de quel pays ?", options: ["la Mongolie","la Lettonie","le Royaume-Uni","la Croatie"], correct: 1 },
  { text: "Tallinn est la capitale de quel pays ?", options: ["le Royaume-Uni","l'Estonie","la Croatie","le Mali"], correct: 1 },
  { text: "Minsk est la capitale de quel pays ?", options: ["la Croatie","la Biélorussie","le Mali","la Chine"], correct: 1 },
  { text: "Tirana est la capitale de quel pays ?", options: ["le Mali","l'Albanie","la Chine","le Liban"], correct: 1 },
  { text: "Nicosie est la capitale de quel pays ?", options: ["la Chine","Chypre","le Liban","la Biélorussie"], correct: 1 },
  { text: "La Valette est la capitale de quel pays ?", options: ["le Liban","Malte","la Biélorussie","le Mozambique"], correct: 1 },
  { text: "Monaco est la capitale de quel pays ?", options: ["la Biélorussie","Monaco","le Mozambique","la Suède"], correct: 1 },
  { text: "Doha est la capitale de quel pays ?", options: ["le Mozambique","le Qatar","la Suède","l'Algérie"], correct: 1 },
  { text: "Abou Dabi est la capitale de quel pays ?", options: ["la Suède","les Émirats arabes unis","l'Algérie","le Mexique"], correct: 1 },
  { text: "Koweït est la capitale de quel pays ?", options: ["l'Algérie","le Koweït","le Mexique","le Vietnam"], correct: 1 },
  { text: "Mascate est la capitale de quel pays ?", options: ["le Mexique","Oman","le Vietnam","la Birmanie"], correct: 1 },
  { text: "Sanaa est la capitale de quel pays ?", options: ["le Vietnam","le Yémen","la Birmanie","le Koweït"], correct: 1 },
  { text: "Oulan-Bator est la capitale de quel pays ?", options: ["la Birmanie","la Mongolie","le Koweït","l'Espagne"], correct: 1 },
  { text: "Astana est la capitale de quel pays ?", options: ["le Koweït","le Kazakhstan","l'Espagne","la Bulgarie"], correct: 1 },
  { text: "Tachkent est la capitale de quel pays ?", options: ["l'Espagne","l'Ouzbékistan","la Bulgarie","l'Afrique du Sud"], correct: 1 },
  { text: "Bakou est la capitale de quel pays ?", options: ["la Bulgarie","l'Azerbaïdjan","l'Afrique du Sud","le Venezuela"], correct: 1 },
  { text: "Erevan est la capitale de quel pays ?", options: ["l'Afrique du Sud","l'Arménie","le Venezuela","l'Arabie saoudite"], correct: 1 },
  { text: "Harare est la capitale de quel pays ?", options: ["le Venezuela","le Zimbabwe","l'Arabie saoudite","la Lituanie"], correct: 1 },
  { text: "Lusaka est la capitale de quel pays ?", options: ["l'Arabie saoudite","la Zambie","la Lituanie","l'Arménie"], correct: 1 },
  { text: "Maputo est la capitale de quel pays ?", options: ["la Lituanie","le Mozambique","l'Arménie","la Suisse"], correct: 1 },
  { text: "Antananarivo est la capitale de quel pays ?", options: ["l'Arménie","Madagascar","la Suisse","la Turquie"], correct: 1 },
  { text: "Tripoli est la capitale de quel pays ?", options: ["la Suisse","la Libye","la Turquie","la Tanzanie"], correct: 1 },
  { text: "Khartoum est la capitale de quel pays ?", options: ["la Turquie","le Soudan","la Tanzanie","l'Inde"], correct: 1 },
  { text: "Kampala est la capitale de quel pays ?", options: ["la Tanzanie","l'Ouganda","l'Inde","la Nouvelle-Zélande"], correct: 1 },
  { text: "Quelle monnaie utilise le Japon ?", options: ["l'euro","le yen","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quelle monnaie utilise le Royaume-Uni ?", options: ["le yen","la livre sterling","le franc suisse","le dollar"], correct: 1 },
  { text: "Quelle monnaie utilise la Suisse ?", options: ["la livre sterling","le franc suisse","le dollar","le yuan"], correct: 1 },
  { text: "Quelle monnaie utilise les États-Unis ?", options: ["le franc suisse","le dollar","le yuan","la roupie"], correct: 1 },
  { text: "Quelle monnaie utilise la Chine ?", options: ["l'euro","le yuan","le yen","la livre sterling"], correct: 1 },
  { text: "Quelle monnaie utilise l'Inde ?", options: ["le yen","la roupie","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quelle monnaie utilise la Russie ?", options: ["la livre sterling","le rouble","le franc suisse","le dollar"], correct: 1 },
  { text: "Quelle monnaie utilise la Pologne ?", options: ["le franc suisse","le zloty","le dollar","le yuan"], correct: 1 },
  { text: "Quelle monnaie utilise la Suède ?", options: ["l'euro","la couronne","le yen","la livre sterling"], correct: 1 },
  { text: "Quelle monnaie utilise le Danemark ?", options: ["le yen","la couronne","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quelle monnaie utilise la Turquie ?", options: ["la livre sterling","la livre turque","le franc suisse","le dollar"], correct: 1 },
  { text: "Quelle monnaie utilise le Brésil ?", options: ["le franc suisse","le réal","le dollar","le yuan"], correct: 1 },
  { text: "Quelle monnaie utilise le Mexique ?", options: ["l'euro","le peso","le yen","la livre sterling"], correct: 1 },
  { text: "Quelle monnaie utilise l'Afrique du Sud ?", options: ["le yen","le rand","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quelle monnaie utilise le Maroc ?", options: ["la livre sterling","le dirham","le franc suisse","le dollar"], correct: 1 },
  { text: "Quelle monnaie utilise la Thaïlande ?", options: ["le franc suisse","le baht","le dollar","le yuan"], correct: 1 },
  { text: "Quelle monnaie utilise la Corée du Sud ?", options: ["l'euro","le won","le yen","la livre sterling"], correct: 1 },
  { text: "Quelle monnaie utilise le Vietnam ?", options: ["le yen","le dong","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quelle monnaie utilise l'Égypte ?", options: ["la livre sterling","la livre égyptienne","le franc suisse","le dollar"], correct: 1 },
  { text: "Quelle monnaie utilise le Canada ?", options: ["le franc suisse","le dollar canadien","le yuan","la roupie"], correct: 1 },
  { text: "Quelle monnaie utilise l'Australie ?", options: ["l'euro","le dollar australien","le yen","la livre sterling"], correct: 1 },
  { text: "Quelle monnaie utilise la Norvège ?", options: ["le yen","la couronne","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quelle monnaie utilise Israël ?", options: ["la livre sterling","le shekel","le franc suisse","le dollar"], correct: 1 },
  { text: "Quelle monnaie utilise l'Arabie saoudite ?", options: ["le franc suisse","le riyal","le dollar","le yuan"], correct: 1 },
  { text: "Quelle monnaie utilise le Nigeria ?", options: ["l'euro","le naira","le yen","la livre sterling"], correct: 1 },
  { text: "Quelle monnaie utilise le Kenya ?", options: ["le yen","le shilling","la livre sterling","le franc suisse"], correct: 1 },
  { text: "Quel pays africain est traversé par l'équateur et abrite une grande forêt ?", options: ["Égypte","RD Congo","Maroc","Algérie"], correct: 1 },
  { text: "Quelle est la plus longue frontière terrestre du monde (entre 2 pays) ?", options: ["USA-Mexique","Canada-États-Unis","Russie-Chine","Argentine-Chili"], correct: 1 },
  { text: "Quel pays compte le plus grand nombre d'îles ?", options: ["Indonésie","Suède","Philippines","Japon"], correct: 1 },
  { text: "Quelle ville est la plus peuplée du monde (aire urbaine) ?", options: ["New York","Tokyo","Shanghai","Delhi"], correct: 1 },
  { text: "Quel pays a pour capitale Wellington ?", options: ["Australie","Nouvelle-Zélande","Fidji","Samoa"], correct: 1 },
];
