// QuizzMaster — thème 📜 Histoire. 205 questions.

module.exports = [
  { text: "En quelle année a commencé la Première Guerre mondiale ?", options: ["1912","1914","1916","1918"], correct: 1 },
  { text: "En quelle année s'est terminée la Première Guerre mondiale ?", options: ["1916","1917","1918","1920"], correct: 2 },
  { text: "En quelle année a commencé la Seconde Guerre mondiale ?", options: ["1937","1939","1941","1945"], correct: 1 },
  { text: "En quelle année s'est terminée la Seconde Guerre mondiale ?", options: ["1943","1944","1945","1946"], correct: 2 },
  { text: "En quelle année a eu lieu le débarquement de Normandie ?", options: ["1943","1944","1945","1942"], correct: 1 },
  { text: "Quel pays a lâché les bombes atomiques sur le Japon en 1945 ?", options: ["URSS","États-Unis","Royaume-Uni","Allemagne"], correct: 1 },
  { text: "Sur quelles villes japonaises les bombes atomiques sont-elles tombées ?", options: ["Tokyo et Osaka","Hiroshima et Nagasaki","Kyoto et Kobe","Nagoya et Sapporo"], correct: 1 },
  { text: "Qui dirigeait l'Allemagne nazie ?", options: ["Himmler","Hitler","Goering","Hess"], correct: 1 },
  { text: "Qui dirigeait l'URSS pendant la Seconde Guerre mondiale ?", options: ["Lénine","Staline","Trotski","Khrouchtchev"], correct: 1 },
  { text: "Qui était Premier ministre britannique pendant la Seconde Guerre mondiale ?", options: ["Chamberlain","Churchill","Attlee","Eden"], correct: 1 },
  { text: "En quelle année a eu lieu la révolution russe d'Octobre ?", options: ["1905","1917","1922","1924"], correct: 1 },
  { text: "Qui a mené la révolution bolchevique de 1917 ?", options: ["Staline","Lénine","Marx","Gorbatchev"], correct: 1 },
  { text: "En quelle année l'URSS a-t-elle été dissoute ?", options: ["1989","1991","1993","1995"], correct: 1 },
  { text: "En quelle année le mur de Berlin est-il tombé ?", options: ["1987","1989","1991","1985"], correct: 1 },
  { text: "Quel président américain a aboli l'esclavage ?", options: ["Washington","Jefferson","Lincoln","Roosevelt"], correct: 2 },
  { text: "En quelle année a eu lieu la guerre de Sécession (début) ?", options: ["1851","1861","1871","1881"], correct: 1 },
  { text: "Qui a découvert l'Amérique en 1492 (du point de vue européen) ?", options: ["Magellan","Christophe Colomb","Vasco de Gama","Cortés"], correct: 1 },
  { text: "Quel navigateur a réalisé le premier tour du monde (expédition) ?", options: ["Colomb","Magellan","Vasco de Gama","Drake"], correct: 1 },
  { text: "Quelle civilisation a construit les pyramides de Gizeh ?", options: ["Les Grecs","Les Égyptiens","Les Romains","Les Perses"], correct: 1 },
  { text: "Quel pharaon est célèbre pour son masque funéraire en or ?", options: ["Ramsès II","Toutânkhamon","Khéops","Akhenaton"], correct: 1 },
  { text: "Quelle civilisation a bâti le Machu Picchu ?", options: ["Aztèques","Mayas","Incas","Olmèques"], correct: 2 },
  { text: "Quelle civilisation précolombienne vivait au Mexique central ?", options: ["Incas","Aztèques","Mayas","Mochicas"], correct: 1 },
  { text: "Qui était le premier empereur romain ?", options: ["Jules César","Auguste","Néron","Trajan"], correct: 1 },
  { text: "Quel général carthaginois a traversé les Alpes avec des éléphants ?", options: ["Hamilcar","Hannibal","Hasdrubal","Magon"], correct: 1 },
  { text: "Quelle guerre a opposé Athènes et Sparte ?", options: ["Guerres médiques","Guerre du Péloponnèse","Guerre de Troie","Guerres puniques"], correct: 1 },
  { text: "Qui a conquis un immense empire et fondé Alexandrie ?", options: ["Périclès","Alexandre le Grand","Léonidas","Darius"], correct: 1 },
  { text: "Quel empire byzantin est tombé en 1453 ?", options: ["Romain d'Occident","Byzantin","Ottoman","Perse"], correct: 1 },
  { text: "Quelle ville est tombée en 1453 marquant la fin de Byzance ?", options: ["Rome","Constantinople","Athènes","Jérusalem"], correct: 1 },
  { text: "Quelle dynastie a unifié la Chine en -221 ?", options: ["Han","Qin","Tang","Ming"], correct: 1 },
  { text: "Qui a proclamé la République populaire de Chine en 1949 ?", options: ["Sun Yat-sen","Mao Zedong","Deng Xiaoping","Tchang Kaï-chek"], correct: 1 },
  { text: "Quel mur immense protège la Chine du nord ?", options: ["Mur d'Hadrien","La Grande Muraille","Le mur de Berlin","Le limes"], correct: 1 },
  { text: "En quelle année a eu lieu la Révolution française ?", options: ["1776","1789","1815","1848"], correct: 1 },
  { text: "Qui était le roi de France pendant la Révolution ?", options: ["Louis XIV","Louis XV","Louis XVI","Charles X"], correct: 2 },
  { text: "Quel empereur français a été vaincu à Waterloo ?", options: ["Louis XVIII","Napoléon Ier","Napoléon III","Charles X"], correct: 1 },
  { text: "En quelle année a eu lieu la bataille de Waterloo ?", options: ["1805","1812","1815","1821"], correct: 2 },
  { text: "Quelle reine de France a été guillotinée ?", options: ["Anne d'Autriche","Marie-Antoinette","Catherine de Médicis","Marie de Médicis"], correct: 1 },
  { text: "Qui a unifié l'Italie au XIXe siècle (un des artisans) ?", options: ["Garibaldi","Mussolini","Cavour seul","Victor-Emmanuel III"], correct: 0 },
  { text: "Qui a unifié l'Allemagne en 1871 ?", options: ["Guillaume II","Bismarck","Hitler","Adenauer"], correct: 1 },
  { text: "Quelle reine a régné sur le Royaume-Uni au XIXe siècle pendant 63 ans ?", options: ["Élisabeth Ire","Victoria","Anne","Marie Ire"], correct: 1 },
  { text: "Quel roi anglais a fondé l'Église anglicane ?", options: ["Henri VIII","Édouard VI","Jacques Ier","Henri VII"], correct: 0 },
  { text: "Qui a mené les troupes françaises et libéré Orléans ?", options: ["Jeanne d'Arc","Aliénor","Catherine","Blanche de Castille"], correct: 0 },
  { text: "Quelle guerre a duré plus de cent ans entre la France et l'Angleterre ?", options: ["Guerre de Trente Ans","Guerre de Cent Ans","Guerre de Sept Ans","Croisades"], correct: 1 },
  { text: "Quel explorateur portugais a atteint l'Inde par la mer en 1498 ?", options: ["Magellan","Vasco de Gama","Diaz","Cabral"], correct: 1 },
  { text: "Quelle période a suivi le Moyen Âge en Europe ?", options: ["L'Antiquité","La Renaissance","La Préhistoire","Les Lumières"], correct: 1 },
  { text: "Quel mouvement intellectuel du XVIIIe siècle prône la raison ?", options: ["La Renaissance","Les Lumières","Le Romantisme","La Réforme"], correct: 1 },
  { text: "Qui a affiché ses 95 thèses et lancé la Réforme protestante ?", options: ["Calvin","Luther","Zwingli","Knox"], correct: 1 },
  { text: "Quel italien a écrit Le Prince au XVIe siècle ?", options: ["Dante","Machiavel","Pétrarque","Galilée"], correct: 1 },
  { text: "Quelle révolution industrielle a commencé au Royaume-Uni au XVIIIe siècle ?", options: ["Numérique","Industrielle","Verte","Agricole"], correct: 1 },
  { text: "Quel mur séparait l'Empire romain de l'Écosse ?", options: ["Mur de Berlin","Mur d'Hadrien","Grande Muraille","Limes du Rhin"], correct: 1 },
  { text: "Qui a écrit la Déclaration d'indépendance américaine (1776, principal auteur) ?", options: ["Washington","Jefferson","Franklin","Adams"], correct: 1 },
  { text: "En quelle année les États-Unis ont-ils déclaré leur indépendance ?", options: ["1776","1789","1804","1812"], correct: 0 },
  { text: "Quel roi de France était surnommé le Roi-Soleil ?", options: ["Louis XIII","Louis XIV","Louis XV","Henri IV"], correct: 1 },
  { text: "Quel empereur a fait construire le Colisée (achevé) à Rome ?", options: ["Néron","Les Flaviens (Titus)","Trajan","Hadrien"], correct: 1 },
  { text: "Quelle bataille de 1066 a vu Guillaume le Conquérant vaincre les Anglais ?", options: ["Azincourt","Hastings","Crécy","Bouvines"], correct: 1 },
  { text: "Qui était le chef de la France libre durant la Seconde Guerre mondiale ?", options: ["Pétain","De Gaulle","Laval","Reynaud"], correct: 1 },
  { text: "Quel traité de 1919 met fin à la Première Guerre mondiale ?", options: ["Traité de Rome","Traité de Versailles","Traité de Vienne","Traité de Maastricht"], correct: 1 },
  { text: "Quelle organisation a été créée en 1945 pour la paix mondiale ?", options: ["SDN","ONU","OTAN","UE"], correct: 1 },
  { text: "Quelle alliance militaire occidentale a été créée en 1949 ?", options: ["ONU","OTAN","Pacte de Varsovie","UE"], correct: 1 },
  { text: "Quel conflit a opposé les blocs de l'Est et de l'Ouest sans guerre directe ?", options: ["Guerre de Cent Ans","Guerre froide","Guerre des Boers","Guerre de Crimée"], correct: 1 },
  { text: "Quelle crise a failli déclencher une guerre nucléaire en 1962 ?", options: ["Crise de Suez","Crise des missiles de Cuba","Crise de Berlin","Guerre du Kippour"], correct: 1 },
  { text: "Qui a été le premier homme dans l'espace en 1961 ?", options: ["Armstrong","Gagarine","Glenn","Terechkova"], correct: 1 },
  { text: "Quel président américain a été assassiné en 1963 à Dallas ?", options: ["Roosevelt","Kennedy","Nixon","Johnson"], correct: 1 },
  { text: "Qui a prononcé le discours « I have a dream » ?", options: ["Malcolm X","Martin Luther King","Obama","Mandela"], correct: 1 },
  { text: "Qui est devenu président d'Afrique du Sud en 1994 après la fin de l'apartheid ?", options: ["Tutu","Mandela","Biko","De Klerk"], correct: 1 },
  { text: "Quelle dynastie égyptienne Cléopâtre appartenait-elle ?", options: ["Les Ptolémées","Les Ramsès","Les Thoutmosis","Les Saïtes"], correct: 0 },
  { text: "Quel empire mongol a été fondé par Gengis Khan ?", options: ["Empire perse","Empire mongol","Empire ottoman","Empire moghol"], correct: 1 },
  { text: "Quel explorateur a donné son prénom au continent américain ?", options: ["Colomb","Amerigo Vespucci","Cabot","Vespasien"], correct: 1 },
  { text: "Quel roi de France a été décapité en 1793 ?", options: ["Louis XV","Louis XVI","Charles X","Louis XVIII"], correct: 1 },
  { text: "Quel événement marque le début de la Révolution française (14 juillet 1789) ?", options: ["Sacre de Napoléon","Prise de la Bastille","Fuite à Varennes","Serment du Jeu de paume"], correct: 1 },
  { text: "Qui a peint la chapelle Sixtine ?", options: ["Léonard de Vinci","Michel-Ange","Raphaël","Botticelli"], correct: 1 },
  { text: "Quelle grande peste a ravagé l'Europe au XIVe siècle ?", options: ["La grippe espagnole","La peste noire","Le choléra","La variole"], correct: 1 },
  { text: "Quel empire d'Amérique du Sud a été conquis par Pizarro ?", options: ["Aztèque","Inca","Maya","Olmèque"], correct: 1 },
  { text: "Quel pays a colonisé le Brésil ?", options: ["Espagne","Portugal","France","Pays-Bas"], correct: 1 },
  { text: "Quelle langue ancienne était parlée dans la Rome antique ?", options: ["Le grec","Le latin","L'étrusque","Le punique"], correct: 1 },
  { text: "Qui a inventé l'imprimerie en Europe (vers 1450) ?", options: ["Gutenberg","Galilée","Da Vinci","Copernic"], correct: 0 },
  { text: "Quel astronome a soutenu que la Terre tourne autour du Soleil et fut jugé ?", options: ["Newton","Galilée","Kepler","Brahe"], correct: 1 },
  { text: "Quel roi a fait bâtir le château de Versailles ?", options: ["Louis XIII","Louis XIV","Louis XV","François Ier"], correct: 1 },
  { text: "Quelle guerre civile a opposé Nordistes et Sudistes aux États-Unis ?", options: ["Guerre d'indépendance","Guerre de Sécession","Guerre du Vietnam","Guerre hispano-américaine"], correct: 1 },
  { text: "Quel pays a construit le premier les chemins de fer à vapeur ?", options: ["France","Royaume-Uni","Allemagne","États-Unis"], correct: 1 },
  { text: "Quelle reine d'Égypte s'est alliée à César puis à Antoine ?", options: ["Néfertiti","Cléopâtre","Hatchepsout","Néfertari"], correct: 1 },
  { text: "Quel mur a divisé Berlin de 1961 à 1989 ?", options: ["Mur d'Hadrien","Le mur de Berlin","La ligne Maginot","Le rideau de fer (au sens propre)"], correct: 1 },
  { text: "Quelle dynastie chinoise a construit la majeure partie de la Grande Muraille actuelle ?", options: ["Han","Tang","Ming","Qing"], correct: 2 },
  { text: "Quel pays était dirigé par les tsars avant 1917 ?", options: ["Allemagne","Russie","Autriche","Turquie"], correct: 1 },
  { text: "Quelle bataille de 1916 fut l'une des plus meurtrières de la Grande Guerre (France) ?", options: ["Verdun","Austerlitz","Waterloo","Marignan"], correct: 0 },
  { text: "Quel traité de 1992 a fondé l'Union européenne ?", options: ["Traité de Rome","Traité de Maastricht","Traité de Lisbonne","Traité de Nice"], correct: 1 },
  { text: "En quelle année l'euro est-il entré en circulation (pièces et billets) ?", options: ["1999","2000","2002","2004"], correct: 2 },
  { text: "Quel empereur français est l'auteur d'un Code civil de 1804 ?", options: ["Louis XVIII","Napoléon Bonaparte","Charles X","Louis-Philippe"], correct: 1 },
  { text: "Qui a été la première femme Première ministre du Royaume-Uni ?", options: ["Theresa May","Margaret Thatcher","Liz Truss","Indira Gandhi"], correct: 1 },
  { text: "Quelle ville italienne fut le berceau de la Renaissance ?", options: ["Rome","Florence","Venise","Milan"], correct: 1 },
  { text: "Quel peuple guerrier scandinave a navigué et pillé l'Europe au Moyen Âge ?", options: ["Les Goths","Les Vikings","Les Huns","Les Saxons"], correct: 1 },
  { text: "Quel empire a dominé l'Anatolie et le Moyen-Orient jusqu'en 1922 ?", options: ["Perse","Ottoman","Byzantin","Moghol"], correct: 1 },
  { text: "Quel roi français a promulgué l'édit de Nantes (1598) ?", options: ["François Ier","Henri IV","Louis XIII","Charles IX"], correct: 1 },
  { text: "Quelle révolution a renversé la monarchie en France en 1789 ?", options: ["Révolution russe","Révolution française","Révolution américaine","Révolution industrielle"], correct: 1 },
  { text: "Quel personnage a uni les tribus gauloises contre César ?", options: ["Brennus","Vercingétorix","Astérix","Ambiorix"], correct: 1 },
  { text: "Quelle ville antique a été détruite par l'éruption du Vésuve en 79 ?", options: ["Rome","Pompéi","Carthage","Athènes"], correct: 1 },
  { text: "Quel pays a lancé le premier satellite artificiel (Spoutnik) en 1957 ?", options: ["États-Unis","URSS","France","Chine"], correct: 1 },
  { text: "Quelle grande épidémie a frappé le monde en 1918-1919 ?", options: ["Peste noire","Grippe espagnole","Choléra","Variole"], correct: 1 },
  { text: "Quel roi de Macédoine fut le précepteur d'Alexandre, philosophe grec ?", options: ["Platon","Aristote","Socrate","Diogène"], correct: 1 },
  { text: "Quel pays a été le théâtre de la révolution des Œillets en 1974 ?", options: ["Espagne","Portugal","Grèce","Italie"], correct: 1 },
  { text: "Quel président français a été au pouvoir de 1981 à 1995 ?", options: ["Giscard d'Estaing","Mitterrand","Chirac","Pompidou"], correct: 1 },
  { text: "Quel empire précolombien avait Tenochtitlan pour capitale ?", options: ["Inca","Aztèque","Maya","Toltèque"], correct: 1 },
  { text: "Quelle expédition a permis le premier alunissage habité ?", options: ["Apollo 11","Apollo 13","Gemini 4","Soyouz 1"], correct: 0 },
  { text: "Quel président américain dirigeait pendant la crise de 1929 puis le New Deal ?", options: ["Hoover","Roosevelt","Truman","Wilson"], correct: 1 },
  { text: "Quelle crise économique a frappé le monde à partir de 1929 ?", options: ["La Grande Dépression","La crise des subprimes","La bulle Internet","La crise pétrolière"], correct: 0 },
  { text: "Quel mur de séparation existait entre Berlin-Est et Berlin-Ouest ?", options: ["Mur d'Hadrien","Mur de Berlin","Ligne verte","Rideau d'acier"], correct: 1 },
  { text: "Quel pays a envahi la Pologne en septembre 1939 ?", options: ["France","Allemagne","URSS seule","Italie"], correct: 1 },
  { text: "Quelle bataille aéronavale de 1942 a marqué un tournant dans le Pacifique ?", options: ["Pearl Harbor","Midway","Iwo Jima","Okinawa"], correct: 1 },
  { text: "Quel jour les États-Unis sont-ils entrés en guerre après l'attaque de 1941 ?", options: ["Après Midway","Après Pearl Harbor","Après le débarquement","Après Hiroshima"], correct: 1 },
  { text: "Quel chancelier allemand a réunifié l'Allemagne en 1990 ?", options: ["Adenauer","Kohl","Schmidt","Brandt"], correct: 1 },
  { text: "Quelle ville française a été libérée en août 1944 ?", options: ["Lyon","Paris","Marseille","Strasbourg"], correct: 1 },
  { text: "Qui a dirigé la Chine et lancé la Révolution culturelle ?", options: ["Deng Xiaoping","Mao Zedong","Zhou Enlai","Jiang Zemin"], correct: 1 },
  { text: "Quel dirigeant soviétique a lancé la perestroïka ?", options: ["Brejnev","Gorbatchev","Eltsine","Andropov"], correct: 1 },
  { text: "Quelle dynastie française a précédé la Révolution de 1789 ?", options: ["Valois","Bourbons","Capétiens directs","Carolingiens"], correct: 1 },
  { text: "Quel empereur romain a légalisé le christianisme (édit de Milan) ?", options: ["Néron","Constantin","Dioclétien","Trajan"], correct: 1 },
  { text: "Quelle ville était la capitale de l'Empire romain d'Orient ?", options: ["Rome","Constantinople","Athènes","Antioche"], correct: 1 },
  { text: "Quel philosophe grec a été condamné à boire la ciguë ?", options: ["Platon","Socrate","Aristote","Épicure"], correct: 1 },
  { text: "Quelle bataille opposa 300 Spartiates aux Perses ?", options: ["Marathon","Thermopyles","Salamine","Platées"], correct: 1 },
  { text: "Quel empire a construit des routes et des aqueducs dans toute l'Europe antique ?", options: ["Grec","Romain","Perse","Égyptien"], correct: 1 },
  { text: "Qui a écrit Mein Kampf ?", options: ["Goebbels","Hitler","Himmler","Goering"], correct: 1 },
  { text: "Quel pays a accueilli les Jeux olympiques antiques ?", options: ["Rome","Grèce","Égypte","Perse"], correct: 1 },
  { text: "Quelle dynastie chinoise est la dernière (jusqu'en 1912) ?", options: ["Ming","Qing","Han","Tang"], correct: 1 },
  { text: "Quel roi de France était marié à Marie-Antoinette ?", options: ["Louis XV","Louis XVI","Charles X","Louis XVIII"], correct: 1 },
  { text: "Quel pays a offert la statue de la Liberté aux États-Unis ?", options: ["Royaume-Uni","France","Italie","Espagne"], correct: 1 },
  { text: "Quelle guerre a opposé la France à la Prusse en 1870 ?", options: ["Guerre de Crimée","Guerre franco-prussienne","Guerre de Sept Ans","Guerre de Trente Ans"], correct: 1 },
  { text: "Quel traité a partagé les terres entre Espagne et Portugal en 1494 ?", options: ["Traité de Tordesillas","Traité de Versailles","Traité d'Utrecht","Traité de Rome"], correct: 0 },
  { text: "Quel roi anglais a signé la Magna Carta en 1215 ?", options: ["Richard Ier","Jean sans Terre","Henri II","Édouard Ier"], correct: 1 },
  { text: "Quelle reine catholique a financé le voyage de Colomb ?", options: ["Élisabeth Ire","Isabelle de Castille","Marie Tudor","Catherine"], correct: 1 },
  { text: "Quel pays a colonisé l'Inde jusqu'en 1947 ?", options: ["France","Royaume-Uni","Portugal","Pays-Bas"], correct: 1 },
  { text: "Qui a mené l'indépendance de l'Inde par la non-violence ?", options: ["Nehru","Gandhi","Bose","Patel"], correct: 1 },
  { text: "En quelle année l'Inde est-elle devenue indépendante ?", options: ["1945","1947","1950","1962"], correct: 1 },
  { text: "Quel empereur a déplacé la capitale romaine vers Byzance ?", options: ["Auguste","Constantin","Néron","Hadrien"], correct: 1 },
  { text: "Quel pays a été dirigé par Franco jusqu'en 1975 ?", options: ["Italie","Espagne","Portugal","Grèce"], correct: 1 },
  { text: "Quel dictateur italien a fondé le fascisme ?", options: ["Franco","Mussolini","Salazar","Hitler"], correct: 1 },
  { text: "Quel événement a déclenché la Première Guerre mondiale (assassinat) ?", options: ["À Sarajevo","À Vienne","À Berlin","À Paris"], correct: 0 },
  { text: "Quel archiduc a été assassiné à Sarajevo en 1914 ?", options: ["Franz Ferdinand","Guillaume II","Nicolas II","François-Joseph"], correct: 0 },
  { text: "Quelle ville a accueilli la conférence de paix après 1918 ?", options: ["Vienne","Paris (Versailles)","Berlin","Londres"], correct: 1 },
  { text: "Quel pont aérien a ravitaillé Berlin-Ouest en 1948-1949 ?", options: ["Pont de Berlin","Blocus de Berlin (pont aérien)","Pont de Yalta","Pont de Potsdam"], correct: 1 },
  { text: "Quelle conférence de 1945 a réuni Staline, Roosevelt et Churchill ?", options: ["Munich","Yalta","Versailles","Vienne"], correct: 1 },
  { text: "Quel pays a perdu la guerre du Vietnam (puissance étrangère retirée en 1973) ?", options: ["URSS","États-Unis","France à nouveau","Chine"], correct: 1 },
  { text: "Quel pays a colonisé l'Indochine avant les États-Unis ?", options: ["Royaume-Uni","France","Japon seul","Pays-Bas"], correct: 1 },
  { text: "Quelle révolution a eu lieu en France en juillet 1830 ?", options: ["Les Trois Glorieuses","La Commune","Février 1848","Mai 68"], correct: 0 },
  { text: "Quel régime a suivi la chute de Napoléon III en 1870 ?", options: ["IIe République","IIIe République","Empire","Restauration"], correct: 1 },
  { text: "Quelle insurrection parisienne a eu lieu en 1871 ?", options: ["La Fronde","La Commune de Paris","La Terreur","Les Journées de Juin"], correct: 1 },
  { text: "Qui était le ministre de Louis XIV chargé des finances ?", options: ["Mazarin","Colbert","Richelieu","Fouquet"], correct: 1 },
  { text: "Quel roi a révoqué l'édit de Nantes en 1685 ?", options: ["Louis XIII","Louis XIV","Louis XV","Henri IV"], correct: 1 },
  { text: "Quelle dynastie régna en France de 987 à 1328 (lignée directe) ?", options: ["Carolingiens","Capétiens","Valois","Bourbons"], correct: 1 },
  { text: "Qui a fondé la dynastie capétienne en 987 ?", options: ["Charlemagne","Hugues Capet","Clovis","Charles le Chauve"], correct: 1 },
  { text: "Quel empereur a divisé l'Empire romain en deux en 395 (à sa mort) ?", options: ["Constantin","Théodose","Dioclétien","Justinien"], correct: 1 },
  { text: "Quel empereur byzantin a codifié le droit romain (Code) ?", options: ["Constantin","Justinien","Héraclius","Basile II"], correct: 1 },
  { text: "Quelle bataille de 732 a stoppé l'avancée arabe en Gaule ?", options: ["Poitiers (Charles Martel)","Roncevaux","Bouvines","Tours-et-Poitiers seulement"], correct: 0 },
  { text: "Quel chef franc a gagné la bataille de Poitiers en 732 ?", options: ["Clovis","Charles Martel","Pépin le Bref","Charlemagne"], correct: 1 },
  { text: "Quel roi d'Angleterre a perdu la bataille d'Hastings en 1066 ?", options: ["Harold","Guillaume","Édouard","Harald"], correct: 0 },
  { text: "Quelle famine et maladie a frappé l'Irlande au XIXe siècle ?", options: ["La grande famine (pomme de terre)","Le choléra","La peste","La grippe"], correct: 0 },
  { text: "Quel pays a aboli l'esclavage en 1848 (colonies françaises) ?", options: ["Royaume-Uni","France","Espagne","Portugal"], correct: 1 },
  { text: "Qui a fait abolir l'esclavage dans les colonies françaises en 1848 ?", options: ["Victor Schoelcher","Robespierre","Jules Ferry","Gambetta"], correct: 0 },
  { text: "Quel pays a construit le canal de Panama (achevé en 1914) ?", options: ["France seule","États-Unis","Royaume-Uni","Espagne"], correct: 1 },
  { text: "Quel pays a construit le canal de Suez (ingénierie française) ?", options: ["Royaume-Uni","France (Lesseps)","Égypte seule","Italie"], correct: 1 },
  { text: "Quel roi de France est mort sur l'échafaud en janvier 1793 ?", options: ["Louis XV","Louis XVI","Louis XVII","Charles X"], correct: 1 },
  { text: "Quelle période révolutionnaire (1793-1794) est dite « la Terreur » ?", options: ["Le Directoire","La Terreur","Le Consulat","La Restauration"], correct: 1 },
  { text: "Qui a dominé la Terreur avant d'être guillotiné en 1794 ?", options: ["Danton","Robespierre","Marat","Saint-Just seul"], correct: 1 },
  { text: "Quel régime a suivi la Révolution sous Napoléon avant l'Empire ?", options: ["Le Directoire","Le Consulat","La Restauration","La Régence"], correct: 1 },
  { text: "Quelle bataille navale de 1805 a vu la défaite franco-espagnole face à Nelson ?", options: ["Trafalgar","Aboukir","Lépante","Actium"], correct: 0 },
  { text: "Quel amiral britannique a vaincu à Trafalgar ?", options: ["Drake","Nelson","Cook","Hood"], correct: 1 },
  { text: "Quelle grande victoire de Napoléon a eu lieu en 1805 (les Trois Empereurs) ?", options: ["Austerlitz","Iéna","Wagram","Eylau"], correct: 0 },
  { text: "Quel pays Napoléon a-t-il envahi en 1812 avec la Grande Armée ?", options: ["Autriche","Russie","Prusse","Espagne"], correct: 1 },
  { text: "Quel empereur français a été exilé à Sainte-Hélène ?", options: ["Napoléon III","Napoléon Ier","Charles X","Louis-Philippe"], correct: 1 },
  { text: "Quelle île a vu naître Napoléon Bonaparte ?", options: ["Sardaigne","Corse","Sicile","Elbe"], correct: 1 },
  { text: "Quel pays a lancé la première bombe H testée par l'URSS dans les années 1950 ?", options: ["États-Unis","URSS","Chine","France"], correct: 1 },
  { text: "Quelle organisation regroupait les pays communistes face à l'OTAN ?", options: ["SDN","Pacte de Varsovie","CEE","Komintern"], correct: 1 },
  { text: "Quel pays a accueilli les premiers Jeux olympiques modernes (1896) ?", options: ["France","Grèce","Royaume-Uni","États-Unis"], correct: 1 },
  { text: "Qui a rénové les Jeux olympiques modernes ?", options: ["Pierre de Coubertin","Jules Ferry","Léon Blum","Jean Jaurès"], correct: 0 },
  { text: "Quel homme politique français a instauré l'école gratuite et laïque ?", options: ["Gambetta","Jules Ferry","Clemenceau","Ferry seul"], correct: 1 },
  { text: "Quel président du Conseil a mené la France pendant la fin de la Grande Guerre ?", options: ["Poincaré","Clemenceau","Briand","Daladier"], correct: 1 },
  { text: "Quelle ligne de fortifications française a été contournée en 1940 ?", options: ["Ligne Siegfried","Ligne Maginot","Ligne Gustave","Ligne Hindenburg"], correct: 1 },
  { text: "Quel maréchal a signé l'armistice en juin 1940 ?", options: ["Foch","Pétain","Joffre","Leclerc"], correct: 1 },
  { text: "Quel résistant a unifié la Résistance intérieure française ?", options: ["De Gaulle","Jean Moulin","Leclerc","Brossolette"], correct: 1 },
  { text: "Quelle ville a accueilli le procès des dignitaires nazis en 1945-1946 ?", options: ["Berlin","Nuremberg","Munich","Francfort"], correct: 1 },
  { text: "Quel pays a été divisé en deux (Nord/Sud) jusqu'en 1975 en Asie ?", options: ["Corée","Vietnam","Allemagne","Yémen"], correct: 1 },
  { text: "Quel pays reste divisé en deux États depuis 1948 dans la péninsule asiatique ?", options: ["Vietnam","Corée","Chine","Inde"], correct: 1 },
  { text: "Quelle puissance coloniale a quitté Hong Kong en 1997 ?", options: ["France","Royaume-Uni","Portugal","Pays-Bas"], correct: 1 },
  { text: "Quelle ancienne colonie portugaise est revenue à la Chine en 1999 ?", options: ["Hong Kong","Macao","Goa","Timor"], correct: 1 },
  { text: "Quel roi de France a engagé la France dans la guerre d'indépendance américaine ?", options: ["Louis XIV","Louis XVI","Louis XV","Charles X"], correct: 1 },
  { text: "Quel général français a aidé les insurgés américains ?", options: ["Lafayette","Rochambeau seul","Napoléon","Foch"], correct: 0 },
  { text: "Quelle ville allemande a été lourdement bombardée et incendiée en 1945 ?", options: ["Munich","Dresde","Cologne","Hambourg"], correct: 1 },
  { text: "Quel mouvement des années 1950-60 luttait pour les droits civiques aux USA ?", options: ["Le New Deal","Le mouvement des droits civiques","La Prohibition","Le maccarthysme"], correct: 1 },
  { text: "Quel pays a lancé le programme Apollo ?", options: ["URSS","États-Unis","Chine","France"], correct: 1 },
  { text: "Quelle ville a vu la chute d'un mur célèbre en 1989 ?", options: ["Berlin","Vienne","Prague","Budapest"], correct: 0 },
  { text: "Quelle révolution de velours a eu lieu en 1989 en Tchécoslovaquie ?", options: ["Révolution d'Octobre","Révolution de velours","Printemps de Prague","Révolution orange"], correct: 1 },
  { text: "Quel empereur a fait construire un immense tombeau gardé par une armée de terre cuite ?", options: ["Qin Shi Huang","Wu Zetian","Kangxi","Hongwu"], correct: 0 },
  { text: "Quel pharaon a fait construire la plus grande pyramide de Gizeh ?", options: ["Khéphren","Khéops","Mykérinos","Djéser"], correct: 1 },
  { text: "Quelle écriture les Égyptiens anciens utilisaient-ils ?", options: ["Cunéiforme","Hiéroglyphes","Alphabet latin","Runes"], correct: 1 },
  { text: "Quel peuple antique a inventé l'alphabet diffusé en Méditerranée ?", options: ["Les Phéniciens","Les Romains","Les Perses","Les Hittites"], correct: 0 },
  { text: "Quelle cité-État grecque était célèbre pour ses guerriers ?", options: ["Athènes","Sparte","Thèbes","Corinthe"], correct: 1 },
  { text: "Quel empereur a fait du christianisme la religion d'État romaine ?", options: ["Constantin","Théodose","Néron","Auguste"], correct: 1 },
  { text: "Quel navigateur a contourné l'Afrique (cap de Bonne-Espérance) ?", options: ["Vasco de Gama","Bartolomeu Dias","Magellan","Cabral"], correct: 1 },
  { text: "Quelle guerre a opposé la France et l'Angleterre de 1337 à 1453 ?", options: ["Guerre de Cent Ans","Croisades","Guerre de Trente Ans","Fronde"], correct: 0 },
  { text: "Qui a peint le plafond de la chapelle Sixtine ?", options: ["Raphaël","Michel-Ange","Botticelli","Titien"], correct: 1 },
  { text: "Quel scientifique a été condamné par l'Église pour l'héliocentrisme ?", options: ["Newton","Galilée","Kepler","Copernic"], correct: 1 },
  { text: "Quelle reine d'Angleterre a vaincu l'Invincible Armada en 1588 ?", options: ["Marie Ire","Élisabeth Ire","Victoria","Anne"], correct: 1 },
  { text: "Quel pays a déclaré son indépendance le 4 juillet 1776 ?", options: ["Le Canada","Les États-Unis","Le Mexique","Le Brésil"], correct: 1 },
  { text: "Quel empereur a vendu la Louisiane aux États-Unis en 1803 ?", options: ["Louis XVI","Napoléon Ier","Charles X","Louis-Philippe"], correct: 1 },
  { text: "Quelle ville japonaise a subi la première bombe atomique ?", options: ["Nagasaki","Hiroshima","Tokyo","Kyoto"], correct: 1 },
  { text: "Quel mur de fer séparait l'Europe en deux blocs selon Churchill ?", options: ["Le mur de Berlin","Le rideau de fer","La ligne Maginot","Le limes"], correct: 1 },
  { text: "Quelle dynastie chinoise a précédé la République en 1912 ?", options: ["Ming","Qing","Han","Tang"], correct: 1 },
  { text: "Quel roi français était surnommé « le Bien-Aimé » ?", options: ["Louis XIII","Louis XV","Louis XVI","Henri IV"], correct: 1 },
];
