// QuizzMaster — thème 🔬 Sciences & Tech. 206 questions.

module.exports = [
  { text: "Quel élément chimique a pour symbole H ?", options: ["Lithium","Hydrogène","Magnésium","Calcium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole He ?", options: ["Magnésium","Hélium","Calcium","Or"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Li ?", options: ["Calcium","Lithium","Or","Uranium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole C ?", options: ["Or","Carbone","Uranium","Krypton"], correct: 1 },
  { text: "Quel élément chimique a pour symbole N ?", options: ["Uranium","Azote","Krypton","Carbone"], correct: 1 },
  { text: "Quel élément chimique a pour symbole O ?", options: ["Krypton","Oxygène","Carbone","Aluminium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole F ?", options: ["Carbone","Fluor","Aluminium","Fer"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ne ?", options: ["Aluminium","Néon","Fer","Mercure"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Na ?", options: ["Fer","Sodium","Mercure","Baryum"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Mg ?", options: ["Mercure","Magnésium","Baryum","Xénon"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Al ?", options: ["Baryum","Aluminium","Xénon","Azote"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Si ?", options: ["Xénon","Silicium","Azote","Cuivre"], correct: 1 },
  { text: "Quel élément chimique a pour symbole P ?", options: ["Azote","Phosphore","Silicium","Cuivre"], correct: 1 },
  { text: "Quel élément chimique a pour symbole S ?", options: ["Silicium","Soufre","Cuivre","Plomb"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Cl ?", options: ["Cuivre","Chlore","Plomb","Brome"], correct: 1 },
  { text: "Quel élément chimique a pour symbole K ?", options: ["Plomb","Potassium","Brome","Radium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ca ?", options: ["Brome","Calcium","Radium","Oxygène"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Fe ?", options: ["Radium","Fer","Oxygène","Phosphore"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Cu ?", options: ["Oxygène","Cuivre","Phosphore","Zinc"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Zn ?", options: ["Phosphore","Zinc","Nickel","Platine"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ag ?", options: ["Zinc","Argent","Nickel","Platine"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Sn ?", options: ["Nickel","Étain","Platine","Plutonium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole I ?", options: ["Platine","Iode","Plutonium","Fluor"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Au ?", options: ["Plutonium","Or","Fluor","Soufre"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Hg ?", options: ["Fluor","Mercure","Soufre","Argent"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Pb ?", options: ["Soufre","Plomb","Argent","Cobalt"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ni ?", options: ["Argent","Nickel","Cobalt","Tungstène"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Co ?", options: ["Tungstène","Cobalt","Hydrogène","Néon"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Mn ?", options: ["Tungstène","Manganèse","Hydrogène","Néon"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Cr ?", options: ["Hydrogène","Chrome","Néon","Chlore"], correct: 1 },
  { text: "Quel élément chimique a pour symbole U ?", options: ["Néon","Uranium","Chlore","Étain"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ba ?", options: ["Chlore","Baryum","Étain","Manganèse"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Br ?", options: ["Étain","Brome","Manganèse","Titane"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Pt ?", options: ["Manganèse","Platine","Titane","Hélium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole W ?", options: ["Titane","Tungstène","Hélium","Sodium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ti ?", options: ["Hélium","Titane","Sodium","Potassium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ar ?", options: ["Sodium","Argon","Potassium","Iode"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Kr ?", options: ["Potassium","Krypton","Iode","Chrome"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Xe ?", options: ["Iode","Xénon","Chrome","Argon"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Ra ?", options: ["Chrome","Radium","Argon","Lithium"], correct: 1 },
  { text: "Quel élément chimique a pour symbole Pu ?", options: ["Argon","Plutonium","Lithium","Magnésium"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Hydrogène » ?", options: ["Ca","H","Sn","Ni"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Hélium » ?", options: ["Sn","He","Ni","Ba"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Lithium » ?", options: ["Ni","Li","Ba","Ar"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Carbone » ?", options: ["Ba","C","Ar","H"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Azote » ?", options: ["Ar","N","H","O"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Oxygène » ?", options: ["H","O","Al","K"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Fluor » ?", options: ["O","F","Al","K"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Néon » ?", options: ["Al","Ne","K","Ag"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Sodium » ?", options: ["K","Na","Ag","Pb"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Magnésium » ?", options: ["Ag","Mg","Pb","U"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Aluminium » ?", options: ["Pb","Al","U","Ti"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Silicium » ?", options: ["U","Si","Ti","Pu"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Phosphore » ?", options: ["Ti","P","Pu","N"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Soufre » ?", options: ["Pu","S","N","Mg"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Chlore » ?", options: ["N","Cl","Mg","Zn"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Potassium » ?", options: ["Mg","K","Cl","Zn"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Calcium » ?", options: ["Cl","Ca","Zn","Hg"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Fer » ?", options: ["Zn","Fe","Hg","Cr"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Cuivre » ?", options: ["Hg","Cu","Cr","W"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Zinc » ?", options: ["Cr","Zn","W","Ra"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Argent » ?", options: ["W","Ag","Ra","C"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Étain » ?", options: ["Ra","Sn","C","Na"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Iode » ?", options: ["C","I","Na","S"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Or » ?", options: ["Na","Au","S","Cu"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Mercure » ?", options: ["S","Hg","Cu","Au"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Plomb » ?", options: ["Cu","Pb","Au","Mn"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Nickel » ?", options: ["Au","Ni","Mn","Pt"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Cobalt » ?", options: ["Mn","Co","Pt","Xe"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Manganèse » ?", options: ["Pt","Mn","Xe","Li"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Chrome » ?", options: ["Xe","Cr","Li","Ne"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Uranium » ?", options: ["Li","U","Ne","P"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Baryum » ?", options: ["Ne","Ba","P","Fe"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Brome » ?", options: ["P","Br","Fe","I"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Platine » ?", options: ["Fe","Pt","I","Co"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Tungstène » ?", options: ["I","W","Co","Br"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Titane » ?", options: ["Co","Ti","Br","Kr"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Argon » ?", options: ["Br","Ar","Kr","He"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Krypton » ?", options: ["He","Kr","F","Si"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Xénon » ?", options: ["He","Xe","F","Si"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Radium » ?", options: ["F","Ra","Si","Ca"], correct: 1 },
  { text: "Quel est le symbole chimique de l'élément « Plutonium » ?", options: ["Si","Pu","Ca","Sn"], correct: 1 },
  { text: "Quelle est la formule chimique de l'eau ?", options: ["CO₂","H₂O","O₂","NaCl"], correct: 1 },
  { text: "Quelle est la formule du dioxyde de carbone ?", options: ["CO₂","H₂O","O₂","CH₄"], correct: 0 },
  { text: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", options: ["Oxygène","Azote","CO₂","Hélium"], correct: 2 },
  { text: "Quel gaz respirons-nous principalement pour vivre ?", options: ["Azote","Oxygène","CO₂","Hydrogène"], correct: 1 },
  { text: "Quelle planète est la plus proche du Soleil ?", options: ["Vénus","Mercure","Mars","Terre"], correct: 1 },
  { text: "Quelle est la plus grande planète du système solaire ?", options: ["Saturne","Jupiter","Neptune","Uranus"], correct: 1 },
  { text: "Quelle planète est surnommée la planète rouge ?", options: ["Vénus","Mars","Jupiter","Mercure"], correct: 1 },
  { text: "Combien de planètes dans le système solaire ?", options: ["7","8","9","10"], correct: 1 },
  { text: "Quel astre la Lune tourne-t-elle autour ?", options: ["Le Soleil","La Terre","Mars","Jupiter"], correct: 1 },
  { text: "Quelle est la vitesse de la lumière (ordre de grandeur) ?", options: ["3 000 km/s","300 000 km/s","30 000 km/s","3 millions km/s"], correct: 1 },
  { text: "Qui a énoncé E = mc² ?", options: ["Newton","Einstein","Bohr","Planck"], correct: 1 },
  { text: "Qui a formulé la loi de la gravitation universelle ?", options: ["Galilée","Newton","Kepler","Copernic"], correct: 1 },
  { text: "Quelle force attire les objets vers le sol ?", options: ["Le magnétisme","La gravité","La friction","La pression"], correct: 1 },
  { text: "Combien d'os possède le corps humain adulte ?", options: ["196","206","226","256"], correct: 1 },
  { text: "Quel est le plus grand organe du corps humain ?", options: ["Le foie","La peau","Le cœur","Les poumons"], correct: 1 },
  { text: "Quel organe pompe le sang ?", options: ["Le foie","Le cœur","Les reins","Les poumons"], correct: 1 },
  { text: "Combien de chambres compte le cœur humain ?", options: ["2","3","4","5"], correct: 2 },
  { text: "Quel organe filtre le sang et produit l'urine ?", options: ["Le foie","Les reins","La rate","Le pancréas"], correct: 1 },
  { text: "Combien de chromosomes dans une cellule humaine ?", options: ["23","42","46","48"], correct: 2 },
  { text: "Quelle molécule porte l'information génétique ?", options: ["ARN","ADN","ATP","Protéine"], correct: 1 },
  { text: "Quel scientifique a proposé la théorie de l'évolution ?", options: ["Lamarck","Darwin","Mendel","Pasteur"], correct: 1 },
  { text: "Qui a découvert la pénicilline ?", options: ["Pasteur","Fleming","Koch","Jenner"], correct: 1 },
  { text: "Quel est l'élément le plus abondant dans l'univers ?", options: ["Oxygène","Hydrogène","Hélium","Carbone"], correct: 1 },
  { text: "Quel métal est liquide à température ambiante ?", options: ["Plomb","Mercure","Étain","Zinc"], correct: 1 },
  { text: "Quel gaz compose majoritairement l'atmosphère terrestre ?", options: ["Oxygène","Azote","CO₂","Argon"], correct: 1 },
  { text: "Quelle est l'unité de mesure du courant électrique ?", options: ["Volt","Ampère","Watt","Ohm"], correct: 1 },
  { text: "Quelle est l'unité de la tension électrique ?", options: ["Ampère","Volt","Watt","Joule"], correct: 1 },
  { text: "Quelle est l'unité de puissance ?", options: ["Joule","Watt","Newton","Pascal"], correct: 1 },
  { text: "Quelle est l'unité de force ?", options: ["Joule","Newton","Pascal","Watt"], correct: 1 },
  { text: "Quelle est l'unité de fréquence ?", options: ["Hertz","Décibel","Lumen","Candela"], correct: 0 },
  { text: "Quelle est l'unité de température du Système international ?", options: ["Celsius","Kelvin","Fahrenheit","Newton"], correct: 1 },
  { text: "À quelle température l'eau bout-elle au niveau de la mer ?", options: ["90 °C","100 °C","110 °C","120 °C"], correct: 1 },
  { text: "À quelle température l'eau gèle-t-elle ?", options: ["-10 °C","0 °C","4 °C","10 °C"], correct: 1 },
  { text: "Combien de bits dans un octet ?", options: ["4","8","16","32"], correct: 1 },
  { text: "Que signifie CPU en informatique ?", options: ["Mémoire","Processeur","Écran","Disque"], correct: 1 },
  { text: "Quel langage a été créé par Brendan Eich en 1995 ?", options: ["Python","JavaScript","Ruby","PHP"], correct: 1 },
  { text: "Quelle entreprise a créé l'iPhone ?", options: ["Microsoft","Apple","Samsung","Nokia"], correct: 1 },
  { text: "Que signifie WWW ?", options: ["World Wide Web","Wide World Web","Web World Wide","World Web Wide"], correct: 0 },
  { text: "Quel est le composant qui stocke les données de façon permanente ?", options: ["RAM","Disque dur/SSD","Processeur","Carte graphique"], correct: 1 },
  { text: "Quelle particule a une charge négative ?", options: ["Proton","Neutron","Électron","Photon"], correct: 2 },
  { text: "Quelle particule a une charge positive dans le noyau ?", options: ["Électron","Proton","Neutron","Photon"], correct: 1 },
  { text: "Quel est l'état de l'eau à -20 °C ?", options: ["Liquide","Solide","Gazeux","Plasma"], correct: 1 },
  { text: "Quel scientifique a découvert la radioactivité (avec les Curie) ?", options: ["Becquerel","Röntgen","Rutherford","Bohr"], correct: 0 },
  { text: "Qui a découvert les rayons X ?", options: ["Becquerel","Röntgen","Curie","Tesla"], correct: 1 },
  { text: "Quel sang est donneur universel ?", options: ["A+","O-","AB+","B+"], correct: 1 },
  { text: "Quelle vitamine est produite par la peau au soleil ?", options: ["Vitamine A","Vitamine C","Vitamine D","Vitamine K"], correct: 2 },
  { text: "Quel est le métal le plus abondant dans la croûte terrestre ?", options: ["Fer","Cuivre","Aluminium","Or"], correct: 2 },
  { text: "Quelle planète possède de grands anneaux visibles ?", options: ["Jupiter","Saturne","Uranus","Mars"], correct: 1 },
  { text: "Combien de temps met la Terre pour tourner sur elle-même ?", options: ["1 mois","24 heures","1 an","12 heures"], correct: 1 },
  { text: "Quel scientifique a affirmé que la Terre tourne autour du Soleil ?", options: ["Ptolémée","Copernic","Aristote","Galien"], correct: 1 },
  { text: "Quel est l'organe de la respiration ?", options: ["Le cœur","Les poumons","Le foie","L'estomac"], correct: 1 },
  { text: "Quelle énergie est produite par le Soleil par fusion ?", options: ["Chimique","Nucléaire","Mécanique","Électrique"], correct: 1 },
  { text: "Quel appareil mesure la température ?", options: ["Baromètre","Thermomètre","Hygromètre","Anémomètre"], correct: 1 },
  { text: "Quel appareil mesure la pression atmosphérique ?", options: ["Thermomètre","Baromètre","Altimètre","Boussole"], correct: 1 },
  { text: "Quelle est la planète la plus chaude du système solaire ?", options: ["Mercure","Vénus","Mars","Jupiter"], correct: 1 },
  { text: "Quel mathématicien grec a un théorème sur le triangle rectangle ?", options: ["Euclide","Pythagore","Thalès","Archimède"], correct: 1 },
  { text: "Combien font 7 × 8 ?", options: ["54","56","63","48"], correct: 1 },
  { text: "Quel est le résultat de 12² ?", options: ["124","144","148","122"], correct: 1 },
  { text: "Quelle est la racine carrée de 81 ?", options: ["7","8","9","11"], correct: 2 },
  { text: "Combien de côtés a un hexagone ?", options: ["5","6","7","8"], correct: 1 },
  { text: "Combien de degrés dans un cercle complet ?", options: ["180","270","360","400"], correct: 2 },
  { text: "Quel est le plus petit nombre premier ?", options: ["0","1","2","3"], correct: 2 },
  { text: "Quel gaz noble est utilisé dans les enseignes lumineuses rouges ?", options: ["Argon","Néon","Krypton","Hélium"], correct: 1 },
  { text: "Quel organe produit l'insuline ?", options: ["Le foie","Le pancréas","La rate","Les reins"], correct: 1 },
  { text: "Quel est le plus grand mammifère vivant ?", options: ["Éléphant","Baleine bleue","Cachalot","Girafe"], correct: 1 },
  { text: "Combien de pattes a un insecte ?", options: ["4","6","8","10"], correct: 1 },
  { text: "Combien de pattes a une araignée ?", options: ["6","8","10","12"], correct: 1 },
  { text: "Quel animal est un mammifère marin ?", options: ["Requin","Dauphin","Thon","Raie"], correct: 1 },
  { text: "Quelle planète est la plus éloignée du Soleil ?", options: ["Saturne","Uranus","Neptune","Pluton"], correct: 2 },
  { text: "Combien font 9 × 9 ?", options: ["72","81","91","99"], correct: 1 },
  { text: "Combien font 6 × 7 ?", options: ["42","48","36","49"], correct: 0 },
  { text: "Combien font 8 × 8 ?", options: ["56","64","72","48"], correct: 1 },
  { text: "Quelle est la racine carrée de 144 ?", options: ["11","12","13","14"], correct: 1 },
  { text: "Combien de minutes dans une heure ?", options: ["50","60","100","30"], correct: 1 },
  { text: "Combien de secondes dans une minute ?", options: ["50","60","100","120"], correct: 1 },
  { text: "Combien de côtés a un pentagone ?", options: ["4","5","6","7"], correct: 1 },
  { text: "Combien de côtés a un octogone ?", options: ["6","7","8","9"], correct: 2 },
  { text: "Combien d'angles a un triangle ?", options: ["2","3","4","5"], correct: 1 },
  { text: "Quel est le nombre Pi arrondi au centième ?", options: ["3,14","3,16","3,12","3,41"], correct: 0 },
  { text: "Quel est le plus grand nombre : 0,5 ou 0,45 ?", options: ["0,45","0,5","Égaux","Indéterminé"], correct: 1 },
  { text: "Combien font 100 divisé par 4 ?", options: ["20","25","40","50"], correct: 1 },
  { text: "Quel organe permet de voir ?", options: ["L'oreille","L'œil","Le nez","La langue"], correct: 1 },
  { text: "Quel organe permet d'entendre ?", options: ["L'œil","L'oreille","Le nez","La peau"], correct: 1 },
  { text: "Combien de poumons a l'être humain ?", options: ["1","2","3","4"], correct: 1 },
  { text: "Quel liquide rouge circule dans les veines ?", options: ["La lymphe","Le sang","La bile","Le plasma seul"], correct: 1 },
  { text: "Quel groupe d'animaux pond des œufs et a des plumes ?", options: ["Mammifères","Oiseaux","Reptiles","Poissons"], correct: 1 },
  { text: "Quel animal est connu pour son long cou ?", options: ["Zèbre","Girafe","Lama","Autruche"], correct: 1 },
  { text: "Combien de pattes a un mille-pattes (au sens strict, beaucoup) ?", options: ["6","8","Beaucoup","4"], correct: 2 },
  { text: "Quel est le plus rapide animal terrestre ?", options: ["Lion","Guépard","Cheval","Antilope"], correct: 1 },
  { text: "Quel reptile peut changer de couleur ?", options: ["Iguane","Caméléon","Gecko","Varan"], correct: 1 },
  { text: "Quel insecte produit le miel ?", options: ["La guêpe","L'abeille","Le bourdon","La mouche"], correct: 1 },
  { text: "Quelle est la planète où nous vivons ?", options: ["Mars","La Terre","Vénus","La Lune"], correct: 1 },
  { text: "Combien de temps met la Terre pour faire le tour du Soleil ?", options: ["1 mois","1 semaine","1 an","1 jour"], correct: 2 },
  { text: "Quelle étoile est au centre de notre système solaire ?", options: ["La Lune","Le Soleil","Sirius","Polaris"], correct: 1 },
  { text: "Qu'est-ce qu'une éclipse solaire ?", options: ["La Lune cache le Soleil","Le Soleil cache la Lune","La Terre brille","Une étoile filante"], correct: 0 },
  { text: "Quel satellite naturel tourne autour de la Terre ?", options: ["Mars","La Lune","Phobos","Titan"], correct: 1 },
  { text: "Quel est le premier homme à avoir marché sur la Lune ?", options: ["Gagarine","Armstrong","Aldrin","Collins"], correct: 1 },
  { text: "En quelle année l'homme a-t-il marché sur la Lune ?", options: ["1959","1969","1979","1989"], correct: 1 },
  { text: "Quel télescope spatial a été lancé en 1990 ?", options: ["James Webb","Hubble","Kepler","Spitzer"], correct: 1 },
  { text: "Quel gaz fait gonfler les ballons et monte dans l'air ?", options: ["Oxygène","Hélium","Azote","CO₂"], correct: 1 },
  { text: "Quel métal précieux a le symbole Au ?", options: ["Argent","Or","Cuivre","Platine"], correct: 1 },
  { text: "Quel acide se trouve dans l'estomac ?", options: ["Acide citrique","Acide chlorhydrique","Acide acétique","Acide nitrique"], correct: 1 },
  { text: "Quelle énergie renouvelable vient du vent ?", options: ["Solaire","Éolienne","Hydraulique","Géothermique"], correct: 1 },
  { text: "Quelle énergie renouvelable vient du soleil ?", options: ["Éolienne","Solaire","Marémotrice","Biomasse"], correct: 1 },
  { text: "Quel combustible fossile est un liquide ?", options: ["Charbon","Pétrole","Gaz","Tourbe"], correct: 1 },
  { text: "Que mesure un sismographe ?", options: ["La pluie","Les séismes","Le vent","La température"], correct: 1 },
  { text: "Quelle échelle mesure la magnitude des séismes ?", options: ["Beaufort","Richter","Celsius","Mohs"], correct: 1 },
  { text: "Quelle échelle mesure la force du vent ?", options: ["Richter","Beaufort","Mohs","Kelvin"], correct: 1 },
  { text: "Quel phénomène provoque les marées ?", options: ["Le vent","L'attraction de la Lune","La pluie","Les courants chauds"], correct: 1 },
  { text: "Quel est l'os le plus long du corps humain ?", options: ["Le tibia","Le fémur","L'humérus","Le radius"], correct: 1 },
  { text: "Combien de dents a un adulte (avec les dents de sagesse) ?", options: ["28","30","32","36"], correct: 2 },
  { text: "Quel sens est associé à la langue ?", options: ["L'ouïe","Le goût","L'odorat","La vue"], correct: 1 },
  { text: "Quel sens est associé au nez ?", options: ["Le goût","L'odorat","Le toucher","L'ouïe"], correct: 1 },
  { text: "Quelle cellule transporte l'oxygène dans le sang ?", options: ["Globule blanc","Globule rouge","Plaquette","Neurone"], correct: 1 },
  { text: "Quel scientifique a inventé l'ampoule électrique (popularisée) ?", options: ["Tesla","Edison","Volta","Faraday"], correct: 1 },
  { text: "Qui a inventé le téléphone (breveté) ?", options: ["Edison","Graham Bell","Marconi","Morse"], correct: 1 },
  { text: "Qui a développé la théorie de la relativité générale ?", options: ["Newton","Einstein","Hawking","Bohr"], correct: 1 },
  { text: "Quel appareil sert à voir les très petites choses ?", options: ["Télescope","Microscope","Périscope","Stéthoscope"], correct: 1 },
  { text: "Quel appareil sert à observer les étoiles ?", options: ["Microscope","Télescope","Baromètre","Sismographe"], correct: 1 },
  { text: "Quel est le symbole du pourcentage ?", options: ["#","%","&","@"], correct: 1 },
  { text: "Quelle forme géométrique n'a aucun angle ?", options: ["Triangle","Carré","Cercle","Losange"], correct: 2 },
  { text: "Quel solide a 6 faces carrées ?", options: ["Pyramide","Cube","Sphère","Cylindre"], correct: 1 },
  { text: "Combien de faces a un dé classique ?", options: ["4","6","8","12"], correct: 1 },
  { text: "Quel nombre est pair ?", options: ["7","13","18","21"], correct: 2 },
];
